### ISSUE TITLE
Permissions issues when using configmap

### ISSUE THREAD

**Issue by InfoSec812** [fabric8io/fabric8-maven-plugin#1002]
### Description
I'm using an example [project](https://github.com/InfoSec812/vertx-configmap-example)
leveraging Vert.x Config with the kubernetes configmap module. When I try to launch the application, I get
an error from OpenShift about permissions to the configmap.

### Info

* f-m-p version : 3.5.19
* Maven version (`mvn -v`) : 3.3.9
```

```
* Kubernetes / OpenShift setup and version : CDK 3.0
* If it's a bug, how to reproduce : Use example project linked above
* Sample project : https://github.com/InfoSec812/vertx-configmap-example.git

**Comment by rhuss** [comment]
You configmap.yaml has an invalid format (there is no 'spec' level for a configmap).
Also, you need of course reference the configmap somehow in your deployment for doing something useful.

**Comment by InfoSec812** [comment]
I had figured out about the `spec` section, bit thanks for the reminder. As for referencing the configmap in the deployment, when using Vert.x's config module it is not needed. I should be able to communicate directly with Kubernetes to retrieve the configmap.

**Comment by rhuss** [comment]
Ah, ok. Does it work now ?

**Comment by InfoSec812** [comment]
We finally got it working. There were a few issues and most of it was on the Vert.x code implementation side. The one issue we had to fix in OpenShift/fabric8 was to give permissions to the "default" user in order to allow access to the configmaps and secrets.

**Comment by rhuss** [comment]
you mean when connecting via the API directly to retrieve the configmap data ? Yes, you might need an enabled serviceaccount for this.

If you don't mind I'm closing this issue. Feel free to reopen if there is something we can help.
