### ISSUE TITLE
Kompose: allow using profiles

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1007]
The current kompose integration allows to generate resources from a `docker-compose.yaml` file. Resources are then used as input for enrichers. The list of enrichers is the one corresponding to the global profile defined at plugin level.

A user might be interested to specify a profile to enable/disable some enrichers for the docker-compose resources. A typical example is when (some) docker-compose resources are complete and don't need enrichment. In this case the user may want to use the predefined `raw` profile for that resources.

There are multiple possible approaches (e.g.):

1. Define a global option `fabric8.compose.profile` to define a profile that applies to all resources generated through kompose

2. Define profile paths. Currently resource fragments can be put in `src/main/fabric8/minimal` and they will be enriched using the `minimal` profile. This works also with custom profile names.
Currently kompose resources should be defined in `src/main/fabric8-compose`. We may define directories like `src/main/fabric8-compose/minimal` to look for resources that should be enriched using the `minimal` profile.
Currently, using multiple docker-compose files is not supported. Profile dirs have meaning only if we allow to define multiple docker-compose files (we should evaluate if it's possible for the users to split a definition into multiple files without losing anything).

As an aside: we have talked in other threads to move the root dir for profiles. If we decide e.g. to move the profile root dir to `src/main/fabric8/profile/`, the default compose dir may be changed from `src/main/fabric8-compose/` into `src/main/fabric8/compose/`. An then, a profile dir for compose may be `src/main/fabric8/compose/profile/minimal/` (or maybe `src/main/fabric8/profile/minimal/compose/`).

3. Other ideas? @hrishin @Preeticp @rhuss @jstrachan @pradeepto

**Comment by rhuss** [comment]
I like the Nr. 2 as it would be consistent with our current approach with using profile directores. Still it should be possible to specify a global "profile". This would be applied to everything not in profile directories (so to the configuration coming from compose files as well as the 'normal' fragments. Don't think we need to differentiate here much). 

I also opt for the later suggestion to use a dedicated profile directory with `src/main/fabric8`. That we can even provide more concise conventions by inspecting the directory structure.

**Comment by rhuss** [comment]
I still think we should go for it + we should do a refactoring of the fragment root dir to `src/main/fabric8/fragments` to allow parallel directories below `src/main/fabric8`

**Comment by rohanKanojia** [comment]
After discussion with Roland I'm not sure whether to proceed with this or not. Not sure how is kompose support right now and what is upstream standing for kompose. I'm putting this on hold for now and would pick this up if someone objects in #1486

**Comment by dev-gaur** [comment]
Closing as Kompose support has been removed. #1494
