### ISSUE TITLE
Kompose: support build section in docker-compose files

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1008]
Images cannot be built using kompose in the current integration.
A generic `docker-compose.yaml` file can define a `build` section (for each service) that specifies how a image should be built (Dockerfile, config override from base image, etc.).

That build section indicates just how an image should be built. But, once it's built, in order to use it inside Kubernetes/Openshift, it must be "published", i.e.:
- *Just tagged in the docker daemon*: when using minishift, minikube, `oc cluster up` or other local environments
- *Tagged and pushed*: to a docker registry (not only the docker hub) when using a real Kubernetes cluster
- *Pushed to the internal Openshift registry*: when using Openshift, you don't need a Docker daemon and you may not be able to contact the internal registry directly. S2I builds (like binary builds) should be used to install the image into Openshift.

Kompose has currently an embedded way to handle image building and installation (that is compatible also with Openshift).
The `docker-maven-plugin` can build Docker images, tag and push them to a Docker registry. The fabric8-maven-plugin can build images for usage inside Openshift.

We should evaluate which build strategy should be used when dealing with docker-compose files having `build` sections.

Again, ideas? @hrishin @Preeticp @rhuss @jstrachan @pradeepto

**Comment by rhuss** [comment]
Actually, that would be a good addition to docker-maven-plugin, too. As we use the build part there anyway it might make sense to put build support based on compose file into d-m-p and use it in f-m-p. For fmp4 we want to extract that 'build' part into a separate module, would be awesome if the compose build feature could stay together with the regular build based on configuration (and generators).

This wouldn't help for s2i based builds, but as I see (c|k)ompose as a pure kubernetes tech I don't think its not a damage if s2i doesnt have support for building based on kompose files.

**Comment by hrishin** [comment]
Noted very well, thanks @nicolaferraro  for this :)

> - Just tagged in the docker daemon: when using minishift, minikube, oc cluster up or other local environments

I think here well, plugin needs to build->push the image to registry as minikube, minishift is running a single node cluster in VM. 
right?

From implementation stand point:
1. Alter build image flow:
At present, plugin exhibits default  build flow to building container image. If Docker Compose file has `build` section then plugin should entertain it and bypass it default flow for building `jboss` container image for instance
2. Configuration option for enabling/disabling 'build'
Building and pushing images always may looks intensive task, in some case it may be desired to skip the build/push process from Docker Compose flow.

**Comment by rohanKanojia** [comment]
@hrishin @nicolaferraro @rhuss Does this feature request still valid? I don't see any related issue on docker maven plugin related to this. There is one issue related to volume support, but I'm not sure about this.

**Comment by rhuss** [comment]
We should re-evaluate our kompose support and whether we should continue to work on this. But this is a bigger story, where this issue is a part of. Nevertheless, I put this one into the backlog as a kind of placeholder.

**Comment by dev-gaur** [comment]
Closing as Kompose support has been removed. #1494
