### ISSUE TITLE
JAVA_OPTIONS not merged when using the vertx generator

### ISSUE THREAD

**Issue by cescoffier** [fabric8io/fabric8-maven-plugin#1009]
I'm not sure if it's the desired behavior or a bug...

### Description

When the user uses a `deployment.yml` setting `JAVA_OPTIONS`, the value is overridden by the generator (
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/generator/vertx/src/main/java/io/fabric8/maven/generator/vertx/VertxGenerator.java#L59)

Anything that needs to be done to "append" both ?

### Info

* f-m-p version : 3.5.1
* Maven version (`mvn -v`) : 3.5.0
* Kubernetes / OpenShift setup and version : v1.5.1+7b451fc, kubernetes v1.5.2+43a9be4 (minishift)

**Comment by nicolaferraro** [comment]
Definitely this is not the desired behavior. Similar issues have been raised in #957 and #937.

There's not a default way to "append" to a env variable in f-m-p. Usually env-vars having multiple "declarations" are subject to a sort of "priority" and only one of them is used. In this case it seems the "priority" for `JAVA_OPTIONS` is not what a user expects.

I think we can default to an "append" mode for some environment variables like `JAVA_OPTIONS`, and this can be configurable. Wdyt @rhuss ?

**Comment by nicolaferraro** [comment]
@cescoffier I'm trying to investigate on the current behavior to understand what the plugin should do. I've added a IT test [here])https://github.com/nicolaferraro/fabric8-maven-plugin/blob/19b8f8985e671edcb47f0bfbdecf3e9a95609fde/it/src/it/vertx/expected/kubernetes.yml#L45-L46), but what I see is:
- The `JAVA_OPTIONS` created by the generator are put in the Docker image
- The `JAVA_OPTIONS` in the resource fragment are put in the kubernetes resources

At the end, the first `JAVA_OPTIONS` (`-Dvertx.cacheDirBase=/tmp`) are used during the build (S2I or Docker), while the one in `deployment.yml` is used at runtime in the Pod, and it overrides the one in the docker image (not vice-versa).

Is this correct?

**Comment by cescoffier** [comment]
Right now I see the opposite. The options from the generator are used and not the one from the deployment.yml.

**Comment by nicolaferraro** [comment]
Interesting... can you share your project, so I can check what's happening?

**Comment by cescoffier** [comment]
Hi @nicolaferraro 

Here is a reproducer: https://github.com/openshiftio-vertx-boosters/vertx-http-booster/tree/log4j2
(notice the branch log4j2)

This project uses the Vert.x generator and has a `deployment.yml` setting `JAVA_OPTIONS`. When launched, only the options provided by the generator are used:

```
exec java -Dvertx.cacheDirBase=/tmp -javaagent:/opt/jolokia/jolokia.jar=config=/opt/jolokia/etc/jolokia.properties -cp . -jar /deployments/http-vertx-9-SNAPSHOT.jar
```

To reproduce the issue:

```
$ git clone https://github.com/openshiftio-vertx-boosters/vertx-http-booster.git
$ git checkout log4j2
$ mvn fabric8:deploy -Popenshift
```

**Comment by nicolaferraro** [comment]
Definitely it's the `fabric8.mode` that changes the behavior. You're using `openshift` while my example is using `kubernetes`. There's a `OpenShiftS2IEnricher` that [overrides](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/OpenShiftS2IEnricher.java#L77) what's set in the fragment with what's required by the generator.

We need an alternative way to set these env variables, that is consistent with what it's done in kubernetes mode.

**Comment by nicolaferraro** [comment]
I've found a way to uniform the behavior of `kubernetes` and `openshift` mode for environment variables.

Basically, we can **safely remove the `OpenShiftS2IEnricher`** to avoid polluting Openshift resources with environment variables from the Generator. We can **inject those environment variables during binary build**.

I've changed the plugin code to inject a `.s2i/environment` file into the tar binary. This file contains all environment variables that we want to set in the build container and in the final docker image, as explained [here](https://github.com/openshift/source-to-image/blob/master/README.md#build-workflow).

This way we have a consistent behavior between Kubernetes and Openshift: in both cases, **env variables defined at generator level will be encoded in the docker image only**, without changing Openshift resources.

Users (through fragments and xml configuration) will be free to set the same env variables at Openshift/Kubernetes level, overriding the values encoded in the docker image.

This does not add a "append" mode for that `JAVA_OPTIONS` property, but I think it is a lot better than not being able to override it.

@jstrachan do you think the approach is ok?

It requires a small change to the `docker-maven-plugin`. Also @rhuss ?

**Comment by MarWestermann** [comment]
I am not sure if this fix is already in the current version of fmp but nevertheless I found a workaround by setting the JAVA_TOOL_OPTIONS env variable which is beeing picked up by the jvm on startup. That way you can extend the JAVA_OPTIONS passed via command line.

**Comment by nicolaferraro** [comment]
@MarWestermann, great. I was looking for a workaround like that but didn't find it. The issue is not fixed yet but we are making progress..
