### ISSUE TITLE
Include a default Revision History Limit to avoid keeping old RCs / RSs

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#1017]
By default if no Revision History Limit is added to DeploymentConfigs or Deployments spec then all old ReplicationControllers / ReplicaSets will be kept.  This consumes resources in etcd and crowding the output of `kubectl get rs` / `oc get rc` source https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#revision-history-limit

Should we add a default value when generating DC / deployment yaml?

**Comment by rawlingsj** [comment]
@nicolaferraro I'd like to add a default .spec.revisionHistoryLimit to fmp generated deployment.yml and deploymentConfig.yml files. Is this something that can be easily done?  If you're able to give me a starting point I can have a crack myself?

**Comment by nicolaferraro** [comment]
Yes @rawlingsj, I don't think there will be particular problems in implementing it.
I think the best way to do it is to add another enricher. Enrichers should be declared in a [manifest file](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/standard/src/main/resources/META-INF/fabric8/enricher-default) and added to profiles. Imo it can be added at the end of the default profile [here](https://github.com/fabric8io/fabric8-maven-plugin/blob/ead7267d33c92257d67f0b3c2c74bb8d6527274c/plugin/src/main/resources/META-INF/fabric8/profiles-default.yml#L44). It will be executed after all resources have been generated by other enrichers and it will just add the limits to that resources.

You may use the visitor pattern to augment resources, like [here](https://github.com/fabric8io/fabric8-maven-plugin/blob/ead7267d33c92257d67f0b3c2c74bb8d6527274c/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ImageEnricher.java#L141-L152). You can also define [specific configuration options](https://github.com/fabric8io/fabric8-maven-plugin/blob/ead7267d33c92257d67f0b3c2c74bb8d6527274c/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/VolumePermissionEnricher.java#L53-L58) for the enricher e.g. to let users set a limit different from the default.

**Comment by rawlingsj** [comment]
@nicolaferraro perfect! That's exactly what I was after, thanks.  I'll give it a whirl.

**Comment by jstrachan** [comment]
I wonder whats a good value to default it to - 2? or 3?

**Comment by rawlingsj** [comment]
yeah 2 should be a good enough default

**Comment by jstrachan** [comment]
@hrishin fancy taking a stab at this one?

figure we could add a new Enricher thats enabled by default which takes an optional configuration (that defaults to `2`) that then adds the revision history limit. It'd be nice to enable "2" OOTB without any user configuration (folks can easily opt out by excluding the enricher)

**Comment by hrishin** [comment]
@nicolaferraro 

> Enrichers should be declared in a manifest file and 

Is it "fabric8" or "standard" manifest? could you please confirm?

**Comment by jstrachan** [comment]
I guess this would be `standard` enricher; as its standard stuff and not related to whether fabric8 CI / CD was being used

**Comment by rhuss** [comment]
would also opt for 'standard'

**Comment by hrishin** [comment]
@rhuss 

> would also opt for 'standard'

Sorry but didn't get it

**Comment by jstrachan** [comment]
so it'd go in this package https://github.com/fabric8io/fabric8-maven-plugin/tree/master/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard then be in this  file
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/standard/src/main/resources/META-INF/fabric8/enricher-default

**Comment by hrishin** [comment]
Yes :+1:

**Comment by hrishin** [comment]
In case of OpenShift we expect `revisionHistoryLimit` to be present in `deploymentconfig`?

**Comment by nicolaferraro** [comment]
Fixed
