### ISSUE TITLE
Kubernetes authenticated by token

### ISSUE THREAD

**Issue by maragao** [fabric8io/fabric8-maven-plugin#1028]
I'm getting this warning when i run mvn fabric8:xxxxx (any goal)

[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://kubernetes.service.infra.development.kubernetes.intranet/. Message: Forbidden! User development doesn't have permission. User "xxxxxxx" cannot get path "/"..

It's a develpment environment authenticated by token.
In a sandbox environment (wich I have a root equivalent permission) this don't happen.
I think it is trying to do a GET in the server root context instead my namespace. Not sure.

* f-m-p version : 3.5.25
* Maven version (`mvn -v`) : 3.3.3

* Kubernetes / OpenShift setup and version : Kubernetes 1.7.3

**Comment by carlossg** [comment]
this is a problem in the kubernetes-client https://github.com/fabric8io/kubernetes-client/issues/850

**Comment by rohanKanojia** [comment]
I think we need to fix fabric8io/kubernetes-client#850 first, then we can jump onto this
