### ISSUE TITLE
Resource validation must be done on client-side constraints

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1039]
An example [here](https://github.com/nicolaferraro/fabric8-maven-plugin-sidecar).

`spec.tags[0].generation` is an example of data that is *mandatory* on resources returned by the server, while it is probably *forbidden* (or at least *optional*) in the client request.

```
[INFO] F8: validating /home/nferraro/git/owned/fabric8-maven-plugin-sidecar/target/classes/META-INF/fabric8/openshift/jaeger-agent-is.yml resource
[ERROR] F8: Invalid Resource : /home/nferraro/git/owned/fabric8-maven-plugin-sidecar/target/classes/META-INF/fabric8/openshift/jaeger-agent-is.yml
[message=.spec.tags[0].annotations: is missing but it is required, violation type=required]
[message=.spec.tags[0].generation: is missing but it is required, violation type=required]
[ERROR] F8: use "mvn -Dfabric8.skipResourceValidation=true" option to skip the validation
```

We should do validation on client side constraints. @hrishin are there available in the schema?

**Comment by nicolaferraro** [comment]
[The kubernetes api spec](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json) seems to be mostly correct, while the Openshift one contains many errors. I wonder whether we can open an issue and fix it in the origin repo. If they are not used for validation of server-generated resources, that can be done...

**Comment by hrishin** [comment]
Yes, lets raise an issue and ball rolling on for it.

**Comment by hrishin** [comment]
this issue is closed now
