### ISSUE TITLE
Resource validation should not prevent deployment

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1040]
Resource validation is quite a new feature, so f-m-p should not block the deployment if some resources are not valid (e.g. #1039).

We should turn validation errors into warnings until it becomes stable.

**Comment by hrishin** [comment]
Yes @nicolaferraro warning looks better approach. For now their is provision to skip the validation all together with `mvn -Dfabric8.skipResourceValidation=true` so deployment wont get block.

**Comment by nicolaferraro** [comment]
Yes, but I'd like not to block existing projects because of an "invalid validation". I'm turning them into warnings for now. The "fail on error" behavior can be turned on, but it's not the default.

They'll be useful to debug also as warnings and when we manage to make it stable, we can flip the default again.

**Comment by hrishin** [comment]
Totally agreed @nicolaferraro
