### ISSUE TITLE
build log watching doesn't work with FMP 3.5.30 and OpenShift 3.6

### ISSUE THREAD

**Issue by Ladicek** [fabric8io/fabric8-maven-plugin#1048]
### Description

Doing `mvn clean fabric8:deploy` against OpenShift 3.6 (tried both with remote OCP 3.6 cluster and local `oc cluster up`), using FMP 3.5.30. (Using this app https://github.com/Ladicek/rourka/ but not sure if that's relevant).

It all works fine, but the build log isn't showed. When I attached a debugger to the Maven process, it seems `OpenshiftBuildService.startBuild` only returns after the build finishes, and then obviously `waitForOpenShiftBuildToComplete` doesn't log anything, because the build is already complete.

### Info

* f-m-p version : 3.5.30
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /home/lthon/software/apache-maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-94-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version : OpenShift 3.6 (both actual OCP 3.6 cluster and local `oc cluster up`)
* If it's a bug, how to reproduce : run `mvn clean fabric8:deploy` and watch if the build log is showed
* Sample project : https://github.com/Ladicek/rourka/

**Comment by hrishin** [comment]
fixed now fabric8io/kubernetes-client#883
F-M-P 3.5.33
