### ISSUE TITLE
samples have no CI coverage

### ISSUE THREAD

**Issue by jhalliday** [fabric8io/fabric8-maven-plugin#1052]
https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/* don't get run by CI.
Currently e.g. xml-config doesn't build (stale snapshot dependency) and doesn't 'fabric8:build' cleanly on openshift even when the dep is fixed.

**Comment by hrishin** [comment]
@jhalliday could you post error logs please?

**Comment by rohanKanojia** [comment]
@hrishin Does this look like a sane change request to you? Shall we add samples also to CI? Otherwise, Can we close this?
