### ISSUE TITLE
S2I not yet supported for the webapp-generator - for artefacts created from swagger-codegen

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8-maven-plugin#1053]
I decided to use swagger-codegen on a swagger.json I created

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -DdebugModels=true -i audit/swagger.json -l jaxrs -o samples/server/ob/jaxrs-spec

then used mvn io.fabric8:fabric8-maven-plugin:3.5.28:setup
then fabric8:run gave me the error:

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.28:build (fmp) on project swagger-jaxrs-server: Execution fmp of goal io.fabric8:fabric8-maven-plugin:3.5.28:build failed: S2I not yet supported for the webapp-generator. Use -Dfabric8.mode=kubernetes or -Dfabric8.buildStrategy=docker for OpenShift mode. Please refer to the reference manual at https://maven.fabric8.io for details about build modes. -> [Help 1]

I seem to remember hitting this problem a few years ago and got around it by hacking on the pom file but it would nice not to have to

**Comment by jsight** [comment]
Possibly related PR: https://github.com/fabric8io/fabric8-maven-plugin/pull/1060

**Comment by nicolaferraro** [comment]
@stevef1uk does it work with `mvn fabric8:run -Dfabric8.mode=kubernetes`?
