### ISSUE TITLE
overriding a ConfigMap from a dependency preserves a duplicate in the k8s-template.yml file

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#1062]
here's a sample repository:
https://github.com/fabric8-jenkins/fabric8-jenkins-platform

if you build it then look in the generated file `fabric8-jenkins-platform/packages/fabric8-jenkins-github/target/classes/META-INF/fabric8/k8s-template.yml` you'll see 2 `ConfigMap`'s called `jenkins` despite the `ConfigMap jenkins` being overridden in the source of the project via https://github.com/fabric8-jenkins/fabric8-jenkins-platform/blob/master/packages/fabric8-jenkins-github/src/main/fabric8/jenkins-kubernetes-cm.yml

it looks like the generation of the kubernetes Template needs to add a filter to avoid duplicates (picking the local generated resource ahead of any dependency)

**Comment by jstrachan** [comment]
there's also a duplicate `Secret jenkins-maven-settings` too I noticed

**Comment by hrishin** [comment]
@jstrachan this is fixed now. With the coming f-m-p release can we test this fix with fabric8 repos?
