### ISSUE TITLE
Release new 4.0.0 of fabric8-maven-plugin?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#1065]
we've just cut the new major version of the kubernetes-model (2.x), kubernetes-client (3.x) and fabric8 (3.x) to include the latest kubernetes 1.7 schema stuff inside.

it'd be nice to get a version of fabric8-maven-plugin out using the new schema (once it works ;).

Should we bump to a major new version for fabric8-maven-plugin to indicate the new schema version?

**Comment by jstrachan** [comment]
cc @nicolaferraro @ro14nd @hrishin

**Comment by jstrachan** [comment]
BTW a first spike of a PR to use 3.x of kubernetes-client here https://github.com/fabric8io/fabric8-maven-plugin/pull/1067

**Comment by nicolaferraro** [comment]
@jstrachan I'd go for a bump in the major version also for f-m-p.
