### ISSUE TITLE
sourceDir/outputDir for helm and target fabric8:distro are not working

### ISSUE THREAD

**Issue by rgsell** [fabric8io/fabric8-maven-plugin#1072]
### Description
We are trying to generate kubernetes configurations/helm as delivery for multiple environments. In our development environment we use additional configuration which is not necessary in release artefacts. Our approach is to use multiple fabric8 directories with resource fragments, let's say src/main/fabric8-dev and src/main/fabric8-prod, like mentioned in #729 . Is there an other way to achieve this goal?  

For each environment we have configured an execution with own targetDir configuration. Now we are experiencing the problem that we can not set the sourceDir for helm charts as expected.

```
<configuration>
  <resourceDir>${basedir}/src/main/fabric8-dev</resourceDir>
  <targetDir>${basedir}/target/classes/META-INF/fabric8-dev</targetDir>
  <helm>
    <chart>${helm.chart.name}-dev</chart>
    <sourceDir>${basedir}/target/classes/META-INF/fabric8-dev</sourceDir>
  </helm>
</configuration>
```
It looks like the sourceDir for helm is always loaded from property fabric8.helm.sourceDir, the helm config is ignored.
https://github.com/fabric8io/fabric8-maven-plugin/blob/9102af60e232c1ac6e2cc29d81ffd8f13f562bab/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java#L136-L139

As an alternative we have tried to use the target fabric8:distro to create a tarball to use as delivery but this doesn't work at all. The target always fails with:

> goal io.fabric8:fabric8-maven-plugin:3.5.31:distro failed: [local_module_path]/target/distro isn't a directory.

In this case the helm configuration for outputDir is also ignored as far as i can see in the Mojo.
https://github.com/fabric8io/fabric8-maven-plugin/blob/9102af60e232c1ac6e2cc29d81ffd8f13f562bab/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/DistroMojo.java#L157-L160

### Info

* f-m-p version : 3.5.31
* Maven version (`mvn -v`) :3.3.3

**Comment by elmguyc** [comment]
Hi @rgsell ,
Were you able to solve this problem? I'm having a similar issue.
It seems that the helm templates are stored under the folder 'target\classes\META-INF\fabric8\kubernetes', but when building the chart the plugin is looking in another folder target\classes\META-INF\fabric8\k8s-template.
Changing the helm configuration sourceDir to the first folder seems to be ignored by the plugin.
This problem even appears in the README.md sample output:
[WARNING] F8: Chart source directory /home/rohan/work/repos/fabric8-maven-plugin/samples/spring-boot/target/classes/META-INF/fabric8/k8s-template does not exist so cannot make chart fabric8-maven-sample-spring-boot. Probably you need run 'mvn fabric8:resource' before.
thanks!

**Comment by rgsell** [comment]
Hi @elmguyc 

Thats does not relate to the issue described, but i experienced the same issue you are describing with the maven plugin update to 3.5.33. 
Since 3.5.32 with #1077 you can make use of a template to parametrise the helm chart. For the generation of the helm chart there is now the k8s-template expected (even if you don't make use of a template):
https://github.com/fabric8io/fabric8-maven-plugin/blob/426649978709e5654d0a144cc6f4d1c6d054884d/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java#L300-L307

The k8s-template is generated by fabric8:resource if you have placed a template.yaml in your fabric8 resource fragment folder (resourceDir: default "src/main/fabric8/"). Sadly this part is not well documented.

example template.yaml:
```
kind: Template
parameters:
- name: PROJECT_NAMESPACE
```

you're welcome.

**Comment by elmguyc** [comment]
that's it, thanks!

**Comment by fforloff** [comment]
@rgsell Thanks for your suggestion. Works like a charm. One question - have you figured out how to deal with integers? The Openshift way (i.e. ${{ integer_parameter }} ) does not seem to work for me.

**Comment by rgsell** [comment]
@fforloff I'm not sure what you are trying to achieve. The fabric8 templates will be processed by the maven plugin and ${*} will be replaced with the maven property (this is a String replacement). At the end you get kubernetes (or openshift) resources enriched by fabric8 and with replaced properties. 
See https://maven.fabric8.io/#build-filtering (you could also configure the filter delimiters).

**Comment by rohanKanojia** [comment]
@fforloff @rgsell @elmguyc: Hi, Are you guys still using `fabric8:helm`? We're cleaning up unneeded Mojos and would appreciate your response.

**Comment by fforloff** [comment]
Hi, yes we are using fabric8:helm - with all the drawbacks I still find it
convenient.

**Comment by elmguyc** [comment]
Hi, we are not using fabric8:helm, thanks.

**Comment by alexscal** [comment]
yeah, I would like to start using fabric8:helm to generate the charts for all the microservices.

**Comment by retogsell** [comment]
Hi, we are not using helm charts in production yet because of described issue.
