### ISSUE TITLE
HelmMojo strips extension from README.md file when creating helm package

### ISSUE THREAD

**Issue by djotanov** [fabric8io/fabric8-maven-plugin#1073]
### Description
If the project has README.md file, after running "mvn fabric8:helm" the resulting tar.gz archive contains file README without the ".md" extension

* f-m-p version : 3.5.31
* Maven version (`mvn -v`) : 3.5.0

* If it's a bug, how to reproduce :
- Create new fabric8 project and place empty file README.md in the root of the project
- Run "mvn fabric8:helm"
- Observer that the resulting archive contains file README (instead of README.md)

**Comment by rohanKanojia** [comment]
@djotanov : Hi, Do you still use `fabric8:helm` goal? We are cleaning up unused Mojos and right now we're not sure whether it's actually used or not.

**Comment by djotanov** [comment]
I do use it. Thats one of the most useful features for me. Is there an alternative way for creating helm charts using fabric8?

**Comment by rohanKanojia** [comment]
@djotanov : Alright, Thanks. Unfortunately I'm not aware of any other way of creating helm charts. Actually we're cleaning up unneeded Mojos in PR(linked above) and were not sure whether to keep HelmMojo or not.
