### ISSUE TITLE
Update the CHANGELOG.md

### ISSUE THREAD

**Issue by getjack** [fabric8io/fabric8-maven-plugin#1078]
Please have a place where you post the changes of the maven plugin.

There are no release notes, the webpage is horribly out of date and the CHANGELOG.md file has been abandoned. There is no way to figure out what has changed or breaks my project building except lurking through all the commits or diffs.

I guess you/ we can fix that.

**Comment by hrishin** [comment]
@getjack totally agreed. It's not that organized yet but will try to accommodate it.
Thanks for reporting this.
