### ISSUE TITLE
fabric8-includes does not seem to work with Karaf generator

### ISSUE THREAD

**Issue by cunningt** [fabric8io/fabric8-maven-plugin#1079]
The JavaExecGenerator supports adding additional files to the docker image if they are put into src/main/fabric8-includes or src/main/fabric8-includes/bin  : 

https://github.com/fabric8io/fabric8-maven-plugin/blob/master/generator/java-exec/src/main/java/io/fabric8/maven/generator/javaexec/JavaExecGenerator.java#L196-L197

The KarafGenerator extends the BaseGenerator and not JavaExecGenerator and does not seem to support this.   

https://github.com/fabric8io/fabric8-maven-plugin/blob/master/generator/karaf/src/main/java/io/fabric8/maven/generator/karaf/KarafGenerator.java

The documentation is pretty clear that fabric8-includes is a feature, it should work for Karaf images as well.

### Info

* f-m-p version : 3.5.17
* Maven version (`mvn -v`) : 3.3.9
```

```

**Comment by davsclaus** [comment]
Karaf needs to be started using a script and hence why its not extending the java-exec generator.

**Comment by davsclaus** [comment]
What is your use-case?

**Comment by cunningt** [comment]
Use case is adding a custom jolokia or prometheus configuration or a custom javaagent.

**Comment by rohanKanojia** [comment]
let me pick this up.
