### ISSUE TITLE
Setting options for docker building

### ISSUE THREAD

**Issue by stefanmakarewicz** [fabric8io/fabric8-maven-plugin#1089]
I want to use standard --no-cache --pull and --rm options during building docker image but don't know how. I'm using external Dockerfile. I've tried this:
`<image>
...
<build>
<buildOptions>
<rm />
</buildOptions>
</build>`
but this end with NullPointerException.
Any hint?

**Comment by rohanKanojia** [comment]
@stefanmakarewicz : I see in[ dmp documentation](http://dmp.fabric8.io/#build-configuration) that these options are mentioned, although there is no example for xml config. Could you please take a look there again(if you haven't) and see if it helps ;-)
