### ISSUE TITLE
convention for running locally (spring-boot:run) versus on kubernetes/openshift (mvn install fabric8:deploy)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#109]
I wonder if we should have a goal `mvn fabric8:run` that's the cluster equivalant of `mvn spring-boot:run` for locally running things which also ensured that the `install goal` was run?

I've been setting the `<defaultGoal/>` for funktion stuff to be `spring-boot:run` for local stuff; wonder if we should add a profile to act as a simple alias for `mvn install fabric8:deploy` as its quite a mouthful to type. 

Not sure of a concise catchy name yet though ;). Any good suggestions?

How about:

```mvn -Pf8```

**Comment by rhuss** [comment]
Aggree that there should be an single goal for doing the whole workflow. However I'm still not sure whether to sacrifice the `fabric8:run` slot for this :). I'm still thinking whether it would make sense to bring in `docker:run` in some form into this plugin for easy local, docker based development and testing but withouth Kubernetes:

* All images with a `<build>` (either explicitely configured or determined by a customizer) are started as container sharing a single container's networks space (that's how pod works, with a network mode 'container')
* All images without a build section (but a `<run>` section as known from d-m-p) are started along in a custom network, which also the app-pod joins
* Integration tests can run against this, you can develop against this and use nicely `docker:watch` (or the fabric8 equivalent). 

This is just an idea, don't know whether it make sense and whether it in scope of this plugin. It would make only sense, if for the development its 'close enough' to the target platform and if the developing against the target platform (k8s/os) is to painful to that this mode would add some value.

Back to the original question, some name suggestions for a combined goals:

* `fabric8:fabric8`
* `fabric8:all`
* `fabric8:go`
* `fabric8:bring-it-on` :) ....

The profile would be also an alternative but is not combinable with other goals, so I'd prefer a dedicated goal.

`docker:source` will include the other phases, too, by forking the lifefcyle, there will be soon a `docker:source-nofork` for attaching this to an execution (where forking doesnt make sense). Could this be an option for `fabric8:deploy`, too ?

E.g. 

```java
@Mojo(name = "deploy", defaultPhase = LifecyclePhase.INSTALL)
@Execute(phase = LifecyclePhase.INSTALL)
public class DeployMojo extends AbstractFabric8Mojo {
// ...
}
```

**Comment by jstrachan** [comment]
We've experimented with no-kubernetes local machine stuff before; e.g. auto-generating environment variables to simulate being inside kubernetes (e.g. the old [mvn fabric8:create-env](http://fabric8.io/guide/mavenFabric8CreateEnv.html) command).

The thing is things soon break down on any vaguely real world app due to secrets, ConfigMap, Service Accounts, volumes, service discovery, load balancing, scaling or use of the kubernetes API. Given that anyone on a mac or windows machine needs to run a VM to run docker anyways; it seems simpler to just focus on really running things in kubernetes all the time; rather than trying to plug all the leaky abstractions? If folks wanna focus on pure docker, there's the docker-maven-plugin for that. I'd rather the fabric8 plugin focus 100% on running on kubernetes/openshift (even if thats just 1 local VM).

Even if 'pure docker' was an option; its easy to really run kubernetes on docker anyways  too ;) - plus I suspect its going to be rarer to use pure docker than kubernetes; so I'd sooner have `fabric8:run` be 'run my app on kubernetes' and have `fabric8:docker-run` to remove all the kubernetes stuff but just run some docker images as best you can - ignoring most of the kubernetes manifest metadata that doesn't apply to docker?

I do like, whatever we call the goal, (deploy/run/whatever) - having it bind to install so it can be a single goal. I'm kinda liking `fabric8:run` TBH; as folks tend to think of deploy as installing jars in a remote mvn repo; which we don't tend to do when running things on k8s - we just make a local docker image and run it (via rolling upgrade / create / apply of resources).

**Comment by rhuss** [comment]
Convinced :)

I agree, that we shouldn't go the leaky abstraction route, its just too painful and maintenance intensive and probably doesnt add much value anyway.

I'm also ok with `fabric8:run` (`docker:run` was introduced only recently as an alias for `docker:start` mostly because I constantly typed it wrong :). So lets introduce a `fabric8:run`. The question is how to do this best:

* An alternative to `fabric8:deploy` but forking the lifecycle. But then you have to ensure that `fabric8:resource` and `fabric8:build` is bound to the executions (in some parent pom), otherwise they wouldn't be called.
* Dispatching internally to the Mojos (or the functionality behind it). E.g. RunMojo would call into ResourceMojo, BuildMojo and DeployMojo (if this is technically possible, but should be because I had sth similar for a `postWatchGoal` in d-m-p. However, any Maven phases in between (like compile) would be skipped here. Maybe not what we want.

So the most simple way is probably to fork the lifecycle. As said, we need to ensure that then 

```xml
       <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
```

need to be present. Or we define an own packaging `fabric8` which includes this in its lifecycle description. 

Are there any other options ?

btw, mixing d-m-p and f-m-p in one pom.xml is probably not so a good idea, because there is no easy way to share the configuration (and hence would need to be duplicated).

**Comment by jstrachan** [comment]
I guess we could add fabric8:docker-run for the pure docker case if we needed it. Not sure its worth it TBH though.

I do like the `fabric8` packaging option for spring boot apps on kubernetes & would like to try it out. Until then I've been putting those executions into projects already; so we should be in good shape if we fork the lifecycle to ensure the run/deploy Mojo ensures the install phase is done first?

**Comment by rhuss** [comment]
@jstrachan yep, guess its worth a try. its only subclassing DeployMojo and add the proper annotation.

Would you like to do it, or should I give it a try ? (its really a quick one).

**Comment by jstrachan** [comment]
I'm a bit knee deep in jboss forge stuff right now but can have a try later if you like; feel free to dive in if you want ;). The funktion quickstarts or the spring boot quickstarts are handy apps we can use to try things out now BTW

* https://github.com/fabric8-quickstarts/spring-boot-camel
* https://github.com/fabric8-quickstarts/funktion-java-example

**Comment by rhuss** [comment]
cool, so I will pick up this one.

**Comment by jstrachan** [comment]
I think this is all sorted now
