### ISSUE TITLE
Improve fabric8 Import

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#1091]
Improve the fabric8:import goal 

- to support adding webhooks
- other git providers like bitbucket, gitlab
- IT and UT test cases
- Refactoring of vars, methods that are irrelavant

**Comment by kameshsampath** [comment]
it improves on #1081

**Comment by hrishin** [comment]
Two more things:
* import without Jenkins file
* possible to have custom build config #1070

**Comment by dev-gaur** [comment]
Is this issue relevant now ? fabric8:import is out of the plugin now.
