### ISSUE TITLE
Stacktrace when being offline and the schema files couldn't be downloaded

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1092]
When I prepared a demo for f-m-p while being offline (train ride), then the json schema files couldn't be downloaded. There was a warning, but also a very ugly stacktrace printed out. This should be avoided (or only put out when debugging is on)

I wonder whether we could optimize the schema download, as I generally don't consider it a good practive to use an external system (github) when doing a build. There can be always all sort of network issues (or github being done).

Some suggestion:

* Package the json schema files (which fit to the kubernetes client in use) directly into the JAR. This is my prefered option.
* Cache the json files and fallback if they could not be downloaded. 

Maybe combined with an option to download it on demand ?

**Comment by hrishin** [comment]
hey @rhuss 
Fixing the stack trace issue. :)

Yes, we are getting rid of external JSON schema soon.  #1051

**Comment by rhuss** [comment]
cool thanks ;-)

**Comment by hrishin** [comment]
issue is fixed now :)
