### ISSUE TITLE
Setting environment variable DOCKER_CONTENT_TRUST

### ISSUE THREAD

**Issue by adam66** [fabric8io/fabric8-maven-plugin#1098]
How do you set the DOCKER_CONTENT_TRUST environment variable in a d-m-p section to ensure that downloaded docker images are properly signed and not tampered with?

I can't even see how to set any docker environment variable so i guess I'm missing a piece of the puzzle. 

* f-m-p version : 0.22.1
* Maven version (`mvn -v`) : 3.3.9

**Comment by rohanKanojia** [comment]
Did you accidently posted dmp issue on fmp(fmp includes dmp bdw :-) )? Anyways, please take a look at http://dmp.fabric8.io/#property-configuration and see if it helps :)
