### ISSUE TITLE
fabric8:debug keeps giving Connection Refused Error

### ISSUE THREAD

**Issue by deepank-sharma** [fabric8io/fabric8-maven-plugin#1116]
After deploying my application in minikube, when I run mvn fabric8:debug from another tab in the Terminal and tries to attach a remote debugger from STS [Eclipse] on a Spring Boot app, the debugger keeps failing with Connection Refused error.
### Info
[WARNING] F8:port-forward E1129 22:31:02.006587   53164 portforward.go:331] an error occurred forwarding 5005 -> 5005: error forwarding port 5005 to pod 70be95b7a71f7430b22782dbb8a5577b4c856862e12480305541e1b268e7a002, uid : exit status 1: 2017/11/30 03:31:01 socat[14252.140167599941376] E connect(5, AF=2 127.0.0.1:5005, 16): Connection refused

* f-m-p version : 3.5.33
* Maven version (`mvn -v`) : 3.5.0
```

```
* Kubernetes / OpenShift setup and version : minikube version: v0.22.2
* Sample project : https://github.com/deepank-sharma/ms_travel_project_v2

**Comment by rhuss** [comment]
I think there has been a race introduced recently. If you run `mvn fabric8:debug` a second time right after this call, does it work then ? (This happened to work for me when I did a demo lately)

**Comment by deepank-sharma** [comment]
I tried it, still does not work. I am working on a Mac though. Steps:
1. Started my application through mvn fabric8:deploy fabric8: log
2. Opened a new terminal mvn fabric8:debug. I saw it restarted my POD with JAVA_DEBUG_ENABLED as true.
3. Opened my project in STS, created a new Remote Java Debug Config at localhost:5005.
4. As soon as I hit Debug I get following error in STS 
Failed to connect to remote VM
com.sun.jdi.connect.spi.ClosedConnectionException

5. The logs under fabric8:debug terminal shows 
[WARNING] F8:port-forward E1130 13:22:29.041177   26253 portforward.go:331] an error occurred forwarding 5005 -> 5005: error forwarding port 5005 to pod fc10c5e39a65935953b3e099aca08266e0c8f863b9bd1314398a13bc3167ca49, uid : exit status 1: 2017/11/30 18:22:28 socat[5065.140221186778880] E connect(5, AF=2 127.0.0.1:5005, 16): Connection refused

I tried closing the current session and restarting , still get the same error.

**Comment by deepank-sharma** [comment]
Attached complete set of logs from fabric8:debug window, if it helps 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building ms-travel-website 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.33:debug (default-cli) @ ms-travel-website ---
[INFO] F8: Using Kubernetes at https://192.168.99.100:8443/ in namespace default with manifest /Users/sharde6/Downloads/ms_travel_project_v2/target/classes/META-INF/fabric8/kubernetes.yml 
[INFO] Using namespace: default
[INFO] Updating a Service from kubernetes.yml
[INFO] Updated Service: target/fabric8/applyJson/default/service-ms-travel-website-1.json
[INFO] Using namespace: default
[INFO] Updating ConfigMap from kubernetes.yml
[INFO] Updated ConfigMap: target/fabric8/applyJson/default/configmap-ms-travel-website-1.json
[INFO] F8: Enabling debug on Deployment ms-travel-website
[INFO] F8: Waiting for debug pod with selector LabelSelector(matchExpressions=[], matchLabels={app=ms-travel-website, provider=fabric8, group=com.mytravel}, additionalProperties={}) and $JAVA_ENABLE_DEBUG = true
[INFO] F8:[W] ms-travel-website-1141802263-w60xc status: Running Ready
[INFO] F8:[W] ms-travel-website-2545493797-5ssxb status: Pending 
[INFO] F8:[W] ms-travel-website-1141802263-w60xc status: Running Ready
[INFO] F8:[W] ms-travel-website-2545493797-5ssxb status: Pending 
[INFO] F8:[W] ms-travel-website-1141802263-w60xc status: Running 
[INFO] F8:[W] ms-travel-website-1141802263-w60xc status: Running 
[INFO] F8:[W] ms-travel-website-2545493797-5ssxb status: Running 
[INFO] F8:[W] ms-travel-website-1141802263-w60xc status: Running 
[INFO] F8:[W] ms-travel-website-1141802263-w60xc status: Running : Pod Deleted
[INFO] F8:[W] ms-travel-website-2545493797-5ssxb status: Running Ready
[INFO] F8: Port forwarding to port 5005 on pod ms-travel-website-2545493797-5ssxb using command /usr/local/bin/kubectl
[WARNING] F8:port-forward E1130 13:22:12.106251   26253 portforward.go:331] an error occurred forwarding 5005 -> 5005: error forwarding port 5005 to pod fc10c5e39a65935953b3e099aca08266e0c8f863b9bd1314398a13bc3167ca49, uid : exit status 1: 2017/11/30 18:22:12 socat[4987.139655014201088] E connect(5, AF=2 127.0.0.1:5005, 16): Connection refused
[WARNING] F8:port-forward E1130 13:22:29.041177   26253 portforward.go:331] an error occurred forwarding 5005 -> 5005: error forwarding port 5005 to pod fc10c5e39a65935953b3e099aca08266e0c8f863b9bd1314398a13bc3167ca49, uid : exit status 1: 2017/11/30 18:22:28 socat[5065.140221186778880] E connect(5, AF=2 127.0.0.1:5005, 16): Connection refused

**Comment by deepank-sharma** [comment]
Found the solution, seems the connection was being terminated at the Pod but not reaching the container.
I added the following args to the image configuration in POM and was able to debug then.

<arg>-Xdebug</arg>
											<arg>-Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n</arg>
