### ISSUE TITLE
Docker run unable to access JAR file

### ISSUE THREAD

**Issue by anrvorc** [fabric8io/fabric8-maven-plugin#1121]
Hi, I am using XML Configuration method to generate Dockerfile for my project.The generated Dockerfile looks OK and it gets built fine. However when I run it it always fails with the error 

Error: Unable to access jarfile echo-0.0.1.jar

### Info

* f-m-p version : 3.5.31
* Maven version (`mvn -v`) : Apache Maven 3.3.9
* Kubernetes / OpenShift setup and version : N/A

My POM file: 

`		<plugin>
				<groupId>io.fabric8</groupId>
				<artifactId>fabric8-maven-plugin</artifactId>
				<version>3.5.31</version>

				<configuration>
					<images>
						<image>
							<name>echo-image:latest</name>
							<build>
								<entryPoint>
									<arg>java</arg>
									<arg>-jar</arg>
									<arg>/deployments/echo-0.0.1.jar</arg>
								</entryPoint>
								<from>fabric8/java-alpine-openjdk8-jdk:1.2</from>
								<user>root</user>
								<tags>
									<tag>latest</tag>
								</tags>
								<ports>
									<port>7000</port>
								</ports>
								<env>
									<JAVA_LIB_DIR>/deployments</JAVA_LIB_DIR>
								</env>
								<assembly>
									<basedir>/deployments</basedir>
									<descriptorRef>artifact</descriptorRef>
								</assembly>

							</build>
							
						</image>
					</images>
				</configuration>
			</plugin>`

Generated Docker File: 
`FROM fabric8/java-alpine-openjdk8-jdk:1.2
ENV JAVA_LIB_DIR=/deployments
EXPOSE 7000
COPY maven /deployments/
ENTRYPOINT ["java","-jar","/deployments/echo-0.0.1.jar"]
USER root`

mvn build:
`mvn clean package fabric8:build`

Docker run:
`Error: Unable to access jarfile /deployments/echo-0.0.1.jar`

What am I missing? It is frustrating to not able to get this to work. Please help!

**Comment by hrishin** [comment]
@anrvorc answer for this is on [StackOverflow](https://stackoverflow.com/questions/47612400/docker-run-unable-to-access-jar-file) 
Hope this helps :)
