### ISSUE TITLE
fabric8:build converting tcp to http within dockerHost

### ISSUE THREAD

**Issue by anrvorc** [fabric8io/fabric8-maven-plugin#1129]
### Description
I am working on creating a Jenkins build from mvn fabric8:build. I've specified dockerHost value within my pom.xml. While executing the build the dockerHost protocol is getting converted from tcp to http.

Please help to resolve this issue.

Docker is running on linux 7
Docker daemon.json

`
{
  "ipv6": false ,
  "live-restore": true,
  "insecure-registries" : ["seng-docker.dockerhub-den.oraclecorp.com"],
"debug": true,
"hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]
}

`
`netstat -tunlp | grep 2375
tcp6       0      0 :::2375                 :::*                    LISTEN      10737/dockerd`

pom.xml

<configuration>
				   <dockerHost>tcp://10.80.188.123:2375</dockerHost>
					<images>
						<image>
							<name>echo-service-image:latest</name>
							<build>
								<entryPoint>
									<arg>java</arg>
									<arg>-jar</arg>
									<arg>/deployments/echo-0.0.1-SNAPSHOT.jar</arg>
								</entryPoint>
								<from>customImage</from>
								
								<tags>
									<tag>latest</tag>
								</tags>
								<ports>
									<port>8080</port>
								</ports>
								<env>
									<JAVA_LIB_DIR>/deployments</JAVA_LIB_DIR>
								</env>
								<assembly>
									<basedir>/deployments</basedir>
									<descriptorRef>artifact</descriptorRef>
								</assembly>

							</build>
							
						</image>
					</images>
				</configuration>

### Info

* f-m-p version : 3.5.31
* Maven version (`mvn -v`) : Apache Maven 3.3.9
```

Jenkins output
`[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[INFO] F8: Building Docker image in Kubernetes mode
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2017-12-07 21:22:53 INFO  RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.80.188.123:2375: No route to host
2017-12-07 21:22:53 INFO  RetryExec:113 - Retrying request to {}->http://10.80.188.123:2375
2017-12-07 21:22:53 INFO  RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.80.188.123:2375: No route to host
2017-12-07 21:22:53 INFO  RetryExec:113 - Retrying request to {}->http://10.80.188.123:2375
2017-12-07 21:22:53 INFO  RetryExec:97 - I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://10.80.188.123:2375: No route to host
2017-12-07 21:22:53 INFO  RetryExec:113 - Retrying request to {}->http://10.80.188.123:2375
[ERROR] F8: Cannot create docker access object  [Cannot extract API version from server **http:**//10.80.188.123:2375 : No route to host]`

**Comment by rohanKanojia** [comment]
@anrvorc : Where exactly are you specifying `dockerHost`? Could you please share complete pom.xml so that we could reproduce it?
