### ISSUE TITLE
build logs and status is not working with OpenShift

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1132]
### Description
For OpenShiftv3.7 build logs not coming with build goal. It keeps throwing following `backoff` messages 

### Info
-> [INFO] F8: Creating ImageStream http-vertx
-> [INFO] F8: Starting Build http-vertx-s2i
-> [INFO] F8: Waiting for build http-vertx-s2i-1 to complete...
-> [INFO] Current reconnect backoff is 1000 milliseconds (T0)
-> [INFO] Current reconnect backoff is 2000 milliseconds (T1)
-> [INFO] Current reconnect backoff is 4000 milliseconds (T2)
-> [INFO] Current reconnect backoff is 8000 milliseconds (T3)
-> [INFO] Current reconnect backoff is 16000 milliseconds (T4)
-> [INFO] Current reconnect backoff is 32000 milliseconds (T5)

* f-m-p version : v3.5.34 
* Maven version (`mvn -v`) : 
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T17:23:38+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-1.b12.fc25.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.10-200.fc25.x86_64", arch: "amd64", family: "unix"
```

```
* Kubernetes / OpenShift setup and version : v3.7.0
* If it's a bug, how to reproduce : run mvn fabric8:build
* If it's a feature request, what is your use case : issue
* Sample project : https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/spring-boot

**Comment by hrishin** [comment]
### Description
For OpenShiftv3.7 build logs not coming with build goal. It keeps throwing following `backoff` messages 

### Info
 java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@399df1a2 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7c9f68f5[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
-> 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
-> 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
-> 	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
-> 	at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$3.run(WatchHTTPManager.java:207)
-> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
-> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
-> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
-> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
-> 	at java.lang.Thread.run(Thread.java:748)

* f-m-p version : v3.5.34 
* Maven version (`mvn -v`) : 
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T17:23:38+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-1.b12.fc25.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.10-200.fc25.x86_64", arch: "amd64", family: "unix"
```

```
* Kubernetes / OpenShift setup and version : v3.7.0
* If it's a bug, how to reproduce : run mvn fabric8:build
* If it's a feature request, what is your use case : issue
* Sample project : https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/spring-boot

**Comment by rohanKanojia** [comment]
Confirmed, build logs are not showing up on OpenShift 3.7.0. These reconnect
backoff statements appearing in logs are from WatchHttpManager. basically, reconnect attempts whenever we have lost our watch.

Watching over pods in OpenShift 3.7.0, I observed that build pod is taking some time
to get ready, and some more intermediate states:

```

fabric8-maven-sample-spring-boot-s2i-4-build   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-s2i-4-build   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-s2i-4-build   0/1       Init:0/2   0         0s
fabric8-maven-sample-spring-boot-s2i-4-build   0/1       Init:0/2   0         2s
fabric8-maven-sample-spring-boot-s2i-4-build   0/1       Init:1/2   0         4s
fabric8-maven-sample-spring-boot-s2i-4-build   0/1       PodInitializing   0         5s
fabric8-maven-sample-spring-boot-s2i-4-build   1/1       Running   0         6s
fabric8-maven-sample-spring-boot-2-deploy   1/1       Terminating   0         16s
fabric8-maven-sample-spring-boot-2-deploy   0/1       Terminating   0         17s
fabric8-maven-sample-spring-boot-s2i-4-build   0/1       Completed   0         10s
fabric8-maven-sample-spring-boot-3-deploy   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-3-deploy   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-3-deploy   0/1       ContainerCreating   0         0s
fabric8-maven-sample-spring-boot-3-deploy   1/1       Running   0         1s
fabric8-maven-sample-spring-boot-2-deploy   0/1       Terminating   0         18s
fabric8-maven-sample-spring-boot-2-deploy   0/1       Terminating   0         18s
```
On the other hand, when i run these on OpenShift 3.6.0, i get:
```
fabric8-maven-sample-spring-boot-s2i-1-build   0/1       Pending   0          0s
fabric8-maven-sample-spring-boot-s2i-1-build   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-s2i-1-build   0/1       ContainerCreating   0         0s
fabric8-maven-sample-spring-boot-s2i-1-build   1/1       Running   0         7s
fabric8-maven-sample-spring-boot-s2i-1-build   0/1       Completed   0         1m
fabric8-maven-sample-spring-boot-s2i-2-build   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-s2i-2-build   0/1       Pending   0         0s
fabric8-maven-sample-spring-boot-s2i-2-build   0/1       ContainerCreating   0         0s
fabric8-maven-sample-spring-boot-s2i-2-build   1/1       Running   0         1s
fabric8-maven-sample-spring-boot-s2i-2-build   0/1       Completed   0         6s
fabric8-maven-sample-spring-boot-1-deploy   0/1       Pending   0         0s
```
