### ISSUE TITLE
Regression test issues

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1135]
Regression tests are not running well on CI systems

- [x] Test behavior on Travis environment is intermittent. Sometimes tests are getting failed with some errors in f8-m-p like #1133 #111. The potential reason for test failure could be test environment infrastructure or issues with f8-m-p. 
 - [x] Fixed the build issue for OpenShift v3.7 #1130 as its affecting overall test behavior and performance as well

**Comment by hrishin** [comment]
Related to #1103

**Comment by piyush1594** [comment]
@hrishin Can we close this issue?
