### ISSUE TITLE
regression test for Vertx http booster is failing

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1149]
### Description
The regression test for vertx http booster is failing on Travis CI. This behavior is sporadic and usually happens with OpenShift v3.6.0., v3.6.1
Its an issue with the assertion that verifies application endpoint response. Its observed that creating application route may take some time. Before that assertion invokes the application endpoint.

**Comment by rohanKanojia** [comment]
Hey @hrishin,
I tried reproducing it but somehow not able to. Could you please elaborate the kind of error you're watching in logs?, I build a branch 2-3 times but build completed cleanly. You can have a look at it [here](https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/jobs/325138118) and [here](https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/jobs/325138124).

Although one thing I noticed is the breaking watch and repeated reconnect attempts:
```
-> [INFO] Current reconnect backoff is 1000 milliseconds (T0)
-> [INFO] F8: Build spring-boot-rest-http-crud-s2i-5 Complete
-> [INFO] Current reconnect backoff is 2000 milliseconds (T1)
-> [ERROR] Exception in reconnect
-> java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@6b4a6e4d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@2e48ed40[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
-> 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
-> 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
-> 	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
-> 	at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$3.run(WatchHTTPManager.java:207)
-> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
-> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
-> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
-> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
-> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
-> 	at java.lang.Thread.run(Thread.java:748)
```

I wonder if we can get rid of this reconnect backoff messages, maybe increase the reconnect timeout interval. What do you think?

**Comment by hrishin** [comment]
hey @rohanKanojia it's hard to reproduce it. Didn't able to capture the logs. I observed Its an issue with https://github.com/fabric8io/fabric8-maven-plugin/blob/master/rt/src/test/java/io/fabric8/maven/rt/VertxHttpBoosterIT.java#L89, where it invoke application rest endpoint and it gets empty/error message response. Right now test wait for application pod to come up but it looks like time for creating route and service may vary. Even though test already has some [delay](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/rt/src/test/java/io/fabric8/maven/rt/BaseBoosterIT.java#L386  ) to wait until all resources get prepared.

**Comment by rohanKanojia** [comment]
Okay, after lots of attempts I was able to reproduce the bug you mentioned. Is it [this](https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/jobs/329151804) one?

**Comment by rohanKanojia** [comment]
Regarding these exceptions in reconnect error messages, I 'm filing a separate issue [here](https://github.com/fabric8io/fabric8-maven-plugin/issues/1159). It can be taken into consideration sometime later.

**Comment by rohanKanojia** [comment]
Okay, So I've been testing builds on Travis CI again and again. You can have a look at all the jobs [here](https://travis-ci.org/rohanKanojia/fabric8-maven-plugin/builds). After that, i was able to reproduce the bug you reported. But then again, reproducing it again is tough. I'm just wondering whether this has something to do with the Travis CI environment itself. I'm gonna try the same thing with CircleCI also.
