### ISSUE TITLE
3.5.34 release not available in Maven central

### ISSUE THREAD

**Issue by mojsha** [fabric8io/fabric8-maven-plugin#1158]
I can see that F-M-P has gone through parts (or whole?) of the release process but unable to find it in Maven central?

I primarily need to have the dependency on external JSON schemas removed (https://github.com/fabric8io/fabric8-maven-plugin/issues/1051). 

Has the release process failed somewhere? I can see a 3.5.34 tag.

**Comment by rohanKanojia** [comment]
@hrishin @piyush1594 : Do you have any idea about this? If the release process has failed somewhere, maybe we can remove the tag or retrigger release?

**Comment by hrishin** [comment]
Tasks to fix the issues:
- [ ] fix the test case 
- [ ] fix the Jenkins release process. Right now its release first and tets, it should be test first and then release.

**Comment by piyush1594** [comment]
@mojsha 

We are working on the issue and will fix them soon. For the time being, 3.5.34 is now available on maven central.

You can check it [here](https://mvnrepository.com/artifact/io.fabric8/fabric8-maven-plugin)

Thanks

**Comment by piyush1594** [comment]
Since #1170 and #1179 are merged, I am closing this issue.
