### ISSUE TITLE
by default copy annotations from a Deployment -> RS pod template and DeploymentConfig -> RC

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#116]
it looks like if you create a DeploymentConfig with annotations they are lost from the RC that gets created. Am not sure if the same is true for Deployment -> RS yet; but we should probably copy annotations from a `Deployment(Config).metadata.annotations` -> `spec.template.metadata.annotations`

I guess this is a customizer?

**Comment by rhuss** [comment]
If you mangle a k8s resource thant its an *enricher*. If you create Docker image configuration, then its a *customizer*.

But I see this is confusing and tbh I don't like the current naming either. So, my suggestion is:

* **starter** : For creating Docker images on the fly by detecting dependencies and available classes
* **enricher** : For adding labels and annotations 
* **customizer** : For creating new resource objects or more advanced customizations

ok so ?

**Comment by jstrachan** [comment]
well its enriching; by adding annotations to the podTemplate from the metadata; so I guess its enriching? Not sure though - adapter?

**Comment by rhuss** [comment]
Ok, maybe then only `enricher` (as it is now) and `starter` (formerly: `customizer`).

*fabric8 starter*s are the pendant to *spring boot starter*s as they add an image configuration from scratch (merely by adding a dependency). *customize* does not fit so well as it is implies that there is already something to customize (which is not, the config is created afresh). 

(said that a *starter* can still customize existing configuration, but it is not its main purpose)
