### ISSUE TITLE
Fix the Jenkins release workflow 

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1166]
Current workflow F8MP release on Jenkins is 
checkout project snapshot -> tag release on Github-> build and test project -> publish the project to maven central

Change it to
checkout project snapshot -> build and test project -> tag release on Github ->publish the project to maven central

**Comment by piyush1594** [comment]
@hrishin I am closing this issue as #1170 is merged. Thanks
