### ISSUE TITLE
Deployment does not complete with OpenShift 3.7.1

### ISSUE THREAD

**Issue by galderz** [fabric8io/fabric8-maven-plugin#1168]
I'm having issues with fabric8 maven plugin version 3.5.33 and OpenShift 3.7.1.

When I type `mvn fabric8:deploy`, the command ends fine but shows this error:

In OpenShift, the deployment does not complete and I see events like this repeated:

```
11:15:43 AM | app-3-pjzmc | Pod | Warning | Failed | Error: ErrImagePull4 times in the last minute
-- | -- | -- | -- | -- | --
11:15:43 AM | app-3-pjzmc | Pod | Warning | Failed | Failed to pull image "app:latest": rpc error: code = 2 desc = Error response from daemon: {"message":"repository app not found: does not exist or no pull access"}4 times in the last minute
11:15:41 AM | app-3-pjzmc | Pod | Normal | Pulling | pulling image "app:latest"4 times in the last minute
11:15:25 AM | app-3-pjzmc | Pod | Normal | Back-off | Back-off pulling image "app:latest"4 times in the last minute
11:15:25 AM | app-3-pjzmc | Pod | Warning | Failed | Error: ImagePullBackOff4 times in the last minute
```

Looking at the mvn logs, I see this message appearing:

```
[INFO] F8: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"sti-build\" in pod \"app-s2i-2-build\" is waiting to start: PodInitializing","reason":"BadRequest","code":400}
```

Full logs are [here](https://gist.github.com/galderz/8c5015d7a9ae85296fadb292df65a56e).

Any idea what could be causing this?

Cheers,
Galder

**Comment by galderz** [comment]
The plugin configuration I'm using is:

```
        <plugin>
          <groupId>io.fabric8</groupId>
          <artifactId>fabric8-maven-plugin</artifactId>
          <version>${fabric8-maven-plugin.version}</version>
          <executions>
            <execution>
              <id>fmp</id>
              <goals>
                <goal>resource</goal>
                <goal>build</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <resources>
              <labels>
                <all>
                  <property>
                    <name>solution</name>
                    <value>${workshop.solution}</value>
                  </property>
                </all>
              </labels>
            </resources>
          </configuration>
        </plugin>
```

**Comment by rohanKanojia** [comment]
Hi @galderz ,

Which project are you using for fabric8 maven plugin? Build process in OpenShift 3.7 has become a bit slower as compared to the previous versions. This [issue](https://github.com/fabric8io/fabric8-maven-plugin/issues/1132) has been fixed, have a look. This fix is available in 3.5.34, which is now available on maven central.

**Comment by galderz** [comment]
I was trying it out in [this project](https://github.com/galderz/vert.x-openshift). I'll try 3.5.34.

**Comment by galderz** [comment]
Same issue happening with 3.5.34, [here's](https://gist.github.com/galderz/ec4c89c125b73854d95b25b8677cdce1) the maven log.

**Comment by galderz** [comment]
This is happening in a [different project](https://github.com/infinispan-demos/streaming-data-workshop/tree/master/stations-injector). I've recreated with verbose Maven logging, here's the more complete [output])(https://gist.github.com/galderz/b388b8e320b46cffc2a16cd375a072a2).

**Comment by galderz** [comment]
Btw, I think there's really a problem here. Here's more info with an example:

OpenShift had version 5 of the application and run `mvn fabric8:deploy`. Then I call `mvn fabric8:deploy` which finishes at `13:24:25`.

8 minutes later OpenShift eventually deploys version 8 of the application!. You can see [here](https://gist.github.com/galderz/da5931761f164da4b913da8116a475fd) all the events leading up to it.

This is not a problem of being slow, there's a bug and it's simply not usable.

**Comment by rohanKanojia** [comment]
I think this issue is related to OpenShift 3.7 rather than fabric8 maven plugin, have a look at this [issue](https://github.com/fabric8io/fabric8-maven-plugin/issues/1130).

**Comment by djohnston89** [comment]
same issue on 3.6. works for first deploy, but after undeploying and deploying again we get the same image pull issues.

**Comment by rohanKanojia** [comment]
@djohnston89 @galderz : Are you guys still facing this issue on Openshift 3.9.0 ? There was a bug in Openshift related to rolling deployments which got back-ported to 3.7.2

**Comment by galderz** [comment]
I've not used FMP in a while and hence have not tried with recent OpenShift versions
