### ISSUE TITLE
Unable to deploy to an Opeshift 3.5 cluster using FMP 3.5.34

### ISSUE THREAD

**Issue by geoand** [fabric8io/fabric8-maven-plugin#1183]
### Description

When running the integration tests of [this](https://github.com/snowdrop/spring-boot-http-booster/tree/sb-1.5.10) project (which use Arquillian Cube) on an Openshift 3.5 cluster, I am getting the following error

```
java.lang.RuntimeException: io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException: Failure executing: POST at: https://osemaster.spring-boot.osepool.centralci.eng.rdu2.redhat.com:8443/oapi/v1/namespaces/gandrian/deploymentconfigs. Message: DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
Caused by: io.fabric8.kubernetes.clnt.v3_1.KubernetesClientException: Failure executing: POST at: https://osemaster.spring-boot.osepool.centralci.eng.rdu2.redhat.com:8443/oapi/v1/namespaces/gandrian/deploymentconfigs. Message: DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1", metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={})
```

The odd things is that when I the tests are run on an Openshift 3.7 cluster, everything works as expected.

Furthermore, when I change the version of f-m-p to `3.5.30` everything works just fine on both Openshift 3.5 and 3.7

### Info

* f-m-p version : 3.5.34
* Maven version (`mvn -v`) : 3.5.2
```

```
* Kubernetes / OpenShift setup and version : Openshift 3.5
* If it's a bug, how to reproduce : Run `mvn clean verify -Popenshift,openshift-it` on the sb-1.5.10 branch of the aforementioned project:
* Sample project : https://github.com/snowdrop/spring-boot-http-booster/tree/sb-1.5.10

### Notes
You can easily switch versions of fmp in the sample project by setting the `fabric8-maven-plugin.version` Maven property

**Comment by geoand** [comment]
In case it's not very clear, the easiest way to reproduce the problem is to make this single modification to the sample project:

Add the following lines in `pom.xml`

<properties>
  <fabric8-maven-plugin.version>3.5.34</fabric8-maven-plugin.version>  
</properties>

**Comment by piyush1594** [comment]
Hi @geoand

I am not sure but this may be a problem because of you are using latest fmp with latest model and client on previous Openshift.

New openshift generates api version like For DeploymentConfig: apps.openshift.io/v1

So latest fmp may be generating things like that and not supported on previous Openshift version.

You can try this thing if it works.

```
You can also set the apiVersion of the resource like in the case of SecurityContextConstraints :

SecuirtyContextConstraints scc = new SecurityContextConstraintsBuilder()
		.withApiVersion("v1")
		.withNewMetadata().withName("scc").endMetadata()
		.withAllowPrivilegedContainer(true)
		.withNewRunAsUser()
		.withType("RunAsAny")
		.endRunAsUser()
		.build();
```

Ideally, this should be a problem, I am not sure just my initial suspect.

Thanks

**Comment by geoand** [comment]
Hello @piyush1594,

I just wanted to add that doing the following:

```bash
mvn clean package fabric8:deploy -Dfabric8-maven-plugin.version=3.5.34 -DskipTests=true -Popenshift
``` 

also results in the following:

` Message: DeploymentConfig in version "v1" cannot be handled as a DeploymentConfig: no kind "DeploymentConfig" is registered for version "apps.openshift.io/v1"`

About the fix you propose, where would such a change be applied?

**Comment by geoand** [comment]
My best understanding of the problem is the following:

FMP `3.5.34` generates a `DeploymentConfig` using apiVersion `apps.openshift.io/v1` which is not something that Openshift `3.5` understands.
FMP `3.5.30` generated a `DeploymentConfig` using apiVersion `v1` which was correctly understood by Openshift `3.5`.

This raises the question whether Openshift 3.5 is meant to be supported by FMP `3.5.34` or not?
If it is meant to be supported then I guess FMP much determine the version of Openshift that is to be used before creating the `DeploymentConfig`

**Comment by piyush1594** [comment]
Hey @geoand 

I just checked locally building a sample project.

FMP 3.5.34 generates Deployment Config with apiVersion apps.openshift.io/v1

FMP 3.5.30 generates Deployment Config with apiVersion v1

If this is the case, then ideally it is breaking the compatibility with previous Openshift version.

@hrishin @rohanKanojia Need your input into this.

**Comment by geoand** [comment]
@piyush1594 Thanks for confirming!

Is there any documentation on what versions of Kubernetes/Openshift are meant to be supported with each FMP version?

**Comment by piyush1594** [comment]
@geoand 

I don't think we have a documentation for this. We need to start doing this. We need to create matrix table which should inform about a particular fmp version is compatible with following OpenShift or Kubernetes version.

Our documentation is here : https://maven.fabric8.io/

Thanks

**Comment by piyush1594** [comment]
Hey @geoand 

Can we close this issue as we have added matrix table? You can find the matrix table on the website here https://maven.fabric8.io/#compatibility-with-OpenShift-and-Kubernetes

and on GitHub here https://github.com/fabric8io/fabric8-maven-plugin/blob/master/README.md

Thanks

**Comment by geoand** [comment]
Hi @piyush1594 

I really like it! Thank you very much for this!
Feel free to close the issue :)

**Comment by piyush1594** [comment]
Thanks @geoand
