### ISSUE TITLE
Release is breaking on jenkins.cd.test.fabric8.io

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1195]

**Comment by piyush1594** [comment]
Hey @nicolaferraro @rhuss 

Need your help for few things related to PR build and FMP Release

1. The Jenkins file executed at https://ci.fabric8.io/job/fabric8-maven-plugin-pullreq-merge doesn't look like the one checked in with the code. Is the job configured to run a different Jenkins file? 

2. What is the difference b/w https://ci.fabric8.io/job/fabric8-maven-plugin-pullreq-merge and  https://ci.fabric8.io/job/fabric8-maven-plugin-pullreq

3. Are we using different Jenkins files for PR builds and release?

Thanks

cc @hrishin

**Comment by rohanKanojia** [comment]
I'm closing it. Feel free to reopen if anyone faces this again.
