### ISSUE TITLE
Add regression test for multimodule project

### ISSUE THREAD

**Issue by piyush1594** [fabric8io/fabric8-maven-plugin#1197]
Right now, the regression test suite has 6 scenarios of deployment and redeployment. It does not have any related to multimodule project deployment and redeployment.

It will be good to have a scenario of the multimodule project in regression test suite.

#1184 is an issue related to the multimodule project which is failing. These kind of issues can be known before if we do so.

**Comment by piyush1594** [comment]
Hey @geoand 

We are using this regression test https://github.com/fabric8io/fabric8-maven-plugin/blob/master/rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java

Can you please check the test and guide if this is resolving the above-mentioned issue.

Thanks

**Comment by geoand** [comment]
Hello @piyush1594 

It looks good to me, but I would also like to try and run it locally.
Do I need any special setup to do that, or will just using minishift and running the test work?

**Comment by piyush1594** [comment]
Hey,

Mentioning steps to run this test 
1. Run minishift
2. Clone FMP repo
3. Hit `cd rt`
4. Hit `mvn -Dtest="io.fabric8.maven.rt.SpringbootConfigmapBoosterIT" test`

Thanks

**Comment by geoand** [comment]
Thank you @piyush1594 !

I'll try that later on and let you know :)

**Comment by geoand** [comment]
The test looks good and mostly worked for me. It did fail once but for no apparent reason, the booster seemed to have been deployed correctly.

**Comment by piyush1594** [comment]
Thanks a lot @geoand for helping and trying out this. Are we good to close this issue or something needs to be done w.r.t multimodule project.

**Comment by geoand** [comment]
You are welcome!

I believe that the issue has been properly addressed, feel free to close.

Regards

**Comment by piyush1594** [comment]
@pradeepto @hrishin Can we close this?

**Comment by piyush1594** [comment]
I am closing this.
