### ISSUE TITLE
fix maven build performance issues with pipeline builds for OSIO

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1208]
It's been observed that maven takes significant time (around 10-11 mins) for the first build. For all subsequent builds, it takes around 1.5-2 minutes.
After observing detailed build [logs](https://gist.github.com/hrishin/ce8465075355d3f0be7ceb99d6b99895) for a VertX booster [application](https://github.com/hrishin/fmp-test7), it looks like maven build does a lot of tracking file writes to another local repository (/root/.mvnrepository/) from (/root/.m2/).
Jenkins spin ups build jobs in slave pods and use [maven builder image](https://github.com/fabric8io-images/maven-builder) to run the build. For creating slave pods Jenkins build uses [mavenPodtemplate](https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenTemplate.groovy#L36) from fabric8-pipeline-library.

Part of https://github.com/openshiftio/openshift.io/issues/2314

**Comment by kbsingh** [comment]
is it possible to relocate the path used for these maven downloads ?

**Comment by hrishin** [comment]
@kbsingh 
yes here is the [secret](https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/f2dc8a531ccc6f449263505fbe146b893bc52251/apps/jenkins/src/main/fabric8/jenkins-maven-settings-secret.yml#L4) contains maven settings

```
<settings>
  <!-- sets the local maven repository outside of the ~/.m2 folder for easier mounting of secrets and repo -->
  <localRepository>${user.home}/.mvnrepository</localRepository>

  <!-- lets disable the download progress indicator that fills up logs -->
  <interactiveMode>false</interactiveMode>
.......
.......
</settings>
```
being mounted as a [volume](https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenTemplate.groovy#L49) 

Two things to note:
`<localRepository>` : is changed
@rupalibehera @chmouel @jaseemabid any idea why it's changed?

`<interactiveMode>`: hides downloads logs
Wondering if initial assumption is wrong about downloading dependencies.

**Comment by jaseemabid** [comment]
I've almost no idea about the historical decisions that went into this project.

**Comment by rawlingsj** [comment]
@hrishin I just saw this fmp notification, the maven download logs are suppressed by this from memory https://github.com/fabric8io/fabric8-pipeline-library/blob/c835e8f/vars/mavenTemplate.groovy#L26 so it may well appear that nothing is happening but in fact it it's downloading dependencies.

There is no nexus so the first build downloads all dependencies from maven central, therefore it can take quite a while.  To avoid subsequent long build times there's a PV where build dependencies are cached resulting in much improved 1.5 - 2 min build times. 

Hope the info helps.

**Comment by hrishin** [comment]
It's confirmed now for the first build it downloads all dependencies and for the subsequent builds, it uses cached dependencies from the local repo. from attached PVC. Its usual behavior of maven builds that wait for downloading all dependencies, nothing specific to fabric8 maven plugin. Previously were getting the illusion that maven builds pause for doing some config scanning or re-write tracking files to a different location because download logs are disabled.

Ways to optimize the overall maven build process could be

**Caching**

_Improve local repository cache by shared volume: L1 cache_
Right now PV's are getting created with `ReadWriteOnce` [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) i.e it's attach the PV per node. This is proven and reduce the subsequent builds time but not for the first build. For the experiment, let's create a PV using `ReadWriteMany` [access mode](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) with more storage size. This mode will make that the same local repo (cached) volume get available across all build pods. In that way for the first build as well local maven repo get available for the build pod.
On another side, it could have some cons:
- Same volume being used by many build pods so it could become disk I/O bottleneck. 
- Consider more than two build pods running simultaneously. If they are downloading/requesting the same dependencies then potentially it could bring those dependencies in the inconsistent state.
@rohanKanojia and me did experiment with this kind of setup. We run 3-4 build pods simultaneously 
All of them were downloading the dependencies in the same local repo. After some point of time, one build was leveraging on cached dependencies. After completion of one of the pod if we spinup subsequent build pods it was entirely leveraging cached repo
We can do some experiment with this. In fact, this method is posted on [OpenShift blog](https://blog.openshift.com/decrease-maven-build-times-openshift-pipelines-using-persistent-volume-claim/).
To mitigate some this problem we can do a partial cache as well. Here can cache the initial set/subset of dependencies in some volume. before build pod bootup we can copy cached dependency set to the same PVC that is used by build pod using init-containers. This way it first build will also get optimized to a better extent and build process will face any race conditions, potential IO bottleneck.    

_Improve cache at repository level: L2 cache_ 
Setup a maven repo for the cluster to enable better caching at the second level. This can act as interim maven repo which can cache the dependencies from maven central. This would reduce the latency in downloading maven artifacts. Later we found a [good blog](https://blog.openshift.com/improving-build-time-java-builds-openshift/) on OpenShift for this as well.

@kbsingh @chmouel @pradeepto

**Comment by pradeepto** [comment]
cc @maxandersen @aslakknutsen

**Comment by maxandersen** [comment]
please be aware that by default maven does NOT support concurrent builds on local maven repository: https://issues.apache.org/jira/browse/MNG-2802

You'll probably be able to run many concurrent builds before seeing the issue but if you start using snapshot builds, different repos and update dependencies and time it right the local maven cache will become corrupt if left to its own devices.

I normal jenkins this is handled by having separate local repo per build workspace, but have the workspace shared between builds of the same job (which will be non-concurrent under normal circumstances).

There are extensions available like http://takari.io/book/30-team-maven.html#concurrent-safe-local-repository but not sure how maintained these are.

**Comment by maxandersen** [comment]
> I just saw this fmp notification, the maven download logs are suppressed by this from memory https://github.com/fabric8io/fabric8-pipeline-library/blob/c835e8f/vars/mavenTemplate.groovy#L26 so it may well appear that nothing is happening but in fact it it's downloading dependencies.

@rawlingsj any specific reason why not just setup builds to use "mvn -B" (batch mode) so it is not as noisy but at least print out one line for each download that happens ?

**Comment by kbsingh** [comment]
For the L1 piece above, I will let people who know Maven better than me comment. Its something we should definitely explore and scope out. Some of the conditions Max pointed out above may not apply to us, but I will let the build team scope up what it is that we need by way of service and how that maps to maven's capabilities.

for the L2 , cluster wide cache - this  is something that is on the scale radar as well - and its a recommendation coming from the Service team after yesterdays problemws with maven upstream having network issues all the time. Very happy to accelerate that work - can you open that task up under the tracker ( #2314 on gh/osio ) and we can work through that on its own merit.

thanks for the effort here.

**Comment by maxandersen** [comment]
> @maxandersen I think he main reason was when a artifact repo is used like nexus you still get tons of logging when downloading deps. What this means is you get pages and pages of logs when you're only interested in a small percentage of the output like the actual build and tests. It makes following the build harder also if / when folks capture build logs then that will take up a lot of extra space too.

ack - it is definitely a tricky balance to make - especially since blueocean seem to treat every single line individually rather than as one "blob" of dependencies download. Downside is though that users are left without much ability to track what is going  on - and unfortunately if mvn does decide to download dependencies that actually affects the outcome of the build meaning its kinda criticial info to have. 

I believe its good to have the *option* to silent the output even more but having it be hardcoded by default causes some unwanted surprises for users.

**Comment by pradeepto** [comment]
@chmouel @hrishin @jaseemabid How does #2368 change this task? Do we still need it?

**Comment by hrishin** [comment]
A task for this issue is already opened in OSIO https://github.com/openshiftio/openshift.io/issues/2486.
This is good to close.

 @pradeepto @chmouel @jaseemabid

**Comment by chmouel** [comment]
@hrishin  Is global proxy going to fix this task? Do you mean the task where we use a better mirror, isn't it ?

**Comment by hrishin** [comment]
@chmouel its global proxy I meant but better mirror itself is good enough now
