### ISSUE TITLE
Allow generating service without a route

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-maven-plugin#1209]
Currently when generating a service with f-m-p it would generate a Route along the way which is not needed, it would be useful to have a flag so it the Route doesn't get generated along the Service.

**Comment by piyush1594** [comment]
Hey @chmouel 

You need to do some little changes in pom.xml and probably it should work.

```
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>fabric8-maven-plugin</artifactId>
                <version>3.5-SNAPSHOT</version>
                <configuration>
                    <enricher>
                        <excludes>
                            <exclude>f8-expose</exclude>
                        </excludes>
                    </enricher>
                </configuration>
            </plugin>
```

Can you please try this configuration. Please let us know if this doesn't resolve your problem.

Thanks

**Comment by chmouel** [comment]
Ah that's neat but i can't seem to make it works, i have this : 

![image](https://user-images.githubusercontent.com/98980/36486861-dcf2d4a4-171f-11e8-86b8-a91159919f13.png)

but the Route for content-repository still gets generated : 

![image](https://user-images.githubusercontent.com/98980/36486934-03be4a14-1720-11e8-95cc-11c1d76066ca.png)

**Comment by piyush1594** [comment]
Hi @chmouel,

The file you are showing is the resource file which is getting generated. When you hit fabric8 goal, it generates :
- deployment and service for kubernetes.
- deploymentConfig, service, and route for OpenShift

The above configuration I provided will generate all the resource yaml, no change in that behavior but I will not create a route resource on your OpenShift cluster when you hit fabric8: deploy goal. If you hit fabric8: deploy goal without this configuration it will generate a route on your cluster.

Above configuration is wrt to resources on the cluster, not the yaml.

I think this will resolve your problem. Let us know if you have some other doubt.

Thanks

**Comment by hrishin** [comment]
Even making https://github.com/fabric8-services/fabric8-tenant-jenkins/blob/master/apps/content-repository/src/main/fabric8/content-repository-svc.yml#L14 to `false` generating the route resource.

The requirement here is `to not generate route resource` at all.

**Comment by piyush1594** [comment]
As #1211 is merged, I am closing this.
