### ISSUE TITLE
disable Prometheus and re-enable Jolokia for WildFly Swarm

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1217]
The Jolokia agent, which used to have problems with WildFly Swarm due to
how Java LogManager is set, works fine since Jolokia 1.3.6. This means that
the Fabric8 Java S2I image has been OK since version 2.0. Hence I believe
it is safe to re-enable Jolokia for WildFly Swarm applications now.

At the same time, the Fabric8 Java S2I image version 2.1 added a Prometheus
agent, which suffers from the same problem. Hence I believe it should be
disabled for WildFly Swarm applications (for now).

**Comment by piyush1594** [comment]
Closed by #1216

**Comment by dcdh** [comment]
Hello, I am facing an issue with Thorntail.

﻿```
exec java -Dswarm.http.port=8080 -Deventstore.username=devuser -Deventstore.password=devpassword -Deventstore.database=eventstoredb -Deventstore.remote-host=eventstore-database.developer.svc -Deventstore.remote-port=27017 -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/noteapp-write-thorntail.jar
I> No access restrictor found, access to any MBean is allowed
Jolokia: Agent started with URL http://172.17.0.4:8778/jolokia/ 

...

Caused by: java.lang.IllegalStateException: WFLYLOG0078: The logging subsystem requires the log manager to be org.jboss.logmanager.LogManager. The subsystem has not be initialized and cannot be used. To use JBoss Log Manager you must add the system property "java.util.logging.manager" and set it to "org.jboss.logmanager.LogManager"


```

Jolokia break my application startup :(

**Comment by rohanKanojia** [comment]
@dcdh : Could you please provide more details? Like which version of plugin are you using? Is it a regression from this fix?
