### ISSUE TITLE
S2I Cannot find binary directory 

### ISSUE THREAD

**Issue by ccshih** [fabric8io/fabric8-maven-plugin#1222]
### Description

I want to S2I-build a spring-boot project but failed.

**maven output:**
[INFO] --- fabric8-maven-plugin:3.5.30:resource (default-cli) @ fabric8 ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using docker image name of namespace: kafka-cluster
[INFO] F8: fmp-controller: Adding a default Deployment
[INFO] F8: spring-boot-health-check: Adding readiness probe on port 8080, path='/health', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: spring-boot-health-check: Adding liveness probe on port 8080, path='/health', scheme='HTTP', with initial delay 180 seconds
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: f8-icon: Adding icon for deployment
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.30:build (default-cli) @ fabric8 ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] Building tar: D:\demo-fabric8\target\docker\ccshih\fabric8-demo\tmp\docker-build.tar
[INFO] F8: [ccshih/fabric8-demo:latest]: Created docker source tar D:\demo-fabric8\target\docker\ccshih\fabric8-demo\tmp\docker-build.tar
[INFO] F8: Updating BuildServiceConfig fabric8-demo-s2i for Source strategy
[INFO] F8: Adding to ImageStream fabric8-demo
[INFO] F8: Starting Build fabric8-demo-s2i
[INFO] F8: Waiting for build fabric8-demo-s2i-6 to complete...
[ERROR] F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
...
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.30:build (default-cli) on project fabric8: Failed to execute the build: Unable to build the image using the OpenShift build service: OpenShift Build fabric8-demo-s2i-3: Failed: AssembleFailed -> [Help 1]

**oc build logs:**

Starting S2I Java Build .....
S2I binary build from fabric8-maven-plugin detected
Aborting due to error code 1 for No single directory found in /tmp/src but:\n total 4
-rw-r--r--. 1 jboss root 60 Mar  6 06:53 Dockerfile
error: build error: non-zero (13) exit code from fabric8/s2i-java:2.0

**tree /target/docker**
```
|   build.timestamp
|
+---ccshih
|   \---fabric8-demo
|       +---build
|       |       Dockerfile
|       |
|       +---tmp
|       |       docker-build.tar
|       |
|       \---work
\---fabric8
    \---latest
        +---build
        |   |   Dockerfile
        |   |
        |   \---maven
        |           fabric8-0.0.1-SNAPSHOT.jar
        |
        +---tmp
        |       docker-build.tar
        |
        \---work
```

### Info
* f-m-p version : 3.5.30
* Maven version (`mvn -v`) : 3.3.9
```

```
* Kubernetes / OpenShift setup and version : OpenShift 3.5

**Comment by ccshih** [comment]
It turns out that I added a custom name in pom.xml configuration/images/image
`<name>ccshih/fabric8-demo</name>`
So, in /target/docker, it generates a `ccshih/fabric8-demo` directory.

If I modified the name to `<name>fabric8/latest</name>`, it will work.

**Comment by piyush1594** [comment]
Are we good to close this issue?
