### ISSUE TITLE
plugin fails to deploy changes to an application

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1226]
### Description
Issue description https://github.com/openshiftio/openshift.io/issues/2505

* f-m-p version : 3.5.33
* Maven version (`mvn -v`) : 3.3.9
```
* Sample project : *[GitHub Clone URL]* https://github.com/openshiftio-vertx-boosters/vertx-http-booster

**Comment by piyush1594** [comment]
This is closed by #1225
