### ISSUE TITLE
f8-mp with CoresOS Tectonic ? 

### ISSUE THREAD

**Issue by nebrass** [fabric8io/fabric8-maven-plugin#1230]
### Description
I want to use  the f8-m-p with CoreOS Tectonic Sandbox 😄 and as Tectonic uses Kubernetes RBAC to manage user roles and permissions within its clusters, I hope to know these points:

- How to use f8-m-p with an RBAC enabled cluster ?
- How f8-m-p authenticates into Kubernetes? What ServiceAccount does it use? How to customize it? 

Here is my case:
When I try to `fabric8:apply`, I am getting this error:

```
[INFO] --- fabric8-maven-plugin:3.5.38:apply (default-cli) @ my-project-reactive ---
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://172.17.4.101/. Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized
```

This happens when my **kubectl** client is configured using a config file stored in `~/.kube/config`, that looks like this:

```yml
apiVersion: v1
kind: Config

clusters:
- cluster:
    server: https://172.17.4.101:443
    certificate-authority-data: XXXXXXXXX
  name: vagrant

users:
- name: tectonic-oidc
  user:
    auth-provider:
      config:
        client-id: tectonic-kubectl
        client-secret: XXXXXXXXXXXX
        id-token: XXXXXXX
        idp-certificate-authority-data: XXXXXXXXXXXXXX
        idp-issuer-url: https://console.tectonicsandbox.com/identity
        refresh-token: XXXXXXXXXXXXXXXXX
        extra-scopes: groups
      name: oidc

preferences: {}

contexts:
- context:
    cluster: vagrant
    user: tectonic-oidc
  name: tectonic

current-context: tectonic
```
But if I define the **KUBECONFIG** variable, that point to a `kubeconfig` file that looks like:

```yml
apiVersion: v1
kind: Config
clusters:
- name: vagrant
  cluster:
    server: https://172.17.4.101:443
    certificate-authority-data: XXXXXXXXXXX
users:
- name: kubelet
  user:
    client-certificate-data: XXXXXXXXXXX
    client-key-data: XXXXXXXXXXX
contexts:
- context:
    cluster: vagrant
    user: kubelet
```

and I try to `fabric8:apply`, I get:

```
[INFO] --- fabric8-maven-plugin:3.5.38:apply (default-cli) @ my-project-reactive ---
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[ERROR] F8: Could not connect to kubernetes cluster!
[ERROR] F8: Have you started a local cluster via `mvn fabric8:cluster-start` or connected to a remote cluster via `kubectl`?
[INFO] F8: For more help see: http://fabric8.io/guide/getStarted/
[ERROR] F8: Connection error: %s: java.net.UnknownHostException: kubernetes.default.svc
```

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 3.5.2
* Kubernetes version : v1.7.5+coreos.1
* Tectonic version : 1.7.5+tectonic.1

**Comment by nicolaferraro** [comment]
Never tried f-m-p with coreos tectonic sandbox, f-m-p works well with minishift, minikube and  'oc cluster up` as development envs.

It seems there's something looked up by f-m-p and not found in the coreos config. Apart from the checks to understand the target environment, the apply process should continue in kubernetes mode, trying to build the image.
F-m-p requires a docker daemon to be connected (`docker ps` should tell which containers are running in the sandbox) in order to work. Did you configure the docker daemon?

Docker daemon is not required in openshift mode.

Have you also considered moving to minikube/minishift for dev purposes?

**Comment by nebrass** [comment]
Thank you for your answer @nicolaferraro 😄I am already using f-m-p with Kubernetes and Openshift (minikube + minishift for dev and real K8s + OCP clusters in Production). But now, I am experimenting CoreOS Tectonic for one of my customers, so I think that doing the same tasks of f-m-p with Tectonic as like K8s & OCP will be great !
