### ISSUE TITLE
Created Helm artifact is not indexed by Helm because of incorrect file extension

### ISSUE THREAD

**Issue by fidget83** [fabric8io/fabric8-maven-plugin#1231]
Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)

Description
Created Helm artifact is not indexed by Helm because of incorrect file extension - plugin creates helm artifact with "tar.gz" extension while Helm repo accepts only "tgz". Simple renaming solves this problem.

Info
d-m-p version :
Plugin version is 3.5.38

Maven version (mvn -v) :
Maven 3.2.5

Docker version :
If it's a bug, how to reproduce :
If it's a feature request, what is your use case :
Sample project : [GitHub Clone URL]

**Comment by rohanKanojia** [comment]
Could you please share which project are you using, and you helm configuration as well?

**Comment by fidget83** [comment]
Project: fabric8-maven-plugin
Config:
<helm>
								<chart>${artifactId}.${groupId}</chart>
								<keywords>
									<keyword>${artifactId}.${groupId}</keyword>
								</keywords>
							</helm>

Created file: ${artifactId}.${groupId}-1.0.100-helm.tar.gz
Helm has default settings, just exec 
"helm repo index ." in the folder with created artifact
Created index:
apiVersion: v1
entries: {}
generated: 2018-03-14T16:28:02.911398453+03:00

**Comment by rohanKanojia** [comment]
Okay, I see you've already sent a pull request for this. I've added reviewers.

**Comment by fidget83** [comment]
Guys, when is the next version of plugin is expected?

**Comment by rohanKanojia** [comment]
We just released fmp last week. It's gonna take few weeks for the next release.

**Comment by fidget83** [comment]
Thanks!
