### ISSUE TITLE
When trimImageInContainerSpec is enabled, the generated yaml is incorrect

### ISSUE THREAD

**Issue by cescoffier** [fabric8io/fabric8-maven-plugin#1237]
### Description

When you ran `mvn fabric8:resource -Dfabric8.openshift.trimImageInContainerSpec=true` the generated `deployment.yaml` contains:

```
image: ' '
```

This is not valid in _pure_ yaml. Typically, it does not pass http://www.yamllint.com/.

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 3.5.3
```

```
* Kubernetes / OpenShift setup and version : not applicable here
* If it's a bug, how to reproduce :

1. `git clone https://github.com/openshiftio-vertx-boosters/vertx-http-booster`
2. `mvn fabric8:resource -Dfabric8.openshift.trimImageInContainerSpec=true -Popenshift` 
3. Check the generated `deployment.yaml`

**Comment by Ladicek** [comment]
Should it be `" "`? (I.e., double quotes instead of apostrophes?)
