### ISSUE TITLE
Use a released version in place of master for boosters

### ISSUE THREAD

**Issue by piyush1594** [fabric8io/fabric8-maven-plugin#1245]
Right now we are using the master of boosters GitHub for regression rest. This will sometimes break because of changes in master. 

You can check this here https://github.com/fabric8io/fabric8-maven-plugin/blob/master/rt/src/test/java/io/fabric8/maven/rt/SpringbootConfigmapBoosterIT.java#L36

We should always use a released version of booster in regression tests and should do an upgrade of booster version whenever required. We should not always rely on the master. This will help us regularly fixing the regression tests.

This will also help in fixing #1198

**Comment by piyush1594** [comment]
Need your inputs, comments or suggestions @hrishin @rohanKanojia

**Comment by piyush1594** [comment]
I am not sure whether a release will happen for boosters. 

@Ladicek @cescoffier Any inputs on this will be really helpful. Thanks

**Comment by hrishin** [comment]
@piyush1594 I second that. Let's do it. At the same time can we make a plan to move regression test from f8-m-p?

**Comment by rohanKanojia** [comment]
There is already a discussion about separating these tests from fmp : #1155 . Feel free to share your thoughts on it.

**Comment by piyush1594** [comment]
@cescoffier @Ladicek Can you please guide if there are any released version of boosters. If yes, then where are released. From Github, it seems like released happened a long time back. TIA

**Comment by Ladicek** [comment]
Yes, boosters are being released. The last releasees happened a couple of weeks ago. You might also want to take a look at the booster catalog (https://github.com/fabric8-launcher/launcher-booster-catalog) -- whatever is recorded there is available through the Launcher.

**Comment by piyush1594** [comment]
Hey @Ladicek 

Thanks for the help. Just one more thing, if you have an idea, which version (community or redhat) is used for OSIO.

Thanks

**Comment by piyush1594** [comment]
I think its the community version that is getting used in OSIO, not sure.

**Comment by gastaldi** [comment]
@Ladicek @piyush1594 it depends on which UI you are running the tests. The legacy UI in OSIO uses the community versions. In the new UI the user is free to select the version.

**Comment by piyush1594** [comment]
Thanks, @gastaldi @Ladicek Right now I have switched the regressions test for latest released community version. #1262 is the PR which will fix this.

**Comment by piyush1594** [comment]
As #1262 is merged, closing this.
