### ISSUE TITLE
Wrap docker:start/docker:stop from docker-maven-plugin

### ISSUE THREAD

**Issue by giannello** [fabric8io/fabric8-maven-plugin#1246]
### Description
According to the documentation, this plugin include docker-maven-plugin for most of the heavy lifting of creating/pushing images. It's a huge benefit, as the existing docker-maven-plugin configuration can be reused for this plugin to work, however the docker:start and docker:stop goals are not working in this context, and fabric8:start/stop are not working as expected, as they need to deploy the application to a cluster to work.
It would be great if the old docker:start/stop/watch could be use with this plugin too, as they are pretty useful for local development/testing.

### Info

* f-m-p version: 3.5.38
* Maven version (`mvn -v`): 3.5.2

**Comment by rohanKanojia** [comment]
Closing it for the moment, feel free to re-open if anyone has any objection. See discussion on #1260
