### ISSUE TITLE
Cannot find 'deployment' in class ResourceConfig

### ISSUE THREAD

**Issue by OndraZizka** [fabric8io/fabric8-maven-plugin#1249]
### Description

The `resources/deployment ` element in pom isn't parsed.
I am following this
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/samples/xml-config/pom.xml
which uses FMP version 3.2-SNAPSHOT

And it fails with
> Unable to parse configuration of mojo io.fabric8:fabric8-maven-plugin:3.5.38:resource for parameter deployment: Cannot find 'deployment' in class io.fabric8.maven.core.config.ResourceConfig
when using FMP version 3.5.38

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 3.5.0
`pom.xml` snippet:
```
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>fabric8-maven-plugin</artifactId>
                        <version>3.3.0</version>
                        <configuration>
                            <resources>
                                <labels><all><group>csa</group></all></labels>
                                <deployments/>
                                <deployment>
                                    <name>${project.artifactId}</name>
                                    <replicas>2</replicas>
                                    <containers>
                                        <container>
                                            <alias>camel-app</alias>
                                            <ports>
                                                <port>9000</port>
                                                <port>9001</port>
                                            </ports>
                                        </container>
                                    </containers>
                                </deployment>
                                <services>
                                    <service>
                                        <name>csa-service</name>
                                        <headless>true</headless>
                                    </service>
                                </services>
                            </resources>
                        </configuration>
```
* Kubernetes / OpenShift setup and version : minikube
* If it's a bug, how to reproduce :
1) Have `<deployment>` element as per the examples
2) Use use version 3.5.38

**Comment by piyush1594** [comment]
Can you provide more details like which is the version of openshift you are using, command you are hitting which is doing this, or the full steps to reproduce this?

**Comment by OndraZizka** [comment]
No OpenShift involved. The command is simply `mvn install`.

It seems that there is a mismatch between the documentation and the sources:

Looking at https://github.com/fabric8io/fabric8-maven-plugin/blob/master/core/src/main/java/io/fabric8/maven/core/config/ResourceConfig.java  , it seems that the `<deployment>` element is not supposed to be there at all.

**Comment by piyush1594** [comment]
'mvn install' is working fine for me. Not able to understand the problem you are trying to explain

**Comment by OndraZizka** [comment]
The problem is:
If there is a `<deployment>` in FMP's `<configuration>`, Maven build fails because it can't parse the POJO's configuration. `ResourceConfig` has no `deployment`.

**Comment by piyush1594** [comment]
I went to the project directory and hit `mvn install -P new` and it worked for me. Any configuration I am missing.

**Comment by giannello** [comment]
@OndraZizka the documentation is not very clear about XML configuration support. Those options are documented but not actually working.

**Comment by piyush1594** [comment]
I can take a look but I am not able to see the error you are facing, Can you provide the exact steps from the start or something else. I am not able to reproduce.

**Comment by OndraZizka** [comment]
@piyush1594  Steps to reproduce:
```
git clone https://github.com/fabric8io/fabric8-maven-plugin.git
cd fabric8-maven-plugin
mvn install
cd samples/xml-config/
mvn -Pnew fabric8:resource
```

**Comment by dev-gaur** [comment]
Hi @OndraZizka you can specify the allowed parameters in the xml config and then the DefaultControllerEnricher takes care of the Deployment creation. 

Look for "1.4.2. XML Configuration" in the documentation maven.fabric8.io

**Comment by dev-gaur** [comment]
Please revert back if your issue gets resolved or not.

**Comment by dev-gaur** [comment]
This issue has a reference to #1259
