### ISSUE TITLE
cannot apply on kubernetes - Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized1]

### ISSUE THREAD

**Issue by idelix** [fabric8io/fabric8-maven-plugin#1254]
### Description

I'm trying to deploy simple spring boot app to Azure Container Service (AKS) while following simple tutorial: https://docs.microsoft.com/en-us/java/azure/spring-framework/deploy-spring-boot-java-app-using-fabric8-maven-plugin

For some reason the last part which is to apply deployment on cluster fails:  mvn fabric8:apply

However I can access the cluster and view its details so kubectl works fine but fabric8 doesn't, I can also run kubectl run gs-spring-boot-docker --image=acrdevwe.azurecr.io/gs-spring-boot-docker:latest and it also works fine.

Could you please advise how can I specify credentials that fabric8 should use to access kubernetes cluster ?

I'm running this on windows 10.

### Error

[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://<MY_CLUSTERNAME>.hcp.westeurope.azmk8s.io/. Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized.
[DEBUG] Trying to configure client from Kubernetes config...
[DEBUG] Found for Kubernetes config at: [C:\Users\user.name\.kube\config].
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.003 s
[INFO] Finished at: 2018-03-27T20:05:13+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.30:apply (default-cli) on project gs-spring-boot-docker: Failure executing: GET at: https://<MY_CLUSTERNAME>.westeurope.azmk8s.io/. Message: Unauthorized! Token may have expired! Please log-in again. Unauthorized. -> [Help 1]

### Info

OS: WIndows 10
* fabric8 v: 3.5.30
* Maven version (`mvn -v`) : Apache Maven 3.5.3
```

```
* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
That's quite an old version of fabric8-maven-plugin. Which version of Kubernetes are you using? If by any chance you're on openshift/minishift; What does `oc whoami` return to you?

Also are you able to apply artifacts generated by fmp on your cluster directly(via `kubectl apply -f ...`)?

**Comment by idelix** [comment]
Hi, 

Sending answers:


# That's quite an old version of fabric8-maven-plugin. Which version of Kubernetes are you using?

I'm running this on kubernetes 1.9.2


# If by any chance you're on openshift/minishift; What does oc whoami return to you?

No I only created AKS cluster in Azure and run everything there.


# Also are you able to apply artifacts generated by fmp on your cluster directly(via kubectl apply -f ...)?

Yes I used mvn fabric8:resource which then produced file target\classes\META-INF\fabric8\kubernetes.yml then I run kubectl apply -f kubernetes.yml and it successfully apply all resources in kubernetes:

output:
secret "mysecrets" created
service "gs-spring-boot-docker" created
deployment "gs-spring-boot-docker" created


So it looks like f8 just can't authenticate even thought kubectl is in right context and I have permissions on k8  I wonder if there is a way to provide credentials like I've done it with images registry by specifying server in settings.xml... I also did not specified any env variables.

**Comment by idelix** [comment]
Hi, 

I also updated fabric8 to v 3.5.38 however still have same error:

[INFO] --- fabric8-maven-plugin:3.5.38:apply (default-cli) @ gs-spring-boot-docker ---
[WARNING] F8: Cannot access cluster for detecting mode: Failure executing: GET at: https://<CLUSTER NAME>.hcp.westeurope.azmk8s.io/. Message: Unauthorized! Token may have expired! Please log-in againd! Please log-in again. Unauthorized.

**Comment by rohanKanojia** [comment]
Hm, Are you able to reproduce this error locally on your machine i.e. on minikube? Otherwise, it might be some problem in your cluster configuration. Looking at the documentation, I also don't see any way to provide Kubernetes credentials; Although they have specified about logging into Openshift but simply via `oc login` command.

**Comment by idelix** [comment]
ok so this is something with AKS as it worked fine when installed on Kubernetes cluster installed through docker for windows:

[INFO] --- fabric8-maven-plugin:3.5.38:apply (default-cli) @ gs-spring-boot-docker ---
[INFO] F8: Using Kubernetes at https://localhost:6445/ in namespace default with manifest C:\Temp\gs-spring-boot-docker\complete\target\classes\META-INF\fabric8\kubernetes.yml
[INFO] Using namespace: default
[INFO] Using namespace: default
[INFO] Creating a Secret from kubernetes.yml namespace default name mysecrets
[INFO] Created Secret: \target\fabric8\applyJson\default\secret-mysecrets.json
[INFO] Creating a Service from kubernetes.yml namespace default name gs-spring-boot-docker
[INFO] Created Service: \target\fabric8\applyJson\default\service-gs-spring-boot-docker.json
[INFO] Using namespace: default
[INFO] Creating a Deployment from kubernetes.yml namespace default name gs-spring-boot-docker
[INFO] Created Deployment: \target\fabric8\applyJson\default\deployment-gs-spring-boot-docker.json
[INFO] F8: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.009 s
[INFO] Finished at: 2018-03-28T19:41:53+01:00

**Comment by idelix** [comment]
ok it was fixed after I installed Docker for windows 18.03.0-ce-win58 (16761) and enabled kubernetes.
Might be that it overwritten kube config file but not sure
