### ISSUE TITLE
samples/xml-config/pom.xml doesn't work

### ISSUE THREAD

**Issue by OndraZizka** [fabric8io/fabric8-maven-plugin#1259]
### Description
Steps to reproduce:
```
git clone https://github.com/fabric8io/fabric8-maven-plugin.git
cd fabric8-maven-plugin
mvn install
cd samples/xml-config/
mvn -Pnew fabric8:resource
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:resource (default-cli) on project fabric8-maven-sample-xml-config: Unable to parse configuration of mojo io.fabric8:fabric8-maven-plugin:3.5.38:resource for parameter group: Cannot find 'group' in class io.fabric8.maven.core.config.MetaDataConfig

This can be fixed by adding `<all>` to  `<label><group>`.

Then the error is:

[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.38:resource (default-cli) on project fabric8-maven-sample-xml-config: Unable to parse configuration of mojo io.fabric8:fabric8-maven-plugin:3.5.38:resource for parameter deployment: Cannot find 'deployment' in class io.fabric8.maven.core.config.ResourceConfig -> [Help 1]

This, in fact, reduces to #1249, except hereby I suggest to fix the documentation.
Or is it in the roadmap? Is it in any branch?
How about putting this docs to a branch and removing the elements which don't work from master?

Thanks :)

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /sw/prog/maven-3.5.0
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /sw/prog/jdk/1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-37-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version :  minikube version: v0.25.0

**Comment by rohanKanojia** [comment]
@rhuss @nicolaferraro : I think we need to take a look at samples which might have gotten deprecated. Even I have some problems in running some of samples. It would be nice if each sample has a `README` for easier usage.

**Comment by rhuss** [comment]
@rohanKanojia yes, that makes sense for sure. Actually, I'm not sure whether we run all samples during integration tests, but might make sense to have them tested automatically, too. Doesnt have to be for every PR, but at least periodically would be a nice to have.

**Comment by dev-gaur** [comment]
@rohanKanojia @rhuss The samples POM use fmp 3.2 as dependencies even though we are on 4.0 now. Should I look into the deprecated samples and send a PR for what can be done?

**Comment by rohanKanojia** [comment]
@dev-gaur : Sounds good. :+1:
