### ISSUE TITLE
WildFly Swarm deprecates the `monitor` fraction, FMP should be able to use MP Health Check too

### ISSUE THREAD

**Issue by Ladicek** [fabric8io/fabric8-maven-plugin#1265]
### Description

FMP is able to detect presence of the `monitor` fraction in WildFly Swarm projects and configure health checks automatically (https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/WildFlySwarmHealthCheckEnricher.java#L53).

However, WildFly Swarm deprecates the `monitor` fraction (https://issues.jboss.org/browse/SWARM-1696) in favor of the MicroProfile Health Check (`microprofile-health`). FMP should be able to detect this fraction too.

### Info

If noone gets to it, I'm volunteering to implement it, but I will take me a week or two to get to it.

**Comment by Ladicek** [comment]
Submitted #1296.

**Comment by piyush1594** [comment]
Fix in #1296

**Comment by mkouba** [comment]
@piyush1594 When do you plan the next release of FMP? We need this in order to finish the WildFly Swarm -> Thorntail project rename; see also [THORN-2048](https://issues.jboss.org/browse/THORN-2048) and linked issues. Thanks for info!

**Comment by hrishin** [comment]
@mkouba we are planning to release FMP 3.5.40 this week (mostly in a couple of days).

@piyush1594 @rohanKanojia

**Comment by mkouba** [comment]
That's great news! Thanks a lot.

**Comment by hrishin** [comment]
@mkouba @piyush1594 has released FMP 3.5.40

**Comment by mkouba** [comment]
@hrishin Thanks!
