### ISSUE TITLE
M-v-p and new k8s API versions

### ISSUE THREAD

**Issue by gintautassulskus** [fabric8io/fabric8-maven-plugin#1267]
### Description

M-v-p fails to deploy a spring app if I specify deployment version to k8s 1.9:

```
apiVersion: apps/v1
kind: Deployment
```
fabric8 fails with the following message:
```
Failed to create Deployment from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/form/deployments. Message: the API version in the data (apps/v1) does not match the expected API version (extensions/v1beta1). 
```
Is there a way to configure deployment (and others) API version?
Alternatively, if the URL and the version tag correlate, maybe the API call could be made dynamic?
E.g. the apps/v1 snipped above would translate to 
`https://192.168.99.100:8443/apis/apps/v1....`

Of course, the structure of the manifest might need to be adjusted as well depending on the version.

### Info

* f-m-p version : 3.5.35
* Maven version (`mvn -v`) : latest to date
* Kubernetes: 1.9

**Comment by piyush1594** [comment]
Hey @gintautassulskus 

FMP uses kubernetes-client to make calls to the cluster which is making API calls according to Kubernetes 1.7 in the current version used.

**Comment by gintautassulskus** [comment]
Thanks, @piyush1594 for clarifying.

**Comment by piyush1594** [comment]
Closing this.

**Comment by yesinc** [comment]
I ran into the same issue. The docs under https://github.com/fabric8io/fabric8-maven-plugin say that the plugin is compatible with Kubernetes 1.9.0 Version. That does not fit with your comment stating that only 1.7 is officially supported.

**Comment by piyush1594** [comment]
That means if you use the 3.5.38 FMP version of kubernetes 1.9 it will work, not fail. But the resource and generated are supported till 1.7 kubernetes right now

In the above example, you are changing the apiversion of deployment but the client is making a call according to kubernetes 1.7 on kubernetes 1.9 which is failing.

If you use the default generated yaml, they will work on k8s 1.9

Hope it helps

Thanks
