### ISSUE TITLE
DNS entry to 'fabric8.io' is gone

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1269]
```
dig fabric8.io

; <<>> DiG 9.9.7-P3 <<>> fabric8.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 51271
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;fabric8.io.			IN	A

;; Query time: 696 msec
;; SERVER: 192.168.178.1#53(192.168.178.1)
;; WHEN: Wed Apr 11 17:02:59 CEST 2018
;; MSG SIZE  rcvd: 39
```

**Comment by nicolaferraro** [comment]
It's still there for me...

**Comment by rohanKanojia** [comment]
It's not there for me as well.. :(

**Comment by rohanKanojia** [comment]
The domains fabric8.io, minishift.io, minishift.org have been moved to Red Hat DNS this morning. We just found out that one out of four of Red Hat's DNS servers is misconfigured and thus result in 1/4 of DNS requests failing. There is a thread going on in devtools about this. I would provide an update soon.

**Comment by rhuss** [comment]
cool, thanks ! Feel free to close the issue as people already working on it

**Comment by rhuss** [comment]
@rohanKanojia btw, there are more issue because of this move --> https://twitter.com/LordY971/status/984353498136489985

You should update certificates, too.

**Comment by rhuss** [comment]
Is there any particular reason why we moved away from Cloudflare for using as entrypoint for fabric8.io ? I mean we have now all sort of cert issues when accessing all github hosted documentations like e.g. https://maven.fabric8.io or https://dmp.fabric8.io

it took us quite some time to get this setup right, using advanced cloudflare features in 2016. But you probably have an answer for this, so please get the certs working again please.

**Comment by rhuss** [comment]
fyi: we used to use cloudflare not only as DNS server but also as proxy for serving certs which match our the fabric8.io domain. The certs were provided by cloudflare (so called "Universal (Shared)" certs but you probably have already seen this when you did the move).

**Comment by piyush1594** [comment]
@rhuss I think this has been fixed. Can we close this?
