### ISSUE TITLE
Support Openshift 3.9

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1273]
Openshift 3.9.0 has been released few weeks ago. We should run regression tests against it and add it to the compatibility matrix if everything is ok.

Wdyt?

**Comment by piyush1594** [comment]
Hey @nicolaferraro 

Already on it, hopefully I will update by tomorrow.

**Comment by piyush1594** [comment]
As #1275 is merged, I am closing this.
