### ISSUE TITLE
Fabric8 3.5.39 release

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#1287]
### Description
Is it time to release 3.5.39?

There are some interesting features that a lot of people would like to have (like support for spring-boot 2).

**Comment by piyush1594** [comment]
Hi the plan is to also update the client which has been blocked on https://github.com/fabric8io/fabric8-maven-plugin/pull/1274

**Comment by rohanKanojia** [comment]
Before doing that, we need to release [fabric8](https://github.com/fabric8io/fabric8/blob/master/pom.xml#L140) also with latest kubernetes-client.

**Comment by piyush1594** [comment]
Yes, well aware of that but waiting for #1274 to fix before releasing that.

**Comment by rohanKanojia** [comment]
Since #1263 is closed, I think we're good for releasing fmp. Kudos to @nicolaferraro for helping me out :)

**Comment by piyush1594** [comment]
As FMP 3.5.39 is released, we are good to close this.
