### ISSUE TITLE
Fabric8:build with openshift - base image pull fails from private registry 

### ISSUE THREAD

**Issue by yadavnikhil** [fabric8io/fabric8-maven-plugin#1293]
### Description
When running fabic8:build goal with base image from private docker registry which requires authentication, mode is openshift & build strategy is docker, the build fails in openshift for pull base image authentication error. I'm using a Dockerfile in src/main/docker location.

I have docker registry authentication details in maven settings.xml. I also have imagePullSecret set for builder service account.
It works fine when running in Kubernetes mode.

It seems the required maven parameters does not take effect in openshift mode ex. docker.pull.registry, <server> tags etc.

When i manually edit the buildConfig for setting the pullSecret for my docker registry, & run the build manually, build passes successfully. 

Is there any way be can pass pullSecret for fabric8:build goal? OR why maven settings are not used when run in Openshift mode?

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T18:41:47+02:00)
Maven home: /opt/maven-3.3.9
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_151/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-693.11.6.el7.x86_64", arch: "amd64", family: "unix"
```

```
* Kubernetes / OpenShift setup and version : Kubernetes v1.7.6, Openshift Origin version 3.7.23

* If it's a bug, how to reproduce :
run fabric8:build in openshift mode & buildStrategy as Docker

**Comment by piyush1594** [comment]
Closed in #1300

**Comment by hrishin** [comment]
@yadavnikhil  FMP 3.5.40 has been released. Thanks @piyush1594 !
