### ISSUE TITLE
WildFly Swarm was renamed to Thorntail

### ISSUE THREAD

**Issue by Ladicek** [fabric8io/fabric8-maven-plugin#1298]
### Description

WildFly Swarm was renamed to Thorntail: https://thorntail.io/

We intend to copy and rename the WildFly Swarm generator and health check enricher, new name being `thorntail-v2` (because there's already a prototype of Thorntail v4, which is a complete rearchitecture: https://docs.thorntail.io/4.0.0-SNAPSHOT/). We'd like to keep the existing `wildfly-swarm` generator and enricher for the time being, even if it results in a slight code duplication (the amount of duplicate code is very small).

### Info

See also https://issues.jboss.org/browse/THORN-2048

**Comment by Ladicek** [comment]
Submitted https://github.com/fabric8io/fabric8-maven-plugin/pull/1301

**Comment by piyush1594** [comment]
Closed in #1301

**Comment by hrishin** [comment]
@Ladicek FMP 3.5.40 is in maven central. Thanks @piyush1594 !

**Comment by Ladicek** [comment]
Thanks all!
