### ISSUE TITLE
autotls feature doesn't work with OpenShift 3.9 (Kubernetes 1.8+) due to InitContainer annotation deprecation

### ISSUE THREAD

**Issue by mojsha** [fabric8io/fabric8-maven-plugin#1299]
The autotls feature uses initContainer alpha annotations (https://github.com/fabric8io/fabric8-maven-plugin/blob/bd414f1ad94fdf48e8de05f25e3e09998b3f7508/enricher/api/src/main/java/io/fabric8/maven/enricher/api/util/InitContainerHandler.java) but this has been deprecated as of Kubernetes 1.8.0 (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#support-and-compatibility). 

We need to replace the annotation with the spec.initContainers field. 

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 3.3.9

* Kubernetes / OpenShift setup and version :
openshift v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657

* If it's a bug, how to reproduce :
Enable and use autotls feature. Initcontainer will not be created.

**Comment by mojsha** [comment]
@rohanKanojia  Any chance you can assign this to somebody?

**Comment by rohanKanojia** [comment]
Sorry for responding late, will take a look soon.

**Comment by hrishin** [comment]
@mojsha feel free to contribute :+1:  
FYI soon we are going release new FMP version which is is targeted Kubernetes 1.8/1.9 and OpenShift 3.9.

**Comment by mojsha** [comment]
@hrishin When will it be released, and will it have solved the autotls issue?

**Comment by mojsha** [comment]
@rohanKanojia @hrishin Any comments/updates (either about the new version for 3.9 or the patch)?

**Comment by rohanKanojia** [comment]
@mojsha: Sorry for the delay, I have a work in progress local branch which updates deprecated annotation. I have to test it

**Comment by mojsha** [comment]
Thanks guys, if the 3.9-compatible release will take its time, we should perhaps have @rohanKanojia make a maintenance release in the interim period until it's done.

**Comment by mojsha** [comment]
@rohanKanojia I just tested it and it looks like the spring-boot-health-check enricher is broken because it is trying to apply the readiness/liveness healthchecks on the InitContainer:

`[ERROR] Failed to update DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://openshift:8443/apis/apps.openshift.io/v1/namespaces/sample/deploymentconfigs/demo. Message: DeploymentConfig "demo" is invalid: [spec.template.spec.initContainers[0].livenessProbe: Invalid value: core.Probe{Handler:core.Handler{Exec:(*core.ExecAction)(nil), HTTPGet:(*core.HTTPGetAction)(0xc43c815960), TCPSocket:(*core.TCPSocketAction)(nil)}, InitialDelaySeconds:180, TimeoutSeconds:1, PeriodSeconds:10, SuccessThreshold:1, FailureThreshold:3}: must not be set for init containers, spec.template.spec.initContainers[0].readinessProbe: Invalid value: core.Probe{Handler:core.Handler{Exec:(*core.ExecAction)(nil), HTTPGet:(*core.HTTPGetAction)(0xc43c8159d0), TCPSocket:(*core.TCPSocketAction)(nil)}, InitialDelaySeconds:10, TimeoutSeconds:1, PeriodSeconds:10, SuccessThreshold:1, FailureThreshold:3}: must not be set for init containers]. `

**Comment by rohanKanojia** [comment]
@mojsha : ah,  Could you please share steps via which you were able to reproduce it? This might be coming because of #1283 , since now we're defining InitContainers on Deployment instead of annotations :-(

**Comment by mojsha** [comment]
@rohanKanojia Essentially, you just need to add the enricher to your F-M-P pom.xml like so:

`<enricher>
<includes>
<include>spring-boot-health-check</include>
</enricher>`

**Comment by rohanKanojia** [comment]
@mojsha : I was trying to reproduce this, but somehow I'm not able to. Here is what I did:
1.) Changed pom.xml of samples/spring-boot like [this](https://pastebin.com/k9Wf7A1g).
2.) Hit mvn clean install
Build was successful. Is there something I could be missing?

**Comment by mojsha** [comment]
@rohanKanojia Do you have initContainers in your DeploymentConfig resource fragment?

**Comment by rohanKanojia** [comment]
ah, no. let me check with this

**Comment by rohanKanojia** [comment]
@mojsha : Hi, I looked into it and looks like it is a case of #1283 . A pull request is already there(see #1202 ) to handle this health check enrichment in such a way that only main container is enriched, or something else depending upon what configuration you provide. I tested and it seemed to be working for me. Hopefully it would get in before next release :-)

**Comment by mojsha** [comment]
@rohanKanojia Cool. Thanks for your efforts!
