### ISSUE TITLE
upgrade kubernetes client to support OpenShift 3.9 and Kubernetes 1.8/1.9

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1308]
### Description
Upgrade kubernetes client to support Kubernetes 1.8/1.9 and OpenShift 3.9

cc: @rohanKanojia @piyush1594

**Comment by geoand** [comment]
Would this include changing the apiVersion from `extensions/v1beta1` to `apps/v1beta1` for the generated `Deployment` in `kubernetes.json`?

**Comment by oscerd** [comment]
yes it is, extensions deployments are now deprecated in favor of apps deployments.

**Comment by geoand** [comment]
@oscerd thanks for the confirmation!

**Comment by rohanKanojia** [comment]
Blocked on fabric8io/kubernetes-model/issues/329

**Comment by rhuss** [comment]
@rohanKanojia wdym with blocked ? The other issue seems to be closed already.

**Comment by rohanKanojia** [comment]
@rhuss : issue is closed but we kubernetes-client is still not released. We can proceed after release of kubernetes-client.

**Comment by piyush1594** [comment]
Great Work @rohanKanojia :tada:
