### ISSUE TITLE
namespaces "sdf" not found

### ISSUE THREAD

**Issue by jeusdi** [fabric8io/fabric8-maven-plugin#1314]
### Description
I don't know fabric8 is getting me `"sdf"` as namespace:

    [INFO] F8: Using docker image name of namespace: sdf

I'm getting this error message when I perform: 

Shortly: 

> message=namespaces "sdf" not found

Detailed:

> Unable to build the image using the OpenShift build service: Failure executing: POST at: https://vault.minishift.svc:8443/apis/image.openshift.io/v1/namespaces/sdf/imagestreams. Message: namespaces "sdf" not found. Received status: Status(apiVersion=v1, code=404, details=StatusDetails(causes=[], group=null, kind=namespaces, name=sdf, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=namespaces "sdf" not found, ...

I don't know why fabric8 plugin is getting `sdf` namespace.
Current `oc project`  is another one and I've not specified "sdf" namespace anywhere. In fact:

    $ grep -rnw './' -e 'sdf'
    no results

### Info
```
* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 4.15.0-23-generic
* Kubernetes / OpenShift setup and version : v1.7.6+a08f5eeb62 / v3.7.0+7ed6862
```

**Comment by rohanKanojia** [comment]
@jeusdi: Hi, Not sure whether it's actually fmp issue or not. Could you please provide more details? Like which project you're using? Can we reproduce it locally?

**Comment by rhuss** [comment]
@jeusdi do you have a concrete pom.xml which we could check for this issue ?
