### ISSUE TITLE
fabric8:push fails going to AWS ECS

### ISSUE THREAD

**Issue by ObviousDWest** [fabric8io/fabric8-maven-plugin#1320]
I am doing local development using Docker for Windows (18.03.1-ce-win65 (17513)) in Linux mode (although I do switch to Windows mode periodically), and fabric8-maven-plugin to build and push images. I've run a local registry inside Docker, and am able to push to that using f-m-p.

However, when I use a repository on AWS ECS, I get:
`Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:push (default-cli) on project jenkins-master: Unable to push 'dbg/jenkins-master' from registry 'xxxx.dkr.ecr.us-west-2.amazonaws.com' : no basic auth credentials -> [Help 1]`

I've successfully tagged, and pushed to this repo using the docker commandline. So I conclude the issue is with f-m-p. E.g.:
```
$ docker tag dbg/jenkins-master xxxx.dkr.ecr.us-west-2.amazonaws.com/dbg/jenkins-master
$ docker push xxxx.dkr.ecr.us-west-2.amazonaws.com/dbg/jenkins-master
```

The config files here are a little ugly, as I've bee trying different workarounds. I would prefer if the system worked with wincred, for safety, since it is integrated with the daily aws get-login system, to avoid cutting and pasting things into config files each day.

For testing, it is easy to create a free aws ecs account, which comes with a registry.

For reference, I suspect it is related to something like the docker-maven-plugin folks faced:
[https://github.com/spotify/docker-maven-plugin/issues/181](https://github.com/spotify/docker-maven-plugin/issues/181)

For login:
`aws ecr get-login --no-include-email`
which spits out a docker login command that you paste into the cli again:
`docker login -u AWS -p ppp https://xxx.dkr.ecr.us-west-2.amazonaws.com`
Maven: 3.3.9
f-m-p: 3.5.40

.docker/config.json:
```
{
	"auths": {
		"xxx.dkr.ecr.us-west-2.amazonaws.com": {},
		"https://xxx.dkr.ecr.us-west-2.amazonaws.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.03.1-ce (windows)"
	},
	"credsStore": "wincred"
}
```
Pom:
 ```
   <properties>
        <fabric8-version>3.5.40</fabric8-version>
        <fabric8.mode>auto</fabric8.mode>
        <fabric8.debug.enabled>true</fabric8.debug.enabled>
        <docker.verbose>true</docker.verbose>
        <docker.registry>xxx.dkr.ecr.us-west-2.amazonaws.com</docker.registry>
        <docker.apiVersion>1.37</docker.apiVersion>
    </properties>

    <build>
        <resources>
            <resource>
                <directory>src/main/fabric8</directory>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/docker</directory>
                <filtering>true</filtering>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>fabric8-maven-plugin</artifactId>
                <version>${fabric8-version}</version>
                <configuration>
                    <verbose>true</verbose>
                    <images>
                        <image>
                            <name>dbg/jenkins-master</name>
                            <alias>dbg/jenkins-master</alias>
                            <build>
                                <dockerFile>JenkinsMaster.Dockerfile</dockerFile>
                                <filter>@</filter>
                            </build>
                        </image>
                         </images>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by rhuss** [comment]
Actually, f-m-p used for pushing image d-m-p internally, which has support for pushing to AWS ECR --> https://dmp.fabric8.io/#extended-authentication

However, I'm not sure whether this is a problem of the integration of d-m-p in f-m-p or whether d-m-p is broken here.

Could you try to replace fabric8-maven-plugin with docker-maven-plugin (version 0.26.0) for a moment and try a 'mvn package docker:build docker:push' to check whether the push works with d-m-p alone ? (possibly also with `mvn -X` if it fails to get some more debug output)

**Comment by Beennnn** [comment]
I face the same problem pushing to Google Cloud Platform.

First I configure docker using `gcloud auth configure-docker`. With this command, gcloud adds the credHelpersto the docker donfig.json. 
Then I simply can push my image with the push command : `docker push eu.gcr.io/xxx:latest`.

But if I add the push goal  to fabric8-maven-plugin execution and I run it with mvn install using the same context it fails with the message:
`Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.40:push (default) on project xxx: Unable to push 'eu.gcr.io/xxx:latest' from registry 'eu.gcr.io' : unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticateyour request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication-> [Help 1]`

I have switched to a direct call to docker push like that:
`
					<plugin>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>exec-maven-plugin</artifactId>
						<executions>
							<execution>
								<id>push-docker-image-to-gcp</id>
								
								
								<phase>install</phase>
								<goals>
									<goal>exec</goal>
								</goals>
								<configuration>
									<executable>docker</executable>
									<arguments>
										<argument>push</argument>
										
										<argument>${docker.image.prefix}/${project.artifactId}:latest</argument>
									</arguments>
								</configuration>
							</execution>
						</executions>
					</plugin>```
`

Do you think it is a bug to be fixed ?

**Comment by Beennnn** [comment]
@rhuss 
I tryed to do it, replacing the plugin with: 
```
<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>docker-maven-plugin</artifactId>
  <version>0.26.0</version>
</plugin>
```
I attach the log file. It looks like it succeeded...
[TRACES.LOG](https://github.com/fabric8io/fabric8-maven-plugin/files/2419164/TRACES.LOG)

I hope it helps.
Ben.

**Comment by rohanKanojia** [comment]
you mean #1327 ;-)

**Comment by rhuss** [comment]
yeah, sorry :)

**Comment by Beennnn** [comment]
@rohanKanojia I just migrated on the new tag yesterday. I hope I can give you a feedback soon

**Comment by rohanKanojia** [comment]
@Beennnn : Polite ping, did you get time to test this?

**Comment by ObviousDWest** [comment]
I am not going to be able to help verify the fix, as I no longer have access to all parts of the system where the issue came up.

**Comment by Beennnn** [comment]
I am not able to test it now. The system I work on does does not use this feature anymore but calls docker directly as a workaround. I plan to migrate back to this feature next month. 
If no one expects a fix, I suggest we can close this, and maybe re-open if someone faces it again.

**Comment by rohanKanojia** [comment]
@Beennnn : Hm, okay. I'm closing this for now.Feel free to re-open anyone faces this again.
