### ISSUE TITLE
Unable to deploy to an EKS cluster

### ISSUE THREAD

**Issue by andrewrutter** [fabric8io/fabric8-maven-plugin#1322]
I am trying to deploy a relatively simple Spring boot application to an AWS EKS cluster but am running into some issues. Pretty sure there is either some rogue configs or missing configs but when I run 
`mvn fabric8:deploy`
I get the following in the console log:
`[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARNING] F8: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[ERROR] F8: Could not connect to kubernetes cluster!
[ERROR] F8: Have you started a local cluster via `mvn fabric8:cluster-start` or connected to a remote cluster via `kubectl`?
[INFO] F8: For more help see: http://fabric8.io/guide/getStarted/
[ERROR] F8: Connection error: %s: java.net.UnknownHostException: kubernetes.default.svc
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34.777 s
[INFO] Finished at: 2018-07-17T18:44:10-04:00
[INFO] Final Memory: 62M/297M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.33:deploy (default-cli) on project collect-user: Could not connect to kubernetes cluster. Have you started a cluster via `mvn fabric8:cluster-start` or connected to a remote cluster via `kubectl`? Error: java.net.UnknownHostException: kubernetes.default.svc: An error has occurred. Unknown host kubernetes.default.svc -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

kubectl is correctly setup and I can run things such as kubectl get svc which is responding as expected.  

Is there a guide to using fabric8 alongside EKS?

Thanks in advance
Andrew

**Comment by andrewrutter** [comment]
I did try to set the KUBERNETES_MASTER environemnt variable to the API server endpoint from my AWS EKS configuration 

Which changes the error to:
`[WARNING] F8: Cannot access cluster for detecting mode: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

I think I just need to inform the plugin of my IAM user keys, but how?

**Comment by rhuss** [comment]
This is likely an issue with the kubernetes-client. Looking into the source code, it the client first tries to read `~/.kube/config` which should be present if you can access your cluster with kubectl. @andrewrutter could you please verify that this file exists for you ? And that you dont have `kubernetes.auth.tryKubeConfig` set as system property or env var ?

Also, running mvn with `-X` to switch on debug would be very helpful. If you could paste the log with debug around this error this might help as there are quite some info during the login process.

**Comment by andrewrutter** [comment]
I opened a support ticket with AWS who came back with the following response.

I have checked our internal documentation and you are correct EKS only uses heptio-authenticator-aws for authentication, also there is no third party system integration with kubectl currently available within EKS. 

However, I have gone ahead and created a feature request for this on your behalf. Unfortunately, I can't provide an exact ETA by which this feature may be introduced, but you can monitor the locations below for any new EKS releases:

https://aws.amazon.com/new/
https://aws.amazon.com/releasenotes/
