### ISSUE TITLE
Move specific generator, enrichers to separate repositories

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1332]
Enricher and Generators which a specific to a tech-stack like spring-boot, vert.x, thorntail should be grouped together. 

When moving to fabric8-build, these enrichers will be ables to support more than Maven but also Graddle and other environments which can provide a proper context. 

So the suggestion is to move those parts out into separate repositories or as part of fabric-build in separate modules.

**Comment by cescoffier** [comment]
@rhuss any idea how enrichers/generators will be configured? I've faced several issues with the current approach and had to find a convoluted way to go back to the roots (Maven XML...).

Another aspect is how the extension mechanism would work? Plugin dependency? Project dependency? My question is somewhat oriented as I would love to see the possibility to add the Vert.x enricher/generator into the Vert.x Maven Plugin and just using this plugin would _magically_ enable the support.

**Comment by rhuss** [comment]
For adding new enricher etc. we are using plugin dependencies. The configuration of the enrichers / generators can be done by XML already (its a generic map) or via properties, too.

See e.g. https://github.com/fabric8io/fabric8-maven-plugin/blob/master/samples/spring-boot-with-yaml/pom.xml#L79-L89

**Comment by cescoffier** [comment]
The issue I faced with configuration was the lack of structural support. It was supporting key-value pairs, but the value was not a composite construct (like another key-value set). Maybe I missed something.

**Comment by cescoffier** [comment]
Any possibility to register an enricher/generator using a programmatic way or Maven Component (@Component)?

**Comment by rohanKanojia** [comment]
Damn you stale bot!
