### ISSUE TITLE
fabric8:deploy does not invoke fabric8:build?

### ISSUE THREAD

**Issue by gdubya** [fabric8io/fabric8-maven-plugin#1352]
### Description
We're getting start with using Spring Boot applications in Openshift. We're trying to use the fabric8 maven plugin to deploy our application to minishift.

After running the usual "mvn clean install" we tried the fabric8:deploy goal, but then there's a message from F8 stating: 

> no such generated manifest file /path/to/project/target/classes/META-INF/fabric8/openshift.yml for this project so ignoring

And then the build finishes with BUILD SUCCESS.

Shouldn't fabric8:deploy also invoke fabric8:build?

### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) : 3.5.2 
* Java version: 1.8.0_172, vendor: Oracle Corporation
```

```
* Kubernetes / OpenShift setup and version :
** Minishift: v1.22.0+7163416
** OpenShift: v3.9.0+71543b2-33

**Comment by rhuss** [comment]
You have to set your `<executions>` right for `fabric8:deploy` to work properly:

```xml
<executions>
   <execution>
      <goals>
         <goal>resource</goal>
         <goal>build</goal>
      </goals>
   </execution>
</executions>
```

**Comment by gdubya** [comment]
Ah sorry, I misunderstood the zero config documentation. Thanks!
