### ISSUE TITLE
Update compatibility matrix

### ISSUE THREAD

**Issue by rdruss** [fabric8io/fabric8-maven-plugin#1356]
The latest released version of FMP is 3.5.41 and OpenShift is 3.10 while the compatibility matrix in the Readme only lists up to FMP 3.5.38 and OpenShift 3.9.

**Comment by rohanKanojia** [comment]
@rdruss : Nice catch, Thanks. We still have to upgrade fmp to the latest [kubernetes-client](https://github.com/fabric8io/fabric8-maven-plugin) in order to use new features in Openshift 3.9. But it should be there in compatibility matrix ;-)
