### ISSUE TITLE
Allow an extra registry when generating a Pod's image declaration.

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#136]
The old plugin had the issue that it takes a fixed image name only which it shared with the d-m-p. However d-m-p has some extra flexibility to provide a registry from the outside (e.g. with `docker.push.registry` or `docker.registry`) which then is used for temporarily tagging the image before push. The same kind of flexibility should be possible for f-m-p when it creates its resource descriptors. 

See also  https://github.com/fabric8io/fabric8/issues/3980 for a real world issue where this is a problem.

**Comment by rohanKanojia** [comment]
I think it's already fixed by #1167

**Comment by rohanKanojia** [comment]
Closing this, please reopen if you think there is something missing here
