### ISSUE TITLE
Deployments out of beta - use apps/v1 API instead of extensions/v1beta1

### ISSUE THREAD

**Issue by kprzerwa-r7** [fabric8io/fabric8-maven-plugin#1369]
### Description
Beta deployments are now depreciated and project can be updated to use `apps/v1` API instead of `extensions/v1beta1`.
Also if you're looking at deployments, can you take a look at https://github.com/fabric8io/fabric8-maven-plugin/issues/742?
### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T19:33:14+01:00)
Maven home: /home/kprzerwa/rapid7/tools/apache-maven-3.5.4
Java version: 1.8.0_162, vendor: Azul Systems, Inc., runtime: /home/kprzerwa/rapid7/tools/jdk/jdk1.8.0_162/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-32-generic", arch: "amd64", family: "unix"

```
* If it's a feature request, what is your use case :
  - create deployment using `apps/v1` API
  - see https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by MichaelSp** [comment]
Oh noes! Please dont close this 😿

**Comment by rhuss** [comment]
We should think a bit harder about our api version management, but actually I think, we should at least track the latest k8s / openshift releases and the latest api's used there.

Ideally we should keep track a kind of matrix and with a mapping of k8s version to supported api versions, and allow the user to specify a target version (with a default to the latest k8s version known when the plugin was released).

**Comment by rohanKanojia** [comment]
I think I updated version to apps/V1. Could you guys please try on 4.0.0?
Otherwise I would test it myself whenever I get time.

मंगल, 19 मार्च 2019, 00:49 को stale[bot] <notifications@github.com> ने लिखा:

**Comment by rohanKanojia** [comment]
@MichaelSp @kprzerwa-r7: I updated this in #1571 , Could you guys please check on the latest version of fabric8 maven plugin 4.0.0?

**Comment by rohanKanojia** [comment]
@MichaelSp @kprzerwa-r7 : polite ping, Did you get time to test this out?

**Comment by MichaelSp** [comment]
Hi @rohanKanojia Sorry, I'm no longer working with fabric8.

**Comment by rohanKanojia** [comment]
oh, okay
