### ISSUE TITLE
Allow the configuration of failureThreshold and successThreshold on readiness and liveness probes

### ISSUE THREAD

**Issue by codependent** [fabric8io/fabric8-maven-plugin#1373]
### Description
Currently there isn't a way to configure the  failureThreshold and successThreshold on readiness and liveness probes using the spring-boot-health-check enricher
### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) : Apache Maven 3.5.2

* Kubernetes / OpenShift setup and version : K8s 1.10.x
* If it's a feature request, what is your use case : a default failureThreshold of 3 is configured. I would like to increase that value.

**Comment by rhuss** [comment]
I think this would be a valuable addition, not only for the spring boot healthcheck enricher, but for all enrichers. Shouldn't be that hard to implement.
