### ISSUE TITLE
Compare Odo and f-m-p from the POV of a Java Developer

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1401]

**Comment by lordofthejars** [comment]
I start adding some points without any order just to have all of them in mind.

* FMP do not need to  download all dependencies from Maven project (as happens with s2i)
* It integrates with Java in a programmatic way (so is integrated with popular tools like Maven)
* Known tool by Java devs (Maven) so no need to learn 
* Works with OpenShift and Kubernetes
* Works with Spring Boot out of the box
* Extensible
* Customizable (no need to know how to do a compliant s2i)
* No installation (self contained in build tool)

**Comment by cmoulliard** [comment]
Some  missing points are : 

- flow processed : odo currently is focused on `innerloop = no docker build => code pushed to dev's pod` while fmp is dedicated to `outerloop = s2i =? building docker image`
- composition of an application (component, service)

**Comment by rhuss** [comment]
@cmoulliard @kadel I started a document at https://docs.google.com/document/d/1DbYjQs0yAxO9P56d9hzMj8uOBd_5XDu993_Fcy78YPo/edit# to collect features and use cases supported by ODO and fabric8-maven-plugin.

As my knowledge of ODO is very limited it would be awesome if you or anybody else, please:

* Add Features and Use Cases which are probably unique to ODO
* Question use cases as being wrongly described or an irrelevant for the majority of Java developers. Please add some Google doc comment in this case.

As mentioned in the introduction, it's not meant as a *shootout*. The document tries to collect some hopefully somewhat objective facts to find out the overlap and difference for ODO and fmp from the point of view of a Java developer.

**Comment by rhuss** [comment]
>     * composition of an application (component, service)

@cmoulliard could you please give me a pointer to the composition feature of Odo so that I compare that with f-m-p dependency enricher ?

>     * project scaffolding

Does this already work for Java apps ? In the google docs its mentioned as "planned".

**Comment by rhuss** [comment]
Summed up the document, in final review now.

**Comment by rhuss** [comment]
I consider the doc as finished for now.
