### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by benike** [fabric8io/fabric8-maven-plugin#1412]
Hello!

I wanted to build the image based on a Dockerfile.

Found this stackowerflow post, but the guy did not open a ticket i think, so i do. https://stackoverflow.com/questions/52618369/fabric8-maven-build-with-external-dockerfile-fails

Running minishift locally, installed from this guide.
https://www.marksei.com/openshift-minishift-widnows/

The sample project.
https://github.com/benike/fabric8-maven-plugin-with-dockerfile

2 commit, first is without Dockerfile, "mvn clean fabric8:deploy" deploys the app and everything works fine, second commit, added dockerfile and the plugin config, build fails.

![kep](https://user-images.githubusercontent.com/17648519/46790731-e4334880-cd3f-11e8-8c31-e5ef51094d2c.png)

maven version 3.5.4
minishift version 1.25.0

Best wishes,
Benike

**Comment by rhuss** [comment]
Looks like that the image name was lost when using a Dockerfile. This is definitely a bug which we need to investigate.
