### ISSUE TITLE
DeploymentConfig is not deleted when undeploy is called

### ISSUE THREAD

**Issue by geoand** [fabric8io/fabric8-maven-plugin#1420]
### Description
When I do 

`mvn fabric:undeploy -Dfabric8-maven-plugin.version=3.5.42` 

after having done 

`mvn fabric8:deploy -Popenshift -Dfabric8-maven-plugin.version=3.5.42 ` 

for [this](https://github.com/snowdrop/spring-boot-http-booster) Spring Boot project, the `DeploymentConfig` is not removed as it should be.

### Info

* f-m-p version : 3.5.42
* Maven version (`mvn -v`) : 3.5.4
* Kubernetes / OpenShift setup and version : OKD 3.10
* If it's a bug, how to reproduce : (same as description)
* Extra information: `oc describe dc ....` : https://gist.github.com/geoand/f428b4a42f623b13f4b9a4ea3f83ef9e

**Comment by geoand** [comment]
I am using an all-in-one OKD cluster launched via openshift-ansible. The openshift version is: `v3.10.0+e3465d0-44`.
On that cluster, the problem appears every time.

I was just now able to reproduce the behavior you are seeing as well on Minishift! Very strange indeed :).
@mocenas you have also seen a similar issue where the `DeploymentConfig` refuses to go away, what Openshift version is your cluster using?

@rhuss If you would like, I can give you access to the cluster our team uses to help debugging. I will also try to see if I can isolate the issue and dig deeper. Something tells that this rabbit hole might be pretty deep.. .

**Comment by mocenas** [comment]
@geoand  Hi, i have OCP v 3.10.45 and OKD v3.10.0+456651d-57. Having this issue on both of them.

**Comment by geoand** [comment]
Thanks for your input @mocenas!

**Comment by rhuss** [comment]
@geoand Could be an issue with OKD 3.9 vs OKD 3.10. AFAIK the kubernetes-client used by fmp only supports up to 3.9 (although it seems to work mostly with 3.10, too), according to https://github.com/fabric8io/kubernetes-client#compatibility-matrix

Unfortunately, there is no team assigned to work on the fabric8/kubernetes-client (except for some volunteering maintenance), so I guess keeping this up to date with the latest k8s / openshift versions will get harder and harder.

**Comment by geoand** [comment]
Thanks @rhuss .

I will carve out some time to look into it and see if I can find the root cause.

**Comment by geoand** [comment]
I just realized the even the Openshift UI does not delete the DeploymentConfig for the miss-behaving cluster...
`oc delete dc...` of course works in all cases.

So I am guessing this goes deeper than I would like to find out :)

**Comment by rohanKanojia** [comment]
@geoand : Seems like an Openshift issue. Do you think it makes sense to keep this issue open?

**Comment by geoand** [comment]
@rohanKanojia Feel free to close it :)

**Comment by rohanKanojia** [comment]
@geoand : Thanks for quick feedback ;-)
