### ISSUE TITLE
support WildFly Swarm OOTB

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#143]
I tried taking this quickstart 
https://github.com/fabric8-quickstarts/swarm-camel

and migrating it to the latest f-m-p without doing anything other than specifying a main class:
https://github.com/jstrachan/swarm-camel/blob/f-m-p-3/pom.xml#L154-L171

but it fails to run. 

It looks like we need to detect WF Swarm and use the docker build configuration something like this OOTB. 

i.e. detecting the `-swarm jar` output by default by the wildfly swarm plugin and using an executable jar entry point?

```xml
                <configuration>
                    <images>
                        <image>
                            <name>${docker.image}</name>
                            <run>
                                <ports>
                                    <port>8080:8080</port>
                                </ports>
                            </run>
                            <build>
                                <from>${docker.from}</from>
                                <ports>
                                    <port>${docker.port.container.http}</port>
                                </ports>
                                <assembly>
                                    <basedir>/opt</basedir>
                                    <inline>
                                        <fileSets>
                                            <fileSet>
                                                <includes>
                                                    <include>${project.build.finalName}-swarm.jar</include>
                                                </includes>
                                                <directory>${project.build.directory}</directory>
                                                <outputDirectory>/</outputDirectory>
                                            </fileSet>
                                        </fileSets>
                                    </inline>
                                </assembly>
                                <entryPoint>
                                    <shell>java -jar /opt/${project.artifactId}-swarm.jar</shell>
                                </entryPoint>
                            </build>
                        </image>
                    </images>
                </configuration>
```

**Comment by rhuss** [comment]
Is this urgent ? If not I can pick it up over the weekend (but have to leave in 20 minutes ...)

**Comment by jstrachan** [comment]
oh its not urgent at all - take your time! :)

**Comment by jstrachan** [comment]
it'd be good to auto-detect Swarm health checks too btw! https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jaxrs/health

**Comment by davsclaus** [comment]
This would be lovely so end users can use the WF Swarm website generator (like spring start) to create a new project that has WF Swarm and what else they use. And then they can fairly easily add f-m-p to their pom.xml to have it working for docker/k8s.

And when we have this we can cut some videos showing this with SB / WF-Swarm.

**Comment by christian-posta** [comment]
this was merged recently; would love if folks could try it and then maybe kick off a new build? then we can update fabric8-forge to use the new build and get wf-swarm working on f8 ci/cd ootb!

**Comment by jstrachan** [comment]
should be there within the hour... 3.1.29

**Comment by christian-posta** [comment]
This seems sorted to me!

**Comment by jstrachan** [comment]
awesome thanks!
