### ISSUE TITLE
Deployment is always deleted

### ISSUE THREAD

**Issue by geertvos** [fabric8io/fabric8-maven-plugin#1441]
### Description
When I deploy a Deployment using the maven plugin, it always recreates the deployment by deleting it first and then creating a new one. This means I cannot have any rolling upgrades on my pods.

Shouldn't the plugin recognize the existing deployment and perform an update?

### Info

* f-m-p version :
3.5.42

* Maven version (`mvn -v`) :

Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-38-generic", arch: "amd64", family: "unix"

```

```
* Kubernetes / OpenShift setup and version :
I am using a Kubernetes cluster version 1.10.5

* If it's a bug, how to reproduce :
The command I execute is mvn fabric8:deploy

**Comment by rohanKanojia** [comment]
@geertvos : In my opinion, this should not be the case. fmp does have a `fabric8.recreate` flag which deletes the previous deployment and then reapplies. Could you please provide sample pom so that we can reproduce issue?
