### ISSUE TITLE
Option to Disable Liveness/readiness checks

### ISSUE THREAD

**Issue by Na3blis** [fabric8io/fabric8-maven-plugin#1444]
### Description
I need to be able to disable the actuator enricher, or be able to overwrite the path that it checks for both liveness and readiness
### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) : 3.6.0
* Kubernetes / OpenShift setup and version : 
minikube v0.30.0
* If it's a feature request, what is your use case :
My project uses custom JWTs to secure endpoints. K8 is not able to access the standard actuator endpoints, and so we have created custom endpoints for liveness/readiness checks that are open for k8. However, since we have actuator on the classpath, f-m-p adds liveness and readiness checks that will always fail because k8 gets a 403 error.

**Comment by rohanKanojia** [comment]
@Na3blis : Could you please try 4.0.0 out and see if it is working as per your use case?

**Comment by Na3blis** [comment]
That's what I was looking for, thanks!

**Comment by rohanKanojia** [comment]
@Na3blis : Did it work according to your use case?

**Comment by Na3blis** [comment]
Yep, that resolved the issues. Both options actually were good, and resolved my issues when testing

**Comment by rohanKanojia** [comment]
good to hear ;-)
