### ISSUE TITLE
Cannot deploy kubernetes resources to a specific namespace when connected to default

### ISSUE THREAD

**Issue by yonoos** [fabric8io/fabric8-maven-plugin#1470]
### Description
It seems that is not possible to deploy namespaced kubernetes fragments when the kube context is connected to an other namespace than one specified in yaml files 
### Info

* f-m-p version : 4.0.0-M2
* Maven version (`mvn -v`) : 3.6.0
```

```
* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce : 

1. set current namespace in ~kube/config to default
2. run fabric8:resources to create a namespace, a deployment and a service in the created namespace 

* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@yonoos : Hi, Could you please elaborate on your issue? A sample pom and error message would be super helpful for us.
