### ISSUE TITLE
SecretPatcher don't handle stringData Secrets correctly

### ISSUE THREAD

**Issue by bohmber** [fabric8io/fabric8-maven-plugin#1475]
### Description
If you provide stringData Secrets the first deploy is fine. All secrets properties are in the data section. After the next deployment all stringData Secrets are deleted from the data section. I assume the patch logic didn't know you can specifiy the secret properties as stringData as well.

https://docs.openshift.com/container-platform/3.7/dev_guide/secrets.html#dev-guide-secrets

### Info

* f-m-p version : 4.0.0-M3
* Maven version (`mvn -v`) : 3.5
```

```
* Kubernetes / OpenShift setup and version : OpenShift 3.7
* If it's a bug, how to reproduce : see description

**Comment by rohanKanojia** [comment]
you mean `4.0.0-M2` not M3, right? :-P

**Comment by bohmber** [comment]
Just tested it with 4.0-SNAPSHOT = 4.0.0-M3. 
I need some features from the snapshot
