### ISSUE TITLE
Support for `odo watch`

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1477]
Implement variation of fabric8:watch which uses "odo watch".

* Switched on by configuration
* Instrument the `DeploymentConfig`:
  - Add an emptyDir volume to the DC
  - Add an init container which contains `supervisord` and copies the binary to the emptyDir volume which has been mounted in the init container
  - Modify the command of the original to use supervisord to call the original entry point (e.g. run.sh)
* Start `odo watch` in binary mode. Specify target directory as a label on the base image. Question: How to specify the files (jar, config) to watch?

Also, consider an incremental by watching the source code and triggering compilation & packaging by a change of a source file. See https://github.com/reactiverse/vertx-maven-plugin/blob/master/src/main/java/io/reactiverse/vertx/maven/plugin/utils/IncrementalBuilder.java as a reference how the vertx-maven-plugin does. This should be possible be enabled and disabled. Allow specifying file patterns for the stuff to be watched.

**Comment by rhuss** [comment]
@lordofthejars Is this something which is still a thing or is such work tracked elsewhere ?

**Comment by lordofthejars** [comment]
Well now this is tracked in `odo-java`

**Comment by rhuss** [comment]
So let's close this issue then.
