### ISSUE TITLE
Move to fabric8-kit's BuildService

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1482]
* Remove dependency on dmp and move to "BuildService" API from the https://github.com/fabric8io/fabric8-kit library.

* Implement an S2I BuildService 

* Think about Jibn implementation

**Comment by rhuss** [comment]
@lordofthejars @dev-gaur Actually this would be the starting point for the GSoC project dealing with Jib or Buildah.

**Comment by rohanKanojia** [comment]
https://github.com/jshiftio/jshift-kit has been created.
