### ISSUE TITLE
Integrate Dekorate into fmp

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1483]
Integrate ap4k (annotation based resource configuration)

See https://github.com/ap4k/ap4k/tree/master/examples/spring-boot-with-fmp-on-kubernetes-example for a simple example. Maybe this is already good enough.

@iocanel wdyt what's needed for a good ap4k integration into fmp ?

**Comment by cmoulliard** [comment]
Have you documented how to use such property system @iocanel ?

**Comment by rohanKanojia** [comment]
The project has been renamed to Dekorate and is available here: https://github.com/dekorateio/dekorate

**Comment by manusa** [comment]
Recording of meeting regarding this topic can be found here:
https://bluejeans.com/playback/s/SlaPpPDBTBmlJwZvsXsiHrh7y1n8hJfNvTz2VSg2RBQpHtCaHXywaG87SkcHfGTV

**Comment by manusa** [comment]
Integration is now ready and available both in FMP and JKube.
