### ISSUE TITLE
auto-detect WAR projects and do the right thing OOTB (also defaulting the webPort to 8080?)

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#149]
we should be able to default the docker build based on project packaging of `war`

**Comment by davsclaus** [comment]
Yeah I hit that issue today to run an old camel + tomcat project.

I was trying to fiddle with the maven plugin to specify a base docker image (from) and select rootWar and whatnot. But failed misrebly.

I think we need a war generator that creates a docker image that runs in tomcat / jetty (easy to pick which one).

**Comment by davsclaus** [comment]
@ro14nd its a bit old school with WAR but it makes a great story for migrating your plain tomcat WARs to docker / kubernetes if all they do is to add the f-m-p.

**Comment by kameshsampath** [comment]
@jstrachan @davsclaus i have a generator locally built to map to this, will send a PR to soon

**Comment by jstrachan** [comment]
awesome!

**Comment by kameshsampath** [comment]
@jstrachan what are the common file detections you feel we can add to the project to set the  default images ?
some things which I see are 

* beans.xml/*-ds.xml - can quality for jboss/wildfly
* jboss-deployment-structure.xml - can qualify for jboss/wildfly
* all others will be fabric8/tomcat-8

**Comment by kameshsampath** [comment]
@davsclaus https://github.com/kameshsampath/fabric8-maven-plugin/tree/issue-149 is the WIP for webapp(war) generator, the samples/simple-webapp does build a webapp with fabric8/tomcat-8 as base image.. please try it out and let me know if improvements.. am working onto improve it further before a PR

**Comment by jstrachan** [comment]
I've totally forgotten the magic file names ;) I thought there was canonical XML files that tomcat/jetty/jboss would look for in /WEB-INF - like jetty-context.xml or something - but can't seem to find them via googling

**Comment by kameshsampath** [comment]
@jstrachan  - they are META-INF/context.xml for tomcat , and WEB-INF/jboss-deployment-structure.xml or jboss-web.xml for Wildfly

**Comment by jstrachan** [comment]
ah cool. for jetty:

* WEB-INF/jetty-web.xml e.g.  https://github.com/jetty-project/spring-petclinic-patched/blob/patched/src/main/webapp/WEB-INF/jetty-web.xml
* target/jetty-logging.properties e.g. https://github.com/jetty-project/jetty-maven-plugin-examples/blob/master/webapp-2.5/src/main/resources/jetty-logging.properties

**Comment by kameshsampath** [comment]
@jstrachan right now the application should detect the image based magic files we discussed so far.

**Comment by rhuss** [comment]
As we have a webapp generator now, this issue can be closed.
