### ISSUE TITLE
Deploy Secret to OpenShift

### ISSUE THREAD

**Issue by Victoria2202** [fabric8io/fabric8-maven-plugin#1513]
Hello,

I am wondering how the Plugin works to only create a new Image-Pull-Secret for OpenShift.

Where do i have to add the OpenShift Server-Informations?

```
<plugin>
			    <groupId>io.fabric8</groupId>
			    <artifactId>fabric8-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>runIT</id>
						<phase>integration-test</phase>
						  <configuration>
							<resources>
								<secrets>
									<secret>
										<dockerServerId>myregistry-id</dockerServerId>
										<name>image-pull-secret</name>
										<namespace>myproject</namespace>
									</secret>
								</secrets>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**Comment by dev-gaur** [comment]
@rohanKanojia @lordofthejars ok to close this ?

@Victoria2202 I forgot to suggest you can just do `mvn fabric8:resource-apply`. Takes care of the `oc apply` part.

**Comment by dev-gaur** [comment]
@Victoria2202 Closing this issue. Feel free to comment here if your problem isn't resolved.
