### ISSUE TITLE
F-M-P should support setting resources on OpenShift deployment strategy (deployer pods)

### ISSUE THREAD

**Issue by mojsha** [fabric8io/fabric8-maven-plugin#1519]
I have a multi-tenant OpenShift cluster with default resource values set for pods. This default is also affecting the deployer pods which do not require alot of resources. E.g., I have a 2 Gb default limit set for pods and this is also allocated to the deployer pods. This hogs alot of resources, especially if I want to deploy alot of services simultaneously (which I do - in my usecase, I am setting up a new namespace with many micro-services). 

So what I want to do is basically to be able to have F-M-P allow me to specify the following section (bold) in the DeploymentConfig which is currently being stripped out:

  strategy:
    activeDeadlineSeconds: 10000
    **resources: {}**
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 3600
      updatePeriodSeconds: 1
    type: Rolling

I have looked at the code and it looks like the **DeploymentConfigOpenShiftConverter** needs to be modified. It is currently creating something pre-defined (ignoring the resource-fragment values) (https://github.com/fabric8io/fabric8-maven-plugin/blob/20dedc4df98e9424cd1168ebc2a00c0e5b2269a3/plugin/src/main/java/io/fabric8/maven/plugin/converter/DeploymentConfigOpenShiftConverter.java#L63).

@rohanKanojia

**Comment by rohanKanojia** [comment]
@mojsha : Could you please share your resource fragment so that I can try it out?

**Comment by mojsha** [comment]
@rohanKanojia I do not have a working resource fragment as this is a new feature. But basically, you can take any DeploymentConfig resource fragment and add the section I mentioned in the original post above, and it should still be there in the generated OpenShift resource file. What is happening currently is that if I add the section above it gets stripped out by F-M-P and doesn't exist in the final OpenShift resource file.

**Comment by hetzge** [comment]
I have the same problem. Always if i want to set the strategy to "Recreate" it ignores the complete strategy section and uses a generated one instead.

```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: ${mongodb.service.name}
spec:
  strategy:
    type: Recreate
...
```
In the target\fabric8 the yaml file is correct but in the target\fabric8\applyJson the json contains the generated strategy.

Is there a workaround to set the strategy in a DeploymentConfiguration ?

**Comment by hetzge** [comment]
I tried it with version 4.0.0 and now it seems to work like expected. The Recreate strategy is not lost anymore. Thank you :)

**Comment by rohanKanojia** [comment]
@mojsha: Strange, I wasn't able to reproduce this issue on `4.0.0`. Here is what I did:

1.) Added a deploymentconfig.yml in src/main/fabric8 directory in `samples/spring-boot`
```
spec:
  strategy:
    type: Recreate
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
  replicas: 1
  template:
    metadata:
      labels:
        component: db
    spec:
      containers:
        # MySql image
      - name: "db"
        image: "mysql:5"
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_DATABASE
          value: abi88
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: "mysql"
          subPath: "mysql"
        resources:
          limits:
            memory: 200Mi
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: abi88
      triggers:
      - type: ConfigChange
```
2.) Did a `mvn clean install fabric8:deploy` to deploy application.
3.) Checked generated DeploymentConfig :
```
~/work/repos/fabric8-maven-plugin/samples/spring-boot : $ oc get pods
NAME                                           READY     STATUS      RESTARTS   AGE
fabric8-maven-sample-spring-boot-1-deploy      1/1       Running     0          25s
fabric8-maven-sample-spring-boot-1-f8kdn       0/2       Pending     0          22s
fabric8-maven-sample-spring-boot-s2i-2-build   0/1       Completed   0          51s
~/work/repos/fabric8-maven-plugin/samples/spring-boot : $ oc get dc -o yaml
apiVersion: v1
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-branch: pr/issue1519
      fabric8.io/git-commit: bc4028f34e0b05ded9319abae7ab38b3e7c0a84c
      fabric8.io/git-url: git@github.com:rohanKanojia/fabric8-maven-plugin.git
      fabric8.io/scm-tag: HEAD
      fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-spring-boot
    creationTimestamp: 2019-03-19T12:49:41Z
    generation: 1
    labels:
      app: fabric8-maven-sample-spring-boot
      group: io.fabric8
      provider: fabric8
      testProject: spring-boot-sample
      version: 4.0-SNAPSHOT
    name: fabric8-maven-sample-spring-boot
    namespace: rohankanojia
    resourceVersion: "3899777786"
    selfLink: /apis/apps.openshift.io/v1/namespaces/rohankanojia/deploymentconfigs/fabric8-maven-sample-spring-boot
    uid: 76722901-4a45-11e9-87e7-12d641ec7610
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: fabric8-maven-sample-spring-boot
      group: io.fabric8
      provider: fabric8
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      type: Recreate
    template:
      metadata:
        annotations:
          fabric8.io/git-branch: pr/issue1519
          fabric8.io/git-commit: bc4028f34e0b05ded9319abae7ab38b3e7c0a84c
          fabric8.io/git-url: git@github.com:rohanKanojia/fabric8-maven-plugin.git
          fabric8.io/scm-tag: HEAD
          fabric8.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/fabric8-maven-sample-spring-boot
        creationTimestamp: null
        labels:
          app: fabric8-maven-sample-spring-boot
          component: db
          group: io.fabric8
          provider: fabric8
          testProject: spring-boot-sample
          version: 4.0-SNAPSHOT
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            value: secret
          - name: MYSQL_DATABASE
            value: abi88
          image: mysql:5
          imagePullPolicy: IfNotPresent
          name: db
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          resources:
            limits:
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql
            subPath: mysql
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: fabric8-maven-sample-spring-boot:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - chmod
          - "777"
          - /var/lib/mysql
          image: busybox
          imagePullPolicy: IfNotPresent
          name: fmp-volume-permission
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: abi88
    test: false
    triggers:
    - type: ConfigChange
  status:
    availableReplicas: 0
    conditions:
    - lastTransitionTime: 2019-03-19T12:49:41Z
      lastUpdateTime: 2019-03-19T12:49:41Z
      message: Deployment config does not have minimum availability.
      status: "False"
      type: Available
    - lastTransitionTime: 2019-03-19T12:49:41Z
      lastUpdateTime: 2019-03-19T12:49:41Z
      message: replication controller "fabric8-maven-sample-spring-boot-1" is waiting
        for pod "fabric8-maven-sample-spring-boot-1-deploy" to run
      status: Unknown
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 1
    replicas: 1
    unavailableReplicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
~/work/repos/fabric8-maven-plugin/samples/spring-boot : $
```

As you can see, I do have resources set on my deployment strategy. It can be a case that this could be an issue on 3.5.42, but I think it is fixed in 4.0.0 since we got rid of these ugly Converters. Please check whether you still face this issue on 4.0.0.

**Comment by rohanKanojia** [comment]
@mojsha : I tried on Openshift 3.10 as well, but in this case also I was able to see desired result:
![Screenshot from 2019-03-19 19-44-42](https://user-images.githubusercontent.com/13834498/54612758-88ec4b80-4a7f-11e9-889f-ee7677a9a2cc.png)

**Comment by rohanKanojia** [comment]
@mojsha : Were you able to resolve this based upon our discussion on IRC? Are we good to close this issue?

**Comment by mojsha** [comment]
@rohanKanojia I can confirm that this is working in 4.0.0. However, in 3.5.42 I could name my DC "xxxx-deploy.yaml" and it would work. Now it requires the whole word "deploymentconfig" in order to generate the resources correctly for some reason.

**Comment by rohanKanojia** [comment]
oops, I did that during modifying apiGroups:

https://github.com/fabric8io/fabric8-maven-plugin/blob/54ec89b469b5eeaf679b5916713f5da0f23e891d/core/src/main/java/io/fabric8/maven/core/util/kubernetes/KubernetesResourceUtil.java#L251-L260

**Comment by rohanKanojia** [comment]
@mojsha : Can we close this issue?

**Comment by mojsha** [comment]
@rohanKanojia I guess you could, but I am still a bit puzzled as to why it processes all of my DC resource fragment save the strategy section if my file contains the substring **deploy** and it works fine, but requires it to contain **deploymentconfig** for the strategy section to get processed.
