### ISSUE TITLE
Environment Selector for Yaml Files

### ISSUE THREAD

**Issue by mathianasj** [fabric8io/fabric8-maven-plugin#1533]
### Description
I would like to be able to have a flag to specify which environment files I would like to deploy.  There is sometime configmaps will vary between environments, and I do not see a way to have a folder and a flag to specify which sets of files to include/exclude as part of yaml fragments.  I would also like to limit a secret only be deployed to the namespace I currently select.  This is so I can maintain promotion to different environments and not affect another.  Currently the way the resource-apply is working and I have a namespace specified for a secret it deploys all the files to every namespace, this is not expected.  Also would like to see the same functionality for configmaps.

**Comment by dev-gaur** [comment]
Would you like to include/exclude yaml fragments for deployment via XML configuration in your project POM ?
