### ISSUE TITLE
Odo Maven plugin should reuse Odo installation

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/fabric8-maven-plugin#1544]

**Comment by dev-gaur** [comment]
So, a user should specify ODO_PATH in system env variable or in pom.xml plugin config, right ?

**Comment by lordofthejars** [comment]
No, it is a bit more complex than this, this is something I discussed with Rohan, and it might need some thinking, the idea is that odo tool is copied only once to a well known Maven directory. But I need to think a bit more exactly what is the best approach to follow, I will advocate for skip this issue for now since it is just an improvement.

**Comment by rohanKanojia** [comment]
@lordofthejars : Hey, Is this issue fixed?? If yes, can we close this issue?

**Comment by lordofthejars** [comment]
Yes, it is fixed.
