### ISSUE TITLE
When to switch on / off online mode for enrichers ?

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#157]
I did a refactoring of the GitEnricher since he constantly throws errors because trying to contact a running Kubernetes Cluster.

IMO the default should be offline, which could be switched on by a CD. The reason is, that enriching the resource descriptors with service urls coming from random clusters where one is currently logged in, and which end up in an jar-artefact, too, is not really good for versioning and reproducability (you can't recreate an artefact later if you are not running in the very same environment).

It's ok when running in a CD in order to store meta data about the current build because this artefact gets pushed around the pipeline (even then, one need to give up the dream that a single GIt tag is enough to reproducably recreate a piece of software). 

So my idea is to start in offline mode and let the CD switch it on with a property. This is currently possible by adding a `-Dfabric8.online` to the build scripts (if #156 gets merged in). Of course this can be set within the `pom.xml`, too for a permanent setting.

I introduced an `AbstractLiveEnricher` which does all the on / offline handling and is supposed to be the single entry point for contacting a cluster. 

I also renamed the GitEnricher to a BuildEnricher (since it adds also Jenkins meta data). 

Is this ok that we start offline by default ? This also avoids nasty errors and pauses when people start from scratch.

**Comment by nicolaferraro** [comment]
+1: I just came up with that (closed) PR for changing the log messages because people were saying "I cannot just execute the `mvn spring-boot:run` to see the quickstart running locally, it requires some kubernetes stuff".

IMHO, the f-m-p should not even try to contact the local kubernetes cluster, unless it is going to deploy the app to a cluster.

**Comment by rhuss** [comment]
I wonder whether there is fabric8 specific CD environment variable, which we could check for an online mode ? `BUILD_ID` is probably not good enough as it is set by **any** Jenkins build.

@rawlingsj maybe you have an idea how we could uniquely detect from within the plugin whether it is running in a CD run so that K8s service are accesible and we can extract the proper URL ?

**Comment by rawlingsj** [comment]
I think `${env.JOB_NAME}` or `${env.BUILD_ID}` should be ok

**Comment by rhuss** [comment]
@rawlingsj Yeah, but isn't `BUILD_ID` set for **any** Jenkins environment, whether it is running in Kubernetes or not ? The problem is, when running *online* then the enricher tries to detect the Service URL for Gogs (also a fabric8 special thing) and Jenkins.

What I really look for is an env which is specific to our CD which runs on top of Kubernetes (so that one can be somewhat sure that service lookup succeeds)

**Comment by rawlingsj** [comment]
Ah I see - as we're only talking for maven jobs here maybe we can use one of the env vars that are used to annotate resources that create UI links`GIT_URL`, `GIT_COMMIT` or `BUILD_URL `

**Comment by rawlingsj** [comment]
We don't have a specific env var used to identify a fabric8 pipeline build in Jenkins but perhaps one of the three above can help.

**Comment by rhuss** [comment]
@rawlingsj yes, that could work. 

Wouldn't it be a good idea to add an env `FABRIC8_CD` or so, that the detection is more bulletproof ? (or we could call it `VOLKSWAGEN_MODE`, too. or any car manufactor's label nowadays really :) We could add this to the Jenkins images (but wonder how slaves could inherit this env). But I guess it similar how `GIT_URL` et al are added.

**Comment by rohanKanojia** [comment]
@rhuss : I don't think this issue is still valid as we have moved fabric8 and fabric8-ui specific enrichers into a deprecated module. WDYT?

**Comment by rhuss** [comment]
Yes, I think we have moved that already out to the deprecated enrichers. Let's close this issue for now.
