### ISSUE TITLE
Support maven --batch-mode option

### ISSUE THREAD

**Issue by edrandall** [fabric8io/fabric8-maven-plugin#1572]
### Description
When running mvn --batch-mode option the expected behaviour is to remove all decorations from the output.  F8 however seems to ignore this and continues to emit output decorated by terminal color escape codes.
Output begins in monochrome but color codes appear as soon as the F8 plugin starts.  This seems to be detected from the terminal somehow, simply piping the mvn output eg. `mvn --batch-mode fabrig8:build | cat` is sufficient to suppress it.
Screenshot shows colorized output beginning with f8 plugin execution.
<img width="707" alt="Screen Shot 2019-03-12 at 15 31 49" src="https://user-images.githubusercontent.com/503627/54213246-02ae9300-44dc-11e9-8ec4-2029d5972628.png">

### Info

* f-m-p version : 3.5.42
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T19:41:47+01:00)
Maven home: /Users/erandall/BLKDeveloper/Apps/apache-maven-3.6.0
Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_171.jdk/Contents/Home/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.6", arch: "x86_64", family: "mac"
```
* Kubernetes / OpenShift setup and version : openshift 3.11
* If it's a bug, how to reproduce : mvn --batch-mode fabric8:build
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by edrandall** [comment]
Refresh.

**Comment by edrandall** [comment]
.

**Comment by rohanKanojia** [comment]
We need to prioritize this

**Comment by rohanKanojia** [comment]
we recently changed logging in docker-maven-plugin. Maybe this is coming from there.
