### ISSUE TITLE
Spring boot generator not working with application.yml file

### ISSUE THREAD

**Issue by atrifyllis** [fabric8io/fabric8-maven-plugin#1581]
### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) : 3.5.2
```

```
* Kubernetes / OpenShift setup and version : Kubernetes 1.11
* If it's a bug, how to reproduce :
run mvn clean install fabric8:build

docker image produced does not expose server.port as defined in application.yml, keeps exposing default 8080 port.

This works with application.properties

* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*
https://github.com/atrifyllis/demo-kube.git

**Comment by rohanKanojia** [comment]
@atrifyllis : Could you please try again with 4.0.0? 3.5.41 is quite old release..

**Comment by atrifyllis** [comment]
Thanks and sorry for the inconvenience. I probably copied the version from an old tutorial..

**Comment by rohanKanojia** [comment]
@atrifyllis : No problem, Glad to know it's working on 4.0.0 :tada:
