### ISSUE TITLE
Enricher API : enricher.create is called twice by manager instead of enricher.enrich

### ISSUE THREAD

**Issue by Beennnn** [fabric8io/fabric8-maven-plugin#1582]
In class EnricherManager, the enricher method calls **enricher.create() instead of enricher.enrich()** see https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/java/io/fabric8/maven/plugin/enricher/EnricherManager.java#L98
Consequently, the create() method is called twice.

Suggested fix: replace` enricher.create(platformMode, builder);` with `enricher.enrich(platformMode, builder);`

It is related to this commit : https://github.com/fabric8io/fabric8-maven-plugin/commit/b3c6060b21fabdbe29eb03cc23cdf08a2353ace2

**Comment by rohanKanojia** [comment]
:face_with_thermometer:

**Comment by rohanKanojia** [comment]
@Beennnn : Thanks for noticing, could you create a quick PR please? Otherwise, I would do it maybe today or tomorrow....
