### ISSUE TITLE
Refactor HandlerHub for lazy loading

### ISSUE THREAD

**Issue by dev-gaur** [fabric8io/fabric8-maven-plugin#1587]
https://github.com/fabric8io/fabric8-maven-plugin/blob/54ebf791ea70c341331824e9e1f517c41f25b70a/core/src/main/java/io/fabric8/maven/core/handler/HandlerHub.java

Currently 8 Handler instances are created by the constructor unnecessary populating the java heap  as only 1 of the 8 instances are used at a moment of time.

**Comment by karthikmg** [comment]
Hi @dev-gaur 
I would like to contribute the fix for this issue.
This is my first time contribution to open source.
Please let me know what approach to take to fix this.
Is it fine to have a null check and then create the instance in the getter methods?

**Comment by dev-gaur** [comment]
Yes, create the instance in the getter methods. 

For eg., 
```
    public JobHandler getJobHandler() {
        return jobHandler;
    }
```
can be refactored as 

```
    public JobHandler getJobHandler() {
        return new JobHandler(podTemplateHandler);
    }
```

**Comment by karthikmg** [comment]
Thanks. Which branch should I use to make these changes and send a pull request?

**Comment by dev-gaur** [comment]
Create a branch called #issue1587 :)

**Comment by dev-gaur** [comment]
> Won't this change make the getter method return a new handler instance every time the getter method is invoked?

If you'll look into the usage of those handlers instance, we don't want to let one instance affect the state of the another handler instance, so we need a fresh instance everytime getXHandler( ) is called.

**Comment by karthikmg** [comment]
@ theexplorist
I was working on this item as you can see from the comments above.
**At least have the courtesy of putting a comment before taking up other's task and submitting a pull request.**

This is the second time I am in this situation in the week. :(

**Comment by dev-gaur** [comment]
@karthikmg we can't lock an issue on any particular contributor. @theexplorist created a PR which was good to merge.

There are other starter issues for you to work on. 

You can get involved in the kubernetes-client repository as well

https://github.com/fabric8io/kubernetes-client/labels/low%20hanging%20fruit
