### ISSUE TITLE
Release FMP 4.1.0

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/fabric8-maven-plugin#1589]

**Comment by rohanKanojia** [comment]
@lordofthejars @dev-gaur @mojsha: I'm thinking about releasing fabric8 maven plugin tomorrow. Does anyone have any objections? Are we good with releasing it? There are some people who want updated version(like in case of #1620) urgently.

**Comment by lordofthejars** [comment]
Go for it. Releasing a new version is just free.

**Comment by mojsha** [comment]
@rohanKanojia Can you please hold off until we have sorted out watch? I am currently unable to test it due to the other issue with duplicate sidecar container.

**Comment by Ladicek** [comment]
Thanks for 4.1.0! :heart_eyes:
