### ISSUE TITLE
Add CRD Support in FMP (also implies a Kubernetes client effort)

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/fabric8-maven-plugin#1591]

**Comment by rohanKanojia** [comment]
Right now we're able to create CustomResourceDefinitions using resource fragments, so if you place your `crd.yml` in `src/main/fabric8` directory and run fabric8 maven plugin goals. You would be able to see your CRDs being created and applied onto the cluster.

However, right now it's not possible to create a CustomResource of that CRD type you just created using fmp in previous step. We need to change things on client side to be able to achieve this.

**Comment by rohanKanojia** [comment]
So, I've raised a PR in client which got merged recently : https://github.com/fabric8io/kubernetes-client/pull/1472 . It has got support for all the basic things like create, get, list, update and delete. This would be available in upcoming release of Fabric8 Kubernetes Client
