### ISSUE TITLE
Create documentation for ODO Java.

### ISSUE THREAD

**Issue by lordofthejars** [fabric8io/fabric8-maven-plugin#1593]

**Comment by rohanKanojia** [comment]
This is something I would love to help you in. We should also consider getting some help from the docs team(since we need resources with good english also)

**Comment by rohanKanojia** [comment]
@lordofthejars : Isn't this closed by https://github.com/jshiftio/odo-java/pull/21 ?

**Comment by lordofthejars** [comment]
Yes
