### ISSUE TITLE
aggregating YAMLs doesn't work for OpenShift with FMP 4.0.0

### ISSUE THREAD

**Issue by Ladicek** [fabric8io/fabric8-maven-plugin#1607]
### Description

The `fmp-dependency` enricher (`DependencyEnricher` class) can aggregate multiple YAMLs available on classpath. In FMP version 4.0.0, this doesn't work for OpenShift -- the aggregated files are identical to the Kubernetes YAMLs.

It's probably easiest for me to explain it on an example. Steps to reproduce:

1. git clone -b update-to-2.4.0 https://github.com/Ladicek/thorntail-circuit-breaker.git
1. cd thorntail-circuit-breaker
1. mvn clean verify -Popenshift,openshift-it
1. observe error `Could not resolve route: thorntail-circuit-breaker-name. Available routes: []`

At this point, look into `tests/target/classes/META-INF/fabric8/`. The `kubernetes` directory and `kubernetes.yml` file are OK, exactly what I'd expect. However, the `openshift` directory and `openshift.yml` file are identical to `kubernetes` / `kubernetes.yml`, which is definitely _not_ what I expect. I expect the aggregate to be, well, an aggregate of the OpenShift files from the `name-service` and `greeting-service` modules.

This works fine in 4.0.0-M2. I was able to track the issue down to this change: https://github.com/fabric8io/fabric8-maven-plugin/commit/9b648cfaf76a04517ff0a6895170019b6006d428#diff-c7c605106d3e8005f2161d83dce35592

### Info

* f-m-p version : 4.0.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /home/lthon/software/apache-maven
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
Default locale: cs_CZ, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-46-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version : OKD 3.11 with Minishift 1.32
* If it's a bug, how to reproduce : see above
* Sample project : https://github.com/Ladicek/thorntail-circuit-breaker.git # note that the `update-to-2.4.0` branch is required

**Comment by juangon** [comment]
This problem affects some aggregated test we are using too. As @Ladicek said, it worked fine on 4.0.0.M2.
Itr would be great if this could be reviewed and released.

Thanks in advance.

**Comment by rohanKanojia** [comment]
@juangon @Ladicek : Thanks a lot for finding issue and pushing a fix, This would be merged and be available in 4.1.0, which is gonna be released within a week :-)

**Comment by Ladicek** [comment]
Great, thanks!

**Comment by rohanKanojia** [comment]
@Ladicek : Just to understand your issue. Is your issue these duplicate files in openshift/ directory:
```
~/work/repos/thorntail-circuit-breaker/tests/target/classes/META-INF/fabric8/kubernetes : $ ls
thorntail-circuit-breaker-greeting-deployment.yml  thorntail-circuit-breaker-name-deployment.yml
thorntail-circuit-breaker-greeting-service.yml     thorntail-circuit-breaker-name-service.yml
~/work/repos/thorntail-circuit-breaker/tests/target/classes/META-INF/fabric8/kubernetes : $ ls
thorntail-circuit-breaker-greeting-deployment.yml  thorntail-circuit-breaker-name-deployment.yml
thorntail-circuit-breaker-greeting-service.yml     thorntail-circuit-breaker-name-service.yml
~/work/repos/thorntail-circuit-breaker/tests/target/classes/META-INF/fabric8/kubernetes : $ cd ..
~/work/repos/thorntail-circuit-breaker/tests/target/classes/META-INF/fabric8 : $ cd openshift/
~/work/repos/thorntail-circuit-breaker/tests/target/classes/META-INF/fabric8/openshift : $ ls
thorntail-circuit-breaker-greeting-deployment.yml  thorntail-circuit-breaker-name-deployment.yml
thorntail-circuit-breaker-greeting-service.yml     thorntail-circuit-breaker-name-service.yml
~/work/repos/thorntail-circuit-breaker/tests/target/classes/META-INF/fabric8/openshift : $ 
```

How can I test your repository on SNAPSHOT version?

**Comment by Ladicek** [comment]
The issue is that the `openshift` directory contains Kubernetes resources. It should contain OpenShift resources.

What do you mean by "test your repository on SNAPSHOT version"? If you mean SNAPSHOT version of FMP, then just update the `version.fabric8-maven-plugin` property in `/pom.xml`.

Just to be sure, again highlighting that the `update-to-2.4.0` branch is required.

**Comment by Ladicek** [comment]
Also, in addition to `openshift` directory, same applies to the `openshift.yml` aggregate file. Again it contains the Kubernetes resources instead of OpenShift resources.

**Comment by rohanKanojia** [comment]
Yeah, I figured that out :laughing: . Testing your change now

**Comment by rohanKanojia** [comment]
@Ladicek : okay, it works! . Just tested your change and it seems to generate  openshift resources in openshift/ directory. But I'm wondering why they're getting generated twice

**Comment by Ladicek** [comment]
I don't think they're generated twice. They are just copied from the `-classes.jar` artifacts of the dependencies. Or I totally misunderstood :-)

**Comment by rohanKanojia** [comment]
Hm, okay
