### ISSUE TITLE
Aggregate profile in OpenShift mode does not use openshift.yml

### ISSUE THREAD

**Issue by gytis** [fabric8io/fabric8-maven-plugin#1620]
### Description
I use aggregate profile to pull in configurations of different modules for integration testing. Tests run on openshift and openshift profile is picked up correctly. However, after upgrade to FMP 4.0.0 aggregate profile started using kubernetes.yml instead of openshift.yml from the dependency jars.
My FMP setup: https://github.com/snowdrop/spring-boot-messaging-work-queue-booster/blob/sb-2.1.x-upgrade-fmp-to-4.0.0/tests/pom.xml#L75

### Info

* f-m-p version : 4.0.0
* Maven version (`mvn -v`) : 3.3.9
* Kubernetes / OpenShift setup and version :
```
OpenShift Master: v3.11.0+06cfa24-67
Kubernetes Master: v1.11.0+d4cacc0
OpenShift Web Console: v3.11.0+ea42280
oc: v3.11.0+0cbc58b
```
* If it's a bug, how to reproduce :

```
git clone https://github.com/snowdrop/spring-boot-messaging-work-queue-booster -b sb-2.1.x-upgrade-fmp-to-4.0.0
cd spring-boot-messaging-work-queue-booster
./mvnw clean verify -Popenshift,openshift-it
```

**Comment by rohanKanojia** [comment]
Umm, it got fixed in #1605 . Could you please try on snapshot build of master?

**Comment by gytis** [comment]
Sorry I missed that. Snapshot works as expected. @rohanKanojia When is the next release expected?

**Comment by rohanKanojia** [comment]
@gytis : It's expected within 1-2 weeks

**Comment by gytis** [comment]
Perfect! Thanks

**Comment by Ladicek** [comment]
It was "within a week" 9 days ago ;-) https://github.com/fabric8io/fabric8-maven-plugin/issues/1607#issuecomment-479440910

For now, we stayed on 4.0.0-M2 in those 2 or 3 boosters that used aggregation.

**Comment by gytis** [comment]
Thanks @Ladicek , I'll start using 4.0.0-M2 as well.

**Comment by rohanKanojia** [comment]
@Ladicek @gytis : yeah, sorry. It has got delayed a bit. I would try to do it as soon as I can.

**Comment by Ladicek** [comment]
4.1.0 is now available, yay :tada: :beers:
