### ISSUE TITLE
Minimal profile needs a relook

### ISSUE THREAD

**Issue by dev-gaur** [fabric8io/fabric8-maven-plugin#1622]
https://github.com/fabric8io/fabric8-maven-plugin/blob/cbe2d51f42a060bafddd4f77bcf9eb92fe1f44e2/plugin/src/main/resources/META-INF/fabric8/profiles-default.yml#L100

FMP code has undergone a lot of refactor since minimal profile was last updated.
A lot of new enrichers have been created.

Here's a list of enrichers I think should be considered to be added :

Default enrichers : That create resources for kuberneteslist from XML config

* DefaultNamespaceEnricher
* DefaultMetadataEnricher
* ConfigMapEnricher ?
* ControllerViaPluginConfigEnricher
* change fmp-project --> fmp-project-label

Enrichers that generate openshift specific enricher

* DeploymentConfigEnricher
* ProjectEnricher ( fmp-openshift-project )
* ExposeEnricher
* RouteEnricher

Suggest the changes to this list. @rohanKanojia @lordofthejars

**Comment by lordofthejars** [comment]
I have no strong opinion about it

**Comment by rohanKanojia** [comment]
Yeah, I'm okay with adding this except ConfigMapEnricher
