### ISSUE TITLE
how to add entrypoint when execute docker:run

### ISSUE THREAD

**Issue by flyingZippo** [fabric8io/fabric8-maven-plugin#1627]
### Description
I am using a flyway docker container https://github.com/flyway/flyway-docker, I would like to execute: docker run --rm boxfuse/flyway -url=jdbc:h2:mem:test -user=sa info

Does f-m-p support to add commands when call mvn docker:run?
But I couldn't find a way to config that in pom.xml
### Info

* f-m-p version : 0.30.0
* Maven version (`mvn -v`) :
```
3.3.9
```

**Comment by rohanKanojia** [comment]
You need to file an issue here: https://github.com/fabric8io/docker-maven-plugin , bdw http://dmp.fabric8.io/#misc-startup might help

**Comment by flyingZippo** [comment]
> You need to file an issue here: https://github.com/fabric8io/docker-maven-plugin , bdw http://dmp.fabric8.io/#misc-startup might help

Thank you, but it is in the build phase, I want to do it in docker run command. I will update the description.

**Comment by lordofthejars** [comment]
I close this issue, as the problem should be raised in https://github.com/fabric8io/docker-maven-plugin repo.
