### ISSUE TITLE
Support S2i images for Web Applications

### ISSUE THREAD

**Issue by ehsavoie** [fabric8io/fabric8-maven-plugin#1629]
### Description
According to the documentation: " S2I builds are currently not yet supported for the webapp generator." 
### Info
Currently those applications are not supported so we can't use fabric8 to builds configurable webapps. Given that  WildFly S2i images are evolving to be lighter and provisioned by the user, this use case would make sense.
* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
being able to build a JavaEE webapp with WildFly.

**Comment by lordofthejars** [comment]
Hi, thank you very much for opening this issue. Currently web applications are supported with s2i in case of using a WAR package by creating a container with Wildfly running the produced WAR.

Can you elaborate more your use case in case that this is not meeting your requirements?
