### ISSUE TITLE
Enrichers to configmap

### ISSUE THREAD

**Issue by h3nrique** [fabric8io/fabric8-maven-plugin#1634]
Its not possible to change the name of configmap in tag `configMap`, always is `xmlconfig`.

```
$ oc get configmap
NAME        DATA      AGE
xmlconfig   1         20m
```
### Description
Include in project the config below and run `mvn fabric8:deploy`
```
<configuration>
                            <resources>
                                <configMap>
                                    <entries>
                                        <entry>
                                            <file>src/main/resources/application.properties</file>
                                        </entry>
                                    </entries>
                                </configMap>
                            </resources>
                        </configuration>
```

### Info

* f-m-p version : 4.1.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.2
Maven home: /usr/share/maven
Java version: 1.8.0_171, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-29deepin-generic", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version (`oc version`) : 
```
oc v3.10.45
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.210:8443
kubernetes v1.11.0+d4cacc0
```

* Minishift version (`minishift version`) : 
```
minishift v1.33.0+ba29431
```

Looking the classes [1] [2] I propose create a property `name` in class [2]. I will try create a local version and if works I open a pull request.

[1] - https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ConfigMapEnricher.java
[2] - https://github.com/fabric8io/fabric8-maven-plugin/blob/master/core/src/main/java/io/fabric8/maven/core/config/ConfigMap.java

**Comment by rohanKanojia** [comment]
@h3nrique : Yeah, looks like a bug which we should fix.

**Comment by rohanKanojia** [comment]
This is due to hardcoding of name in ConfigMapEnricher here:
https://github.com/fabric8io/fabric8-maven-plugin/blob/b0e7ad860a5bbe4ab71be3d0613862a1f14a8be3/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/ConfigMapEnricher.java#L96

This class is used as model for ConfigMap XML configuration: [ConfigMapEntry.java](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/core/src/main/java/io/fabric8/maven/core/config/ConfigMapEntry.java)

**Comment by h3nrique** [comment]
@rohanKanojia I can try update here, what a branch I can make a pull request?

**Comment by rohanKanojia** [comment]
You can make a pull request against latest master
