### ISSUE TITLE
Cannot extract Git information: java.lang.NullPointerException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-maven-plugin#1635]
### Description

when using fabric8-maven-plugin for project that are nto connected to git, there is this error message in log:
```
[INFO] --- fabric8-maven-plugin:7.4.0.sb2.fuse-740002:resource (default) @ camel-ose-springboot-xml ---
[INFO] F8: Using docker image name of namespace: test-ose
[INFO] F8: Running generator spring-boot
[ERROR] F8: spring-boot: Cannot extract Git information: java.lang.NullPointerException: java.lang.NullPointerException
```

### Info

* f-m-p version : using the redhat one 7.4.0.sb2.fuse-740002
* Maven version (`mvn -v`) : 3.5.3
* Kubernetes / OpenShift setup and version : 
OpenShift Master:
v3.9.74
Kubernetes Master:
v1.9.1+a0ce1bc657
OpenShift Web Console:
v3.9.74
* If it's a bug, how to reproduce :
use a project without git information
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@apupier : Do you face this on 4.1.0?

**Comment by apupier** [comment]
> @apupier : Do you face this on 4.1.0?

4.1.0 version of what?

**Comment by rohanKanojia** [comment]
yes latest release of fabric8-maven-plugin

**Comment by apupier** [comment]
I don't reproduce with io.fabric8:fabric8-maven-plugin 4.1.0

thanks @rohanKanojia 

sorry to not have tested to latest community version immediately
