### ISSUE TITLE
Adding image name in XML configuration leads to DuplicateKeyException  

### ISSUE THREAD

**Issue by geoand** [fabric8io/fabric8-maven-plugin#1640]
### Description

When using the [Spring Boot Http Booster](https://github.com/snowdrop/rest-http-example), if I add the following configuration to my `pom.xml`

```
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>fabric8-maven-plugin</artifactId>

            <configuration>
             <!-- this images section is what causes the error -->
              <images>
                <image>
                  <name>somerepo:18444/spring/http:1.0</name>
                </image>
              </images>
            </configuration>

            <executions>
              <execution>
                <id>fmp</id>
                <goals>
                  <goal>resource</goal>
                  <goal>build</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
``` 

then when I execute `mvn fabric8:resource -Popenshift` I get the following exception:

```
Failed to execute goal io.fabric8:fabric8-maven-plugin:4.1.0:resource (default-cli) on project rest-http: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:4.1.0:resource failed: Duplicate key somerepo:18444/spring/http:1.0
...
...
...
Caused by: java.lang.IllegalStateException: Duplicate key 
somerepo:18444/spring/http:1.0
    at java.util.stream.Collectors.lambda$throwingMerger$0 (Collectors.java:133)
    at java.util.HashMap.merge (HashMap.java:1254)
    at java.util.stream.Collectors.lambda$toMap$58 (Collectors.java:1320)
    at java.util.stream.ReduceOps$3ReducingSink.accept (ReduceOps.java:169)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:708)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:499)
    at io.fabric8.maven.enricher.standard.openshift.ImageChangeTriggerEnricher$1.visit (ImageChangeTriggerEnricher.java:72)
``` 

Basically what seems to be happening is that when the image name is set (in this case to artifactrepository.fanniemae.com:18444/demo-boot/demo-boot:1.0), FMP thinks there are two images (the configured one and the default one that is is formed from groupId and artifactId).
This in turn leads FMP to create attempt to create 2 different containers of the same name. The exception is thrown when FMP tries to create a map using the Streams API and having keys collide.

### Info

* f-m-p version : 4.1.0
* Maven version (`mvn -v`) : 3.5.4
* Kubernetes / OpenShift setup and version : 1.11, 3.11

**Comment by geoand** [comment]
I can add a PR for this if someone points me in the right direction.

Basically I see that the final method that adds the second image is `JavaExecGenerator#customize`. I would go ahead and open the PR but I am a little hesitant in doing in that since I don't understand why `JavaExecGenerator#customize` is being used when `List<ImageConfiguration> configs` is not empty.

**Comment by rohanKanojia** [comment]
@geoand: Sorry for the late reply. The reason why `JavaExecGenerator#customize` is being used because we only consider `ImageConfiguration` as null when it's `BuildImageConfiguration` is null. See: 

https://github.com/fabric8io/fabric8-maven-plugin/blob/e0d6b394a7abf75b5a23f6abd23ecba93a27afe7/generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java#L200-L203

If you add `<build>` section to your image configuration then the second image would not be generated.
There is a flag also to override this behavior, but I'm not sure that works properly.
https://github.com/fabric8io/fabric8-maven-plugin/blob/e0d6b394a7abf75b5a23f6abd23ecba93a27afe7/generator/api/src/main/java/io/fabric8/maven/generator/api/support/BaseGenerator.java#L57-L58
