### ISSUE TITLE
Support for zero-config jdk 11 Docker base image

### ISSUE THREAD

**Issue by grantsheer-eoh** [fabric8io/fabric8-maven-plugin#1647]
### Description
Looking to have the FMP support a Zero config JDK 11 Docker base image as it does for JDK 8. So ideally it should use the JDK 8/11 docker base image depending on whether the the compiler version of the Maven build is Java 8/11.
### Info
We ideally would want a zero-config (or close to it) option for creating a Spring Boot app using a JDK 11 Docker base image – as there is for JDK 8. I see there is a JDK 11 docker base image available as of April 2019: 
https://hub.docker.com/r/fabric8/java-centos-openjdk11-jdk
https://hub.docker.com/r/fabric8/java-centos-openjdk11-jre 
 
Also, I see there is a bug logged for JDK 11 on the maven plugin:
https://github.com/fabric8io/fabric8-maven-plugin/issues/1472
https://github.com/fabric8io/fabric8-maven-plugin/pull/1437 
https://github.com/fabric8io/fabric8-maven-plugin/projects/5 

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) : 3.5.3
```

```
* If it's a feature request, what is your use case : Deploy my JDK 11 Spring Boot App in Docker

**Comment by rohanKanojia** [comment]
@dev-gaur  is working on jdk11 Support.

**Comment by grantsheer-eoh** [comment]
Thanks.

@dev-gaur, when are you aiming to have that ready for? 

Also, which version is it planned for?

**Comment by dev-gaur** [comment]
@grantsheer-eoh I'm working on this now..

For the time being..

```
    <profile>
      <id>java11-image</id>
      <activation>
        <jdk>[11,)</jdk>
      </activation>
      <properties>
        <fabric8.generator.fromMode>docker</fabric8.generator.fromMode>
        <fabric8.generator.from>fabric8/java-centos-openjdk11-jre</fabric8.generator.from>
      </properties>
    </profile>
```

Add this profile to your project pom.
