### ISSUE TITLE
Release FMP 4.2.0

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1657]
It's been few months since last release. Let's release a last version of the plugin.

**Comment by aditzel** [comment]
That would be useful as I'm running in this issue that was fixed in the docker maven plugin but the existing version of FMP still references a version with this bug. 

https://github.com/fabric8io/docker-maven-plugin/issues/1152

**Comment by rohanKanojia** [comment]
cool, let's upgrade to dmp 0.30.0 also

**Comment by rohanKanojia** [comment]
I've raised #1658 , so you should get the fix in next release of fmp
