### ISSUE TITLE
cannot execute /usr/libexec/s2i/assemble

### ISSUE THREAD

**Issue by maffeis** [fabric8io/fabric8-maven-plugin#1663]
### Description

Dear all:

I'm doing a fabric8:deploy towards a "pro" account on OpenShift Online. The account has been freshly created, it contains a mysql deployment and nothing more. The error I'm getting is the following;

`F8: Failed to execute the build [Unable to build the image using the OpenShift build service]
[console.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/3345078/console.txt)
`

The console log is attached. My plugin configuration:

```xml
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>fabric8-maven-plugin</artifactId>
                        <version>4.1.0</version>

                        <executions>
                            <execution>
                                <id>fmp</id>
                                <goals>
                                    <goal>resource</goal>
                                    <goal>build</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
```
If I log into the openshift console, I can see the following information for the failed build:

STEP 8: RUN /usr/libexec/s2i/assemble
/bin/sh: 1: /usr/libexec/s2i/assemble: not found
subprocess exited with status 127
subprocess exited with status 127
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 127

[console.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/3345083/console.txt)

### Info

* f-m-p version : fabric8-maven-plugin 4.1.0
* Maven version (`mvn -v`) : 3.6.1
```

**Comment by h3nrique** [comment]
Could you provide a demo project that this occurs?

What's your Windows version?

**Comment by maffeis** [comment]
Hi Paulo

I'm using Windows 10 Pro. I'll try to come up with a stripped down sample project that produces the issue.

Silvano

**Comment by rohanKanojia** [comment]
@maffeis : Could you also share logs with `-X` option? A sample project to reproduce this error would definitely help

**Comment by manusa** [comment]
See https://github.com/fabric8io/fabric8-maven-plugin/issues/1818#issuecomment-654624296
