### ISSUE TITLE
Docs: Compatibility with OpenShift and Kubernetes" section outdated

### ISSUE THREAD

**Issue by getjack** [fabric8io/fabric8-maven-plugin#1664]
### Description
The section "Compatibility with OpenShift and Kubernetes" in the docs is heavily outdated and shows support for versions 3.5x.x but this tool is on 4.x already.

### Info
Either drop the support table or updated it :)

**Comment by rohanKanojia** [comment]
Not sure I understand your point. I agree that we need to add entry for 4.1.0 but what do you mean by `shows support for versions 3.5x.x but this tool is on 4.x already.`

**Comment by getjack** [comment]
Sorry for the late response I'll give you an example.

The plugin is right now at version 4.1.0. The section https://maven.fabric8.io/#kubernetes-compatibility only lists the Plugins compability with Kubernetes for Version 3.5.32 to 3.5.38. So one might think that 4.1.0 does not support Kubernetes.

Same goes for the enricher section. The section https://maven.fabric8.io/#f8-healthcheck-spring-boot shows an enricher example which does not work with version 3.5.42 (i tried that) and has no example for a version 4+ plugin. So this is outdated too.

Is it a bit easier to understand now?

**Comment by rohanKanojia** [comment]
@getjack : oh, right. Could you please raise a quick PR to fix this if you have time?

**Comment by getjack** [comment]
@rohanKanojia Done.
