### ISSUE TITLE
switchToDeployment does not work

### ISSUE THREAD

**Issue by wuyongCloud** [fabric8io/fabric8-maven-plugin#1666]
### Info

* f-m-p version :4.1.0
* Maven version (`mvn -v`) :3.6.1
```
spring boot:2.0.6
label<switchToDeployment> It didn't work，The generated file contains parameters openshift.yaml “kind:DeploymentConfig”
```
* Kubernetes / OpenShift setup and version :v1.10/v3.10

**Comment by rohanKanojia** [comment]
Hmm, Do you need this feature? I think we dropped this while #678 but forgot to remove this flag. Does `fabric8.mode=kubernetes` solve your use case?

**Comment by wuyongCloud** [comment]
@rohanKanojia 
<plugin>
	<groupId>io.fabric8</groupId>
	<artifactId>fabric8-maven-plugin</artifactId>
	<version>${fabric8.maven.plugin.version}</version>
	<executions>
		<execution>
			<id>fmp</id>
			
			<goals>
				<goal>resource</goal>
				<goal>build</goal>
				<goal>push</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<ignoreServices>false</ignoreServices>
		<generateRoute>false</generateRoute>
		<mode>kubernetes</mode>
		<namespace>${deploy.namespace}</namespace>
		<verbose>true</verbose>
		<registry>${docker.registry}</registry>
		<skip>${skipDocker}</skip>
		<switchToDeployment>true</switchToDeployment>
		<skipResourceValidation>true</skipResourceValidation>
		<images>
			<image>
				<name>${docker.namespace}/${project.artifactId}:${project.version}</name>
				<alias>${project.artifactId}</alias>
				<build>
					<dockerFileDir>${project.basedir}/src/main/docker</dockerFileDir>
					<assembly>
						<descriptorRef>artifact</descriptorRef>
						<basedir>/deployments</basedir>
					</assembly>
					<from>fabric8/java-jboss-openjdk8-jdk</from>
				</build>
			</image>
		</images>
		<enricher>
			<excludes>
				<exclude>f8-expose</exclude>
			</excludes>
			<config>
				<fmp-service>
					<type>NodePort</type>
				</fmp-service>
			</config>
		</enricher>
		<generator>
			<includes>
				<include>spring-boot</include>
			</includes>
			<config>
				<spring-boot>
					<color>always</color>
					<from>fabric8/java-jboss-openjdk8-jdk</from>
				</spring-boot>
			</config>
		</generator>
	</configuration>
</plugin>

**Comment by wuyongCloud** [comment]
@rohanKanojia 
[pom.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/3375342/pom.txt)

**Comment by wuyongCloud** [comment]
mode is kubernetes but target/classes/META-INF/fabric8/openshift.yml  contain imagestream triggers.

it does not work.

<switchToDeployment>true</switchToDeployment>
<skipResourceValidation>true</skipResourceValidation>
<enableImageChangeTrigger>false</enableImageChangeTrigger>
<enableAutomaticTrigger>false</enableAutomaticTrigger>
<ignoreServices>false</ignoreServices>
<generateRoute>false</generateRoute>
<mode>kubernetes</mode>
<verbose>true</verbose>

**Comment by rohanKanojia** [comment]
hmm, okay. let's re-add it then

**Comment by dev-gaur** [comment]
@wuyongCloud fixed your issue in this PR. Setting the property fabric8.build.switchToDeployment to true in your project pom should get your job done.
