### ISSUE TITLE
migrating some projects in fabric8-devops to the new plugin breaks 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#167]
as there's no longer a JSON OpenShift Template available

so for now lets by default generate yml and json files as a workaround

**Comment by jstrachan** [comment]
FWIW an empty fabric8-devops repo build fails right now:
```
[ERROR] Failed to execute goal on project management: Could not resolve dependencies for project io.fabric8.devops.packages:management:pom:2.3-SNAPSHOT: Could not find artifact io.fabric8.devops.packages:metrics:json:kubernetes:2.3-SNAPSHOT in oss-sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```
so the PR coming soon should fix this

**Comment by jimmidyson** [comment]
How did this pass ci when I updated to use the new plugin? It's pretty simpler to migrate to the new plugin so when I get a chance I'll do so.

**Comment by jstrachan** [comment]
it got through CI because the old json file was still in the '~/.m2/repository` from the previous CI build.

**Comment by jimmidyson** [comment]
Oh damn!
