### ISSUE TITLE
TLS deployment project error

### ISSUE THREAD

**Issue by fuuqiu** [fabric8io/fabric8-maven-plugin#1670]
#MacOS Docker Client 

Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

#The above information indicates that the server is configured correctly. 

#----------------------Maven Config------------------------------
<plugin>
    <groupId>io.fabric8</groupId>
    <artifactId>docker-maven-plugin</artifactId>
    <version>0.30.0</version> 
    <configuration> 
        <dockerHost>tcp://xxxxx.com:2375</dockerHost> 
        <certPath>~/use/ssl</certPath> 
        <images>

#-----------------------Maven Build -------------------------------------
[INFO] --- docker-maven-plugin:0.30.0:build (default-cli) @ MetisAccount ---
[ERROR] DOCKER> Cannot create docker access object  [null]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.457 s
[INFO] Finished at: 2019-07-16T14:26:36+08:00
[INFO] Final Memory: 18M/794M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.30.0:build (default-cli) on project MetisAccount: Cannot create docker access object: ClientProtocolException: The server failed to respond with a valid HTTP response -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

I hope to hear from you, thank you very much.

**Comment by rohanKanojia** [comment]
I think you filed it at wrong project. You need to create issue here: https://github.com/fabric8io/docker-maven-plugin

**Comment by fuuqiu** [comment]
Yes, the similarity between the two projects is relatively high and has not been seen to distinguish.

**Comment by rohanKanojia** [comment]
This project is kubernetes equivalent of docker-maven-plugin. I understand that name is a bit confusing. It uses docker maven plugin as a dependency to build images ;-)
