### ISSUE TITLE
Support for lattest kubernetes-client 

### ISSUE THREAD

**Issue by Beennnn** [fabric8io/fabric8-maven-plugin#1676]
Hi,

Kubernetes client 4.3 is out.
https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md

Is there a plan to migrate to this new version ?
Thanks,

Ben.

**Comment by rohanKanojia** [comment]
Hm, Yeah would be nice. Would you like to send a quick PR?

**Comment by rohanKanojia** [comment]
@theexplorist : Could you please raise a PR to upgrade kubernetes client to 4.3.1 if you have time?

**Comment by Beennnn** [comment]
Time is hard to find these days... I'll try maybe next month.

**Comment by rohanKanojia** [comment]
@theexplorist : Can you do it if you have time?

**Comment by theexplorist** [comment]
@rohanKanojia okay
