### ISSUE TITLE
fabric8:build crashes on xml-config sample

### ISSUE THREAD

**Issue by dev-gaur** [fabric8io/fabric8-maven-plugin#1678]
* f-m-p version : 4.2-SNAPSHOT
* Sample project : https://github.com/fabric8io/fabric8-maven-plugin/tree/master/samples/xml-config

**Comment by rohanKanojia** [comment]
what error are you getting?

**Comment by theexplorist** [comment]
There was error in <labels> for Pnew, now for Pexternal why we are using digest in from image, it throws image not found and it fails. So if you say I will correct that as well
 @dev-gaur @rohanKanojia

**Comment by rohanKanojia** [comment]
@theexplorist : Is this issue fixed now? Or is there still something left to fix?

**Comment by theexplorist** [comment]
It's fixed
