### ISSUE TITLE
figure out a packaging approach for kubernetes + openshift that can work with gofabric8

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#168]
Right now we're using 2.x of fabric8-maven-plugin to combine json files together into distribution tarballs that gofabric8 uses to install the OpenShift Templates (either as Templates or as ConfigMaps).

The new 3.x of fabric8-maven-plugin generates an openshift.yml and a kubernetes.yml file which are quite different; as right now OpenShift doesn't support Ingress, Deployment or ReplicaSet; so we have to use DeploymentConfig + ReplicationController on OpenShift.

So we could do either of these:

* generate a kubernetes tarball and openshift tarball for each package
* generate a single tarball with a folder for openshift and a folder for kubernetes resources; then update gofabric8 to work with these new tarballs

The dependency mechanism used to make uber packages (like cd-pipeline, management etc) use a dependency on the kubernetes json file. Now we've 2 dependencies (kubernetes.yml + openshift.yml). We could make fabric8-maven-plugin generate a tarball/zip for each build containing both the openshift.yml and kubernetes.yml inside; so we can switch the packaging projects from 'json' to tarball dependency then combine the openshift yml files and kubernetes yml files together. Or we could just depend on the openshift.yml and the kubernetes.yml and try figure out which is which so we know where to put it?

**Comment by jstrachan** [comment]
BTW the distros we create, e.g. here: https://github.com/fabric8io/fabric8-devops/tree/master/packages/distro - contain both the packages (management, metrics, cd-pipeline et al) plus the individual microservices in case folks want to run things piece by piece (e.g. jenkins, grafana etc). So its not just about combining multiple dependencies into uber-yaml files; we also need to keep around the individual parts too

**Comment by rhuss** [comment]
Last week @jimmidyson introduced a [DependencyEnricher](https://github.com/rhuss/fabric8-maven-plugin/blob/2bb923608a316f49297506872f0f50424694c40e/enricher/dependency/src/main/java/io/fabric8/maven/enricher/dependency/DependencyEnricher.java#L42-L42) which can be used to combine the descriptors files contained in compile time dependencies below `META-INF/fabric8/`. This makes the plain dependency on the yaml / json files and the former `combineDependency` mechanism obsolete, reducing the number of different images, too. So instead of putting stuff into plain tars, what's about reusing jars which have the descriptors already included below `META-INF/` ?

**Comment by rhuss** [comment]
For the distro we could add a goal to f-m-p which extracts the yamls from the dependen jars and put them all into a tar (replacing the assembly on the `kubernetes`-classified artefacts).

**Comment by jstrachan** [comment]
using the jars sounds a great idea to simplify the dependency stuff!

We just need to decide what the distros look like (both the uber yaml files and the individual microservices) and whether we go with different distros for kubernetes + openshift or whether we combine them - then making gofabric8 work with whatever we do

**Comment by jstrachan** [comment]
@rhuss BTW we used group ids to decide the difference between apps (microservices like grafana, jenkins) or packages (combinations of apps together like management, metrics, cd-pipeline). So we could do the same in the new f-m-p goal maybe?

**Comment by jstrachan** [comment]
here's the mvn assembly stuff we're currently using to put packages and apps into different folders: https://github.com/fabric8io/fabric8-devops/blob/master/packages/distro/src/main/assembly/templates.xml#L12-L27

**Comment by rhuss** [comment]
What about to use two different Maven modules (one for each group) with different dependencies to create two different dist tars ?

**Comment by jstrachan** [comment]
we could - though I can imagine we end up with inconsistencies copy/pasting the same sets of dependencies twice to 2 different pom.xml files just so we could generate both OpenShift + Kubernetes distros. I'd rather an approach that makes it harder to break things ;). e.g. someone adds a dependency for kubernetes but forgets to do the same for openshift.

Another approach is to generate the OpenShift distro from the Kubernetes one automatically (its mostly just a s/Deployment/DeploymentConfig kinda thing)

**Comment by jstrachan** [comment]
Maybe we just need to be able to specify maven coordinate filters (like the assembly plugin uses) https://github.com/fabric8io/fabric8-devops/blob/master/packages/distro/src/main/assembly/templates.xml#L12-L27 to figure out which folder to use when making the distro? So we generate a tarball like:
```
/kubernetes
  /main
    cd-pipeline.yml
    management.yml
    ...
  /microservices
    grafana.yml
    ...
/openshift
  /main
    ...
  /microservices
    ...
```

Making that tarball is probably the simplest change in gofabric8 too; we just need to look for kubernetes/openshift folders first in the tarballs and use the right one if present etc

**Comment by rhuss** [comment]
> e.g. someone adds a dependency for kubernetes but forgets to do the same for openshift.

As we always put Kubernetes and OpenShift YAMLs in each jar, that shouldn't be possible. When you ad d a dependency you add automatically both files. Its then a matter of the 'fabric8:dist' task to rearrange those files into different hierarchy. 

The `fabric8:dist` task could take a configuration to enable the grouping you envisage.

**Comment by jstrachan** [comment]
think we can close this now - we reuse the jars with the kubernetes and openshift manifests inside
