### ISSUE TITLE
fabric8-maven-enricher-api is not available for the latest release 4.2

### ISSUE THREAD

**Issue by Beennnn** [fabric8io/fabric8-maven-plugin#1684]
Hi,

Is 4.1 version supposed to match with f-m-p version 4.2 ?
Is there a plan to migrate fabric8-maven-enricher-api to version 4.2.

Thanks,

Ben.

**Comment by rohanKanojia** [comment]
It has been renamed, it's here: https://search.maven.org/artifact/io.fabric8/fabric8-maven-plugin-enricher-api/4.2.0/jar

**Comment by Beennnn** [comment]
ok, thanks !
