### ISSUE TITLE
fabric8 installation issue

### ISSUE THREAD

**Issue by siddharthkaushal90** [fabric8io/fabric8-maven-plugin#1686]
While installing fabric8 I am facing some issues, details are below:

1. After installation everything runs fine, but the services in console doesn't come up like jenkins, gogs and nexus. Also all these are working fine when I am opening them separately.

2. It also says no teams found. And there is no option to create any team. 

3. I am using GCP for this installation. But when I am restarting the VM, everything comes up except for gogs, it is throwing blow error:

```
mkdir: cannot create directory '/app/gogs/data/ssh/': Permission denied
/opt/gogs/start.sh: line 24: cd: /app/gogs/data/ssh/: No such file or directory
panic: open gogs.rsa: permission denied

goroutine 1 [running]:
panic(0x519120, 0xc420113c50)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
        /home/jdyson/go/src/github.com/fabric8io/docker-gogs/cmds/ssh-hostkeygen/ssh-hostkeygen.go:41 +0x2c1
2019/08/02 09:21:25 Creating admin user:  true
2019/08/02 09:21:25 [T] Custom path: /opt/gogs/custom
2019/08/02 09:21:25 [T] Log path: /app/gogs/data/logs
2019/08/02 09:21:25 [I] Gogs: Go Git Service 
2019/08/02 09:21:25 [.../gogs/models/repo.go:121 NewRepoContext()] [E] Fail to set git user.email(exit status 255): error: could not lock config file /app/gogs/data/.gitconfig: Permission denied.
```
```

minikube version: v1.2.0
gofabric8 version: '1.8.1'
```

Posting the question here because there are no active issues repo for the installation.

Thanks

**Comment by rohanKanojia** [comment]
@siddharthkaushal90 : Apologies for the late reply, gofabric8 is not supported anymore so I would discourage you to use it.

**Comment by siddharthkaushal90** [comment]
@rohanKanojia : thanks for the update!!
