### ISSUE TITLE
Origin of <dockerHost>${docker.host}</dockerHost>

### ISSUE THREAD

**Issue by neilchaudhuri** [fabric8io/fabric8-maven-plugin#1700]
Quick question: When I run the plugin in debug mode, I see this:

`<dockerHost>${docker.host}</dockerHost>`

I have not configured anything for `{docker.host}`, so can you tell me what the value is that gets passed in here by default? It wasn't clear to me from the documentation or the source. This is running on a Windows 10 machine.

Thanks.

**Comment by rohanKanojia** [comment]
@neilchaudhuri : Plugin tries to detect unit socket or windows pipe as you can see here: https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/access/DockerConnectionDetector.java#L123

Bdw, you're on wrong repository. Maybe you were looking for https://github.com/fabric8io/docker-maven-plugin . This is Kubernetes Maven Plugin(it includes docker maven plugin though).

**Comment by neilchaudhuri** [comment]
Thanks so much for pointing me to the code, and apologies for posting to the incorrect repo.
