### ISSUE TITLE
Migrate all the pending PRs to Jkube

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1701]
We need to port all these PRs to jkube

**Comment by dev-gaur** [comment]
We should label the PRs.

**Comment by rohanKanojia** [comment]
right  now these are the PRs which needs to be ported: https://github.com/fabric8io/fabric8-maven-plugin/pulls?q=is%3Apr+is%3Aclosed+label%3Ajshift%2Fpending

**Comment by dev-gaur** [comment]
I actually removed the jshift/pending label from some PRs which I had migrated successfully. So we'll need to identify those

**Comment by rohanKanojia** [comment]
Not sure what you mean, why do we need to identify if we've already migrated?
