### ISSUE TITLE
Support for binary files in fmp-configmap-file

### ISSUE THREAD

**Issue by erikgb** [fabric8io/fabric8-maven-plugin#1718]
ConfigMapEnricher (fmp-configmap-file) was a very nice addition to f-m-p, and we are using it already.

But when I try to use it for files with binary content, i.e. a Java truststore or a (binary) license file, this does not work.

In order to make ConfigMapEnricher work for binary data, the ConfigMapEnricher has to store the file contents in the binaryData field - instead of the standard data field. And this should ideally be done transparently - with the same logic as oc/kubectl uses when creating ConfigMaps with the '--from-file' option: non-UTF8 data should use the binaryData field, otherwise use the data field (as now).

I had a look at the source code, and I think this can be fixed without too much effort. I could prepare a PR?

**Comment by rohanKanojia** [comment]
@erikgb : Yeah, would really appreciate if you could create a PR. We're going to cut a release soon

**Comment by erikgb** [comment]
@rohanKanojia : Good, I will prepare a PR over the weekend.

Personally I am more keen on having the new release, that will fix some of my blocking issues, as soon as possible. So please do not postpone the release waiting for this new feature....

**Comment by rohanKanojia** [comment]
We are planning to release tomorrow if tests are green :smile:

**Comment by rohanKanojia** [comment]
No worries, Users are our topmost priority we can release early if it's super urgent for you.

**Comment by rohanKanojia** [comment]
@erikgb : I've release [4.3.0,](http://repo2.maven.org/maven2/io/fabric8/fabric8-maven-plugin/4.3.0/) You can try it out and provide feedback.

**Comment by erikgb** [comment]
Cool! Thanks! Looking forward to it. Will test it with my blocking issues first.....

**Comment by rohanKanojia** [comment]
Np, Thanks for your quick fix!
