### ISSUE TITLE
Should be able to add custom route, even if fabric8.openshift.generateRoute=false

### ISSUE THREAD

**Issue by erikgb** [fabric8io/fabric8-maven-plugin#1720]
### Description

We have decided to take more control over the Openshift routes for applications deployed with f-m-p. The route name is included in the URL to access the application from outside Openshift, and we need more control over the URLs for external access.

But when I set the fabric8.openshift.generateRoute to false (a sensible default in our case), to not generate the default route, no routes are added at all!!! This must be a bug.

To reproduce:

- Disable route generation (fabric8.openshift.generateRoute=false)
- Add a custom Route fragment
- Run ``mvn fabric8:resource``

Actual behavior: Your custom route is missing from ./target/classes/META-INF/fabric8
Expected behavior: An enriched version of your custom route in ./target/classes/META-INF/fabric8

I am pretty sure the cause of the this bug is the "catch all" solution implemented here:
https://github.com/fabric8io/fabric8-maven-plugin/blob/7e0bd4d81cea9eb51ae7d876d226691292eb7604/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/ResourceMojo.java#L317

### Info

* f-m-p version : 4.2.0

**Comment by erikgb** [comment]
@rohanKanojia : I think this is a quite embarrassing bug that should be prioritized for the upcoming release. What do you think? At least I do not expect all my routes to be filtered out even if I set the property fabric8.openshift.generateRoute to false....

**Comment by rohanKanojia** [comment]
Yeah, right. I think we should fix it. Let me fix it.
