### ISSUE TITLE
Allow redeploy without changes and RollingParams for Openshift

### ISSUE THREAD

**Issue by bernaxa** [fabric8io/fabric8-maven-plugin#1722]
### Description

Hello,

I've started to use f-m-p but I don't know how to force a redeploy even if there is no change in the templates.

Doing a resource-apply it doesn't deploy and in the logs you can see something like

[INFO] OpenShift platform detected
[INFO] F8: Using project: ****
[INFO] F8: Service has not changed so not doing anything
[INFO] F8: DeploymentConfig has not changed so not doing anything
[INFO] F8: HINT: Use the command `oc get pods -w` to watch your pods start up

If I do a small change in the deployment.yml located in the src/main/fabric8 then the deploy works as expected and in the logs you can see:

[INFO] OpenShift platform detected
[INFO] F8: Using project: ***
[INFO] F8: Updating a Service from openshift.yml
[INFO] F8: Updated Service: **/target/fabric8/applyJson/**/**.json
[INFO] F8: Updating DeploymentConfig from openshift.yml
[INFO] F8: Updated DeploymentConfig: **/target/fabric8/applyJson/**/deploymentconfig-**.json
[INFO] F8: HINT: Use the command `oc get pods -w` to watch your pods start up

Also, If I specify RollingParams like this

  strategy:
    rollingParams:
      maxSurge: 0
      maxUnavailable: 1
    type: Rolling

In the Openshift deploymentconfig I get default values like this

  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling

What can I check?

Thanks

### Info

* f-m-p version : 4.2.0
* Maven version (`mvn -v`) : 3.5.4
```

```
* Kubernetes / OpenShift setup and version : Openshift 3.9

**Comment by rohanKanojia** [comment]
@bernaxa : I'm not sure whether this exactly solves your issue but there is a `fabric8.recreate` flag which updates resources by deleting them first and then creating them again

**Comment by bernaxa** [comment]
No, it doesn't work, I added -Dfabric8.recreate=true to the mvn command and I still get the 

[INFO] F8: DeploymentConfig has not changed so not doing anything

and there is no deployment in OpenShift

**Comment by bernaxa** [comment]
And what about the other topic, how I can configure the deployment.yml so those parameters 

strategy:
rollingParams:
maxSurge: 0
maxUnavailable: 1
type: Rolling

can be applied in the final openshift deploymentconfig?
