### ISSUE TITLE
Helm Mojo not replacing template placeholders with corresponding `.Values.xxx` placeholders

### ISSUE THREAD

**Issue by djotanov** [fabric8io/fabric8-maven-plugin#1732]
# Description
Helm Mojo not replacing template placeholders with corresponding `.Values.xxx` placeholders.
Instead deployment.yml contains resolved strings from template.yaml.

* f-m-p version : 4.3.0

**Comment by rohanKanojia** [comment]
@dantalian-pv : Could you please give a reproducible sample?

**Comment by djotanov** [comment]
I will submit a PR with fix and a new sample

**Comment by rohanKanojia** [comment]
@djotanov : awesome, Thanks :+1:
