### ISSUE TITLE
Missing compatibility of OCP 4

### ISSUE THREAD

**Issue by yanivpaz1973** [fabric8io/fabric8-maven-plugin#1754]
### Description
In https://github.com/fabric8io/fabric8-maven-plugin
"OpenShift and Kubernetes Compatibility" does not include ocp 4.X

**Comment by rohanKanojia** [comment]
@yanivpaz1973 : Nice catch, I think we should update these compatibility matrices with respect to Openshift 4.1 and Openshift 4.2

**Comment by rohanKanojia** [comment]
@yanivpaz1973 : Have you tried our projects on Openshift 4? if yes, you can also submit a patch to update these :smile:
