### ISSUE TITLE
Add QuarkusEnricher for adding Readiness/Liveness health checks

### ISSUE THREAD

**Issue by rohanKanojia** [fabric8io/fabric8-maven-plugin#1760]
We had a discussion with @rhuss  in which he suggested to add Readiness/Liveness probes via extracting ports/URLs from properties. Just like we have in SpringBoot and Vertx

**Comment by rhuss** [comment]
Sorry, missed that. We already have that, a `f8-healthcheck-quarkus` ;)

**Comment by rohanKanojia** [comment]
@rhuss @manusa : ah, Sorry. I didn't remember that it was added already. I should have checked before filing issue.

**Comment by rohanKanojia** [comment]
Right now QuarkusEnricher seems to be adding probes based on Enricher configuration. But it's still missing automatic port detection from quarkus properties like in case of spring boot. I wonder whether Quarkus has a rich set of properties like SpringBoot :thinking:
