### ISSUE TITLE
JIB: Unauthorized registry exception for "from" registry

### ISSUE THREAD

**Issue by yadavnikhil** [fabric8io/fabric8-maven-plugin#1763]
### Description
I'm getting registry unauthorized exception when using Jib when "from" image registry is from a authenticated registry.

Failed to execute the build: java.lang.UnsupportedOperationException: java.lang.IllegalStateException: com.google.cloud.tools.jib.api.RegistryUnauthorizedException

The relevant credentials are set in maven settings.xml. On debugging it looks like for baseImageConfiguration object, no credentials are getting set for CredentialsRetreiver. 

### Info

* Maven version (`mvn -v`) :
```
maven 3.5.0
```

**Comment by rohanKanojia** [comment]
@yadavnikhil : I haven't tested it with credentials in setings.xml. Does it work for you when credentials are in docker config?

**Comment by rohanKanojia** [comment]
> ### Description
> I'm getting registry unauthorized exception when using Jib when "from" image registry is from a authenticated registry.
> 
> Failed to execute the build: java.lang.UnsupportedOperationException: java.lang.IllegalStateException: com.google.cloud.tools.jib.api.RegistryUnauthorizedException
> 
> The relevant credentials are set in maven settings.xml. On debugging it looks like for baseImageConfiguration object, no credentials are getting set for CredentialsRetreiver.
> 
Could you please elaborate which CredentialsRetreiver you're referring to? I couldn't find any object like this in Docker maven plugin source code.

> ### Info
> * Maven version (`mvn -v`) :
> 
> ```
> maven 3.5.0
> ```

**Comment by rohanKanojia** [comment]
Hmm, I think you're right. It's not that registry authentication is not working. I just tried and push seemed to be working when credentials are in settings.xml. But It couldn't work when `from` image was from some private registry. It seems to be always pulling from dockerhub and does not consider credentials while pulling images.

@erikgb : Were you able to find some solution for authentication for pulling images in jib? I remember you filed an issue on Jib repo querying this issue.

**Comment by rohanKanojia** [comment]
Shall we try to upgrade `jib-core` and see if it resolves this issue. I think we're using 5 months old version

**Comment by erikgb** [comment]
@rohanKanojia : JIB API (java) supports it: https://www.javadoc.io/static/com.google.cloud.tools/jib-core/0.12.0/com/google/cloud/tools/jib/api/RegistryImage.html

**Comment by erikgb** [comment]
Relates to https://github.com/fabric8io/fabric8-maven-plugin/issues/1738

**Comment by rohanKanojia** [comment]
@erikgb You're right. We don't seem to be adding `RegistryImage`  object for `from` image. we're only doing it for final image; that's why it works in case of push: https://github.com/fabric8io/fabric8-maven-plugin/blob/49b0f19439fa54d3abf263544b7cae308d0e69b2/core/src/main/java/io/fabric8/maven/core/util/JibBuildServiceUtil.java#L281-L314

**Comment by yadavnikhil** [comment]
@rohanKanojia Thanks a lot for commenting, yes push works fine with authentication, its the issue with ‘from’ image authentication.

I tried just using jib to test and the standalone use worked fine for me. So, fix needed to authenticate base image registry whenever needed in fabric8 maven.

**Comment by rohanKanojia** [comment]
@yadavnikhil : No problem. I'm preparing a PR to fix this issue.

**Comment by dev-gaur** [comment]
Closing since #1766 has been merged.
