### ISSUE TITLE
Invalid classes/META-INF/fabric8/kubernetes yml files generated.

### ISSUE THREAD

**Issue by fforloff** [fabric8io/fabric8-maven-plugin#1773]
### Description
We use both fabric8:helm for the charts generation with the parameters, defined in the template.yml, as well as the plain old fabric8:resource for non-helmcharts kubernetes yml 
I.e. 
template.yml:
`kind: Template
parameters:
- name: limits.memory
  value: "1000Mi"
- name: requests.memory
  value: "1000Mi"
- name: requests.cpu
  value: "200m"`
deployment.yml:
`        resources:
          limits:
            memory: ${limits.memory}
          requests:
            cpu: ${requests.cpu}
            memory: ${requests.memory}`
This would become a helm template:
`        resources:
          limits:
            memory: {{ .Values.limits.memory | default "1000Mi" }}
          requests:
            cpu: {{ .Values.requests.cpu | default "200m" }}
            memory: {{ .Values.requests.memory | default "1000Mi" }}`
This functionality was broken in the FMP version 4.3.0, so recently we updated the plugin version to the latest 4.3.1. However this introduced a new problem.
Previously target/classes/META-INF/fabric8/kubernetes/*-deployment.yml would be generated as just normal kubernetes yml files with ${limits.memory} expanded as "1000Mi" in the example above. 

Now, with 4.3.1 these yml's are generated with  ${limits.memory} still in place - making them invalid.

### Info

* f-m-p version : 4.3.1
* Maven version (`mvn -v`) : 3.6.3
```

```
* Kubernetes / OpenShift setup and version : Kubernetes 1.14.0
* If it's a bug, how to reproduce : Per the above code snippets

**Comment by rohanKanojia** [comment]
Hmm, Thanks for you bug report. @djotanov , Have you faced this issue when generating helm charts?

**Comment by djotanov** [comment]
I just checked with 4.3.1, those placeholders are replaced for me in classes/META-INF/fabric8/kubernetes.yml (and thats the file used in fabric8:deploy for example).
@fforloff what is your use case exactly?

**Comment by manusa** [comment]
Hi
Helm chart generation has been refactored and hopefully fixed in [Eclipse JKube](https://github.com/eclipse/jkube).
It would be really nice if you could check your specific use cases with our current latest release:
https://search.maven.org/search?q=g:%22org.eclipse.jkube%22%20AND%20a:%22kubernetes-maven-plugin%22

**Comment by rohanKanojia** [comment]
@fforloff: poilte ping, were you able to find time to try your bug out on Eclipse JKube?

**Comment by manusa** [comment]
This should be working fine on Eclipse JKube 1.0.1 after several helm chart refactors
- https://github.com/eclipse/jkube/issues/327
- https://github.com/eclipse/jkube/pull/410
