### ISSUE TITLE
Add a generator for Karaf based projects

### ISSUE THREAD

**Issue by dhirajsb** [fabric8io/fabric8-maven-plugin#178]
Created from discussion about https://github.com/fabric8io/docker-maven-plugin/issues/519
Basically, simplify f-m-p config for Karaf projects to remove pom boilerplate cruft.

**Comment by dhirajsb** [comment]
@rhuss can you assign the issue to @lburgazzoli? I don't have the rights to do so.

**Comment by rhuss** [comment]
I invited @lburgazzoli to @fabric8io/contributors , as soon a its accepted I can assign the ticket tho you.

**Comment by lburgazzoli** [comment]
invitation accepted

**Comment by rhuss** [comment]
Thanks ;-)

**Comment by lburgazzoli** [comment]
@dhirajsb @ro14nd I can't close the issue, can you ?

**Comment by rhuss** [comment]
Yeah, will do. Release is underway (just waiting for the d-m-p release to finish)
