### ISSUE TITLE
Executing fabric8:push over a project that previously run fabric8:build and whose image tag contains %t

### ISSUE THREAD

**Issue by nightswimmings** [fabric8io/fabric8-maven-plugin#1786]
### Description

When using 

   ```
                 <configuration>
                        <images>
                           <image>
                             <name>%g/%a:%t</name>
```

on both build execution config and global plugin config, looks like the plugin resolves/reevaluates %t on second call (fabric8:push), so the image cannot be found, because it was generated previously with another timestamp

### Info

* f-m-p version : 4.3.1
* Maven version (`mvn -v`) :3.6.2

**Comment by rohanKanojia** [comment]
I think this was related to https://github.com/fabric8io/fabric8-maven-plugin/issues/1093 . I won't advise using timestamps as tags

**Comment by nightswimmings** [comment]
My problem seemed to be a Maven one, if you have a <configuration> associated to an execution binded to resources/build goals but not push, the %t is reevaluated

**Comment by rohanKanojia** [comment]
@nightswimmings : Hi, we have migrated the project to https://github.com/eclipse/jkube. Would it be possible for you to migate[0] to JKube and provide feedback. Migration is as easy as running these goals:

```
mvn org.eclipse.jkube:kubernetes-maven-plugin:migrate
```

[0] https://www.eclipse.org/jkube/docs/migration-guide/

**Comment by rohanKanojia** [comment]
I would suggest creating a new issue on the Eclipse JKube repository

**Comment by nightswimmings** [comment]
It is not possible for me now though I'm eager to do it soon! But anyway, it has nothing to do with fabric8. Well, perhaps it could handle it by making the push fail by default if the image has not been generated with expected name or considering the artifact from previous goals regardless actual config.  I might be wrong on the analysis though

**Comment by rohanKanojia** [comment]
ohk, I see. In case you face any issues feel free to reach out to us via these channels:

Github: https://github.com/eclipse/jkube/issues
Gitter: https://gitter.im/eclipse/jkube 
Mailing List: https://accounts.eclipse.org/mailing-list/jkube-dev
