### ISSUE TITLE
Labels missing for some objects

### ISSUE THREAD

**Issue by rdruss** [fabric8io/fabric8-maven-plugin#1793]
### Description
In looking at the documentation, you can add labels using maven configuration as outlined [here](https://maven.fabric8.io/#resource-labels-annotations).  It looks like the labels in the "all" section should be applied to all objects, but the labels were not applied to the Build, BuildConfig, or ImageStream objects.  There was a previous GitHub issue that seems to be related to this, #1425.  

### Info

* f-m-p version : 4.4.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T09:06:16-06:00)
Maven home: /usr/local/Cellar/maven/3.6.2/libexec
Java version: 11.0.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.1+13/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
```
* Kubernetes / OpenShift setup and version : minishift with 3.11.0
* If it's a bug, how to reproduce : First login to a usable cluster, then run `mvn clean fabric8:deploy -Popenshift` with the repository below.  Afterwards, run `oc get all --show-labels` and you can see which objects do **not** have any app.kubernetes.io/* labels
* If it's a feature request, what is your use case :
* Sample project : https://github.com/rdruss/vertx-http-example/tree/labels

**Comment by rohanKanojia** [comment]
Actually `BuildConfig`,`ImageStream` objects are not part of the enrichment phase. They are generated during build phase in `OpenshiftBuildService`. I think we should fix this in order to align with other manifests generated by plugin during enrichment phase.

**Comment by rdruss** [comment]
I thought that might be the case, but was confused by the previous issue (#1425) as the associated pull request (#1449) indicated that it had "Added metadata visitors for imagestreams, build and buildconfig".
