### ISSUE TITLE
Spring Boot management server port property has no effect on generated probes

### ISSUE THREAD

**Issue by mab** [fabric8io/fabric8-maven-plugin#1807]
### Description

Setting the property `management.server.port` of a Spring Boot application has no effect on the generated probes in the `kubernetes.yml`. I set `management.server.port=8081` and would expect the generated ports for livenessProbe and readinessProbe to be 8081.

### Info

* f-m-p version : 4.4.1
* Maven version (`mvn -v`) : 
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.2\bin\..
Java version: 1.8.0_242, vendor: Eclipse OpenJ9
Java home: C:\Users\matthias.baumgart\.sdkman\candidates\java\current\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

* Kubernetes / OpenShift setup and version : Kubernetes 1.15.10
* Spring Boot: 2.2.6.RELEASE
* If it's a bug, how to reproduce:  
  * I created a minimal example https://github.com/mab/healthcheck
  * `mvn clean fabric8:resource`
  * generated `kubernetes.yml` contains propes using the default port

**Comment by mab** [comment]
[AbstractSpringBootHealthCheckEnricherTestSupport.java#testWithServerPortAndManagementPort](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/fabric8/src/test/java/io/fabric8/maven/enricher/fabric8/AbstractSpringBootHealthCheckEnricherTestSupport.java#L96) looks like my expectation is correct :confused:

**Comment by rohanKanojia** [comment]
@mab : have you tried out configuring health-check in your plugin configuration like this? If yes, Could you please share it so that we can try to reproduce this issue?
```

       ​<configuration>
         ​<enricher>
           ​<config>
             ​<f8-healthcheck-spring-boot>
               ​<timeoutSeconds>5</timeoutSeconds>
               ​<readinessProbeInitialDelaySeconds>30</readinessProbeInitialDelaySeconds>
               ​<failureThreshold>3</failureThreshold>
               ​<successThreshold>1</successThreshold>
             ​</f8-healthcheck-spring-boot>
           ​</config>
         ​</enricher>
       ​</configuration>
```

**Comment by cheinema** [comment]
I think the problem is you are using the Maven goal `fabric8:resource` right after `clean`. The FMP tries to read the resource `target/classes/application.properties` which doesn't exist yet due to `clean`. In such cases a fallback to the default values will happen (port 8080). If you use `mvn clean process-resources` instead, the resource is created first and then `fabric8:resource` is invoked due to the Maven goal binding in the POM. I was able to reproduce this with the project https://github.com/mab/healthcheck

**Comment by mab** [comment]
@cheinema thank you for the hint.
