### ISSUE TITLE
Update samples/quarkus

### ISSUE THREAD

**Issue by cricket007** [fabric8io/fabric8-maven-plugin#1808]
### Description

[Quarkus sample version is old](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/samples/quarkus/pom.xml#L35)

### Info

https://quarkus.io

* If it's a feature request, what is your use case :  Sampling latest version of Quarkus

**Comment by rohanKanojia** [comment]
@cricket007 : We're currently migrating project to [Eclipse JKube](https://github.com/eclipse/jkube). It's just the rebranded version of FMP. Could you please try out [Quarkus quickstart](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/quarkus) there ?

**Comment by cricket007** [comment]
Gotcha gotcha. Missed the note in the README

Can do
