### ISSUE TITLE
Simple Dockerfile mode: provided Dockerfile is always skipped

### ISSUE THREAD

**Issue by dev-gaur** [fabric8io/fabric8-maven-plugin#1814]
```
FROM fakebaseimage
ENV JAVA_APP_DIR /deployment123
COPY maven /deployment123/
EXPOSE 8080 8778 9779
CMD echo "Hello World"
```

I provided this Dockerfile on the project root directory.. It is always skipped be it  Zero Config mode.
or XML config mode.

This is where the SImpleDockerFIle mode is checked for. https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java#L346 .

FYI, it works fine in DMP, so the issue is on the FMP side.

Documentation : https://maven.fabric8.io/#simple-dockerfile-build

**Comment by manusa** [comment]
Will be fixed in eclipse/jkube#197
