### ISSUE TITLE
FMP OpenShift mode S2I Failed running assemble script - /bin/sh: 1: /usr/libexec/s2i/assemble: not found

### ISSUE THREAD

**Issue by cipley** [fabric8io/fabric8-maven-plugin#1818]
### Description
I am trying the FMP plugin in order to deploy Spring Boot application to an OpenShift platform. However, as the build process is in progress, it failed when running some kind of assemble script(?):
```
...omitted...
[INFO] F8: STEP 1: FROM openjdk:8
[INFO] F8: STEP 2: LABEL "io.openshift.build.source-location"="/tmp/build/inputs"       "io.openshift.build.image"="openjdk:8"
[INFO] F8: STEP 3: ENV OPENSHIFT_BUILD_NAME="springboot-s2i-demo-s2i-1"     OPENSHIFT_BUILD_NAMESPACE="cipley-project"
[INFO] F8: STEP 4: USER root
[INFO] F8: STEP 5: COPY upload/src /tmp/src
[INFO] F8: STEP 6: RUN chown -R 1001:0 /tmp/src
[INFO] F8: STEP 7: USER 1001
[INFO] F8: STEP 8: RUN /usr/libexec/s2i/assemble
[INFO] F8: /bin/sh: 1: /usr/libexec/s2i/assemble: not found
[INFO] F8: subprocess exited with status 127
[INFO] F8: subprocess exited with status 127
```
Which then proceeds with it throwing an error:
`[ERROR] F8: Failed to execute the build: org.apache.maven.plugin.MojoExecutionException: OpenShift Build springboot-s2i-demo-s2i-1 failed: Failed: GenericBuildFailed`

This _might_ be related to #1663 

The Build Config is generated on OpenShift, however the build itself is failed, and the pod is not running. 
#### Build Config
![image](https://user-images.githubusercontent.com/13663799/86720022-d1ea5980-c04e-11ea-8071-9bceb4fb50df.png)

#### Build
![image](https://user-images.githubusercontent.com/13663799/86720241-06f6ac00-c04f-11ea-9208-a1c8435ef4f5.png)

#### `mvn -X` output
[mvn_out.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/4882769/mvn_out.txt)

### Info

* f-m-p version : 4.4.1
* Maven version (`mvn -v`) : 
```
Apache Maven 3.6.3 (NON-CANONICAL_2019-11-27T20:26:29Z_root)
Maven home: /opt/maven
Java version: 11.0.7, vendor: GraalVM Community, runtime: /home/cipley/.sdkman/candidates/java/20.1.0.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.15-1-manjaro", arch: "amd64", family: "unix"
```
* Kubernetes / OpenShift setup and version : OpenShift Code Ready Container 1.12
There is a project already created named `cipley-project`.
* If it's a bug, how to reproduce : from sample project, execute `mvn clean initialize package`, with CRC running and logged in as developer. 
* If it's a feature request, what is your use case : N/A
* Sample project : https://github.com/cipley/springboot-s2i-demo.git

**Comment by manusa** [comment]
It probably is related to #1663 
It looks like the generated Assembly artifact is no longer compatible with the S2I build image.

We are currently shifting all our development efforts towards [Eclipse JKube](https://github.com/eclipse/jkube). I think our current [alpha-4](https://search.maven.org/artifact/org.eclipse.jkube/kubernetes-maven-plugin/1.0.0-alpha-4/maven-plugin) version should be stable enough for your use case (we'll be releasing an RC-1 very soon too). It would be very helpful :heart: for us if you tried JKube and shared your feedback for your current use cases.

**Comment by cipley** [comment]
Ah, I see. I checked out the JKube some time ago, upon discovering that it is the successor of FMP, however I shied away from it since it is still in alpha.
I guess I have to give it a try now that FMP is unsupported.

Since I want to try the S2I capability, is there any workaround for my current setup or should I just change to JKube altogether?

**Comment by manusa** [comment]
> Since I want to try the S2I capability, is there any workaround for my current setup or should I just change to JKube altogether?

It should work OOTB for you. Just be sure to use openshift-maven-plugin:
```xml
<plugin>
    <groupId>org.eclipse.jkube</groupId>
    <artifactId>openshift-maven-plugin</artifactId>
    <version>1.0.0-alpha-4</version>
</plugin>
```

**Comment by cipley** [comment]
HI @manusa , I have tried to use JKube with the version that you provided, however I still have the same error.
I'm not sure whether to continue the issue here or should I open another one in JKube page instead?

**Comment by manusa** [comment]
:( Please if you can open the issue on JKube and provide some way to reproduce.

**Comment by manusa** [comment]
OK, just saw your attached project
Image is not S2I compatible. Try to replace your base image with ours `quay.io/jkube/jkube-java-binary-s2i:0.0.7`. ([`${docker-from}`](https://github.com/cipley/springboot-s2i-demo/blob/1fa4ef8ac808e3a6d711d9f625fb44c2636d4a67/src/main/resources/docker.properties#L9))

**Comment by cipley** [comment]
> OK, just saw your attached project
> Image is not S2I compatible. Try to replace your base image with ours `quay.io/jkube/jkube-java-binary-s2i:0.0.7`. ([`${docker-from}`](https://github.com/cipley/springboot-s2i-demo/blob/1fa4ef8ac808e3a6d711d9f625fb44c2636d4a67/src/main/resources/docker.properties#L9))

Hi @manusa your suggestion worked!
Granted, I was not aware that the base image was not compatible, since I was just tried the DMP in order to deploy to OpenShift.
I retried my build using the FMP 4.4.1 just like my initial configuration.
The s2i build was succeeded for the first deployment. Alas, for the subsequent deployments, it still throws error while trying to build as attached:

![image](https://user-images.githubusercontent.com/13663799/86817920-df83fb80-c0af-11ea-8d66-e6b9b8ac1c5a.png)
 
Perhaps it was time to move on to JKube.....

**Comment by cipley** [comment]
@manusa I confirmed the above error does not show up with JKube.
So I guess I have to move on to JKube as you suggested. Still, many thanks for your inputs!

I'll close this issue.

**Comment by manusa** [comment]
> Perhaps it was time to move on to JKube.....

Time to move on ;)

I'm sorry, I was unclear, the base image I proposed is specifically designed for JKube and its provided generators.
