### ISSUE TITLE
ISTIO artifact Enrichment

### ISSUE THREAD

**Issue by pmbsa** [fabric8io/fabric8-maven-plugin#1820]
### Description
Support ISTIO fragment enrichment or just ISTIO raw resources
### Info
Hi, I realise fabric8 is now deprecated, we are planning a migration but that could take some time in the organisation I am working with. I wanted to know if there is a way for me to manage ISTIO resources within a fabric8 project. Even if I cant enrich them during the build I would like to at least be able to apply them so I can keep the delivery mechanisms the same for all projects. I have tried putting the .yml files into a raw folder but I still couldn't get the project to build. Any advice would be much appreciated.

thanks
Paul

* f-m-p version : 4.3.1

**Comment by rohanKanojia** [comment]
Could you please create an issue here: https://github.com/eclipse/jkube ?

I think migrating to JKube is as simple as running this maven command:
```
mvn org.eclipse.jkube:kubernetes-maven-plugin:migrate
```

**Comment by pmbsa** [comment]
Thanks, I will create it in JKUBE.. Just to clarify though, its not that the migration is difficult its that the organisation which I am contracting for requires change to be managed at a very fine grained level so we schedule things like the migration to Jkube according to what we are allowed to do. As of now Fabric8 4.3.1 is all I have to work with. 
Can you confirm that JKube would have a similar problem though please?

**Comment by rohanKanojia** [comment]
It's the same project(but with a different name) so I think it would be present there too
