### ISSUE TITLE
-D options don't work in IntelliJ Ultimate 2021.2.2 anymore

### ISSUE THREAD

**Issue by vafanasy** [fabric8io/fabric8-maven-plugin#1828]
### Description
In IntellliJ 2021.2.2 me and my colleagues cannot use -D options for the plugin anymore. First, I used -D options in IntelliJ Ultimate 2021.1.3 and it worked, then I updated IntelliJ to 2021.2.2 and -D options stoped working.

For example, `mvn docker:build -Ddocker.base-tag=local` will end up with this error: 

`Unknown lifecycle phase ".base-tag=local". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<p
lugin-version>]:<goal>.`

Only `mvn docker:build` works just fine.

### Info

* Plugin version: 0.34.1
* Maven version (`mvn -v`) : Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
* Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: AdoptOpenJDK\jdk-11.0.11+9
* IDE: IntelliJ Ultimate 2021.2.2

**Comment by vafanasy** [comment]
Any updates here?

**Comment by rohanKanojia** [comment]
@vafanasy : I think you've created issue on wrong repository. Maybe you should create an issue on https://github.com/fabric8io/docker-maven-plugin

From the issue description, it's not quite clear what issue you're facing (Could this be related to IntelliJ instead of the plugin?)

**Comment by rhuss** [comment]
@vafanasy AFAIR you have to specify the Maven options separately from the maven goals to call in IDEA, but I could be wrong.
