### ISSUE TITLE
Multi-Architecture Build query

### ISSUE THREAD

**Issue by mwinzie** [fabric8io/fabric8-maven-plugin#1838]
### I am trying to implement linux/s390x platform to my images as currently am getting images with linux/amd64 architecture. Tried using buildx and specify the platform no success.

* f-m-p version :
* Maven version (`mvn -v`) :
fabric8-maven-plugin 4.3.1

* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@mwinzie : Could you please try this https://github.com/fabric8io/docker-maven-plugin/tree/master/samples/multi-architecture

**Comment by rohanKanojia** [comment]
@mwinzie : Fabric8 Maven Plugin is no longer maintained. It's been refactored into [Eclipse JKube](https://github.com/eclipse/jkube). It's the same project but with different maven coordinates.

If you're coming to Kubernetes background, I suggest creating same issue on Eclipse JKube.

**Comment by mwinzie** [comment]
I will go through it, thanks. 
In the meantime from the pom file using fabric8 maven plugin is there a way you can specify the platform to some architecture and while executing the build goal the image to pick the architecture?
This is my profile from the pom

	<profile>
			<id>openshift-deployment</id>
			<activation>
				<activeByDefault>false</activeByDefault>
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>io.fabric8</groupId>
						<artifactId>fabric8-maven-plugin</artifactId>
						<version>4.3.1</version>
						<executions>
							<execution>
								<goals>
									<goal>resource</goal>
									<goal>build</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>

**Comment by mwinzie** [comment]
I am using fabric8 maven plugin not docker maven plugin

**Comment by rohanKanojia** [comment]
I don't think this feature is present in Fabric8 Maven Plugin. I think you'd need to migrate to Kubernetes Maven Plugin (`mvn org.eclipse.jkube:kubernetes-maven-plugin:migrate`) and provide `<platform>` argument in `<image>` > `<build>` > `<createImageOptions>`

**Comment by mwinzie** [comment]
Thanks, it worked. It was able to pick the platform.
But would like for it to pick a specific base image and platform like  openjdk/openjdk-11-rhel7 with linuxs390x platform

**Comment by rohanKanojia** [comment]
@mwinzie : Sorry, I'm not sure I understand correctly. Could you please create an equivalent issue on https://github.com/eclipse/jkube repository?
