### ISSUE TITLE
Use DeploymentConfigs

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#2]
In the old code there is a section dealing with `DeploymentConfigs`
however, this was never active. When using openshift mode, it should
be able to use DCs

**Comment by jstrachan** [comment]
FWIW we can now create Deployments via renaming a file foo-rc.yml to foo-deployment.yml such as this example https://github.com/jstrachan/springboot-config-demo/blob/master/src/main/fabric8/deployment.yml

I think we should be able to switch to generating DeploymentConfigs too in a similar way.

Though I guess a Microservice developer may want to generate a `kubernetes.yml` using a Deployment and then generate an `openshift.yml` (maybe using a DeploymentConfig?)

**Comment by jstrachan** [comment]
we now create DeploymentConfigs for openshift and Deployments for kubernetes
