### ISSUE TITLE
improve the output artifacts / formats

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#20]
right now we create a single json / yaml file which typically is an OpenShift Template or a kubernetes List.

To make things easier to consume we should probably always have a vanilla k8s yaml folks can run.

There are a few options though:

* deliver a few yaml files for each resource (RC / service / SA etc)
* create a zip of the yaml files (easier for integration into things like helm or putting into git repos - uber yaml files are harder to reason about)
* a single k8s yaml file thats easier to install (with things sorted nicely so services are first etc) - using ConfigMaps if we are using parameterisation
* a single OpenShift template yaml file for folks who wanna parameterise things on install time
* a 'Catalog yaml file' when folks want to install the app into a Catalog (think like an App store - like installing an OpenShift Template but so it works on any k8s environmment  - we could encode the app inside a Config Map).

I wonder if we should do all of the above by default; coming up with standard maven archetype classifiers so folks can easily consume the things they need; a k8s yaml, an OpenShift Template, individual files or a zip of the files or the Catalog yaml etc?

### Catalog resources

Right now we use OpenShift templates as a way of installing a resource into k8s we can then use from the Fabric8 console to run apps via the `Run...` button. Its just a way of storing a blob of YAML inside k8s for running it later.

Going forward we want to support non-OpenShift templates (some things don't need parameterisation). Plus we wanna support vanilla kubernetes - also there's ConfigMap where there's no OpenShift Template and the parameterisation is done by a separate ConfigMap entry.

So we could maybe use ConfigMap as an alternative to OpenShift templates for the 'catalog' of apps folks could choose to run. 

e.g. an app could be turned into this...

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp
  labels:
     kind: catalog
data:
  service-foo.yml: |
    apiVerison: v1
    kind: Service
    ...
  rc.yml: |
    apiVerison: v1
    kind: Service
    ...
```

i.e. we create a ConfigMap instead of an OpenShift Template to store all the resources individually (with each file stored inside the config map as a data entry)

The Fabric8 Console's `Run...` button can then view all the Templates and ConfigMaps in a system to let folks run apps

**Comment by rhuss** [comment]
> I wonder if we should do all of the above by default; coming up with standard maven archetype classifiers so folks can easily consume the things they need; a k8s yaml, an OpenShift Template, individual files or a zip of the files or the Catalog yaml etc?

Maybe that should be a configuration option in the plugin configuration, with a sane default. Maybe we should consider two kinds of users:

* Those users who develop against a specific platform, kubernetes or OpenShift. Mostly inhouse projects, with a single installation. For those its fair to assume that they will stick to a single type (openshift templates or kubernetes vanilla or kubernetes with configmap)
* Those who want to publish the projects for others to use. Here they wont probably publish for both, OpenShift and Kubernetes simultaneously. So it should be possible to publish multiple artefacts.

**Comment by rhuss** [comment]
Having multiple different files has also the advantages that some (but please not to many) meta information can be put in the filename, e.g. the resource's `Kind` (e.g. suffix '-svc.xml`) and name (overwritable, convention-over-configuration style).

**Comment by rhuss** [comment]
When embedding resource descriptors within config map values we should take care to use the full objects, not a string representation (dont know whether config map supports other stuff then strings as values). Otherwise you would loose an IDE / editor support for this 'stringified' objects.

**Comment by jstrachan** [comment]
as someone who makes apps for kubernetes, we'd want our apps to be as easy to consume by any kind of user as possible. So I'd think most folks would want their app to be easy to consume on both kubernetes and OpenShift. 

I guess folks might want to opt out of the 'fabric8 catalog' format though; but we should try encourage folks to opt in - and force folks to disable that option ;)

**Comment by jstrachan** [comment]
@rhuss in ConfigMap the values are strings; but they can be YAML or JSON strings. I'm hoping folks never have to edit these 'Catalog Config Map" files though; its more of a packaging option really.

So folks can package either into a kubernetes List, an OpenShift template (if they have parameterization), a zip or a Catalog yaml file. 

Would it be such a big deal if we always made all 4 by default unless folks choose to opt out? (The OpenShift template would only be generated if folks use template parameters at all)

**Comment by rhuss** [comment]
@jstrachan agreed, let's start with all four. How we are making the defaults can always be decided later on when we have a feeling.

To summarize, the four formats are:

* Plain `-kubernetes.yml` with all objects as list when no params are used. 
* Alternatively a `-kubernetes.zip` with individual files + one file with all objects as list. With `ConfigMap` objects when parameters are used.
* `-openshift.yml` whith OpenShift templates when parameters are used. Or other OpenShift specific features like binary builds (which require ImageStreams instead of flat images etc.)
* `catalog-fabric8.yml` with a singe ConfigMap object holding the other definitions as values. 

Is this roughly that what you mean ?

**Comment by jstrachan** [comment]
Yeah - that sounds good! 

With the kubernetes* files having any OpenShift specific artefacts stripped out (e.g. OAuthClient).

These packaging goals should be able to work with any yaml files; however they are created (hand crafted, generated, post procssed etc). There's always the maven challenge of making sure things happen in the right order mind you ;)

**Comment by rhuss** [comment]
> With the kubernetes* files having any OpenShift specific artefacts stripped out (e.g. OAuthClient).

In contrast to the current plugin I'd like to do the other way round: First build pure Kubernetes objects and then add OpenShift specific things. So when things changes we only have to change one spot (adding the OpenShift feature) and not two (adding OpenShift feature, removing it in a filter step).

hope this ok.

**Comment by jstrachan** [comment]
if folks are writing the yaml files by hand, I figured we'd just have them in the `src/main/kubernetes' folder with the other resources:

```
src/main/kubernetes/
  rc.yml
  service-foo.yml
  service-bar.yml
  sa.yml
  oauthclient.yml
```
then the OpenShift specific stuff (e.g. OAuthClient) would be filtered out by the packaging goals.

**Comment by rhuss** [comment]
understand. Its more about detecting user provided OpenShift specific stuff, then when we implicitily add stuff because of enriching things.

**Comment by jstrachan** [comment]
I think we've most of this sorted now. FWIW `gofabric8` now imports OpenShift templates and other resources as ConfigMap; we have an openshift and kubernetes yml files along with individual files too.

So I think for now we could mark this one as closed and we can raise separate issues later (e.g. kubernetes helm support)
