### ISSUE TITLE
icon post processor

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#21]
the old fabric8:json goal used to try detect a file called `icon.(jpg|jpeg|png|svg|gif)` in `src/main/fabric8` and if so annotate the generated Template. The original motivation was to try use data URLs for icons so we could embed them inside the templates. We soon found a single template (e.g. cd-pipeline) could require lots of icons (jenkins / gogs / nexus etc) so soon backed away from embedded data urls to just regular URLs.

As we move away from OS Template as the default output to being either a kubernetes zip of resources;  a single kubernetes List or an OpenShift List/Template then we should avoid relying on an OpenShift Template being present to give the icon annotation. Instead we should annotate ServiceAccount / Service / Deployment / ReplicationController / ReplicaSet resources with the icon annotation. 

Then it doesn't matter how folks run things; the icons will be preserved. Right now we actually try to find the Template for a Service / RC to find the icon in the console :)

**Comment by rhuss** [comment]
Good point. The idea is to have a dedicated "enricher" for Icons, similar to [ProjectInfoEnricher](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/src/main/java/io/fabric8/maven/fabric8/enricher/impl/ProjectInfoEnricher.java). 

The [Enricher](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/src/main/java/io/fabric8/maven/fabric8/enricher/Enricher.java) API is not finalized, but the idea should be clear. People can switch on / off certain enrichers in the configuration which encapsulate specific aspect like 'iconify' resources. 

fwiw, at the moment I'm busy with my talk's demo (which by the way will be also good for a quick resource comparisation between boot and swarm) and the slides, but will continue in full steam after the presentation. Really keen on moving forwards here ...

**Comment by jstrachan** [comment]
this issue is now fixed - we now annotate the Service + Deployment/RepliaSet/ReplicationController so icons work great on kubernetes or openshift
