### ISSUE TITLE
ServiceGenerator should evaluate Image labels for ports

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#222]
The `SeviceEnricher` could check the Docker image configuration for specific labels (e.g. `fabric8.service.myservice=9090`) so that it could use this in a service's port specification. The last part of the label should be the service name.

That ways, generators like the spring-boot generator can transport such information to the enrichers in a transparent way. It would be also nice to have that sort of meta-data directly within the Docker image.

**Comment by rohanKanojia** [comment]
@rhuss : What other information can be consumed by enrichers using labels apart from port specification? I see right now we're examining image build configuration.
