### ISSUE TITLE
Lookup IANA service names

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#23]
If only a port number is detected, try to guess the service name by looking up IANA service names.

Idea: Create a populate HashMap from

http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml

(there's an XML option, too), serialize it and store it in the jar. For a lookup, deserialize the JAR into an HashMap object. 

Only if not to large (maps could be sharded by port range).

**Comment by rhuss** [comment]
b

**Comment by jimmidyson** [comment]
The XML file is about 3.5MB (430k gzipped). Could add embed in a separate JAR with all unnecessary info stripped out (only keeping name/port/protocol) & get it down to about 100k gzipped. We can then provide a lookup function via simple xpath query over the resource as a stream?

**Comment by rhuss** [comment]
My initial idea was to use a helper program which reads in the XML data
into a Java map and then writes it out as a serialized object to disc. This
file then could be added to the jar and read in when required by a class
path lookup. It static anyway (mostly, but could be recreated if required).

Jimmi Dyson <notifications@github.com> schrieb am Mo., 29. Aug. 2016, 08:39:

**Comment by rhuss** [comment]
We have this enricher now since some time, thanks @jimmidyson !
