### ISSUE TITLE
hande empty maven projects - or figure out an easy way to disable the f-m-p plugin executions on a project in a multi-maven project?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#254]
in fabric8-devops we configure the f-m-p plugin in a profile: https://github.com/fabric8io/fabric8-devops/blob/master/pom.xml#L334-L380 which means the plugin is then active for all child projects.

It turns out we don't want to generate any resources or perform a docker build for one of these child projects:
https://github.com/fabric8io/fabric8-devops/tree/master/collector-utils

we could totally refactor things and add a level of indirection; but I wonder if we can figure out an easy way to disable f-m-p for this project? Maybe a maven property or a configuration or something? I tried re-defining the executions (to an empty list of goals) in this project; or tried redefining the fmp3 profile; neither worked.

For now I'm gonna keep this project on the 2.x maven plugin as a hack ;) it'd be nice to figure out a nice way around this one really. 

e.g. maybe the f-m-p should ignore any project which there is not a Container generated or configured? As generating an empty Deployment with no containers just causes issues?

**Comment by rhuss** [comment]
You can set certain `skip` properties / config options on the sub-modules.

E.g. `fabric8.skip` will skip the resource execution, `docker.skip` the build execution ...

We have to harmonize the property names, though, but the general mechanism is to let the Mojo Run but do nothing if configured so.

Would this be sufficient here ?

**Comment by jstrachan** [comment]
yeah - that'd be fine. 

Though I so think in the case that there's no Container configured / generated we shouldn't generate a Deployment yaml file either (and generate a nice warning that no container could be discovered or is configured - then mention that the `fabric8.skip` property could be used to remove the warning).

**Comment by jstrachan** [comment]
so kinda relates to https://github.com/fabric8io/fabric8-maven-plugin/issues/207

**Comment by jstrachan** [comment]
to disable a build failing from not being able to access the docker daemon we currently have to specify 2 properties:
```
mvn clean install -Ddocker.skip.build=true -Ddocker.skip=true
```
We probably want to just have one property we can used to skip docker from the fabric8-maven-plugin build (e.g. just `docker.skip`?)
