### ISSUE TITLE
need access to project dependencies to add custom enrichers

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8-maven-plugin#269]
so I'd love to be able to add a dependency, for example, io.fabric8:spring-cloud-kubernetes-netflix to my project.... and have any custom enrichers from that dependency (project dependency) available to the f-m-p so that it can scan that dependency for enrichers. right now, if i add the io.fabric8:spring-cloud-kubernetes-netflix dependency to `<plugin><f-m-p><dependencies>` then it finds it okay, but i'd rather have the f-m-p able to look up the project's dependencies. 

have you done this before @rhuss or @jstrachan ? 

Think we need to load up the Classloader ourself. 

http://maven.apache.org/guides/mini/guide-maven-classloading.html

**Comment by christian-posta** [comment]
have a PR in the works...

**Comment by rhuss** [comment]
i think this should be easily possible these days with adding just a plugin dependency holding the enrichers. Please reopen this issue if this is still a thing.
