### ISSUE TITLE
mvn fabric8:run vs mvn package fabric8:resource fabric8:build fabric8:push fabric8:deploy

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#287]
I was previously using the `fabric8:run` maven goal but I'm not sure if its correct as the https://maven.fabric8.io/ docs don't reference it?

It is mentioned in the quickstart readme though https://github.com/fabric8-quickstarts/spring-boot-camel#running-the-example-in-kubernetes 

FWIW I find 
```
mvn fabric8:run fabric8:push -Ddocker.push.registry=my.registry
```
simpler to get going than the below
```
mvn package fabric8:resource fabric8:build fabric8:push fabric8:deploy -Ddocker.push.registry=my.registry
```
If the full maven goals are required maybe we should have a TL;DR at the top of https://maven.fabric8.io/ to deploy an app?

**Comment by LewisWatson** [comment]
Hi Rawlings. I also noticed that `fabric8:run` is undocumented, which is unfortunate as it is the only way I've managed to get the [Fabric8 Maven Workflow] to work with my OpenShift Origin server.

The [OpenShift docs](https://docs.openshift.com/enterprise/3.1/using_images/xpaas_images/fuse.html) recommend using pre-configured maven profiles.

### `mvn -Pf8-build`
Comprises of clean, install, docker:build, and fabric8:json. This will build dockerfile and JSON template for a project.

### `mvn -Pf8-local-deploy`
Comprises of clean, install, docker:build, fabric8:json, and fabric8:apply. This will create docker and JSON templates and then apply them to OpenShift.

### `mvn -Pf8-deploy`
Comprises of clean, docker:build, fabric8:json, docker:push, and fabric8:apply. This will create docker and JSON templates, push them to docker registry and apply to OpenShift.

Would these be applicable for your situation? I don't think you are using OpenShift but the concepts may be similar.

[Fabric8 Maven Workflow]: https://docs.openshift.com/enterprise/3.1/using_images/xpaas_images/fuse.html#fabric8-maven-workflow

**Comment by jstrachan** [comment]
Those are for the 2.x maven plugin, they don't apply to 3.x

JamesR the main difference between fabric8:run and fabric8:deploy is that the former forks the install goal (which in turn calls the favric8:resource goal to generate the kubernete & openshift manifests and fabric8:build to create the docker image - a regular mvn install will invoke those two)

So mvn fabric8:run == mvn install fabric8:deploy

**Comment by rawlingsj** [comment]
Thanks for the idea @LewisWatson but yeah it's the f-m-p 3.x that I'm looking at which doesn't work for those profiles.

@jstrachan ok cool that makes sense, so `fabric8:run` is totally valid and just missing from the https://maven.fabric8.io/ docs.  Just wanted to confirm as I'm updating some examples and wasn't sure.

- **mvn fabric8:resource** generates the manifests
- **mvn fabric8:build** builds the docker image
- **mvn install** generates the resources **and** builds the docker image
- **mvn fabric8:deploy** applies the manifest 
- **mvn fabric8:run** generates the resources **and** builds the docker image **and** applies the manifest

**Comment by rawlingsj** [comment]
Closing as it makes sense now.  Also discussed in more detail in https://github.com/fabric8io/fabric8-maven-plugin/issues/289#issuecomment-242679954
