### ISSUE TITLE
Error creating assembly archive docker: You must set at least one file. with mode dir

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#289]
Using the defaults when prompted:

```
mvn org.apache.maven.plugins:maven-archetype-plugin:2.2:generate -Dfilter=io.fabric8:spring-boot-camel-archetype -DgroupId=my.test -DartifactId=fabric8-test-project
cd fabric8-test-project
```

```
➜  fabric8-test-project mvn clean fabric8:resource fabric8:build fabric8:push fabric8:deploy -Ddocker.push.registry=fabric8-docker-registry.default.beast.fabric8.io
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: Spring-Boot :: Camel 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fabric8-test-project ---
[INFO] Deleting /Users/jamesrawlings/archs/fabric8-test-project/target
[INFO]
[INFO] --- fabric8-maven-plugin:3.1.17:resource (default-cli) @ fabric8-test-project ---
[INFO] F8> Running in Kubernetes mode
[INFO] F8> Running generator spring-boot
[INFO] F8> fmp-service: Adding a default Service with ports [8080]
[INFO] F8> fmp-controller: Adding a default Deployment
[WARNING] F8> No .git/config file could be found so cannot annotate kubernetes resources with git commit SHA and branch
[WARNING] F8> No .git/config file could be found so cannot annotate kubernetes resources with git commit SHA and branch
[INFO]
[INFO] >>> fabric8-maven-plugin:3.1.17:build (default-cli) > initialize @ fabric8-test-project >>>
[INFO]
[INFO] <<< fabric8-maven-plugin:3.1.17:build (default-cli) < initialize @ fabric8-test-project <<<
[INFO]
[INFO] --- fabric8-maven-plugin:3.1.17:build (default-cli) @ fabric8-test-project ---
[INFO] F8> Running in Kubernetes mode
[INFO] F8> Running generator spring-boot
[WARNING] Cannot include project artifact: my.test:fabric8-test-project:jar:1.0-SNAPSHOT; it doesn't have an associated file or directory.
[WARNING] The following patterns were never triggered in this artifact inclusion filter:
o  'my.test:fabric8-test-project'

[ERROR] F8> Failed to create assembly for docker image: Error creating assembly archive docker: You must set at least one file. with mode dir
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by rawlingsj** [comment]
The error is with the combination of fabric8:resource and fabric8:build

```
mvn clean fabric8:resource fabric8:build
```
gives
```
[ERROR] F8> Failed to create assembly for docker image: Error creating assembly archive docker: You must set at least one file. with mode dir
```
Incidentally 
```
mvn install
```
works; it generates the resources and builds the docker image

**Comment by jimmidyson** [comment]
You haven't run the actual build - `package` needs to be run to create the contents for the assembly I gues.

**Comment by rawlingsj** [comment]
yeah that was it @jimmidyson, I skipped that line in the docs as they're in two separate commands.

I wonder instead of `mvn package fabric8:resource fabric8:build` we just recommend `mvn fabric8:run`?

Related to https://github.com/fabric8io/fabric8-maven-plugin/issues/287#issuecomment-242666456

**Comment by jimmidyson** [comment]
`mvn package fabric8:resource fabric8:build` should simply be `mvn install` shouldn't it? `mvn fabric8:run` actually deploys it as well (effectively `mvn install fabric8:deploy`).

**Comment by rawlingsj** [comment]
oh crap - yeah sorry run does the deploy too, getting mixed up.  

perhaps there's too many goals or maybe I'm just being especially slow this Friday

**Comment by jimmidyson** [comment]
There are a lot of goals. My workflow I tend to use `mvn clean install fabric8:deploy` although I guess `mvn clean fabric8:run` is slightly shorter to type I guess.

**Comment by rawlingsj** [comment]
There's probably good reason and previous discussion around this but if

```
mvn install == mvn package fabric8:resource fabric8:build
```
couldn't we have
```
mvn deploy == mvn clean install fabric8:deploy ||  mvn fabric8:run
```
?

**Comment by jimmidyson** [comment]
Hmm it's not normal deploy semantics which is generally used to distribute artifacts to remote repositories. I don't personally think it's a good thing to piggy back off as it introduces a change to the regular maven workflow that users know. The previous steps are just generating resources so fine to run in previous lifecycle phases without going against known convention, e.g. `fabric8:resources` is tied to `process-resources` which is what it is actually doing to update the artifacts accordingly.

**Comment by rawlingsj** [comment]
Yeah that's a fair point.

So maybe its just the 
`mvn clean package fabric8:resource fabric8:build` that we could avoid recommendeding and suggest 
`mvn clean install` instead?

Then when someone whats to run that on kubernetes or openshift we recommened either

`mvn clean fabric8:run`
or 
`mvn clean install fabric8:deploy`

As per the workflow you're using @jimmidyson ?

**Comment by jimmidyson** [comment]
Sounds good to me. If you want to make it look cleaner, drop the `clean` (how ironic). Most of the time it shouldn't be needed, incremental builds should be fine.

**Comment by rawlingsj** [comment]
Ok cool - I'll leave the issue open until others are back from PTO to confirm this is aligned with their thoughts.  I'm happy to update docs and wotnot after that.

**Comment by rhuss** [comment]
Just a note: We could make fabric8:build fork the life cycle an implicitly
include the package phase. For binding to an execution we then would need
to introduce a fabric8:build-nofork (much like the maven-source-plugin
does).

James Rawlings <notifications@github.com> schrieb am Fr., 26. Aug. 2016,
10:39:

**Comment by davsclaus** [comment]
Yeah this is still a tad confusing what mvn goals to run to have it do a rebuild of the source code, docker images and then deploy to k8s so you can do development cycle. eg developer change some code, and then want to run/update in k8s the running pods of his/her project.

**Comment by davsclaus** [comment]
So far seems this one is the shortest so far

     mvn package fabric8:build fabric8:run

**Comment by rhuss** [comment]
for a full deployment, yes. However its more convenient to bind these goals to their default lifecycles so you get everything with 'mvn install' 

```xml
<plugin>
   ....
        <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build</goal>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
</plugin>
```

This can go even in a parent pom.xml (btw, that also how the spring-boot-maven-plugin hooks into the install phase).

In order to safe the `package` phase for `fabric8:build`, if could introduce a lifecycle fork for this goal, and introduce a `fabric8:build-nofork` which is the *old* `fabric8:build` to be used in the execution phase which then read like

```xml
<plugin>
   ....
        <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build-nofork</goal>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
</plugin>
```

Otherwise, `package` would be called twice. This means, we would have to update all our quickstarts, devops stuff, etc. 

@fabric8io/maintainers any opinion on that ?

**Comment by OndraZizka** [comment]
In short: The message is weird, but what it means is that the assembly plugin can't find the dependency you set in `<dependencySets>`.

    <dependencySets>
        <dependencySet>
            <useProjectArtifact>false</useProjectArtifact>
            <includes>
                <include>com.mycompany:bpds-api</include>
            </includes>
            <outputDirectory>.</outputDirectory>
            <outputFileNameMapping>bpds-fabric8.jar</outputFileNameMapping>
        </dependencySet>
    </dependencySets>

You need to add that to project's dependencies. Check that it's not `test` scope.

    <dependencies>
        <dependency>
            <groupId>com.mycompany</groupId>
            <artifactId>bpds-api</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

**Comment by rohanKanojia** [comment]
@fabric8io/fmp-core-team : Do we need to take any action on this?

**Comment by rhuss** [comment]
I think we can close it. It's a well-known issue, that you need to have the package phase running in order for an assembly to succeed. It's documented in the docs, and there is no general solution to this problem.

Let's close it for now, but feel free to reopen it if you think this is still an issue.

**Comment by emaayan** [comment]
hi, i have an issue, with this, my current build, does infact creates a tar.gz and i'd like to include THAT in the image, the reason is that assembly plugin already sets the execute permissiosn inside the tar and converts the files in to linux line endings. 
while i can use the same descriptor i'm using in the assembly plugin, i'm using windows to build the container for linux and without the tar file the permissions will be reset. 
so is there a way to have the tar itself included in the image. 
the module is a sub-module that does the building.
if i create a standalone module and add the tar manualy to the resources it works .

**Comment by rohanKanojia** [comment]
@emaayan : This project has been migrated to https://github.com/eclipse/jkube . Could you please file an issue there?
