### ISSUE TITLE
fabric8:deploy should check for ~/.kube/config and if not present suggest either using kubectl or `mvn fabric8:install`

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#304]
it might be nice if folks try to run `mvn fabric8:build` or `mvn fabric8:deploy` before they have installed/setup a local cluster - instead of barfing or blocking on some non existent docker / kubernetes call to warn the user that there's no ~/.kube/config and then fail the build and then tell the user to either run `mvn fabric8:install` to install a local cluster or use kubectl to connect to a remote cluster.

e.g. if folks try to run 'mvn install' on a fabric8-maven-plugin enabled project, we should try help them to setup a local cluster or point to a remote cluster

**Comment by rhuss** [comment]
Good idea ! This would be very helpful for an intuitive first operation. We could emit such a message also after the end of a 'mvn fabric8:setup' when called for the first time to indicate the 'next step'.

**Comment by jstrachan** [comment]
here's what it looks like if `mvn fabric8:deploy` fails:
```
[INFO] --- fabric8-maven-plugin:3.1.11:deploy (default-cli) @ funktion-java-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.872 s
[INFO] Finished at: 2016-09-05T09:03:08+01:00
[INFO] Final Memory: 38M/515M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.11:deploy (default-cli) on project funktion-java-example: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.11:deploy failed: An error has occurred. connect timed out -> [Help 1]
```
it'd be nice to add more diagnostic errors indicating that we couldn't connect to kubernetes - that maybe kubectl / mvn fabric8:install is required etc

**Comment by rhuss** [comment]
btw I wonder whether we should allow providing credentials like in d-m-p (as direct properties or via ~/.m2/settings.xml in `<server>` sections), so that `kubectl` is not required for login. Don't know whether this is easily possible but maybe worth the effort is `kubectl` is only needed for authentication.

**Comment by jimmidyson** [comment]
There are different options for authentication (basic auth user/pass, bearer token, client certificate spring to mind immediately). Not sure we could support all of those via server section in settings.xml? Also config for CA certificate or disabling cert verification would be required. Could just support simple username/password in settings.xml I guess?

**Comment by jstrachan** [comment]
delegating to kubectl / oc for that kinda stuff seems simpler?

**Comment by jstrachan** [comment]
then we just load whatever's in `~/.kube/config` in java land via the kubernetes-client?

**Comment by rhuss** [comment]
@jimmidyson you are right, `<server>` supports user & password (the password can be encrypted with a master password) and additional freeform configuration via `<configuration>`. See http://maven.apache.org/xsd/settings-1.1.0.xsd , look for the `Server` element. So theoretical we could add anything here (even plain certificates) and feed the Kubernetes Client with that. A (temporary) bearer token probably doesn't makes much sense to add here, or ?

@jstrachan completely agreed, it definitely simpler from an implementation standpoint. Just wanted to point out in case we want to get rid of the hard requirement of a local kubectl or oc install, we could offer this, too, as an alternative. But for complex authentication scenarios using kc / oc is safer.

**Comment by jimmidyson** [comment]
We could use create a `~/.kube/config` (it's just another type in kubernetes-model) if we made fabric8:install interactive & ask for what kind of auth to use? kubernetes-client will use whatever's there regardless of what set it up.

**Comment by jimmidyson** [comment]
@rhuss Temporary bearer token doesn't make sense, but long running bearer tokens (API keys) do make sense.

**Comment by jstrachan** [comment]
I've added a separate issue https://github.com/fabric8io/fabric8-maven-plugin/issues/33 for `mvn fabric8:build` as it required a change in docker-maven-plugin to add a different way to detect the docker daemon if there's no DOCKER_HOST.

**Comment by jstrachan** [comment]
updated issue to be just about fabric8:deploy / run
