### ISSUE TITLE
automatically include files in the docker image from a canonical folder

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#321]
e.g. `src/main/docker` or `src/main/deployment`

for example if you wish to override the `run.sh` or copy in some configuration files into the `/deployment` folder it'd be nice to just add the necessary files to a canonical place (which could be configured to be a different folder if folks really cared); then those files in that folder would automatically by default get copied into the docker tarball and docker image.

e.g. adding a properties file to `src/main/docker/config/log4j.properties` or whatever

**Comment by rhuss** [comment]
We already support this in d-m-p via an assembly descriptor. There is also support for predefined assembly descriptors which could easily provide and refer to from an f-m-p generator. I wouldn't hardcod this but settle on the existing caps.

**Comment by jstrachan** [comment]
I'm more thinking of a more concise way to do this than creating an assembly descriptor. For fat jar / flat classpath microservices like Spring Boot or DropWizard, we don't really need to make an assembly descriptor. So for those users, I figured having a default folder folks could use to drop files into the /deployment would be easier for users than troubling them about creating an assembly descriptor in pom.xml

**Comment by rhuss** [comment]
We could provide a default assembly descriptor, referencable via `descriptorRef`, which includes a directory, let's say `src/main/fabric8-includes`. It doesnt harm if this directory doesnt exist. We then use this assembly descriptor as default for our enrichers.

**Comment by jstrachan** [comment]
Sounds good to me

**Comment by chirino** [comment]
+1 for the src/main/fabric8-includes
Should it also defulat to chmod 755 src/main/fabric8-includes/bin and src/main/fabric8-includes/lib in case we want to put native binaries or shared libs there?

**Comment by chirino** [comment]
BTW a good use case for this might also be how to add custom JVM agents like YourKit for profiling to a JVM.

**Comment by rhuss** [comment]
Fixed with latest PR (default dir is now `src/main/deployments`), works with java base images > 1.20
