### ISSUE TITLE
Allow to turn of default service created by generator

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#329]
Sometimes you have a Sprint Boot or other kind of application which should not expose any service. Currently they get automatic a service created on port 8080 using the maven artifact id as the name.

We should make it possible to turn that off.

**Comment by jstrachan** [comment]
Yeah - we should have a configuration option to turn it off.

BTW there's 2 levels of exporting; there's is the service visible inside the kubernetes cluster; then secondly what kind of service is it (internal or external); the latter requires custom YAML to export it outside of the cluster

**Comment by rhuss** [comment]
We also still need a more sophisticated way to detect the port, e.g by analysing the spring-boot runtime configuration.

**Comment by jstrachan** [comment]
@rhuss we have some of that already for health check: https://github.com/jstrachan/fabric8-maven-plugin/blob/d2c3cd953d9c6524da879af8b63a6683957371b9/core/src/main/java/io/fabric8/maven/core/handler/ContainerHandler.java#L118-L118

we should use that lookup to override the web endpoint too though

**Comment by rhuss** [comment]
yes, something like we should use for the spring-generator. 

And we have to move the generation of the health check to the spring-boot generator, too.
