### ISSUE TITLE
`fabric8:build` should check if there is no docker host, then if gofabric8 is on the PATH use `gofabric8 docker-env`

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#333]
if someone clones a fabric8 enabled project and doesn't install docker or kubernetes, they'll have no `dockerHost` maven property in their `~/.m2/settings.xml` or have `$DOCKER_HOST`

However now we have `mvn fabric8:install` we've java code that can easily check for `gofabric8` on the PATH and download it if required (maybe with a user prompt).

Also if we find `gofabric8` there's a new command soon: `gofabric8 docker-env` which will figure out the docker env vars for minikube or minishift (maybe others later on).

So if there's no DOCKER_HOST the code could run `gofabric8 docker-env` to find the env vars required.

I had a quick look at implementing this - looks like docker-maven-plugin has a private method 
https://github.com/fabric8io/docker-maven-plugin/blob/7e1af5b66871631d4ab3403c282d55f9c6c520d3/src/main/java/io/fabric8/maven/docker/AbstractDockerMojo.java#L298

it would be nice to make that protected so we can override it in the fabric8:build goal to auto-detect docker via gofabric8 instead.

**Comment by jstrachan** [comment]
FWIW this one change would be really handy for me - as I often switch & restart minishift + minikube so a given shell usually doesn't know how to talk to the current kubernetes/openshift clusters's docker daemon at any point in time. I'd prefer all my shells to have no DOCKER_HOST by default and to lazily evaluate them via `gofabric8 docker-env`.

Its also tempting to alias `docker` to be a bash script to `eval $(docker-env}` then run the real docker binary ;)

**Comment by rhuss** [comment]
I will have a look today. Shouldn't be that hard to make it protected in docker-maven-plugin.

**Comment by jstrachan** [comment]
Awesome! We have `gofabric8 docker-env` now, so we should be able to easily check if gofabric8 is on the PATH, that DOCKER_HOST is missing and if so parse the results to setup the various DOCKER env stuff like DOCKER_HOST et al.

Maybe if there's no gofabric8 on the PATH and no DOCKER_HOST / dockerHost property we could also display some text after the warning about no DOCKER_HOST along the lines of 

```
no gofabric8 binary was found on the PATH which can setup your environment automatically. Try running: `mvn fabric8:install` to setup your local machine!
```

**Comment by jstrachan** [comment]
actually its maybe better to just prompt the user in the case of no gofabric8 binary on the PATH and no DOCKER_HOST:
```
No DOCKER_HOST defined.... and no gofabric8 was found on the PATH.

Would you like to setup a kubernetes cluster on your local machine? (y/N): _
```
and then just do the install ;)

**Comment by rhuss** [comment]
working on it right now. I can reuse quite a bit of code from the docker-machine stuff to run the `gofabric8 env` command.

**Comment by jstrachan** [comment]
I just tried it. Almost there - it does detect DOCKER_HOST now:
```
[INFO] F8> DOCKER_HOST from gofabric8 : tcp://192.168.64.81:2376
2016-09-26 09:10:26 INFO  RetryExec:96 - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->tcp://192.168.64.81:2376: tcp protocol is not supported
2016-09-26 09:10:26 INFO  RetryExec:112 - Retrying request to {}->tcp://192.168.64.81:2376
2016-09-26 09:10:26 INFO  RetryExec:96 - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->tcp://192.168.64.81:2376: tcp protocol is not supported
2016-09-26 09:10:26 INFO  RetryExec:112 - Retrying request to {}->tcp://192.168.64.81:2376
2016-09-26 09:10:26 INFO  RetryExec:96 - I/O exception (org.apache.http.conn.UnsupportedSchemeException) caught when processing request to {}->tcp://192.168.64.81:2376: tcp protocol is not supported
2016-09-26 09:10:26 INFO  RetryExec:112 - Retrying request to {}->tcp://192.168.64.81:2376
[ERROR] F8> Cannot create docker access object
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.082 s
[INFO] Finished at: 2016-09-26T09:10:26+01:00
[INFO] Final Memory: 39M/477M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "quickstarts" could not be activated because it does not exist.
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:build (fmp) on project demo: Cannot create docker access object: Cannot extract API version from server tcp://192.168.64.81:2376: tcp protocol is not supported -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
Not sure what the issue is. If I ran `eval $(gofabric8 docker-env)` it was all fine. I wonder if the java code needs to interpret `tcp://` as `http://` (have some vague memory the java code prefers http:// URLs

**Comment by rhuss** [comment]
will check that, you are probably right.

**Comment by jstrachan** [comment]
still doesn't work for me here:
```
[INFO] --- fabric8-maven-plugin:3.1-SNAPSHOT:build (fmp) @ demo ---
[INFO] F8> Running in Kubernetes mode
[INFO] F8> Generators:
[INFO] F8>  - spring-boot
[INFO] F8>  - karaf
[INFO] F8>  - wildfly-swarm
[INFO] F8>  - java-exec
[INFO] F8> Running generator spring-boot
[INFO] F8> DOCKER_HOST from gofabric8 : https://192.168.64.81:2376
[ERROR] F8> Cannot create docker access object
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.304 s
[INFO] Finished at: 2016-09-26T15:44:05+01:00
[INFO] Final Memory: 39M/478M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "quickstarts" could not be activated because it does not exist.
[WARNING] The requested profile "fmp-snapshotpwd" could not be activated because it does not exist.
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1-SNAPSHOT:build (fmp) on project demo: Cannot create docker access object: Cannot extract API version from server https://192.168.64.81:2376: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

I guess we also need to set the environment variables from the output of `gofabric8 docker-env`? e.g. these?

```
export DOCKER_TLS_VERIFY="1"
export DOCKER_CERT_PATH="/Users/jstrachan/.minikube/certs"
```

**Comment by rhuss** [comment]
yes, have to check this again.
