### ISSUE TITLE
have an interactive fabric8:run mode?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#338]
something like:
```
$ mvn fabric8:run-interactive
....
deploying app foo
...
waiting for pod foo-1234 to be ready.....

pod foo-1234 is now ready!

Please press Ctrl-C to terminate the app!

log of pod is now tailed to the console....

....
[Ctrl-C pressed]
scaling down deployment foo.....
pods all terminated
```

so that to java developers it looks and feels like you just did `mvn spring-boot:run` and to stop it you just ctrl-C it.

**Comment by kameshsampath** [comment]
@jstrachan, shall we also add option to fabric8:run to expose the service as well ?

**Comment by jstrachan** [comment]
FWIW its the `fabric8:resource` that does that. I've raised a separate issue for improving the UX of exposing services:  https://github.com/fabric8io/fabric8-maven-plugin/issues/341

**Comment by jstrachan** [comment]
I've been prefixing the log output with the pod name then using a colour to highlight the log coming from the pod. 

I wonder if this is a bit too wide? Maybe we just use "Pod >" as the prefix and have the first line list the pod name? 

<img width="1707" alt="console" src="https://cloud.githubusercontent.com/assets/30140/18583404/48ab9b6e-7c02-11e6-964f-7dc426b85e00.png">

**Comment by jstrachan** [comment]
I think this is a bit easier to grok, particularly on smaller screens:

<img width="1568" alt="2__spring-boot-webmvc__java__and_3__plugin__bash_" src="https://cloud.githubusercontent.com/assets/30140/18583534/fefa7962-7c02-11e6-8dfb-bc2c051f161f.png">

**Comment by jstrachan** [comment]
Here's an example of pressing `Ctrl-C` which then undeploys the app:

I've made it the default; we can disable the deleteOnExit via `-Dfabric8.deleteOnExit=false`

<img width="1699" alt="2__spring-boot-webmvc__bash__and_3__plugin__bash_" src="https://cloud.githubusercontent.com/assets/30140/18583757/678e4ade-7c04-11e6-83b0-bf67b1faca99.png">

**Comment by jstrachan** [comment]
all sorted! we've `mvn fabric8:log` too for similar stuff when folks use `mvn fabric8:deploy`
