### ISSUE TITLE
mvn fabric8:stop / fabric8:delete commands to stop / delete something after a fabric8:run / fabric8:deploy

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#339]
the fabric8:stop goal would just scale down any D/DC or RS/RC and wait for things to be stopped.

the fabric8:delete would delete all the resources created (properly scaling down the D/DC/RS/RC first then removing them) so that any deployed resources are removed

**Comment by kameshsampath** [comment]
👍

**Comment by jstrachan** [comment]
think we're all good now - mvn fabric8:undeploy or mvn fabric8:stop

**Comment by kameshsampath** [comment]
super @jstrachan !! will try and let you know on it

**Comment by jstrachan** [comment]
@kameshsampath we've tidied up some of the names of the maven goals; so the docs are the best place to check the goal names etc:
https://maven.fabric8.io/

I'm loving the new `fabric8:run` goal btw!
https://maven.fabric8.io/#fabric8:run
