### ISSUE TITLE
better support for service exposing

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#341]
We need better docs on how to expose services easily. 

Up to now lots of our quickstarts have used `type: LoadBalancer` to expose services. We need to update those to use the label `expose: true` instead so that things get annotated nicely and if folks are running router / ingress controller they get a route/ingress.

e.g. by adding something like this to `src/main/fabric8/foo-service.yml`

``` yaml
metadata:
  labels:
      expose: true
```

Its worth adding a section to the docs on all this too as a its a little confusing

**Comment by kameshsampath** [comment]
@jstrachan  this also needs to have router running as part of the minishift startup to have the service exposed and accessible via the route url like `myservice.demo.<ip>.xip.io`

**Comment by jstrachan** [comment]
@kameshsampath yeah - if the router is running `expose: true` will create a Route; if there's the ingress controller running on kubernetes we'll create an Ingress otherwise we default to nodePorts locally. On a cloud provider you can also use `type: LoadBalancer` to get an external IP address. 

This complexity is why we created the exposecontroller microservice to take care of all this:
https://github.com/fabric8io/exposecontroller/

**Comment by jstrachan** [comment]
the expose services docs should reference this too: https://blog.fabric8.io/accessing-your-applications-on-kubernetes-or-openshift-3e69be0ad3bc#.cphg55mzp

**Comment by kameshsampath** [comment]
Thanks @jstrachan

**Comment by jstrachan** [comment]
there's improvements on #409 to expose by default in the fabric8 profile

**Comment by kameshsampath** [comment]
thanks @jstrachan , i see that coming with latest 3.1-SNAPHOT plugin

**Comment by jstrachan** [comment]
I'll leave this open for now - we should be able to remove all the type:LoadBalancer stuff from quickstarts as the default profile now exposes services; we can then use the `internal-microservice` profile to disable it again
