### ISSUE TITLE
Cannot find 'group' in class io.fabric8.maven.core.config.MetaDataConfig

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#344]
When I use this config with the new plugin (version 3.1.38) - https://github.com/cmoulliard/use-cases/blob/master/vertx-kube-configmap/pom.xml 

I get this error 

```
io.fabric8:fabric8-maven-plugin:3.1.38:build for parameter group: Cannot find 'group' in class io.fabric8.maven.core.config.MetaDataConfig
```

here is the maven stacktrace : https://gist.github.com/cmoulliard/94d57e98da14b515c8d22ec110327d01

**Comment by rhuss** [comment]
Version 3 of f-m-p is a complete rewrite with a completely new configuration syntax. You need to adapt your configuration accordingly. Luckily there is a Maven goal for **version 2** of f-m-p which helps in the migration.

See https://maven.fabric8.io/#migration and http://fabric8.io/guide/mavenFabric8Migrate.html for details. 

Please contact us in IRC for further assistance.

**Comment by cmoulliard** [comment]
I will try to migrate my project ;-). Thank
