### ISSUE TITLE
lets not limit the yml files to a naming convention 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#35]
I'm trying to create a ServiceAccount; there will be all kinds of k8s resources over time. (Ingress, Deployment, ConfigMap and many others).

Right now I get
```
resource failed: Unknown type 'sa'. Must be one of : svc, rc, rs, service
```

Lets use the naming convention of files purely to default the `kind`. Otherwise lets read any other files and assume they must include a `kind: Foo` statement. 

Though we could add `sa` and `cm / configmap` as other extensions too I guess; along with `deployment`

**Comment by rhuss** [comment]
yeah, good idea. I will pick this.
