### ISSUE TITLE
Distinguish between resource templates to apply to the build image and others

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#359]
Currently, when we found skeleton resources in `src/main/fabric8` we enrich them all without differentiation whether it should apply to the current app (that which is build) or a other resources which should not be enriched with build information. like database services and others.

Examples are:

* All service templates found are enriched with the ports of the image configuration found
* All rc templates found are enriched with the configured image names and put into the container specs.

My suggestion is to check if no name for a  resource in `src/main/fabric8`  is set and only enrich this with the build information for default service and default controller (and the name from the configuration). E.g. we would store those objects ins `svc.yml` or `rc.yml` whereas other resources are called like `couchdb-svc.yml` or `couchdb-rc.yml`.

**Comment by jstrachan** [comment]
Wonder if we should use an annotation to exclude enrichment? I can imagine all YAML files having a name irrespective of if you want enrichment?

**Comment by rhuss** [comment]
You can have files like `svc.yml` which only carry the type (this is already supported). Of course there should be no name in the yml, too.

But an annotation would be also ok (however not so easily visible from the outside by only looking to the filename). The problem for the enrichers ares, that many use visitors and don't get easy information in which top-level object they are (the name would be on the top-level object) (there are no traversal methods on the builders).

**Comment by rhuss** [comment]
Also its even a bit more tricky, because we still might want *some* enrichments also for some databases (like the maven coordinates as labels for easy grouping).

**Comment by jstrachan** [comment]
Ok how about a folder for 'dependencies' which don't get the same enrichment rules.

Btw if an app defines services for things it requires (databases etc ) those should still get enriched right? It's just the deployment or endpoints that are not?

we could have test scoped resources only used for tests & 'mvn fabric8:run'? In src/test/fabric8

**Comment by rhuss** [comment]
Currently our enrichments works that e.g. alls services are enriched with the ports from the application to build (the visitor will be applied to all service objects found). Obviously not what we want if we have a MySQL service as dependencies which should be deployed along the app. There are more examples.

**Comment by jstrachan** [comment]
Ah you mean for app enrichments (ports, health checks etc) those would only apply to resources named '${project.artifactId}' right? Whether in the foo-svc.yml or svc.yml files - it'd match the app name? I've seen folks use both file names

I think I misunderstood your initial comments (I blame jetlag!) you can still have enrichments on all resources with all names (eg labels) but only do port stuff on the app's default svc/deployment

**Comment by rhuss** [comment]
yes, that's what I mean ;-)

**Comment by rhuss** [comment]
good luck btw for today ;-)

**Comment by jstrachan** [comment]
Thanks! This issue sounds good to me!
