### ISSUE TITLE
Add WildFly-Swarm readiness check

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#376]
WF Swarm has healthcheck if you add the monitor dependency.

However it has a little flaw that when calling /health it returns 503 if there is no custom health endpoints, as it does not provide a default OOTB. So you can use /node to check if the node is running.

Hopefully they make /health better. I logged a ticket:
https://issues.jboss.org/browse/SWARM-693

But we could make f-m-p detect the monitor dependency in the pom.xml and then add /node as readiness/liveness probe - like we do for Spring Boot.

**Comment by davsclaus** [comment]
@christian-posta did a webinar recently and got readiness check working on wf-swarm. So we could likely add the fractions to our swarm quickstarts. And then make the fmp plugin detect this fraction and then automatic add a readiness/liveness check on that url

**Comment by davsclaus** [comment]
The new 2016.12 release now has health check support on the same endpoint `health` as SB does. We can then use that if `swarm-monitoring` is on the classpath.

**Comment by rhuss** [comment]
Implemented already for Wildfly and Thorntail V2.
