### ISSUE TITLE
fabric8:run followed by CTRL+C fails to delete replicaset/controller

### ISSUE THREAD

**Issue by christian-posta** [fabric8io/fabric8-maven-plugin#381]
And this leaves some pods around..

**Comment by jstrachan** [comment]
Yeah - it's a known bug on k8s with kubernetes-client. Hopefully sorted soon!

Btw just cut a release where stop is the default rather than delete (which also avoids services changing IP & node port URLs between runs)

https://maven.fabric8.io/#fabric8:run

**Comment by jstrachan** [comment]
BTW I think this is now fixed for Deployment, RS, RC - it now scales to 0 by default. 

There's a pending issue that we can't scale DC resources yet:   https://github.com/fabric8io/kubernetes-client/issues/512 - hopefully it'll be fixed very soon - will leave this issue open until then

**Comment by jstrachan** [comment]
fixed in 3.1.57 or later
