### ISSUE TITLE
We can't use another Docker image with the java generator

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#383]
If I try to configure f-m-p to use another docker image for the java generator

```
<configuration>
    <generator>
        <config>
            <from>docker.io/java:openjdk-8-jdk</from>
            <java-exec>
                <mainClass>io.fabric8.quickstarts.swarm.MainApp</mainClass>
            </java-exec>
        </config>
    </generator>
</configuration>
```
- as described within the doc - https://maven.fabric8.io/#generators-default and
- coded here  https://github.com/fabric8io/fabric8-maven-plugin/blob/v3.1.46/generator/api/src/main/java/io/fabric8/maven/generator/api/BaseGenerator.java#L97

then the image added with the generated Dockerfile is still based on fabric8/jdk8 image and not the one defined --> 

```
FROM fabric8/java-alpine-openjdk8-jdk
EXPOSE 8080 8778 9779
COPY maven /app/
```

**Comment by rhuss** [comment]
First, you should put `<from>` within the `<java-exec>` section.
Then, this won't work since openjdk-8-jdk doesn't come with a proper startup script. Your best choice is one the Java base images as decribed [here](https://github.com/fabric8io-images/README#java)

Confessedly the documentation is a bit confusing at that point, will add some examples.

Does this help ?

**Comment by cmoulliard** [comment]
I will make a new test & move the <from>

Remark : I can't use the Fabric8 Docker image as WildFly Swarm has an issue due to conflict with the Jolokia Logging jar and what is loaded by Wildfly swarm (https://issues.jboss.org/browse/SWARM-204)

**Comment by rhuss** [comment]
You can if you switch off agent bond. But will fix the jolokia issue ASAP (since JBoss doesn't seem to move to fixe their bogus logging initialisation issue).

**Comment by cmoulliard** [comment]
The dockerfile generated still uses this image `FROM fabric8/java-alpine-openjdk8-jdk` after doing this change 

```
                <configuration>
                    <generator>
                        <config>
                            <java-exec>
                                <from>docker.io/java:openjdk-8-jdk</from>
                                <mainClass>io.fabric8.quickstarts.swarm.MainApp</mainClass>
                            </java-exec>
                        </config>
                    </generator>
                </configuration>
```

Project tested : https://github.com/cmoulliard/swarm-camel/blob/master/pom.xml

**Comment by rhuss** [comment]
If you use wildfly-swarm then by default the wildfly-swarm detector kicks. Which means, you dont need to a main class and the configuration should look like

```
<configuration>
   <generator>
          <config>
             <wildfly-swarm>
               <from>docker.io/java:openjdk-8-jdk</from>
             </wildfly-swarm>
          </config>
      </generator>
</configuration>
```

**Comment by cmoulliard** [comment]
Dockerfile has been created correctly now

```
FROM docker.io/java:openjdk-8-jdk
```

Could you add this example to the doc page (I mean : how to configure a different image for wildfly-swarm) ?

**Comment by rhuss** [comment]
@cmoulliard sorry, that I couldn't get to the documentation. And in the meantime the jolokia should be fixed, too. I hope you don't mind when I close this issue, but feel free to reopen it if you think its not solved. If its about the documentation only, we would happily also accept a PR.
