### ISSUE TITLE
 java.util.UnknownFormatConversionException when using fabric8:run

### ISSUE THREAD

**Issue by chirino** [fabric8io/fabric8-maven-plugin#387]
ran `mvn fabric8:run -s configuration/settings.xml ` against git://github.com/fabric8-quickstarts/jboss-fuse-camel-rest-sql.git and got the following error:

	[INFO] Pod> Executing /deployments/karaf/bin/karaf server ...
	[INFO] Pod> I> No access restrictor found, access to all MBean is allowed
	[INFO] Pod> Jolokia: Agent started with URL https://172.17.0.5:8778/jolokia/
	[INFO] Pod> Please wait while Fabric8 is loading...
	[INFO] Pod> 
	Exception in thread "Thread-3" java.util.UnknownFormatConversionException: Conversion = ' '
		at java.util.Formatter.checkText(Formatter.java:2579)
		at java.util.Formatter.parse(Formatter.java:2565)
		at java.util.Formatter.format(Formatter.java:2501)
		at java.util.Formatter.format(Formatter.java:2455)
		at java.lang.String.format(String.java:2940)
		at io.fabric8.maven.docker.util.AnsiLogger.colored(AnsiLogger.java:217)
		at io.fabric8.maven.docker.util.AnsiLogger.info(AnsiLogger.java:68)
		at io.fabric8.maven.plugin.AbstractTailLogMojo$3.run(AbstractTailLogMojo.java:261)

**Comment by rhuss** [comment]
Thanks, will have a look

**Comment by jstrachan** [comment]
@rhuss that could be my fault ;) 

See anything obvious with the creation of the AnsiLogger?
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/java/io/fabric8/maven/plugin/AbstractFabric8Mojo.java#L66

unless its an issue with the AnsiLogger (e.g. maybe dealing with ansi logging codes from the underlying log itself?)

**Comment by rhuss** [comment]
I will check, however they cut my internet connection somehow just ten
minutes ago :-( internet sick, roland sick, not such a good week)

James Strachan <notifications@github.com> schrieb am Mi., 21. Sep. 2016,
10:25:

**Comment by jstrachan** [comment]
@rhuss wonder if any messages sent to the logger need to be encoded in some way? Seems whenever a specific string arrives in the logger that we get this exception

**Comment by rhuss** [comment]
The first argument of the logger is a pattern like for String.format(..), the remaining arguments are then filled in. So you should always use a pattern e.g. like '%s' instead of concatenation with + to avoid construction an invalid pattern 'by accident'.

**Comment by rhuss** [comment]
So instead of 

```
log.info(line)
```

--> 

```
log.info("%s",line);
```

**Comment by rhuss** [comment]
fixed, however we should be careful always to use formats when showing external output.
