### ISSUE TITLE
lets have a `mvn fabric8:import` goal to make it easy to import projects into fabric8

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#389]
which then creates the `BuildConfig` from the git repository of the local project. If there is no git repository then also create a new gogs repository and push the code there. 

This goal should also prompt the user for user/password for https based git protocols; or SSH keypairs for git/ssh protocol so that we can pre-populate the secrets easily for reuse by the console

**Comment by rhuss** [comment]
Is this specific to the fabric8 CD setup or could this be also used when f-m-p is used outside the context of fabric8 ?

**Comment by jstrachan** [comment]
it should work with vanilla openshift too really; one day when we've got ThirdPartyResources for kubernetes; it can support there too really

**Comment by rhuss** [comment]
I mean because of 

> If there is no git repository then also create a new gogs repository and push the code there.

I thought Gogs is specific to our setup.

**Comment by jstrachan** [comment]
ah yeah. Over time I'd like to support other git providers really; but right now gogs is all we have

**Comment by rhuss** [comment]
I mean, even if we support other Git providers, we *assume* that a Git service is running in Kubernetes / OpenShift with the proper secrets setups, which by default is probably not the case.

**Comment by jstrachan** [comment]
yeah - if there's no git service in the current namespace we should fail nicely with a tip on how the user can fix it

**Comment by jstrachan** [comment]
@rhuss BTW added a nicer warning if there's no gogs running:
```
[WARNING] F8> No running endpoints for service gogs in namespace. Please run the `gogs` or the `cd-pipeline` application in the fabric8 console!
```

**Comment by rhuss** [comment]
@jstrachan so this goal really makes only sense when used together with CD ? (that was my initial question ;-) For any other user who (for what reason ever ;-) doesn't want to run the fabric8 infra, the goal is of no use ? 

If so, we should document this and maybe call the goal 'cd-import' ?

**Comment by jstrachan** [comment]
its of use to anyone using OpenShift or fabric8 on kubernetes. Not sure CD is the right name; they are called Jobs in Jenkins and BuildConfigs in OpenShift - we tend to call them apps in fabric8, iPaaS and MBaaS ;)

**Comment by jstrachan** [comment]
a build may not have any CD; may not have any CI - could just be a build - so not totally sure of a better prefix really ;)

**Comment by jstrachan** [comment]
another word than `import` could be `share` - as the idea is to share the code/build with folks on the cluster?
