### ISSUE TITLE
mvn clean install fabric8:run can result in docker build running twice

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#393]
I've things like this do 2 builds (which can take a long time)

```
mvn clean install fabric8:run
```

I wonder if `fabric8:build` should check if its been invoked already and not rerun itself?

**Comment by rhuss** [comment]
Thats because its bound to execution phase which is called by `install` and `fabric8:run`. In fact, I though that `fabric8:run` implies `install` (so running certain goals seems to be natural).

I wouldn't introduce logic to circumvent certain goals to run but do nothing. Instead I'd prefer to get our lifecycles right. Its already complex enough.

**Comment by jstrachan** [comment]
I guess spring-boot:run just invokes the [test-compile goal](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-tools/spring-boot-maven-plugin/src/main/java/org/springframework/boot/maven/RunMojo.java#L40)

I wonder if we should avoid the forking of Install - making folks have to type:
```
mvn install fabric8:run
```
Was just wondering if we could make the forking of the install goal conditional on the install goal being already invoked or not to avoid the double-invoke issue

**Comment by davsclaus** [comment]
Yes would be good to invoke the 2x as it will also speedup the build process. I think many end users would be hit by this. They just want to run as few maven goals and have it just work (tm)

**Comment by rhuss** [comment]
I don't think this can be easily fixed and we are currently on the way to make goals independent and do not look up whether they are called together with other goals.

As I suppose that's an intrinsic Maven issue, I'm going to close this.
