### ISSUE TITLE
Icon handling

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#4]
The icon handling via annotations needs to be readded in a dedicated enricher, enabled by default.

**Comment by jstrachan** [comment]
FWIW its processing any icon files in `src/main/fabric8/icon.*` just fine now. It might be nice if there's no icon to default them based on if its spring boot / WF Swarm / Karaf / Tomcat et al?

**Comment by jstrachan** [comment]
FWIW we now auto-detect funktion, camel, spring-boot, wildfly-swarm, vertx etc
