### ISSUE TITLE
lets default services to use port 80 for things like 8080/9090 if its not already used

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#404]
as it results in nicer URLs for using route / ingress

**Comment by jimmidyson** [comment]
> as it results in nicer URLs for using route / ingress

This shouldn't effect routes/ingress, i.e. external URLs, should it? The service port should be hidden from external URLs & should be handled by the router/ingress controller shouldn't it?

**Comment by jstrachan** [comment]
if the service port is 8080, then folks will have to use http://foo.bar:8080/ when using a Route right?

**Comment by jimmidyson** [comment]
No. The router/ingress ports are defined in the router config, not in the route/ingress objects itself. External ports are mapped to service port.

e.g. in OpenShift, the Router only binds to ports 80/443 (by default anyway - a good default that most people won't/shouldn't change). The route host would be `foo.bar`. The service name would be `foo`. The Router will route traffic on `http://foo.bar` (port 80) to `foo` service at whatever port the service is listening on. This is the same for service -> pod ports.

**Comment by jstrachan** [comment]
@jimmidyson at least this fix will let folks access services directly via `http://foo/` rather than having to use `http://foo:8080/` when using internal services

**Comment by jimmidyson** [comment]
Yeah I prefer it! Just wanted to point out that it's not a prerequisite for nice route URLs really.
