### ISSUE TITLE
Describe what fabric8:setup goal is doing

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#438]
The existing doc about the goal fabric8:setup is poor to explain what this goal is doing and also the sentence is incorrect `It can be used to set up afresh this plugin`

"3.1. fabric8:setup
This goal is for setting up maven projects to use f8-m-p. It can be used to set up afresh this plugin in the pom.xml or to update an existing configuration."
- [x] The text should be corrected
- [x] Actions performed by the plugin should be described

**Comment by rhuss** [comment]
PRs are highly welcome, especially on documentation.

**Comment by cmoulliard** [comment]
#441

**Comment by rohanKanojia** [comment]
fabric8:setup goal was dropped in #1313
