### ISSUE TITLE
cluster-goal doesn't exist with 3.1.0.redhat-000033

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-maven-plugin#442]
The doc mentions (https://maven.fabric8.io/#fabric8:setup) to use this f-m-p version (mvn io.fabric8:fabric8-maven-plugin:3.1.0.redhat-000033:setup) but unfortunately, the goal cluster-start doesn't exist.

```
mvn fabric8:cluster-start -Dfabric8.cluster.kind=openshift

[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'cluster-start' in plugin io.fabric8:fabric8-maven-plugin:3.1.0.redhat-000033 among available goals build, debug, deploy, distro, help, import, log, push, resource, resource-apply, run, setup, start, stop, undeploy, watch -> [Help 1]
[ERROR] 
```

**Comment by rhuss** [comment]
Please try the latest version `3.1.55` since these goals were introduced quite lately.

**Comment by cmoulliard** [comment]
I accept to close the issue if the doc is updated too.
