### ISSUE TITLE
lets add wildflyswarm swagger annotations if we detect it

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#449]
see:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/service-discovery.md

would be good to do the same for spring boot + swagger too really

**Comment by davsclaus** [comment]
A bit further down the road, maybe detect Camel Rest-DSL that has swagger doc support, and generate that kind of annotation for those as well.

**Comment by jstrachan** [comment]
great idea! given, say, spring boot - is there a canonical URL that it gets exposed at?

**Comment by davsclaus** [comment]
No as the end user configures what the url should be, but we could maybe add a sensitible default url, like /api-doc/swagger.json or something.

But I have also though of a Camel Maven Plugin that can validate your source code for Camel mistakes and at the same time also generate metadata about your app, such as swagger doc endpoints, Camel route endpoints and so on. So its maybe a bit further down the road if its just automatic detect and generated.

**Comment by rhuss** [comment]
@KurtStam has implemented this recently via #1402
