### ISSUE TITLE
repurpose this blog post content as a 'quickstart' section in the docs?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#455]
https://blog.fabric8.io/a-busy-java-developers-guide-to-developing-microservices-on-kubernetes-and-docker-98b7b9816fdf#.aerjlhhbd

as it kinda shows how to use the plugin from a java developers perspective who may know an app server or something etc.

**Comment by rohanKanojia** [comment]
@rhuss : We do need to update our README with a new blog, as per left Mojos or maybe use https://asciinema.org/ for showcasing a standard Java developer workflow using fmp.

**Comment by rhuss** [comment]
@rohanKanojia agreed, I opened #1409 to track the README update, so lets close this one for now.
