### ISSUE TITLE
Add labels from label-schema.org to the generators

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#456]
microbadger looks cool 
https://microbadger.com/

and has a set of [canonical docker labels](https://microbadger.com/labels) we should automatically add into our docker images as part of a build

**Comment by jstrachan** [comment]
doh raised it here too:
https://github.com/fabric8io/docker-maven-plugin/issues/492

but at the fabric8 layer we know a bit more about the image already I guess and can reuse metadata from the kubernetes annotations etc

**Comment by jstrachan** [comment]
e.g. we already have lots of the git URL / tags / jenkins build stuff as annotations in the yaml

**Comment by rhuss** [comment]
We should add the "standard"  labels fromhttp://label-schema.org/rc1/ and add it via the generator for all the information we find.

**Comment by dev-gaur** [comment]
Apparently, S2I doesn't allow to override images labels.
```s2i build . centos/ruby-22-centos7 hello-world-app```

Though, s2i images do have schema labels of their own, these are the labels in the fabric8/s2i-java image.

![image](https://user-images.githubusercontent.com/7551036/54116879-b39e2a80-4415-11e9-84e8-59ebaa1306a5.png)

So, I think I'll only append the schema labels for Kubernetes mode.
