### ISSUE TITLE
cluster-start fails on windows

### ISSUE THREAD

**Issue by pax95** [fabric8io/fabric8-maven-plugin#457]
mvn fabric8:cluster-start

fails on windows with
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.56:cluster-start (default-cli) on project demo: Failed to open URL: https://github.com/fabric8io/gofabric8/releases/download/v0.4.73/gofabric8-windows-amd64. java.io.FileNotFoundException: https://github.com/fabric8io/gofabric8/releases/download/v0.4.73/gofabric8-windows-amd64

Windows details:
OS-navn Microsoft Windows 7 Enterprise  
Version 6.1.7601 Service Pack 1 Build 7601  
Systemproducent LENOVO  
Systemmodel 20EGS0U600  
Systemtype  x64-based PC  
Processor   Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz, 2901 Mhz, 4 Kerne(r), 8 Logisk(e) processor(er)

I know windows 7 should not be able to run kubernetes due to missing virtualization. This should only be possible if you run windows 10 afaik. But the above error is not related to this.

**Comment by jstrachan** [comment]
are you behind a HTTP proxy by any chance?

**Comment by jstrachan** [comment]
doh! the URL is wrong: https://github.com/fabric8io/gofabric8/releases/download/v0.4.73/gofabric8-windows-amd64.exe

lemme fix that ASAP!

**Comment by jstrachan** [comment]
looks like this was a regression when we modified the gofabric8 packaging to a direct binary rather than a tarball - whoops! Should have 3.1.58 of the plugin available to test in 30 mins...

**Comment by pax95** [comment]
Will give it a go when I see the release

**Comment by jstrachan** [comment]
thanks! almost there - will comment when its in mvn central... :)

**Comment by jstrachan** [comment]
its there in maven central now! http://central.maven.org/maven2/io/fabric8/fabric8-maven-plugin/3.1.58/ hopefully that works better. We're just about to try test it here too...

**Comment by jstrachan** [comment]
a horrid workaround for now is to manually [download the gofabric8 binary](https://github.com/fabric8io/gofabric8/releases) and put it onto your PATH but I was hoping we could automate all that stuff!

**Comment by jstrachan** [comment]
the maven plugin will reuse the `gofabric8` binary found on the PATH if its there already btw

**Comment by jstrachan** [comment]
the fix might take a little longer it seems; some windows boxes don't let you download a .exe it seems :(

**Comment by pax95** [comment]
@jstrachan Sure I'll give at go when I get my hands on a windows 7 box at work monday, and thanks !

**Comment by pax95** [comment]
Minikube is downloaded ok, but kubectl is downloaded without exe extension so activation fails.

> mvn fabric8:cluster-start                                                                                                    
[INFO] Scanning for projects...                                                                                                
[INFO]                                                                                                                         
[INFO] ------------------------------------------------------------------------                                                
[INFO] Building demo 0.0.1-SNAPSHOT                                                                                            
[INFO] ------------------------------------------------------------------------                                                
[INFO]                                                                                                                         
[INFO] --- fabric8-maven-plugin:3.1.79:cluster-start (default-cli) @ demo ---                                                  
[INFO] F8: Found c:\users\pras\.fabric8\bin\gofabric8.exe                                                                      
[INFO] F8: Running c:\users\pras\.fabric8\bin\gofabric8.exe version --batch                                                    
[INFO] F8:gofabric8 gofabric8, version 0.4.95 (branch: 'master', revision: '0be321b')                                          
[INFO] F8:gofabric8   build date:       '20161022-18:06:09'                                                                    
[INFO] F8:gofabric8   go version:       '1.7.1'                                                                                
[INFO] F8: Running c:\users\pras\.fabric8\bin\gofabric8.exe start --console --batch                                            
[INFO] F8:gofabric8 minikube.exe is already available on your PATH                                                             
[INFO] F8:gofabric8 Downloading https://storage.googleapis.com/kubernetes-release/release/v1.2.7/bin/windows/amd64/kubectl.exe.
..                                                                                                                             
[INFO] F8:gofabric8 Downloaded C:\.fabric8\bin\kubectl                                                                         
[INFO] F8:gofabric8 using the executable C:\.fabric8\bin\minikube.exe                                                          
[INFO] F8:gofabric8 minikube.exe already running                                                                               
[INFO] F8:gofabric8 using the executable C:\.fabric8\bin\kubectl                                                               
[INFO] F8:gofabric8 Unable to start exec: "C:\\.fabric8\\bin\\kubectl": file does not existCannot connect to api server, retrying...                                                                                                                          
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...                                                                  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...

**Comment by jstrachan** [comment]
@pax95 apologies! That broke in a recent refactoring. I've just tested it here and it works again. Could you delete `~/.fabric8/bin/*` and try again please?

The current code assumes Hyper-V is installed BTW https://maven.fabric8.io/#prerequisites

You can also specify: `-Dfabric8.vm.driver=virtualbox` if you want to use virtualbox instead
https://maven.fabric8.io/#vm-drivers

**Comment by pax95** [comment]
@jstrachan That was better.
tried it with 
mvn fabric8:cluster-start -Dfabric8.vm.driver=virtualbox and it downloaded the binaries fine.

minishift virtualbox starts, but after that i get
[INFO] F8:gofabric8 Kubectl is now configured to use the cluster.  
[INFO] F8:gofabric8 Cannot connect to api server, retrying...      
[INFO] F8:gofabric8 Cannot connect to api server, retrying...      
[INFO] F8:gofabric8 Cannot connect to api server, retrying...      
[INFO] F8:gofabric8 Cannot connect to api server, retrying...      

and gofabric8 seems not able to connect ??

I havnt tried to use Hyper-V. Thats a bit uphill on a windows7 machine. As most other things.

**Comment by jstrachan** [comment]
@pax95 getting closer! Did you install Virtualbox first before running the maven command?

**Comment by pax95** [comment]
@jstrachan yeah it was allready there

**Comment by pax95** [comment]
Got it working after all. I deleted the .minikube folder and virtualbox image, and ran
mvn fabric8:cluster-start -Dfabric8.vm.driver=virtualbox

Got an error while renaming tmp iso name. See below.

When i renamed the tmp iso to minikube-0.7.iso the command completed. Fabric8 templates+console downloaded and worked.

[INFO] F8:gofabric8 running: C:\.fabric8\bin\minikube.exe start --vm-driver=virtualbox --memory=4096 --cpus=1                  
[INFO] F8:gofabric8 Starting local Kubernetes cluster...                                                                       
[ERROR] F8:gofabric8 E1024 12:59:32.172686    8112 start.go:90] Error starting host: Error attempting to cache minikube iso fro
m url: Error copying temp iso file to destination: rename C:\.minikube\cache\iso\.tmp-minikube-0.7.iso332480235 C:\.minikube\ca
che\iso\minikube-0.7.iso: The process cannot access the file because it is being used by another process.. Retrying.           
[INFO] F8:gofabric8 ================================================================================                           
[ERROR] F8:gofabric8 E1024 12:59:32.173686    8112 start.go:96] Error starting host:  Error attempting to cache minikube iso fr
om url: Error copying temp iso file to destination: rename C:\.minikube\cache\iso\.tmp-minikube-0.7.iso332480235 C:\.minikube\c
ache\iso\minikube-0.7.iso: The process cannot access the file because it is being used by another process.                     
[INFO] F8:gofabric8 An error has occurred. Would you like to opt in to sending anonymized crash                                
[INFO] F8:gofabric8 information to minikube to help prevent future errors?                                                     
[INFO] F8:gofabric8 To opt out of these messages, run the command:                                                             
[INFO] F8:gofabric8     minikube config set WantReportErrorPrompt false                                                        
[INFO] F8:gofabric8 ================================================================================                           
[INFO] F8:gofabric8 Unable to start exit status 1Cannot connect to api server, retrying...                                     
[INFO] F8:gofabric8 Cannot connect to api server, retrying...

**Comment by daniExChay** [comment]
**Cannot connect to api server on Win 7**
Cmd:
gofabric8 start --vm-driver=virtualbox
minikube.exe is already available on your PATH
kubectl.exe is already available on your PATH
Downloading https://github.com/fabric8io/funktion-operator/releases/download/v1.0.10/funktion-operator-windows-amd64.exe
...
Downloaded C:\Users\c16963a\.fabric8\bin\funktion
using the executable minikube.exe
running: minikube.exe start --vm-driver=virtualbox --memory=6144 --cpus=1 --disk-size=50g
Starting local Kubernetes cluster...
Starting VM...
Downloading Minikube ISO
 89.26 MB / 89.26 MB [==============================================] 100.00% 0s
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
Cannot connect to api server, retrying...

**Comment by daniExChay** [comment]
MY WORKAROUND!!!
My Cisco AnyConnect VPN was killing my local Kubernetes cluster communication.
Turning VPN off allowed me to follow the instructions here to get local fabric8 going:
https://blog.fabric8.io/a-busy-java-developers-guide-to-developing-microservices-on-kubernetes-and-docker-98b7b9816fdf

It would be nice to have my kubernetes and my VPN too!

**Comment by jasclarke24** [comment]
You alluded to above an issue related to cluster-start behind a proxy. I am on Windows 10 behind a proxy and I am failing to download the VERSION of goFabric8

Failed to load version from https://raw.githubusercontent.com/fabric8io/gofabric8/master/version/VERSION. java.net.ConnectException: Connection timed out: connect

**Comment by rohanKanojia** [comment]
cluster-start is not supported anymore, so closing this.
