### ISSUE TITLE
for folks not using yaml files we should provide a configuration option on the maven plugin to specify if Deployment/DeploymentConfig/ReplicaSet/ReplicationController should be generated

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#46]
we should default to Deployment OOTB I would think really as its the k8s standard and has rolling upgrades baked in etc

**Comment by rhuss** [comment]
'dont know much about `Deployment` yet, but I agree that we should default to K8s and allow OpenShift extension via configuration. The idea was a global 'mode' which by default it `kubernetes` but can be set to `openshift`, too, in which case the openshift extension like BuildConfigs and DeploymentConfigs are used. Also the build itself will then be different (not building directly but pushing a docker.tar to openshift with a buildconfig).

Can we agree on that we already support features marked as `v1beta1` in 1.2 (like `Deployment`, `ReplicaSet` or `Ingress`) as defaults in f-m-p (setting this as the lower bound for our k8s requirement) ?

**Comment by jstrachan** [comment]
`Deployment` is kind like a `ReplicaSet` from a developer perspective; it just has the extra rolling upgrade configuration. Every time you change a Deployment it makes a new ReplicaSet and does rolling upgrades (so you can roll back too etc).

I'd like the OOTB default to use Deployment really; unless folks configure it differently. 

In terms of kubernetes versus openshift; from an Microservice developer it'd be nice if the app could be deployed on any platform really; so maybe we should generate a kubernetes.yml (using Deployment) and an openshift.yml (using DeploymentConfig?) maybe? Not sure if/when OpenShift will support Deployment. The openshift.yml could include extra openshift-specific resources too; like OAuthClient, RoleBinding (there could be others too - maybe a custom Route?)

**Comment by jstrachan** [comment]
lets try using Deployment by default and check it works on k8s and openshift? seems openshift currently supports Deployments - its worth a try to start with.

Though I do also think we'll need the option of an openshift.yml too for a place to put all the kubernetes + openshift specific resources (as we don't wanna put openshift specific stuff into kubernetes.yml)

**Comment by rhuss** [comment]
Beside possible differences for `fabric8:resources`, we also need to adapt the `fabric8:build` process for the openshift mode to don't build against a Docker daemon but against OpenShift (with all the `BuildConfig` et al beauty :). See also #12  

I completely agree which should settle fully on `Deployment` and then see what breaks and what not.
