### ISSUE TITLE
fmp:deploy - Problems with SNAPSHOT and timestamped images

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#467]
The fmp:run works fine and it startup your project.

But its the fmp:deploy that has problems.

1. It does not build the image first, so if you run fmp:deploy the first time, you get image download error in k8s as there is no image
2. If you have previously done a fmp:run and then cltr + c, and now want to deploy it instead, and run mvn fabric:deploy, then  which cannot download the image.
  ( the pod has image: 'foo/helloswarm:snapshot-161001-101723-0954')
But the images in the repo are:
```
foo/helloswarm                                        latest                        1912c26b9720        4 minutes ago       200.9 MB
foo/helloswarm                                        snapshot-161001-101528-0680   1912c26b9720        4 minutes ago       200.9 MB
foo/helloswarm                                        snapshot-161001-101438-0628   4266a8e83f44        5 minutes ago       200.9 MB
foo/helloswarm                                        snapshot-161001-101031-0691   5b8fddf92be9        9 minutes ago       200.9 MB
foo/helloswarm                                        snapshot-161001-100521-0516   b5be4ab5cb71        14 minutes ago      200.9 MB
```

**Comment by davsclaus** [comment]
In general there is a bit of "problems" with the ease of use with fmp:run / deploy etc and using SNAPSHOT maven versions. However its common to use SNAPSHOT and certainly if you create new projects from start.spring.io, maven archetypes, or the fabric8 project-new etc.

We are almost there, but it needs a little more hardening to get this timestamp problems.

Also we should update the documentation to be exact what the mvn goals you should run are, as sometimes you may run: mvn clean install fabric8:deploy and other times just mvn fabric:run etc.

**Comment by davsclaus** [comment]
I tried again, and deleted all the foo/helloswarm docker images from the docker registry, and undeployed it from k8s so it was clean and ran

1. mvn clean install
2. mvn fabric8:deploy

And I get image download problem.

I captured the output in a gist
https://gist.github.com/davsclaus/8c5867aadc65804dbb958d6584fd27a4

**Comment by davsclaus** [comment]
@jstrachan sorry to bother you on a weekend, but I think we got a bit of trouble for next weeks demo.

**Comment by jstrachan** [comment]
agreed!

I'm wondering if 'run' and 'deploy' should work the same & always build the image.

After Ctrl-C you can use 'start' to avoid doing a full build again - or use the mvn property on 'run' to not stop on Ctrl-C. Or stick to 'deploy & log'?

I wonder if start & deploy should default to tailing the log too? I guess folks can just add a 'log' goal though?

**Comment by davsclaus** [comment]
Yeah I think it would be less confusing if deploy and run are the same, just that run tails the log by default.

**Comment by jstrachan** [comment]
yeah sounds good - fixed that; will cut a release shortly
