### ISSUE TITLE
f-m-p has a different pull request process to all other fabric8 projects

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-maven-plugin#475]
currently the f-m-p release pipeline is stuck because a PR request was merged but still had pending actions.  

<img width="559" alt="screen shot 2016-10-01 at 21 17 28" src="https://cloud.githubusercontent.com/assets/1457180/19016797/9156d948-881c-11e6-8b96-e84687f10bdb.png">

cause..

<img width="787" alt="screen shot 2016-10-01 at 21 15 06" src="https://cloud.githubusercontent.com/assets/1457180/19016784/41916ef0-881c-11e6-8113-16fbd9ddf854.png">

I added a comment of lgtm and the pipeline finally finished.

f-m-p is one of many fabric8 repos, if a change to CI / pull request or pipeline processes are needed then that's fine but we need to first agree and second apply that to all repos (many under fabric8io and ~40 under fabric8-quickstarts orgs), also pipeline scripts will need to be changed.

Changing things is totally fine but as long as we do that for every project in a coordinated way.  

This needs to happen now if f-m-p still wants to include the lgtm comment or revert to carry on using the existing pipelines.

**Comment by jimmidyson** [comment]
This also highlights a bug in pipeline scripts BTW. Should be enough that the PR is merged shouldn't it? Looking at the image looks like it was already merged somehow but waiting for status updates which are irrelevant after PR is merged.

**Comment by rhuss** [comment]
I also remarked today, that although a version update PR has been merged, the pipeline still reports a status of _pending_. However eventually it detects it and continues (maybe after 5 mins or so). 

Guess its more an issue of the pipeline, but since its working, I'm going to close this issue for now.
