### ISSUE TITLE
Usage of Java 8 features

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#480]
For the time being, our minimal Java requirement is Java 7, but `DebugMojo` uses [Java 8 features](https://github.com/rhuss/fabric8-maven-plugin/blob/b73ab086f14639258ac92a84138d86c2f40c54bd/plugin/src/main/java/io/fabric8/maven/plugin/DebugMojo.java#L233-L234)

**Comment by davsclaus** [comment]
Yeah its fine IMHO to be Java8+

**Comment by rhuss** [comment]
@davsclaus remember when we had support Maven 3.0.5 which is barely Java 7 ? 99% of our code is Java 7 still for some reason: A tool which is used in thousand of different environments should be as conservative as possible w.r.t to JDK requirements (for d-m-p I had even a request to support [Java 6](https://github.com/fabric8io/docker-maven-plugin/issues/396)) 

So I don't want to give that up only for having this single Java 8 code snippet in the code base. The rest is still perfectly working in Java 7. If we would writing our own app I'm all for using Java 8 (and in fact I really looking forward to use finally lambdas ;-)

@davsclaus could I convince you to stick to Java 7 for such a developer tool ? :)

**Comment by davsclaus** [comment]
Crap button next to comment. 

Its a balance. If the code uses too old Java then people stop contribute as they want to work with newer Java, especially Java 8.

@rhuss you are free to change the code in the debug so you can use java 7. You work the most on these plugins. I am going back to my beloved Camel instead.

**Comment by rhuss** [comment]
Camel 'already' moved to Java 8, right ? Good animal ....

Yeah, you are right, getting talents is harder with rusty Java 7. But don't underestimate the happiness of people when they final find something running in their ivory enterprisy towers.

Lets keep Java 8 for the next major version of f-m-p, which for sure will come ;)

**Comment by rhuss** [comment]
We already moved to Java 8
