### ISSUE TITLE
cluster-start fails on linux (fedora)

### ISSUE THREAD

**Issue by sterpico** [fabric8io/fabric8-maven-plugin#482]
Having the following plugin configuration:
`<plugin>
  <groupId>io.fabric8</groupId>
	<artifactId>fabric8-maven-plugin</artifactId>
	<version>3.1.58</version>
	<executions>
	<execution>
	 <id>fmp</id>
		<goals>
			<goal>resource</goal>
			<goal>helm</goal>
			<goal>build</goal>
		</goals>
	</execution>
	</executions>
</plugin>`
and issuing mvn fabric8:cluster-start, generates the following error:
 ...
[INFO] --- fabric8-maven-plugin:3.1.58:cluster-start (default-cli) @ kubernetes-fabric8 ---
[INFO] F8> Downloading version 0.4.77 of gofabric8 to /home/sterpico/.fabric8/bin/gofabric8 
...
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.58:cluster-start (default-cli) on project kubernetes-fabric8:
Failed to open URL: https://github.com/fabric8io/gofabric8/releases/download/v0.4.77/gofabric8-linux-amd64. java.io.FileNotFoundException:
https://github.com/fabric8io/gofabric8/releases/download/v0.4.77/gofabric8-linux-amd64 -> [Help 1]

I manually installed gofabric8 version 0.4.76 (latest at the time of writing), however the plugin always attempts to resolve this version instead. The issue could be similar to the windows one, however is there a way to instruct it to work with this gofabric8 version?

**Comment by anthonykulis** [comment]
following. i get the same issue on mac

**Comment by sterpico** [comment]
By browsing through the source code, the call to https://raw.githubusercontent.com/fabric8io/gofabric8/master/version/VERSION returns 0.4.77 instead of 0.4.76, so the plugin attempts to resolve that version instead.

**Comment by diesim** [comment]
Same issue all around no matter OS. This is also the same as the windows one posted earlier.

**Comment by jimmidyson** [comment]
Looks like a borked release - will fix up soon.

**Comment by jimmidyson** [comment]
Didn't know that was how the version was discovered... We'll change that
soon.

**Comment by jimmidyson** [comment]
This should be fixed now that 0.4.77 of gofabric8 is released. I'll open a new issue to discuss how the plugin is doing the latest version check.
