### ISSUE TITLE
Goals revisited

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#501]
To cover all use cases we should have at least an `ApplyMojo`, too.

Then the possible workflows are (if `fabric8:resource` and `fabric8:build` are bound to executions):

* **install** --> `fabric8:resource` + `fabric8:build`
* **fabric8:deploy** --> `fabric8:resource` + `fabric8:build` + `fabric8:apply`
* **fabric8:run** --> `fabric8:resource` + `fabric8:build` + `fabric8:apply` + tail on log
* **fabric8:resource** --> `fabric8:resource`
* **fabric8:build** --> `fabric8:build`
* **fabric8:resource-apply** --> `fabric8:resource` + `fabric8:apply`
* NEW: **fabric8:apply** --> `fabric8:apply`

Actually I even would strongly recommend  to combine **fabric8:deploy** and **fabric8:run** to  a single goal since they are _so_ similar that e.g. tailing could be switched on/off via a simple flag (or permanently via a config option). 

My suggestion would be (going back to the old `fabric8:deploy` behaviour):

* **fabric8:deploy** (or _fabric8:apply_) --> deploys resources only (no fork)
* **fabric8:resource-deploy** (or _fabric8:resource-apply_) --> recreates resources and deploys resources
* **fabric8:run** --> forks, so runs resource, build, deploy and tails, where the tail can be switched off (or on).
* **fabric8:resource** and **fabric8:build** would remain the same

hatever we could call it "deploy" or "apply" (thats not so important). It would also match nicely to the d-m-p workflow where there is a `mvn docker:run -Ddocker.follow` (also permanently configurable, also via setting). At least we wouldn't need both "deploy" and "apply" as goal names which adds to quite some confusion. 

It's also important to think about what happens when `resource` and `build` are **not** bound to executions to their default phases in the pom.xml namely that  `fabric8:run` (and the currently forked `fabric8:deploy`) will only deploy the current descriptors.

**Comment by rhuss** [comment]
@fabric8io/core any opinions on this ?

**Comment by davsclaus** [comment]
After giving demos and whatnot I really like that `deploy` and `run` are separate goals. Using flags with maven is soooo cumbersome and you cannot remember what the names of the options are and there is no easy way, tab completion etc.

Remember run / deploy are the goals that new users to fabric8 are to use, and they should have it very easy. 

For example spring-boot - jetty - swarm - et all uses run to start the app in the foreground.

**Comment by jimmidyson** [comment]
Agree that flags on mvn goals are awful - it's a shame it's not like any other normal cmd line tool...

**Comment by rhuss** [comment]
Thanks for the feedback. So we all agree that `fabric8:run` and `fabric8:deploy` should be separate goals and flags should be avoided.

My question is now, whether `fabric8:deploy` should fork the lifecycle, which means that `fabric8:deploy` will create resources, run an image build and applies the resource descriptors to a running cluster. `fabric:resource-deploy` does the same but without build. 

My suggestion above to make `fabric8:deploy` only deploy the resource descriptors. That way its on the same footprint as `resource` and `build` and can be bound to executions (you cant bind a forked goal to an execution because then many goals run twice). The alternative is add a new goal 'apply' for this (i.e. deploy without fork). But then, who can tell the difference between 'apply' and 'deploy' by heart ?

And btw, we could rename `deploy` also back to `apply` (seems a better fit).

**Comment by rhuss** [comment]
My worklow which I used lately quite often was, todo a `fabric8:resource`, have a check of the created files, and then want to apply these resources without recreating. This is currently not possible. Don't know whether this is a valid use case, though.

**Comment by jstrachan** [comment]
@rhuss initially I made `fabric8:deploy` as you suggest above; but found it confusing and ended up making `deploy` and `run` work the same really (just like deploy + run do with other maven plugins - like tomcat/jetty/karaf/wildfly/spring-boot). If we want a goal that doesn't build jars or docker images and just deploys the resources only then I'd prefer to make that less common - like `resource-deploy` or something. Folks can also use `kubectl apply -f` too after a `resource` goal

**Comment by rhuss** [comment]
For me its about only applying the resource without recreating them and tbh `kubectl` is as a solution as `minishift start && gofabric8 deploy` would be for `cluster-start`. Obviously the advantage of a `fabric8:apply` is that it know *what* to apply. With `kubectl` you would have to write (and **remember** !) `kubectl -f target/classes/META-INF/fabric8/kubernetes.yml`. Quite a mouthful compared to a `mvn fabric8:deploy`

**Comment by rhuss** [comment]
And as you said `deploy` and `run` work the same, but why do we need both then doing the same. Its not about the amount of goals (already lost here ;-), its about the `deploy` _slot_ which I would like to have nicely aligned with `resource` and `build`.  

Or other: why can't deploy a bit different by not forking the lifecycle (you still have run, you still can run 'resource-deploy', you still can bind `deploy` to an execution then so a `mvn deploy` can do all of `resource`, `build`, `deploy`.

Regardless what we decide, I really would want to a goal which deploys and can be bound to executions like `resource` and `build`. Its so much easier to explain this in the docs. In the worst case I would call it `apply` (but then we have the confusion between `apply` and `deploy`).

**Comment by jstrachan** [comment]
we need both `deploy` and `run` as thats the common experience of using tomcat/jetty/karaf/wildfly; `deploy` is an async chuck it into the app server and return immediately; `run` is run it right now in the current shell, see the log and `Ctrl-C` stop it. Yes they both do common pieces under the covers but to a developer they are very different operations.

I agree its handy being able to just re-create resources without building anything else and being able to apply them would be good too; more for the case where you're tweaking the resources. I like combining with the `resource` goal too to make it less things to remember. So how about `resource` and `resource-apply` (which would regenerate the resources and apply them without building/deploying images too)

**Comment by rhuss** [comment]
* Agreed with having two commands for sync and async start of an application (in the tomcat and jetyy world these are called `start` and `run`).

* we already have `resource-apply`, but it doesn't solve
  - that I can't bind the apply step to a lifecycle in `<executions>`
  - that I can't apply resources without recreating them (that was my initial use case)

If we can't rename the current `deploy` to e.g. `start` (because this is actually for rescaling already existing entities) to free the name for the use case above, I then would opt for introducing a new goal `apply` with the characteristics described above (bindable & isolated). (if so I question that we still need `resource-apply`).

But maybe we can rename `start` --> `up` and `stop` --> `down` (would also map nicely to the action it performs, scaling up and down).

So:

* `start` -> `up`
* `stop` -> `down`
* `deploy` -> `start`
* `undeploy` -> `stop` (tbh don't know whether we have an `undeploy` yet)
* `run` -> `run`
* new `deploy` which does not fork lifecycle (alternative: back to `apply` ?)

That would be nicely symmetric and maps the appserver paradigms with start & run, and `up` + `down` scaling.

**Comment by jstrachan** [comment]
BTW I want our goal names to be familiar to java devs who've used maven tooling for tomcat / jetty / karaf / wildfly. Thats why we went with `deploy`,`undeploy` and  `run` which are common already; they mostly have `start` too though its either`stop` or `shutdown` it seems.

Am cool with `apply` btw - we started there in the beginning back in f-m-p 1.x and 2.x as thats what `kubectl` uses and its kinda unique so am happy with that goal

**Comment by rhuss** [comment]
@jstrachan there is no **deploy** and **undeploy** for Tomcat, or did I miss something ? All what is there is a **start** and **stop** for async operation and **run** for sync. 

My suggestion above would exactly map nicely on these Tomcat terms, in order to reach the goal of familiarity with known tasks.

**Comment by jstrachan** [comment]
[tomcat7](http://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/plugin-info.html): deploy, undeploy, run, shutdown
[tomee](http://tomee.apache.org/tomee-maven-plugin.html): deploy, undeploy, run, start, stop
[wildfly](https://docs.jboss.org/wildfly/plugins/maven/latest/): deploy, undeploy, run, start, shutdown
jetty: deploy-war, run, start, stop

**Comment by rhuss** [comment]
Ok, I was more about `catalina.sh`:

```
Usage: catalina.sh ( commands ... )
commands:
  debug             Start Catalina in a debugger
  debug -security   Debug Catalina with a security manager
  jpda start        Start Catalina under JPDA debugger
  run               Start Catalina in the current window
  run -security     Start in the current window with security manager
  start             Start Catalina in a separate window
  start -security   Start in a separate window with security manager
  stop              Stop Catalina, waiting up to 5 seconds for the process to end
  stop n            Stop Catalina, waiting up to n seconds for the process to end
  stop -force       Stop Catalina, wait up to 5 seconds and then use kill -KILL if still running
  stop n -force     Stop Catalina, wait up to n seconds and then use kill -KILL if still running
  configtest        Run a basic syntax check on server.xml - check exit code for result
  version           What version of tomcat are you running?
Note: Waiting for the process to end and use of the -force option require that $CATALINA_PID is defined
```

**Comment by jstrachan** [comment]
starting or stopping an app server is kinda different - you usually don't use the same CLI to deploy things or run local builds of things; though it has run/start/stop at least. 

The maven plugins for developers to work with app servers are surprisingly consistent in their goals though - adding run/deploy/undeploy to the mix

**Comment by rhuss** [comment]
@jstrachan thanks for the clarification (and for bearing with me that long ;-), I think I got it now.

I think we had simply different metaphors for what the *app-server* really is in our context. We both already agreed that it is not the k8s / openshift cluster itself, but:

* your approach is that of a *virtual server*, which gets started and stopped with the lifecycle commands:
  - **start** & **stop** : start the virtual server by scaling up / down the resource objects which are already existant.
  - **run** : The same in the foreground but from scratch + including a fresh **deploy**
  - **deploy** and **undeploy** : Add / remove the application to / from this virtual server.

* mine is more that of *the application is the server*:
  - **start** & **stop** : Start the application & remove it from the cluster (like starting and stopping the server)
  - **run** : Start the application in the foreground (like starting the server in the foreground)
  - **deploy**  and **undeploy** are not really needed when using the *application is the server* metaphor, but would could have one like "pause" / "resume" for the scaling goals.
 
I hope it's fair to summarise that your approach mimics the classical Java EE server workflow by coming from the existing goals and mapping them to this 'virtual' server, mine is not so strict in the similarity but maybe easier to understand when not coming from a Java EE server background (because of less goals which maps better to the real *application lifecycle*).

Now that I understand the metaphor behind your approach I can live better with it (although I think its more elaborated than needed, but that's the price for this mapping to Java EE concepts).

Let's leave the goal as they are but let me introduce a new 'apply' goal with the characteristics I described.

**Comment by jstrachan** [comment]
FWIW in the traditional app server model; developers deploy/run their `app` into an `app server`; the developer doesn't much care if there's a single JVM running for all apps; or a cluster of them or if app server processes stop when there's no more apps to deploy or if the app server cluster runs individual JVMs per deployment unit or not. 

So the metaphor of deploying `apps` to the `app server` works pretty well for kubernetes too; its just the `app server` is kubernetes. In kubernetes for each `app` there's 0...N docker containers created - but thats implementation detail that the application developer doesn't need to worry about - just like if you deploy to an app server thats really a cluster of JVMs acting as a logical app server you don't worry too much about what JVMs are running under the covers; it looks like a logical `app server`.

I don't want to confuse or promote leaky abstractions of the new kubernetes awesomeness; but I think Java folks can view kubernetes as like an `app server` or to be more accurate an `app platform` that they deploy their apps to and it just works; it just so happens that each `app` maps to 0..N individual docker containers which are easier to scale and manage independently. 

Though we may as well stick with common habits, terminology and approaches if it helps folks get stuff done

**Comment by rhuss** [comment]
I think we are now on a good way to converge ;-)  

Still, I don't think that Kubernetes plays the `app server` role here as it's not Kubernetes which gets started or stopped with the `start` and `stop` goals but an "abstract server concept". But as I said I can live with it even when having a different opinion.

Let me add the new `apply` goal and I'll shut up. This fits also nicely into the row of our technical goals like `resource`, `build`, `push`. hopefully folks don't confuse it with `deploy`, thats my only concern left.

**Comment by jstrachan** [comment]
@rhuss they are different for sure but conceptually with an app server you deploy, say, a WAR with embedded manifests; with kubernetes you deploy a manifest which references 0..N docker images but I see them as conceptually very similar from 30,000 feet - but yeah - quite different too ;)
