### ISSUE TITLE
WebappGenerator incorrectly overrides WildFly image CMD

### ISSUE THREAD

**Issue by jamesnetherton** [fabric8io/fabric8-maven-plugin#502]
See [here](https://github.com/fabric8io/fabric8-maven-plugin/blob/366def2e2fee8729ca4b7490f98cbbd251f20e8c/generator/webapp/src/main/java/io/fabric8/maven/generator/webapp/handler/WildFlyAppSeverHandler.java#L53). This overrides the original WildFly image command which is:

`CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]`

The -b bit is crucial, else the container binds to the loopback address and no external requests ever get served.

Maybe `getCommand()` should return `null` for the WildFly case? I see no reason to be overriding the default command.

**Comment by rhuss** [comment]
Yeah, thinks its perfectly fine to use the default command. Only the deployment directory is different.

@kameshsampath wdyt ?

**Comment by kameshsampath** [comment]
I would prefer not to override the `-b` as part of the image build. I would prefer to leave it to the user during `run` as we might not know which ip user wants to bind as `0.0.0.0` is too open and user might have restrictions in using it

**Comment by rhuss** [comment]
Well when running in a container binding to localhost doesn't make much sense. I guess you almost always want to bind to the external interface of the container.

So the idea is to simply leave the default as it is from the base image (getCommand() return null) and if the user has a more restrictive setup then he can still override the `cmd` option.

**Comment by kameshsampath** [comment]
ok @rhuss lets do it as needed
