### ISSUE TITLE
fabric8:watch for WAR projects should default to `copy` mode and maybe use expanded WARs?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#510]
all servlet containers can watch the deployments folder and reload on the fly; so for WAR projects there's no need to do a full docker rebuild and rolling upgrade; we can just send the new WAR over via copying to the docker container.

Typically WARs can be kinda big though; easily 20-60Mb. Its kinda better to not have to re-send those 20-60Mb of dependencies for any change when dependencies rarely ever change.

So it'd be nice to be able to just rsync across changed file. Particularly in the use case of folks editing a HTML / CSS / JSP file; that should rsync super fast and let folk have nice fast reloading of all parts of a WAR; whether its content or java.

To make the reload faster, using expanded WAR layout would help with the faster rsyncing/copying - then if java code does change, the servlet container doesn't have to do the un-jar of the WAR

**Comment by rhuss** [comment]
good idea. btw, do you know of a good java rsync library ?

We would need to adapt our webapp base images and the assembly descriptor in the webapp-generator but that is not a big thing.

**Comment by jstrachan** [comment]
I don't know a good rsync library for java am afraid. TBH just copying files changed since last deploy/copy might be enough really (skinny JARs are not too big these days). There is the openshift rsync thingy isn't there? (but that might require using the oc binary maybe).

On the assembly descriptor; we could maybe have an expanded WAR flavour which we switch to by default for WARs in watch mode?

**Comment by jstrachan** [comment]
Incidentally, spring boot's devtools supports LiveReload too which is super cool for automatically reloading a browser while changing CSS/HTML - it lets the developer stay in their IDE and just see the output in the browser window (without changing window and hitting refresh after each change).

I wonder how hard it'd be to also enable livereload with a WAR; we may need a port forward or extra service for the LiveReload browser plugin to connect to the container

**Comment by rhuss** [comment]
yes, would require the oc binary which we actually do not need directly (only for doing logins). Using an external rsync also isnt easy e.g. for Windows users as they would need to install stuff. So plain copy makes more sense probably.

w.r.t assembly: Yes this would work, however we need to propagate (or even introduce) the operation mode ('watch' or 'dist') to the generators. No problem, as we do this for the platform mode, too.

**Comment by rhuss** [comment]
afaiu live reload goes the other way round: The app contacts the browser on a port (but could be wrong here)

If so, a poor man solution for live reload would be when the plugin itself contacts the browser for refresh (considering the plugin know the access URL) as I think it will not be easy for a container to reach out to the browser.

**Comment by jstrachan** [comment]
BTW I'm experimenting with the spring-boot flavour of watch also triggering a `deploy`; so that we can generate a slightly different container image (adding spring-boot-devtools jar, generating the remote token) so its a simple one command to start watching. We may want to start to do the same for WAR building; the `build` goal could detect if its being triggered in watch mode etc

**Comment by rhuss** [comment]
This kind of operational mode is coming soon. Spring boot watching is already implemented but broken. For WAR application watch we will need another solution (skinny wars).

Let's close this for now and keep it in memory as another great discussion about things which are all still valid.
