### ISSUE TITLE
Support for PetSet and DaemonSet deployment options

### ISSUE THREAD

**Issue by ucosty** [fabric8io/fabric8-maven-plugin#517]
I'm working on a project that requires the use of both Pet Sets and Daemon Sets for certain parts of the application. Trying to generate these using YAML fragments produces errors like the following

> resource failed: Unknown type 'daemonset' for file
> resource failed: Unknown type 'petset' for file

**Comment by rhuss** [comment]
Thanks, we will pick that up into the list of recognized types.

In the meantime you could name your fragments without type (e.g. `name.yml`) and set a 'kind: PetSet' within the file.

**Comment by ucosty** [comment]
Thanks for the speedy response, I had no idea the error was coming from the filename.

**Comment by ucosty** [comment]
I may have spoken too soon. Daemon sets seem to work properly, but the PetSet type is not liked at all.

> [ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.75:resource (default-cli) on project consul: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.75:resource failed: No resource type found for kind:PetSet
> [ERROR] at [Source: N/A; line: -1, column: -1]
> [ERROR] -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.75:resource (default-cli) on project consul: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.75:resource failed: No resource type found for kind:PetSet
>  at [Source: N/A; line: -1, column: -1]
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
> 	at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:334)
> 	at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:104)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.fabric8:fabric8-maven-plugin:3.1.75:resource failed: No resource type found for kind:PetSet
>  at [Source: N/A; line: -1, column: -1]
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
> 	... 10 more
> Caused by: java.lang.IllegalArgumentException: No resource type found for kind:PetSet
>  at [Source: N/A; line: -1, column: -1]
> 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3580)
> 	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3499)
> 	at io.fabric8.maven.core.util.KubernetesResourceUtil.getResource(KubernetesResourceUtil.java:142)
> 	at io.fabric8.maven.core.util.KubernetesResourceUtil.readResourceFragmentsFrom(KubernetesResourceUtil.java:115)
> 	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.readResourceFragments(ResourceMojo.java:565)
> 	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.generateAppResources(ResourceMojo.java:542)
> 	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.generateResources(ResourceMojo.java:496)
> 	at io.fabric8.maven.plugin.mojo.build.ResourceMojo.executeInternal(ResourceMojo.java:241)
> 	at io.fabric8.maven.plugin.mojo.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:77)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
> 	... 11 more
> Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for kind:PetSet
>  at [Source: N/A; line: -1, column: -1]
> 	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:261)
> 	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1313)
> 	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:55)
> 	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:31)
> 	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3575)
> 	... 20 more
>

**Comment by ucosty** [comment]
I'm quite close to having a pull request ready to implement this. I'll likely raise it in the next day or two. It just depends on getting the fabric8 project built against the latest version of the kubernetes-client project.

**Comment by rhuss** [comment]
Both DaemonSet and StatefulSet are supported in the latest f-m-p. See https://maven.fabric8.io/#custom-kind-filename-mapping for a list of all supported extensions.
