### ISSUE TITLE
WAR projects should default to ROOT.war to avoid context path

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#518]
if we are deploying a single WAR into tomcat/jetty/wildfly it would make sense to use it as a ROOT.war so there's not a fairly useless extra context path to remember/configure for the web app

**Comment by davsclaus** [comment]
Yeah the older fmp plugin used to do that. I saw this recently with a tomcat image for one of our war quickstarts

**Comment by davsclaus** [comment]
I even think the tomcat examples / management console et all was included

**Comment by rhuss** [comment]
This currently already works with the WebAppGenerator
