### ISSUE TITLE
/.fabric8/bin folder is empty

### ISSUE THREAD

**Issue by sebastienblanc** [fabric8io/fabric8-maven-plugin#538]
Hi,

When running `mvn fabric8:cluster-start` it seems downloading the f8 bin but then it fails, not sure what happens here : 

```
[INFO] Building bookservice 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.58:cluster-start (default-cli) @ bookservice ---
[INFO] F8> Downloading version 0.4.78 of gofabric8 to /home/sblanc/.fabric8/bin/gofabric8 ...
[INFO] gofabric8> gofabric8, version 0.4.78 (branch: 'master', revision: '4d06bce')
[INFO] gofabric8>   build date:       '20161010-05:00:05'
[INFO] gofabric8>   go version:       '1.7.1'
[INFO] F8> Downloaded gofabric8 version 0.4.78 platform: linux arch:amd64 on: Linux amd64 to: /home/sblanc/.fabric8/bin/gofabric8
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2016-10-12T09:22:20+02:00
[INFO] Final Memory: 20M/353M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.58:cluster-start (default-cli) on project bookservice: Failed to execute gofabric8 install --batch. java.io.IOException: Failed to execute process stdin for gofabric8 install --batch: java.io.IOException: Cannot run program "/home/sblanc/.fabric8/bin/gofabric8": error=2, No such file or directory -> [Help 1]
```

**Comment by rawlingsj** [comment]
Can you check if gofabric8 was in fact downloaded to `/home/sblanc/.fabric8/bin/gofabric8` and if it is try to run it directly?  I wonder if its not been`chmod +x `?

**Comment by rhuss** [comment]
It looks strange since from the log output it looks like `gofabric8` has been already run (see the version info).

**Comment by sebastienblanc** [comment]
No, the folder is empty but I would have expected an exception/error if the download would have failed.

**Comment by rhuss** [comment]
@sebastienblanc Do you have `gofabric8` somewhere in your path ? As it seems, gofabric8 was already called which produced this output:

```
[INFO] gofabric8> gofabric8, version 0.4.78 (branch: 'master', revision: '4d06bce')
[INFO] gofabric8>   build date:       '20161010-05:00:05'
[INFO] gofabric8>   go version:       '1.7.1'
```

**Comment by rhuss** [comment]
Just checked: `gofabric8` gets first downloaded into a temp directory (somewhere below `/tmp`), then its gets executed from there to get the version info. Next it gets [renamed or copied](https://github.com/rhuss/fabric8-maven-plugin/blob/4b89058a9347586cc37538568e16688e7aafcc1b/plugin/src/main/java/io/fabric8/maven/plugin/AbstractInstallMojo.java#L197-L205) to the directory in your home directory.

This seems to go wrong somehow, without error. I will try to reproduce it, and check why no error is thrown.

@sebastienblanc on which OS does this happen ?

**Comment by sebastienblanc** [comment]
I can indeed see all the fabric8 bin files in /tmp , my OS is Fedora 23.

**Comment by sebastienblanc** [comment]
Update : with `master` they file is copied (the rename fails indeed) but then the `destFile` is not set to executable, I did a PR for that https://github.com/fabric8io/fabric8-maven-plugin/pull/540

**Comment by davsclaus** [comment]
Assume it works with the PR thanks @sebastienblanc
