### ISSUE TITLE
avoiding duplicate kubernetes resource dependencies

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#542]
right now we use regular `<dependency>` relationships so that we can compose things together; e.g. `cd-pipeline` depends on `gogs`, `jenkins` etc.

However due to transitive dependencies, when the `DependencyEnricher` kicks in, it sees `cd-pipeline` (which contains gogs) and also `gog` so it ends up duplicating all the resources twice.

I wonder if we can help trim dependency trees; so when we create `cd-pipeline` jar its not really transitively dependent on `gogs` & `jenkins` etc.

Not 100% sure the ideal approach. We could use `provided` or `test` scope for these kinds of dependencies? Not totally sure which; either should hopefully limit the scope and reduce this issue.

**Comment by jimmidyson** [comment]
Wonder if we could just build a set of dependencies to remove dupes before we write out the aggregated manifests?

**Comment by jstrachan** [comment]
when we make an uberjar and you consume it, you don't also transitively also depend on all the parts that made the uberjar (as you'd get duplicates) - we make a new jar with no dependencies. 

I was hoping we could do the same kinda thing with how we do composition of kubernetes manifests - to avoid unnecessary duplicates. There's also the issue that by depending on, say, `cd-pipeline` in an Arquillian test you bring in all the maven dependency trees of all the stuff used to build those apps. It'd be nice to stop the transitive dependency trees for these `packages` - from a dependency management perspective, they are just stand alone jars with manifests inside.

I originally started hacking a merge goal; its just slightly scary just throwing stuff away when really its just dodgy mvn dependency trees making things look like there's duplicates. I was hoping we could define a 'build time dependency' to build a jar; then those dependencies disappear when its then used to build a different jar. e.g. if we have 2 Deployments called 'foo' - which one wins? 

Maybe the cleanest option is to just put the dependencies in the maven plugin; so that there's really no maven dependencies for `cd-pipeline` for example?

**Comment by jstrachan** [comment]
I'm thinking of adding the `<dependency>` elements inside the `fabric8-maven-plugin` then its much cleaner and avoids unnecessary transitive dependencies.

I'll add more warnings if we find duplicates as well.
