### ISSUE TITLE
fabric8:deploy after undeploy fails on OpenShift

### ISSUE THREAD

**Issue by abouchama** [fabric8io/fabric8-maven-plugin#545]
When i run fabric8:undeploy and deploy after on OpenShift it fails.

$ mvn fabric8:deploy
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Fabric8 :: Quickstarts :: Spring-Boot :: Camel XML 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> fabric8-maven-plugin:3.1.71:deploy (default-cli) > install @ camel-spring-boot >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ camel-spring-boot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.71:resource (default) @ camel-spring-boot ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using docker image name of namespace: devoxxma
[INFO] F8: spring-boot: Using fat jar packaging as the spring boot plugin is using `repackage` goal execution
[INFO] F8: Running generator spring-boot
[INFO] F8: Using resource templates from /home/aboucham/dev/workspace/camel-spring-boot/src/main/fabric8
2016-10-13 14:40:37 INFO  Version:30 - HV000001: Hibernate Validator 5.2.4.Final
[INFO] F8: fmp-service: Adding a default Service with ports [8080]
[INFO] F8: fabric8-expose: Adding Service label `expose:true` on service camel-spring-boot so that it is exposed by the exposecontroller microservice. To disable use the maven argument: `-Dfabric8.profile=internal-microservice`
[INFO] F8: f8-icon: Generated icon file /home/aboucham/dev/workspace/camel-spring-boot/target/fabric8/template-workdir/icon.null from icon reference: camel
[INFO] F8: f8-icon: Icon URL: data:text/plain;charset=UTF-8;base64,cm91dGVzLnhtbAo=
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ camel-spring-boot ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ camel-spring-boot ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/aboucham/dev/workspace/camel-spring-boot/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ camel-spring-boot ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ camel-spring-boot ---
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ camel-spring-boot ---
[INFO] Building jar: /home/aboucham/dev/workspace/camel-spring-boot/target/camel-spring-boot-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.4.1.RELEASE:repackage (default) @ camel-spring-boot ---
[INFO] 
[INFO] >>> fabric8-maven-plugin:3.1.71:build (default) > initialize @ camel-spring-boot >>>
[INFO] 
[INFO] <<< fabric8-maven-plugin:3.1.71:build (default) < initialize @ camel-spring-boot <<<
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.71:build (default) @ camel-spring-boot ---
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: spring-boot: Using fat jar packaging as the spring boot plugin is using `repackage` goal execution
[INFO] F8: Running generator spring-boot
[INFO] Copying files to /home/aboucham/dev/workspace/camel-spring-boot/target/docker/camel-spring-boot/latest/build/maven
[INFO] Building tar: /home/aboucham/dev/workspace/camel-spring-boot/target/docker/camel-spring-boot/latest/tmp/docker-build.tar
[INFO] F8: [camel-spring-boot:latest] "spring-boot": Created docker source tar /home/aboucham/dev/workspace/camel-spring-boot/target/docker/camel-spring-boot/latest/tmp/docker-build.tar
[INFO] F8: Using BuildConfig camel-spring-boot-s2i for S2I build
[INFO] F8: Using ImageStream camel-spring-boot
[INFO] F8: Starting Build camel-spring-boot-s2i
[INFO] F8: Waiting for build camel-spring-boot-s2i-2 to complete...
[INFO] F8: I1013 08:40:44.590900       1 source.go:180] Receiving source from STDIN as archive ...
[INFO] F8: I1013 08:40:45.221157       1 install.go:251] Using "assemble" installed from "image:///usr/local/s2i/assemble"
[INFO] F8: I1013 08:40:45.221187       1 install.go:251] Using "run" installed from "image:///usr/local/s2i/run"
[INFO] F8: I1013 08:40:45.221200       1 install.go:251] Using "save-artifacts" installed from "image:///usr/local/s2i/save-artifacts"
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: ... done
[INFO] F8: I1013 08:40:47.682934       1 sti.go:268] Using provided push secret for pushing 172.30.62.124:5000/devoxxma/camel-spring-boot:latest image
[INFO] F8: I1013 08:40:47.682951       1 sti.go:272] Pushing 172.30.62.124:5000/devoxxma/camel-spring-boot:latest image ...
[INFO] F8: I1013 08:40:50.413583       1 sti.go:288] Successfully pushed 172.30.62.124:5000/devoxxma/camel-spring-boot:latest
[INFO] F8: Build camel-spring-boot-s2i-2 Complete
[INFO] F8: Updated ImageStream camel-spring-boot to namespace: devoxxma name: camel-spring-boot@sha256:3356c6be600d8d01d9f0d1510c0ed24d45fd6355f4b08fbfce42f07c188d23b0
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ camel-spring-boot ---
[INFO] Installing /home/aboucham/dev/workspace/camel-spring-boot/target/camel-spring-boot-1.0-SNAPSHOT.jar to /home/aboucham/dev/localrepo/org/redhat/camel-spring-boot/1.0-SNAPSHOT/camel-spring-boot-1.0-SNAPSHOT.jar
[INFO] Installing /home/aboucham/dev/workspace/camel-spring-boot/pom.xml to /home/aboucham/dev/localrepo/org/redhat/camel-spring-boot/1.0-SNAPSHOT/camel-spring-boot-1.0-SNAPSHOT.pom
[INFO] Installing /home/aboucham/dev/workspace/camel-spring-boot/target/classes/META-INF/fabric8/openshift.yml to /home/aboucham/dev/localrepo/org/redhat/camel-spring-boot/1.0-SNAPSHOT/camel-spring-boot-1.0-SNAPSHOT-openshift.yml
[INFO] Installing /home/aboucham/dev/workspace/camel-spring-boot/target/classes/META-INF/fabric8/openshift.json to /home/aboucham/dev/localrepo/org/redhat/camel-spring-boot/1.0-SNAPSHOT/camel-spring-boot-1.0-SNAPSHOT-openshift.json
[INFO] Installing /home/aboucham/dev/workspace/camel-spring-boot/target/classes/META-INF/fabric8/kubernetes.yml to /home/aboucham/dev/localrepo/org/redhat/camel-spring-boot/1.0-SNAPSHOT/camel-spring-boot-1.0-SNAPSHOT-kubernetes.yml
[INFO] Installing /home/aboucham/dev/workspace/camel-spring-boot/target/classes/META-INF/fabric8/kubernetes.json to /home/aboucham/dev/localrepo/org/redhat/camel-spring-boot/1.0-SNAPSHOT/camel-spring-boot-1.0-SNAPSHOT-kubernetes.json
[INFO] 
[INFO] <<< fabric8-maven-plugin:3.1.71:deploy (default-cli) < install @ camel-spring-boot <<<
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.71:deploy (default-cli) @ camel-spring-boot ---
[INFO] F8: Using OpenShift at https://10.1.2.2:8443/ in namespace devoxxma with manifest /home/aboucham/dev/workspace/camel-spring-boot/target/classes/META-INF/fabric8/openshift.yml 
[INFO] OpenShift platform detected
[INFO] Using project: devoxxma
[INFO] Updating a Service from openshift.yml
[INFO] Updated Service: target/fabric8/applyJson/devoxxma/service-camel-spring-boot-1.json
[INFO] Updating ImageStream camel-spring-boot from openshift.yml
[INFO] Updating DeploymentConfig from openshift.yml
[ERROR] Failed to update DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.1.2.2:8443/oapi/v1/namespaces/devoxxma/deploymentconfigs/camel-spring-boot. Message: DeploymentConfig "camel-spring-boot" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=status.latestVersion, message=Invalid value: 0: latestVersion cannot be decremented, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=DeploymentConfig, name=camel-spring-boot, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=DeploymentConfig "camel-spring-boot" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. DeploymentConfig(apiVersion=v1, kind=DeploymentConfig, metadata=ObjectMeta(annotations={fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/git-commit=fb54fdb82c173a34894ba8ce596523ea573708dd, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-spring-boot&var-version=1.0-SNAPSHOT, fabric8.io/git-branch=master, fabric8.io/docs-url=dav:http://content-repository/sites/org.redhat/camel-spring-boot/1.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-spring-boot, version=1.0-SNAPSHOT, group=org.redhat}, name=camel-spring-boot, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentConfigSpec(minReadySeconds=null, paused=null, replicas=1, revisionHistoryLimit=null, selector={project=camel-spring-boot, provider=fabric8, group=org.redhat}, strategy=DeploymentStrategy(annotations=null, customParams=null, labels=null, recreateParams=null, resources=null, rollingParams=RollingDeploymentStrategyParams(intervalSeconds=null, maxSurge=null, maxUnavailable=null, post=null, pre=null, timeoutSeconds=10800, updatePercent=null, updatePeriodSeconds=null, additionalProperties={}), type=Rolling, additionalProperties={}), template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/git-commit=fb54fdb82c173a34894ba8ce596523ea573708dd, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-spring-boot&var-version=1.0-SNAPSHOT, fabric8.io/git-branch=master, fabric8.io/docs-url=dav:http://content-repository/sites/org.redhat/camel-spring-boot/1.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-spring-boot, version=1.0-SNAPSHOT, group=org.redhat}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={}), EnvVar(name=JAVA_APP_DIR, value=/deployments, valueFrom=null, additionalProperties={})], image=camel-spring-boot:latest, imagePullPolicy=Always, lifecycle=null, livenessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8081, Kind=null, StrVal=null, additionalProperties={}), scheme=null, additionalProperties={}), initialDelaySeconds=180, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), name=spring-boot, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8081, Kind=null, StrVal=null, additionalProperties={}), scheme=null, additionalProperties={}), initialDelaySeconds=10, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), resources=ResourceRequirements(limits={cpu=Quantity(amount=1.0, format=null, additionalProperties={}), memory=Quantity(amount=800Mi, format=null, additionalProperties={})}, requests={cpu=Quantity(amount=0.2, format=null, additionalProperties={}), memory=Quantity(amount=800Mi, format=null, additionalProperties={})}, additionalProperties={}), securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), test=null, triggers=[DeploymentTriggerPolicy(imageChangeParams=null, type=ConfigChange, additionalProperties={}), DeploymentTriggerPolicy(imageChangeParams=DeploymentTriggerImageChangeParams(automatic=true, containerNames=[spring-boot], from=ObjectReference(apiVersion=null, fieldPath=null, kind=ImageStreamTag, name=camel-spring-boot:latest, namespace=null, resourceVersion=null, uid=null, additionalProperties={}), lastTriggeredImage=null, additionalProperties={}), type=ImageChange, additionalProperties={})], additionalProperties={}), status=null, additionalProperties={})
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.1.2.2:8443/oapi/v1/namespaces/devoxxma/deploymentconfigs/camel-spring-boot. Message: DeploymentConfig "camel-spring-boot" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=status.latestVersion, message=Invalid value: 0: latestVersion cannot be decremented, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=DeploymentConfig, name=camel-spring-boot, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=DeploymentConfig "camel-spring-boot" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:314)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:267)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:236)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:229)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:213)
    at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:582)
    at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:87)
    at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation$2.apply(HasMetadataOperation.java:82)
    at io.fabric8.openshift.api.model.DoneableDeploymentConfig.done(DoneableDeploymentConfig.java:27)
    at io.fabric8.openshift.api.model.DoneableDeploymentConfig.done(DoneableDeploymentConfig.java:6)
    at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:94)
    at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.replace(DeploymentConfigOperationsImpl.java:70)
    at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.replace(DeploymentConfigOperationsImpl.java:42)
    at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.replace(DeploymentConfigOperationsImpl.java:68)
    at io.fabric8.openshift.client.dsl.internal.DeploymentConfigOperationsImpl.replace(DeploymentConfigOperationsImpl.java:42)
    at io.fabric8.kubernetes.api.Controller.applyResource(Controller.java:878)
    at io.fabric8.kubernetes.api.Controller.applyEntity(Controller.java:248)
    at io.fabric8.kubernetes.api.Controller.apply(Controller.java:224)
    at io.fabric8.maven.plugin.AbstractDeployMojo.applyEntities(AbstractDeployMojo.java:443)
    at io.fabric8.maven.plugin.AbstractDeployMojo.executeInternal(AbstractDeployMojo.java:396)
    at io.fabric8.maven.plugin.AbstractFabric8Mojo.execute(AbstractFabric8Mojo.java:71)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.484 s
[INFO] Finished at: 2016-10-13T14:40:51+02:00
[INFO] Final Memory: 52M/778M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.71:deploy (default-cli) on project camel-spring-boot: Failed to update DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.1.2.2:8443/oapi/v1/namespaces/devoxxma/deploymentconfigs/camel-spring-boot. Message: DeploymentConfig "camel-spring-boot" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=status.latestVersion, message=Invalid value: 0: latestVersion cannot be decremented, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=DeploymentConfig, name=camel-spring-boot, retryAfterSeconds=null, additionalProperties={}), kind=Status, message=DeploymentConfig "camel-spring-boot" is invalid: status.latestVersion: Invalid value: 0: latestVersion cannot be decremented, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).. DeploymentConfig(apiVersion=v1, kind=DeploymentConfig, metadata=ObjectMeta(annotations={fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/git-commit=fb54fdb82c173a34894ba8ce596523ea573708dd, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-spring-boot&var-version=1.0-SNAPSHOT, fabric8.io/git-branch=master, fabric8.io/docs-url=dav:http://content-repository/sites/org.redhat/camel-spring-boot/1.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-spring-boot, version=1.0-SNAPSHOT, group=org.redhat}, name=camel-spring-boot, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=DeploymentConfigSpec(minReadySeconds=null, paused=null, replicas=1, revisionHistoryLimit=null, selector={project=camel-spring-boot, provider=fabric8, group=org.redhat}, strategy=DeploymentStrategy(annotations=null, customParams=null, labels=null, recreateParams=null, resources=null, rollingParams=RollingDeploymentStrategyParams(intervalSeconds=null, maxSurge=null, maxUnavailable=null, post=null, pre=null, timeoutSeconds=10800, updatePercent=null, updatePeriodSeconds=null, additionalProperties={}), type=Rolling, additionalProperties={}), template=PodTemplateSpec(metadata=ObjectMeta(annotations={fabric8.io/iconUrl=img/icons/camel.svg, fabric8.io/git-commit=fb54fdb82c173a34894ba8ce596523ea573708dd, fabric8.io/metrics-path=dashboard/file/camel-routes.json/?var-project=camel-spring-boot&var-version=1.0-SNAPSHOT, fabric8.io/git-branch=master, fabric8.io/docs-url=dav:http://content-repository/sites/org.redhat/camel-spring-boot/1.0-SNAPSHOT}, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={provider=fabric8, project=camel-spring-boot, version=1.0-SNAPSHOT, group=org.redhat}, name=null, namespace=null, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), spec=PodSpec(activeDeadlineSeconds=null, containers=[Container(args=[], command=[], env=[EnvVar(name=KUBERNETES_NAMESPACE, value=null, valueFrom=EnvVarSource(configMapKeyRef=null, fieldRef=ObjectFieldSelector(apiVersion=null, fieldPath=metadata.namespace, additionalProperties={}), resourceFieldRef=null, secretKeyRef=null, additionalProperties={}), additionalProperties={}), EnvVar(name=JAVA_APP_DIR, value=/deployments, valueFrom=null, additionalProperties={})], image=camel-spring-boot:latest, imagePullPolicy=Always, lifecycle=null, livenessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8081, Kind=null, StrVal=null, additionalProperties={}), scheme=null, additionalProperties={}), initialDelaySeconds=180, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), name=spring-boot, ports=[ContainerPort(containerPort=8080, hostIP=null, hostPort=null, name=http, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=9779, hostIP=null, hostPort=null, name=prometheus, protocol=TCP, additionalProperties={}), ContainerPort(containerPort=8778, hostIP=null, hostPort=null, name=jolokia, protocol=TCP, additionalProperties={})], readinessProbe=Probe(exec=null, failureThreshold=null, httpGet=HTTPGetAction(host=null, httpHeaders=[], path=/health, port=IntOrString(IntVal=8081, Kind=null, StrVal=null, additionalProperties={}), scheme=null, additionalProperties={}), initialDelaySeconds=10, periodSeconds=null, successThreshold=null, tcpSocket=null, timeoutSeconds=null, additionalProperties={}), resources=ResourceRequirements(limits={cpu=Quantity(amount=1.0, format=null, additionalProperties={}), memory=Quantity(amount=800Mi, format=null, additionalProperties={})}, requests={cpu=Quantity(amount=0.2, format=null, additionalProperties={}), memory=Quantity(amount=800Mi, format=null, additionalProperties={})}, additionalProperties={}), securityContext=SecurityContext(capabilities=null, privileged=false, readOnlyRootFilesystem=null, runAsNonRoot=null, runAsUser=null, seLinuxOptions=null, additionalProperties={}), stdin=null, stdinOnce=null, terminationMessagePath=null, tty=null, volumeMounts=[], workingDir=null, additionalProperties={})], dnsPolicy=null, host=null, hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], nodeName=null, nodeSelector=null, restartPolicy=null, securityContext=null, serviceAccount=null, serviceAccountName=null, subdomain=null, terminationGracePeriodSeconds=null, volumes=[], additionalProperties={}), additionalProperties={}), test=null, triggers=[DeploymentTriggerPolicy(imageChangeParams=null, type=ConfigChange, additionalProperties={}), DeploymentTriggerPolicy(imageChangeParams=DeploymentTriggerImageChangeParams(automatic=true, containerNames=[spring-boot], from=ObjectReference(apiVersion=null, fieldPath=null, kind=ImageStreamTag, name=camel-spring-boot:latest, namespace=null, resourceVersion=null, uid=null, additionalProperties={}), lastTriggeredImage=null, additionalProperties={}), type=ImageChange, additionalProperties={})], additionalProperties={}), status=null, additionalProperties={}) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by rohanKanojia** [comment]
@abouchama: Hi, I tried reproducing it but could not(with 3.5.41). Could you please try you build again with 3.5.41? I'm closing it for now. If you're facing it with 3.5.41 also, feel free to reopen it ;-)

**Comment by immortal-anna** [comment]
I am facing same problem , here is the extract of log 
[INFO] OpenShift platform detected
[INFO] F8: Using project: test
[INFO] F8: Service has not changed so not doing anything
[INFO] F8: Updating DeploymentConfig from openshift.yml
[ERROR] F8: Failed to update DeploymentConfig from openshift.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: https://10.0.75.2:8443/apis/apps.openshift.io/v1/namespaces/test/deploymentconfigs/

**Comment by rohanKanojia** [comment]
@immortal-anna : Could you please share a sample project with me which I can use to reproduce your use case?
