### ISSUE TITLE
Spring Boot apps not running on kubernetes

### ISSUE THREAD

**Issue by stevef1uk** [fabric8io/fabric8-maven-plugin#566]
When running through the documented way to get an external SpringBoot project to run on fabric8 I am seeing errors like:

$ kubectl logs spring-boot-sample-webse-2233552943-0i0f1
ERROR: Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 0 found in /deployments (1 expected)

NAME                                        READY     STATUS    RESTARTS   AGE
exposecontroller-3431102810-jbnqk           1/1       Running   2          14h
fabric8-diauw                               2/2       Running   4          14h
fabric8-docker-registry-2762798780-kvhik    1/1       Running   2          14h
fabric8-forge-1556041525-s21yr              1/1       Running   2          14h
gogs-514977531-p04ur                        1/1       Running   2          14h
jenkins-1193727050-to0ox                    1/1       Running   2          14h
nexus-2033320395-q4fb4                      1/1       Running   5          14h
spring-boot-sample-webse-2233552943-0i0f1   0/1       Error     3          49s

The approach I took was to take a working SpringBook sample then:

eval $(minikube docker-env)
mvn io.fabric8:fabric8-maven-plugin:3.1.32:setup
mvn clean install
mvn fabric8:run

**Comment by jstrachan** [comment]
I wonder if using a more recent fabric8-maven-plugin version helps? e.g. try switch to `3.1.76`. BTW is the project a WAR by any chance? We only added nice WAR detection a few releases back

**Comment by stevef1uk** [comment]
I manually undated the pom file to fabric8-maven version 3.1.76. The docker image is created and deployed. I see a lot of the following messages:

[INFO] F8:[NEW] spring-boot-sample-webse-2241483968-kuqu6 status: Pending

Looking at the Pod's events I see the messages:

Back-off pulling image "boot/spring-boot-sample-webservices:snapshot-161021-205445-0208"
Error syncing pod, skipping: failed to "StartContainer" for "spring-boot" with ImagePullBackOff: "Back-off pulling image \"boot/spring-boot-sample-webservices:snapshot-161021-205445-0208\""
Failed to pull image "boot/spring-boot-sample-webservices:snapshot-161021-205445-0208": Error: image boot/spring-boot-sample-webservices not found
Error syncing pod, skipping: failed to "StartContainer" for "spring-boot" with ErrImagePull: "Error: image boot/spring-boot-sample-webservices not found"
pulling image "boot/spring-boot-sample-webservices:snapshot-161021-205445-0208"

Why is the docker image not found?

The sample I am trying from spring-boot is their: spring-boot/spring-boot-samples/spring-boot-sample-webservices project. Which does seem to create a jar file

**Comment by jstrachan** [comment]
That sounds odd! If you type 

    docker images | grep spring-boot

do you see the docker image with the same name & version?

Any chance you could attach a zip of the source of the project & I could try it here

**Comment by stevef1uk** [comment]
Well, today when I ran that command and the image was shown and the pod has started, so yesterday must have been a glitch.
I had no issue when running the same process on my iMac. Probably the documentation needs updating to point people at the latest version of the plugin.

**Comment by stevef1uk** [comment]
James,

Sorry, how do I check he version & how do I  upgrade it? I have just
installed the latest version of everything to the best off my knowledge

Regards

Steve

**Comment by jstrachan** [comment]
@stevef1uk you mean how do you upgrade fabric8 itself (jenkins et al?)

If you've got persistence enabled you can do:
```
gofabric8 cleanup
gofabric8 start
```

which isn't ideal. There's a pending issue:
https://github.com/fabric8io/fabric8/issues/6186

We're hoping we can use helm to install and upgrade fabric8 on kubernetes:

```
helm install fabric8/fabric8-platform
...
helm update
helm upgrade fabric8/fabric8-platform
```

though we've not done enough testing on this yet
