### ISSUE TITLE
seems to always create a Service even when there is no ports known

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#58]
I wonder if this is by design? 

Here's a sample app that doesn't have or need a Service but one gets generated anyway
https://github.com/fabric8io/gitcontroller/tree/master/src/main/fabric8

**Comment by rhuss** [comment]
The idea was to have a [headless service[(https://github.com/fabric8io/fabric8-maven-plugin/blob/032582fe9fea5bc2ca0ead1fcbffa07e8f51beb2/plugin/src/main/java/io/fabric8/maven/plugin/enricher/DefaultServiceEnricher.java#L82-L86) then.

However, I'm not sure whether this makes sense (what are the use case for headless services anyway ? I forgot :).

Any thought on this ?

**Comment by jstrachan** [comment]
[Headless](http://kubernetes.io/docs/user-guide/services/#headless-services) is quite rare; its mostly used when folks wanna use DNS SRV discovery IIRC. 

Maybe we should have a flag in the `<configuration>` to enable headless service creation (which needs explicit [headless configuration too I think - setting ClusterIP to `None`](http://kubernetes.io/docs/user-guide/services/#headless-services)), otherwise don't generate a Service unless there's a port?

**Comment by rhuss** [comment]
Good idea, lets put it into the default enricher configuration, with default to not create a service when there are no ports.

**Comment by dev-gaur** [comment]
I think this issue has already been worked upon. 

https://github.com/fabric8io/fabric8-maven-plugin/blob/ffb72a9454e0136a76965399d2837b0a8fa4802d/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultServiceEnricher.java#L228

@rohanKanojia @lordofthejars WDYT ? Is there anything to be done here now ?
