### ISSUE TITLE
 mvn io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start don open the console

### ISSUE THREAD

**Issue by yeganx** [fabric8io/fabric8-maven-plugin#591]
output of this command is $mvn io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- fabric8-maven-plugin:3.1.74:cluster-start (default-cli) @ standalone-pom ---
[WARNING] F8: The fabric8 bin folder /root/.fabric8/bin is not on the PATH.
[WARNING] F8: To easily start fabric8 CLI tools like gofabric8 directly, please adapt your environment:
[INFO] F8: Please add the following to your ~/.bashrc:
[INFO] F8:   export PATH=$PATH:/root/.fabric8/bin
Would you like to add the path setting to your ~/.bashrc now? (Y/n): 
[INFO] F8: Running /root/.fabric8/bin/gofabric8 start --console --batch
[INFO] F8:gofabric8 Unable to download driver Driver install for linux not yet supported
[INFO] F8:gofabric8 Downloading https://storage.googleapis.com/minikube/releases/v0.12.0/minikube-linux-amd64...Downloaded minikube
[INFO] F8:gofabric8 Downloading https://storage.googleapis.com/kubernetes-release/release/v1.4.4/bin/linux/amd64/kubectl...Downloaded kubectl
[INFO] F8:gofabric8 using the executable /root/.fabric8/bin/minikube
[INFO] F8:gofabric8 minikube already running
[INFO] F8:gofabric8 using the executable /root/.fabric8/bin/kubectl
[INFO] F8:gofabric8 switched to context "minikube".
[INFO] F8:gofabric8 
[INFO] F8:gofabric8 Opening URL http://192.168.99.101:31938
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:57 min
[INFO] Finished at: 2016-10-22T14:06:46+03:30
[INFO] Final Memory: 22M/205M
[INFO] ------------------------------------------------------------------------
[root@localhost ~]#  Running /root/.fabric8/bin/gofabric8 start --console --batch
bash: Running: command not found...
[root@localhost ~]# /root/.fabric8/bin/gofabric8 start --console --batch
Unable to download driver Driver install for linux not yet supported
Downloading https://storage.googleapis.com/minikube/releases/v0.12.0/minikube-linux-amd64...
Downloaded minikube
Downloading https://storage.googleapis.com/kubernetes-release/release/v1.4.4/bin/linux/amd64/kubectl...
Downloaded kubectl
using the executable /root/.fabric8/bin/minikube
minikube already running
using the executable /root/.fabric8/bin/kubectl
switched to context "minikube".

Opening URL http://192.168.99.101:31938

**but the web console can not opens : http://192.168.99.101:31938**
the output of  /root/.fabric8/bin/gofabric8 status
minikubeVM: Running
localkube: Running

**Comment by davsclaus** [comment]
Try again with latest, and reach out to us on IRC chat
https://fabric8.io/community/index.html

You may need to check the logs of the pods on minikube and whatnot, but that is easier to help over chat
