### ISSUE TITLE
 mvn io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start error

### ISSUE THREAD

**Issue by yeganx** [fabric8io/fabric8-maven-plugin#593]
hi,
 mvn io.fabric8:fabric8-maven-plugin:3.1.74:cluster-start error
this error occured :+1: 
[ERROR] F8:gofabric8 /root/.fabric8/bin/gofabric8: line 1: syntax error near unexpected token `newline'
[ERROR] F8:gofabric8 /root/.fabric8/bin/gofabric8: line 1:`<!DOCTYPE html>'

**Comment by rhuss** [comment]
Could you please remove all of `/root/.fabric8` and retry ? The possible reason was the DDOS outage yesterday on GitHub. 

Nevertheless we need to add checksum verification on the binaries we download.
