### ISSUE TITLE
Unsupported value: "tcp" 

### ISSUE THREAD

**Issue by levackt** [fabric8io/fabric8-maven-plugin#596]
I'm not 100% sure it's a bug here, but since updating minikube and kubectl, tcp is not longer supported.
Must be TCP/UDP, resulting in the below error when creating the service.

### Description
[INFO]
[INFO] <<< fabric8-maven-plugin:3.1.79:deploy (default-cli) < install @ spring-boot-hystrix <<<
[INFO]
[INFO] --- fabric8-maven-plugin:3.1.79:deploy (default-cli) @ spring-boot-hystrix ---
[INFO] F8: Using Kubernetes at https://192.168.99.100:8443/ in namespace default with manifest /Users/taariq/code/fabric8-qs/spring-boot-hystrix/target/classes/META-INF/fabric8/kubernetes.yml
[INFO] Using namespace: default
[INFO] Creating a Service from kubernetes.yml namespace default name spring-boot-hystrix
[ERROR] Failed to create Service from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.99.100:8443/api/v1/namespaces/default/services. Message: Service "spring-boot-hystrix" is invalid: [spec.ports[0].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[0].protocol: Invalid value: "tcp": cannot create an external load balancer with non-TCP/UDP ports].

### Info

* fabric8-maven-plugin version: 3.1.79
* Maven version (`mvn -v`) : 3.3.9
* minikube version: v0.12.0
* kubernetes version : v1.4.3 (client and server)
* If it's a bug, how to reproduce: 
Clone the following sample project and deploy to kubernetes
* Sample project: *https://github.com/fabric8-quickstarts/spring-boot-hystrix*

To workaround I added a service.yaml to make it TCP, eg;

```
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"

```

**Comment by rhuss** [comment]
Thanks, that's indeed an issue with the latest changes. I will change this to a case insensitive detection for the next release (which you can expect soon).

**Comment by jimmidyson** [comment]
I think the problem is at [here](https://github.com/fabric8io/fabric8-maven-plugin/blob/a99ca03118304c8cbafa9a10154e63e784a9d745/core/src/main/java/io/fabric8/maven/core/handler/ServiceHandler.java#L72)

**Comment by jimmidyson** [comment]
In fact looks like some of the changes in 716becaeafb4f7ac9d4b0499e14182fd318337b1 probably need revisiting to ensure protocol is always uppercase.

**Comment by rhuss** [comment]
Yeah, my bad. I will change it to case insensitive matching as it makes the most sense.

**Comment by jimmidyson** [comment]
I don't think it's the matching I think it's the setting of the protocol in the service port in the final resource manifest.

**Comment by rhuss** [comment]
Ah, ok. Agreed, these are two different things. Still my fault ;-). I will match on any case for the configuration but convert to upper case when setting the protocol in the model.

Thanks for the heads up.

**Comment by levackt** [comment]
Nice, thanks!
