### ISSUE TITLE
Add a HealthCheck Enricher for Webapps

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#601]
we should generate a readiness & liveness checks OOTB for war packaging apps.

If there is a service annotation for [api.service.kubernetes.io/path](https://github.com/fabric8-quickstarts/spring-boot-hystrix/blob/master/src/main/fabric8/service.yml#L3) we could use that if no explicit happy page URL is configured in the pom.xml; otherwise we could just default to using `/`

**Comment by rhuss** [comment]
the health check enricher should work in the same spirit as the enrichers we have now for Vertx, Prometheus etc.

Alternatively, the webapp generator could also add just a Docker `HEALTHCHECK` we already can be reused by the `DockerHealthCheckEnricher`
