### ISSUE TITLE
it would be nice to add the generated Dockerfile to nexus as part of the release

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#608]
then folks can see the generated Dockerfile in case they wonder what base image was used etc

**Comment by rhuss** [comment]
So, you mean to add it to the generated docker image ? This should be easily possible. Not so easy would be to put it into the jar.

Or do you mean to deploy it as an artefact to a Maven repo ? The difficulty here is, that there can be many Dockerfiles (you can defined N images), and I wonder how the naming of those artefact then should look like. Actually I'm quite happy that we could get away from deploying text files to Maven repos. 

While we are at it, wouldn't it also be nice to put the k8s / os files directly in the Dockerfile (and maybe even add a command to the Dockerfile which simply print these out) ?

**Comment by jstrachan** [comment]
was thinking of adding it as a released artifact, so folks can browse it in nexus. Figure thats gonna be the simplest thing to do to let folks browse them.

Adding it into the jar causes chick and egg though

**Comment by jstrachan** [comment]
if we have N dockerfiles, I figure we just name them using a canonical naming mechanism. So we use `classifier` of the container name and `type` as dockerfile? Then folks can look at any of the dockerfiles created

**Comment by jstrachan** [comment]
not too sure on the kubernetes manifest inside the docker image thing; as there could be many manifests for a single docker image. e.g. to enable/disable features using environment variables. 

For example our jenkins image may have a S2I manifest or a `docker mode` manifest that mounts the docker socket. So its not really 1-1 mapping between a docker image and a kubernetes manifest. Then there's the complexity of vanilla kubernetes versus helm versus OpenShift Template; then the added complication of all the non-portable openshift stuff versus vanilla k8s stuff etc

**Comment by rhuss** [comment]
Agreed with not putting the k8s / openshift files into the images (indeed it probably doesn't make much sense at all).

However, putting a plain Dockerfile as artefact into Nexus doesn't make much sense since the Docker context is missing then (i.e. the files which are added). Actually we already have a `docker:source` which puts the full docker.tar (as used for Docker builds and S2I binary builds) into the maven repository (with a classifier `docker` if only one image is used, or `docker-<alias>` for multiple images. 

I think this is the most comprehensive solution (since you can easily rebuild the image) and would opt to keep that solution.

**Comment by jstrachan** [comment]
putting the tar into nexus is possibly a lot of data; given the tar is inside the docker image layer already I'm not so sure I'd wanna do that by default TBH (our releases are massive and slow enough as it is ;). I'm cool with letting folks choose to opt into that though if they want to.

Deploying the `Dockerfile` into nexus isn't so much to re-create the build again (why would we ever want to do that - the point of the docker image is so that we have an immutable binary output?) - its so that folks can see the `Dockerfile` that was generated & the FROM image and any env vars etc.

**Comment by rhuss** [comment]
@jstrachan You are right, it probably doesn't make sense in the general case to pollute Maven repose with 100 MB blobs, so 

So lets add the plain Dockerfile, too, but probably better into d-m-p. What's about using a classifier of 'dockerfile' when only one image is present, and 'dockerfile-<alias>' for multiple dockerfiles ? What do you suggest as file extension ? `.txt` or something more artificial like `.dck` (or even no file extension at all) ?

Actually the Dockerfile looks quite thin, e.g.

```
FROM fabric8/java-alpine-openjdk8-jdk:1.2.1
ENV JAVA_APP_DIR=/deployments
EXPOSE 8080 8778 9779
COPY maven /deployments/
```
What do you think about adding the content of `/maven` as a kind of `ls -l` output at the end embedded in comments ? That way one would also have a reference to the jars embedded (possibly with the Maven coordinates in the file names.

E.g.

```
FROM fabric8/java-alpine-openjdk8-jdk:1.2.1
ENV JAVA_APP_DIR=/deployments
EXPOSE 8080 8778 9779
COPY maven /deployments/

# Content of 'maven' :
#
# drwxr-xr-x 3 roland staff      102 Oct 13 18:43 bin
# -rw-r--r-- 1 roland staff 14317555 Oct 13 18:43 fabric8-maven-sample-spring-boot-3.1-SNAPSHOT.jar
# 
# maven/bin:
# -rwxr-xr-x 1 roland staff 20 Sep 22 19:57 test.sh
```

**Comment by rhuss** [comment]
I opened https://github.com/fabric8io/docker-maven-plugin/issues/1107 to track this idea and close this issue.
