### ISSUE TITLE
Add source S2I Build to fabric8:build

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#610]
Currently we have the following build types:
- Docker direkt 
- Binary Docker for OpenShift
- Binary S2I for OpenShift

An additional "Source S2I" build should be added to help in creating images for mixed (i.e. non-java) projects on OpenShift.

Therefor `BuildMojo` need to be extended:
- A new property `fabric8.build.s2i.source` should be added with the possible values `binary` or `source` (with `binary` being the default)
- When `source` is selected then:
  - Change the [this source type](https://github.com/rhuss/fabric8-maven-plugin/blob/716becaeafb4f7ac9d4b0499e14182fd318337b1/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java#L645) to `Source`
  - When triggering the build, send a tar archive of the project directory (`${project.baseDir}` excluding `/target` and possibly `.git`) to OpenShift when [triggering the build](https://github.com/rhuss/fabric8-maven-plugin/blob/716becaeafb4f7ac9d4b0499e14182fd318337b1/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java#L561)

This parameter is still a global one which applies to all images to be created. In order to allow image specific `build.strategy` and `build.s2i.source` value from [BuildImageConfiguration.fromExt](https://github.com/fabric8io/docker-maven-plugin/blob/1f8e154d8bf53cf0a14de9718dd59a9abebbb715/src/main/java/io/fabric8/maven/docker/config/BuildImageConfiguration.java#L43) could be extracted, overwriting the global parameter (that's probably not the perfect location where to put this information into, but should be sufficient for now as I consider this a bit of a rare use case, too)

**Comment by rhuss** [comment]
@fabric8io/fmp-core-team do you think this is still a useful extension ? The original idea was to add e.g. simple non-java builds with fmp in order to allow an easy integration.

**Comment by rohanKanojia** [comment]
Since fmp is designed for maven space only, not sure whether it should be added or not. Would it make sense for those non-java based projects to have poms in their repo? Can this be somehow done in fabric8-kit?

**Comment by rhuss** [comment]
yeah, maybe. Let's keep it to not lose the idea, but with a very low priority. We have bigger fish to fry.

**Comment by dev-gaur** [comment]
Closing as per discussion with the current maintainers' team.
