### ISSUE TITLE
it might be nice to generate a YML file for each resource generated/enriched?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#63]
Its kinda hard to read a kubernetes list when there's a bunch of resources inside (SA / Service / RC et al).

Its much easier to just look at individual files. I wonder if by default we should generate individual files from the `kubernetes.yml` so that if you're looking at the generation of, say, foo-rc.yml then you can look at `target/fabric8/kubernetes/foo-rc.yml` to see the fully enriched generated file?

**Comment by rhuss** [comment]
Good Idea. I think we could add even both without harm. What do you think to put this into a `META-INF/fabric8` directory ? When ending up in a Jar, this could still be read as resource, but looks cleaner (to separate it from classes). Its also looks smarter to not pollute the top-level dir :)

**Comment by jstrachan** [comment]
good idea! Have an implementation going; will pop it there instead!
