### ISSUE TITLE
mvn fabric8:run - [SVC] should include service annotation context-path in listed url

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#643]
When running the `war-camel-servlet` quickstart with

   mvn fabric8:run

Then the plugin logs the url to the service as

```
[INFO] F8: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] F8:[SVC] war-camel-servlet: http://192.168.64.19:32741
```

But this opens the default tomcat management web (eg root)

However the service has been annotated with
```
metadata:
  annotations:
    api.service.kubernetes.io/path: /war-camel-servlet/camel/hello
```

And if you open fabric8 web console then you can see the right link as shown:
![screen shot 2016-11-08 at 7 41 08 pm](https://cloud.githubusercontent.com/assets/477100/20112115/53376d02-a5eb-11e6-8f2f-7663a12649e1.png)

Also gofabric8 service does not take that into account, eg

```
davsclaus:/Users/davsclaus/$ gofabric8 service -u war-camel-servlet
http://192.168.64.19:32741
```

with version
```
davsclaus:/Users/davsclaus/$ gofabric8 version
gofabric8, version 0.4.82 (branch: 'master', revision: '49da7d1')
  build date:       '20161014-12:39:38'
  go version:       '1.7.1'
```

**Comment by hrishin** [comment]
@davsclaus @jstrachan 
Are we still able to reproduce this behaviour? Somehow I'm unable to.
In case Yes, please describe how to reproduce it if possible.

**Comment by jstrachan** [comment]
@hrishin ah great - so if the listed URL includes the path  like `http://192.168.64.19:32741/war-camel-servlet/camel/hello` then we can close this one - thanks!

**Comment by hrishin** [comment]
May be related #1014

**Comment by hrishin** [comment]
may be related to #1014
