### ISSUE TITLE
Create an Generator for Microprofile based apps

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#645]
there's a new approach to building microservices based on http://microprofile.io/ which lets you write an app then choose to deploy on tomee, wildfly swarm, liberty profile et al. 

It'd be nice if we had a little enhancer which detected a microprofile WAR; then had an easy setting to configure which flavour is preferred (or maybe even detected via the active profiles or properties in the pom.xml) so we can choose between the right base image of tomee, wildfly swarm, liberty  profile etc.

Over time I'm hoping there's gonna be canonical URLs for liveness & readiness checks too which would be nice to add in as well

**Comment by rhuss** [comment]
It's a bit similar in the spirit of the Webapp generator which also detects various different JEEServer.
