### ISSUE TITLE
validate generated resources

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#66]
it would be nice to generate nice validation error messages if the generated resources are not invalid in any way - linking to the individual generated files in `target/classes/META-INF/fabric8/` so that folks can easily see whats wrong. e.g. missing name / image or bad names for services or whatever

**Comment by rhuss** [comment]
wdym with validation errors ? When doing a `fabric8:deploy` ? Or are there other ways to validate a kubernetes resource file, maybe even offline ?

**Comment by jimmidyson** [comment]
kubernetes-model now has better (more correct) validation but there is no way to link back to the actual source file right now.

**Comment by jstrachan** [comment]
@rhuss we've validation (bean validation) in kubernetes model.

@jimmidyson at least we could iterate through each generated file in `target/classes/META-INF/classes/*.yml` and if validation fails show the file with the issue in the maven log

**Comment by jimmidyson** [comment]
Yeah - I'm just updating so you can catch the proper `ConstraintViolationException` with all violations, property paths, etc.

**Comment by jimmidyson** [comment]
If you use the `client.load(...)` to load a file you will (soon) get validation exceptions with details like:

```
ConstraintViolationImpl{interpolatedMessage='must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"', propertyPath=objects[4].metadata.name, rootBeanClass=class io.fabric8.openshift.api.model.Template, messageTemplate='{io.fabric8.kubernetes.api.model.Pattern.message}'}
``` 

This includes the property path from the root of the file & hopefully a decent-ish error message. Can expand with examples in future too I reckon which might be even nicer for users.

**Comment by rhuss** [comment]
I take this.

**Comment by jimmidyson** [comment]
Validation isn't quite there yet - problem in the builder generators - will reply back once fixed.

**Comment by hrishin** [comment]
@rhuss are you working on this issue?

**Comment by jstrachan** [comment]
He's on vacation so I assume not ;)

**Comment by rhuss** [comment]
sorry, no. I overlooked this since quite some time ;-). 'happy if someone else could take it over.

**Comment by hrishin** [comment]
Few Point(s)
1) JSON Schema Validation: How about using JSON schema to validate resources?
- JSON schema may vary from each Kubernetes/OpenShift version, in this case default Kubernetes/OpenShift version could be?

**Comment by hrishin** [comment]
Implemented initial validation for, its generating message in following format

```
javax.validation.ConstraintViolationException: Invalid Spec : /home/hshinde/fabric8-maven-plugin/core/target/test-classes/validations/openshift-deploymentconfig.yml
[message=.spec.test: is missing but it is required, violation type=required]
[message=.status: is missing but it is required, violation type=required]
```
Is it look informative? Serving its purpose?

@jstrachan @nicolaferraro @rhuss @jimmidyson any reviews on this

**Comment by rhuss** [comment]
imo that looks good (and is of course much, much better than having no validation ;-)

**Comment by jstrachan** [comment]
LGTM!
