### ISSUE TITLE
Multiport services are ignored

### ISSUE THREAD

**Issue by iocanel** [fabric8io/fabric8-maven-plugin#665]
In the case that a generator detects multiple ports, the `EXPOSE` is correctly added to the image, but the generated Service resources, only contain the first service.

It seems that its done on purpose, according to:

https://github.com/fabric8io/fabric8-maven-plugin/blob/e9bc60ab870e8137a6697883b22e9cc536b1d8ae/core/src/main/java/io/fabric8/maven/core/handler/ServiceHandler.java#L77-L77

I don't see a reason for ignoring ports, that we've automatically detected and it pretty much defeats the purpose of auto-detection.

**Comment by iocanel** [comment]
@jstrachan: what's the purpose of the `break`?

**Comment by jstrachan** [comment]
Kubernetes services with more than one port break Routes on OpenShift meaning you can no longer access any ports from the service reliably from outside the cluster when using OpenShift
https://github.com/openshift/origin/issues/2092

its not clear if/when this will ever be fixed TBH so its better to not use multi-port services if you want to use OpenShift

**Comment by jimmidyson** [comment]
Not quite true `route.spec.port` can be used to specify the service port to use for multiport services.

**Comment by iocanel** [comment]
Awesome !!!

**Comment by iocanel** [comment]
@jstrachan: now that we got routes coverred can we revert this?

**Comment by jstrachan** [comment]
we need to check that using Routes with fabric8-maven-plugin with multi-port services actually works though ;) (e.g. check it works with exposecontroller + fabric8-maven-plugin + jenkins pipeline)

**Comment by jstrachan** [comment]
@iocanel why not try create a multi-port service then check it works with exposecontroller + openshift routes with CI / CD pipelines? if all thats good we can revert this

**Comment by rhuss** [comment]
I wonder whether instead of a single multiport service, why don't we create multiples services with a single port ? It seems that e.g. our elasticsearch image does this for port 9300 and 9200 (i.e. creating two services)

Could this be an alternative ?

**Comment by iocanel** [comment]
@rhuss: the main issue with this approach is that we need a different name for each. Isn't that a problem (given that internally we just handle them as a list of numbers)?

**Comment by rhuss** [comment]
We could try to detect a 'main service' which gets the default name, alternative services then this name + the service type (thanks to @jimmidyson we have https://github.com/fabric8io/ianaservicehelper which can lookup the name of an IANA service based on its port), e.g. 'myapp-mysql' (for port 3306 or so). 

Beside the name, I wonder whether there are other implications which make a muliport service different to multiple single services ?

**Comment by iocanel** [comment]
The only known case that comes to mind, which is an edge case really, is zookeeper which defines multiple ports but requires that they are all bound to the same address.

**Comment by rhuss** [comment]
According to the discussion in #666 the current suggestion is to only us a single port by default. In order to improve flexibility a bit, I suggest to add a 'mode' to the `DefaultServiceEnricher` with the following possible value

* **single** : Create a single service with one or more ports (default) (see below)
* **multiple** : Take all exposed ports and create multiple services, one for each port

A second parameter 'ports' holds a list of ports to expose. This can be 

* **first** : Take the first exposed port (default)
* **all** : Take all ports
* **_port1_, _port2_, ...** : Comma separated list of numeric ports to pick

If more flexibility is require the user then use define their services with XML or YAML fragments.

wdyt ?

**Comment by rhuss** [comment]
DefaultServiceEnricher already support multi ports.
