### ISSUE TITLE
Exposing Node IP/Domain as Maven Property

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#667]
_when building appplications that rely on ingress routes/node ip, it will be ideal to have node ip/domain exposed as maven property, enabling the filters on the application properties applied as needed using the maven properties_

### Description
e.g  say we are developing a spring-boot application, that uses swagger. When adding the following property to swagger 
`springfox.documentation.swagger.v2.host`, it will be ideal if the node ip is exposed or manipulated during build and the the above mentioned property set with value like `${node.ip}`

**Comment by jimmidyson** [comment]
At build time you do not know what node the pod will be deployed: both node & domain are deployment specific so should be injected at runtime using configmap or env vars via downward API if available.

**Comment by jstrachan** [comment]
we've discussed this in more detail on IRC. 

The current solution is to use [exposecontroller](https://github.com/fabric8io/exposecontroller/) to inject the external URL of a service like we do with gogs today via a [configmap injection](https://github.com/fabric8io/exposecontroller/#configmap) like [this example](https://github.com/fabric8io/fabric8-devops/blob/master/gogs/src/main/fabric8/gogs-cm.yml#L27).

Then you can either expose the configmap entry as an env var or load it into your explicitly via a file or spring cloud kubernetes plugin etc
