### ISSUE TITLE
BuildMojo must not write into openshift.yml / kubernetes.yml

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#677]
### Description

Currently when doing an OpenShift build it happens that `openshift.yml` that has been created by `fabric8:resource` gets updated by `fabric8:build` with an `ImageStreamImage` and a specific `ImageStreamTag`. This must not happen since this file is already packaged and included in the artifact jar during the `package` phase, which result to inconsistent and unpredictable behavious (as @cescoffier reported yesterday). Also, the jars can be accumulated also via dependencies to large deployments, where this information is missing. This does not make sense.

There are two questions:

* Why is it important to have a (very installation specific) resource object in `openshift.yml` (which is distributed over Maven central, too ?). Isn't it enough to have it create 'live' during the build ? I know we already talked briefly, but I forgot the reason. Sorry, @jstrachan .
* Could it be a different file, which is not `openshift.yml` but lies separately and then e.g. is used by other mojos (like the `ApplyMojo`) ?

IMO its really important to avoid this, because it super hard to debug if things go wrong and it highly depends on the order and how the goals are called and more.

**Comment by nicolaferraro** [comment]
@rhuss I think this has already been addressed. The `ImageStream` is saved in `target/*-is.yml`, and the resource file is not modified. There is a patch into the red hat branch to import such files in Arquillian, so that multi-module IT tests should work https://github.com/fabric8io/fabric8/pull/6721.

Maybe we should just cherry-pick that commit into fabric8:arquillian master.

**Comment by rhuss** [comment]
@nicolaferraro  Yes, that would make sense. Guess also, that we have fixed it, just wanted to be sure that there is not something other left doing the same.

**Comment by nicolaferraro** [comment]
@rhuss I've checked this issue and it is fixed now.
I've merged the code into kubernetes-arquillian master, so it works as expected for single module projects (for multi-module projects there are some known issues, but that should be addressed in kubernetes-arquillian).

I'm going to close this.
