### ISSUE TITLE
Spring-Boot generator can't find fat-jar when target is a war.

### ISSUE THREAD

**Issue by chicagozer** [fabric8io/fabric8-maven-plugin#688]
### Description

Spring-Boot generator can't find fat-jar when target is a war.

### Info

When using Spring Boot to create a war, (http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#build-tool-plugins-maven-packaging), the fabric8:build plugin can't find the target.

` Failed to execute goal io.fabric8:fabric8-maven-plugin:3.2.7:build (default-cli) on project fabric8-maven-sample-spring-boot: Failed to create assembly for docker image  (with mode 'dir'): Error adding file to archive: /Users/me/git/fabric8-maven-plugin/samples/spring-boot/target/fabric8-maven-sample-spring-boot.war -> [Help 1]
`
When I build a jar, everything is fine, but with a war it's leaving off the last part of the target (-3.2-SNAPSHOT) in the filename.

* f-m-p version : 3.2.7
* Maven version (`mvn -v`) :3.3.9

Updated pom.xml here

https://github.com/chicagozer/fabric8-maven-plugin/blob/master/samples/spring-boot/pom.xml

If there is a way to specify the fat-jar I'd be happy to add that to my config.

**Comment by davsclaus** [comment]
Can a SB fat war run like a java -jar ? If so then it ought to be similar to run it on the container, as a java container but with only the file name is .war instead of .jar

**Comment by chicagozer** [comment]
Yes, it runs fine with "java -jar" (as long as you use the SB repackage plugin.)

**Comment by davsclaus** [comment]
Btw is there a special reason you use .war - eg make .jar not .war is the mantra.

**Comment by davsclaus** [comment]
The error is not from fmp but from the spring-boot maven plugin. I think you have configured it wrong or something

**Comment by derkoe** [comment]
With Spring Boot you can create WARs that are also startable JARs. So you can `java -jar app.war` - those WARs should be supported as well.

**Comment by rohanKanojia** [comment]
@chicagozer : Are you still facing this issue? Or was this due to spring-boot maven plugin, as pointed by @davsclaus ?
