### ISSUE TITLE
Change default service type from LoadBalancer to ClusterIP

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#693]
### Description

Using `LoadBalancer` as standard type is not suitable in situation when there is no load balancer available. I guess the only save default is to use `ClusterIP` or nothing (which actually maps to `ClusterIP`, too). This lead also to issue within OpenShift (https://issues.jboss.org/browse/OSFUSE-469)

If an fabric8 environment we still can use the `exposecontroller` to change this type on the fly.

If there are not objection, I would remove the default (so that no type is added).

**Comment by jimmidyson** [comment]
Just submitted #692 which defaults to ClusterIP but happy to remove the default altogether.

**Comment by rhuss** [comment]
Thanks ! Let's wait until monday before changing that

@jstrachan @rawlingsj @davsclaus what's your opinion ? What are the potential pitfalls ?

**Comment by jimmidyson** [comment]
Would like to merge #692. Any objections?

**Comment by rhuss** [comment]
lgtm, I would even remove the default (so don't specify a type if none is given)

**Comment by jimmidyson** [comment]
#692 does remove the default so no type is specified.

**Comment by rhuss** [comment]
sorry, overlooked. all good for me :)

**Comment by muraken720** [comment]
from fabric8-maven-plugin 3.2.7 and 3.2.8, fabric8 console could not be opened.
If you change the type of service from ClusterIP to NodePort, you can access fabric8 console.

**Comment by jimmidyson** [comment]
@muraken720 In general, exposing services outside of the cluster should be opt-in so a default of ClusterIP (internally routable) & ability to change the service type via config (as you can do now) seems fine to me.

**Comment by muraken720** [comment]
@jimmidyson oh I see. Exposecontroller helps it right? So my problem is exposecontroller is not installed default by fabric8-maven- plugin from vet 3.2.7.

**Comment by jimmidyson** [comment]
That's right exposecontroller will update service type appropriately. The Maven plugin does not deploy exposecontroller - that is deployed as part of the fabric8 platform.

**Comment by muraken720** [comment]
Thanks. So fmp seems to be wrong. Cluster-start command waits for access enabled to fabric8 console. But default process did not install exposecontroller and then error occurred on minikube.
