### ISSUE TITLE
Specify Kuberentes/OpenShift login data via configuration (XML/properties)

### ISSUE THREAD

**Issue by apupier** [fabric8io/fabric8-maven-plugin#712]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Description

Maven properties cannot be used to configure the targeted OpenShift instance/application.
It currently requires to use System Environment variables or System Properties.

The Fabric8-maven-plugin relies exclusively on Fabric8 Kubernetes client which is not taking care of Maven properties.

See https://maven.apache.org/plugin-developers/common-bugs.html#Using_System_Properties for Maven plugin best practice
And the implementation currently used as it is delegated completely to another library: https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/Utils.java#L44

### Info

* f-m-p version : 3.2 and 3.1.80
* Maven version (`mvn -v`) :
```

```
* Kubernetes / OpenShift setup and version : CDK 2.3
* If it's a bug, how to reproduce :
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by jstrachan** [comment]
I don't quite follow what this issue means. What do you mean "targeted OpenShift instance/application."

In terms of connecting to a kubernetes cluster and namespace the fabric8-maven-plugin reuses the same `~/.kube/config` file - so it uses the same cluster + namespace as `kubectl` or `oc`. Or if you run maven jobs inside, say, Jenkins inside kubernetes it'll just reuse the local cluster and namespace OOTB.

What do you need?

**Comment by jimmidyson** [comment]
I think @apupier is suggesting that the connection to OpenShift/Kubernetes should be configurable via Maven properties rather than relying on the kubernetes-client library.

**Comment by apupier** [comment]
using ~/.kube/.config is a big issue in a multi-module, CI environment. This is fine only to do little demos.
I asked to have the possibility to use Maven Properties when using the fabric8-maven-plugin.
@nicolaferraro implemented back the way to use system variables instead of relying on .kube/config with https://github.com/fabric8io/fabric8-maven-plugin/pull/689 which is already a good step forward.
Using Maven properties as explained in https://maven.apache.org/plugin-developers/common-bugs.html#Using_System_Properties is the scalable and reliable way of implementing a maven plugin.

**Comment by jstrachan** [comment]
wouldn't environment variables do? e.g. use the same `$KUBECONFIG`environment variable to point to a separate folder to `~/.kube` folder for the config file defining the cluster, token, namespace etc

**Comment by apupier** [comment]
@jstrachan using another kube config folder seems not user friendly, it means that we will have to create a new one for every configuration we want to use. I don't see how to generate them easily, the user will have to create them manually?

**Comment by jstrachan** [comment]
One solution would be just to specify $KUBECONFIG to a local folder, then do an `oc login` with a server URL, login + pwd in your CI job and then the config file/folder would be created with the token etc

Its possible to pass stuff in via mvn properties; its just non trivial with the openshift certs + tokens etc when outside openshift. Its much easier to just use CI jobs inside kubernetes itself then you've none of these issues ;)

**Comment by apupier** [comment]
I don't see what are the additional issues compared to using system variables to configure the plugins which has been done @nicolaferraro regarding these certs + token issues.
Eclipse OpenShift Toolingseems to be able to manage all these certs+ token issues without .kube/config. Maybe we can ask them some help.

For CI, the solution would be to add more steps to the build instead of configuring Maven properties. Sounds not ideal at all but not a big drawback.

What about using in an IDE? I need to generate a new folder for every project that is created and that each build of these projects is using a specific $KUBECONFIG ? We will have to provide a strong fabric8-maven-plugin m2e connectors then (and for other IDE than Eclipse I don't know how it will be possible)

**Comment by jstrachan** [comment]
I was more thinking of the CI case here really. For IDE integration its easy to use whatever IDE storage mechanism you already use to configure clusters & namespaces etc.

Though the easiest way to supply all the various metadata (location of the cluster, token, certs, user name, namespace name and all that jazz) is via a single YAML file (which could then be one single mvn property or the `$KUBECONFIG` env var) but sure use whatever approach that fits best for your CI / IDE use cases; I just favour using a similar approach to `kubectl` and `oc` OOTB where possible as its the most consistent

**Comment by jstrachan** [comment]
BTW usually the namespace is already a parameter you can specify via mvn properties; this discussion around `~/.kube/config` is just around the cluster, user name, token, certs etc

**Comment by rhuss** [comment]
We could map Maven properties (or even better, a more structured XML config structure) which are meaningful to Fabric8 Kubernetes client as system properties before we create the access objects.  And we could go even so far to take this info from `~/.m2/settings.xml` if given, too (as d-m-p does).

**Comment by rhuss** [comment]
@rohanKanojia I'm not sure where we are with this issue. Does the kubernetes-client allow a flexible way of configuration or does it always stick to ~/.kube/config ? If it allows other ways to configure (like with properties) we could leverage this in fmp, too.

If not, it first needs to be implemented in the kubernetes-client.

**Comment by rohanKanojia** [comment]
@rhuss : As far as I know, client only supports configuration via ~/.kube/config file, which can be overridden via system property if required.

**Comment by jimmidyson** [comment]
If you're still using fabric8's kubernetes-client, then it provides completely flexible way to configure the client. Check out `ConfigBuilder`.
