### ISSUE TITLE
have a flag to allow Route creation by default for the openshift.yml

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#713]
while Ingress is the long term mechanism OpenShift should adopt; for a while we're stuck with Routes.

Its looking like some folks really wanna create Routes as part of their quickstarts:
https://issues.jboss.org/browse/OBST-2

while its easy to do by creating a src/main/fabric8/route.yml we might want to add a flag in the pom.xml to enable route generation for the `openshift.yml` file

**Comment by rhuss** [comment]
Sounds like a good idea.

However, if so, we shouldn't do it via properties by default (as it is used now in https://github.com/hikhvar/prometheus-kubernetes-demo). We already were there.

**Comment by jstrachan** [comment]
BTW I was thinking of a flag in the `<configuration>` rather than mvn properties. 

BTW didn't grok how that kubernetes-demo with no pom.xml at all was related

**Comment by rhuss** [comment]
oops, sorry. A completely wrong paste ;-) meant https://issues.jboss.org/browse/OBST-2 

And even misread this ticket (refering to the property in the initial description, but this was for v2). Sorry, I was a bit of a rush.

I can take about that as soon as I'm back.
