### ISSUE TITLE
ClassNotFoundException StringUtils when building with spring boot

### ISSUE THREAD

**Issue by marklester** [fabric8io/fabric8-maven-plugin#716]
when I run 
```
mvn clean package 
```
I get:

https://gist.github.com/marklester/1d965f6643591fe7289ba8e97684c8e3

* f-m-p version :3.2.8
* Maven version (`mvn -v`) : 3.3.9
* dependency tree + pom: https://gist.github.com/marklester/7230ff4a2311cc0ef58c3b6bafb515fb

**Comment by davsclaus** [comment]
And what happens if you remove the fmp plugin, can the project build?

**Comment by marklester** [comment]
wow obvious error. Turns out it was surefire not fmp. Sorry for the wasted time.
