### ISSUE TITLE
Add <env> specified env variables to be added to generators

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#723]
### Description

Our provided generators should respect the `<env>` variables section in the config and add environment variables set there.

**Comment by rhuss** [comment]
Actual this should be added to the `DefaultControllerEnricher`, i.e. it should take the environment variables as configured and then put it into the pod template spec.

The open question is what todo when there is already an env of the same name. which one wins ?

**Comment by rhuss** [comment]
Or maybe even better within the `ImageEnricher`

**Comment by nicolaferraro** [comment]
Well, `ImageEnricher` seems suited for the purpose. I need to add the `ResourceConfig` object to the `EnricherContext`.

Once it is moved, we may also want to move the custom code about annotations and labels into the `adapt()` method of a standard enricher.

For the question about env override (which one wins?), I don't have a final answer. In general we don't override what's been set by previous enrichers. We can keep this behavior (.. and allow the enrichers to behave differently in special circumstances).

The `ImageEnricher` is one of the first enrichers, so it probably won't override anything.

@rhuss wdyt?

**Comment by rhuss** [comment]
@nicolaferraro fine for me with no overriding (but would be nice to print a warning)

w.r.t to moving the `MetaDataEnricher` to standards enrichers: That makes perfect sense to me. We have to touch that API anyway for #678 when we change the chaining API anyway.

**Comment by rhuss** [comment]
@chirino @dsimansk this is the fix for merging in `<env>` defined variables into generator created controller objects (DeploymennConfig etc.), which means this could be a candidate for a patch release by cherry picking https://github.com/fabric8io/fabric8-maven-plugin/commit/580e0dc662f7a4d1df5a879123fb11b9dffb348e into the product branch. wonder whether this is still v3.1.80-redhat ?

**Comment by dsimansk** [comment]
@rhuss @chirino I've created an issue to track backport in product branch https://issues.jboss.org/browse/OSFUSE-561
