### ISSUE TITLE
Add `skip` options to goals

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#732]
### Description

Similar in spirit to the `skip` goals of d-m-p, fabric8 should support options to skip certain goals:

* `resource` (`fabric8.skip.resource`)
* `build` (already supported via `docker.skip.build`, should have a correspondent `fabric8.skip.build`)
* `push` (already supported via `docker.skip.push`, should have a correspondent `fabric8.skip.push`)
* `apply` (`fabric8.skip.apply`)
* `deploy` (`fabric8.skip.deploy`)

**Comment by rhuss** [comment]
Nice starter task which should be implemented to guarantee consistency.

**Comment by dev-gaur** [comment]
@rhuss @rohanKanojia @lordofthejars 

https://github.com/fabric8io/fabric8-maven-plugin/blob/master/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/BuildMojo.java#L85

Every mojo has a skip option already..I don't follow why we need skip.build ..skip.push etc properties ?
