### ISSUE TITLE
OpenShift route generation quirks

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#756]
### Description

Currently the generation of OpenShift `Routes` is broken and doesn't work in the quickstarts. See https://issues.jboss.org/browse/OSFUSE-479 for the downstream issue.

The main reason is, that although `-Dfabric8.deploy.createExternalUrls` is applied to `fabric8:apply` no Route is created when the `Services` found dont have as type `LoadBalancer`. IMO this is a to harsh restriction, since the user explicitly request the generation of a route, so it should be created regardless of the type (and the type should be changed to `LoadBalancer` if this is required). I know, that route / ingress creation is nowadays delegated to exposecontroller, but this is not of much help for the downstream products which do not have an exposecontroller available (not productised). So we need a direct solution here.

At least as it stands now, `fabric8.deploy.createExternalUrls` is useless for auto-generated Services with service type `ClusterIP`.

@fabric8io/maintainers  any opinion on this ? My suggestion is to move the route creation as post-process step which would (a) change the service type to `LoadBalancer` and (b) create the route.

**Comment by jimmidyson** [comment]
Service doesn't need to be loadbalancer type to work with & in fact that it's discouraged as it automatically creates load balancers on public clouds, redundant when you're using the router.

**Comment by rhuss** [comment]
Cool, so it's probably enough to simply remove the check on the service type when a Route is requested.

**Comment by jimmidyson** [comment]
Yep.
