### ISSUE TITLE
Add revisionHistoryLimit config option to the default controller enricher.

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#762]
if we don't specify a limit then folks RS's soon populate with every version ever of a Deployment which can be noisy and painful. Unless users specify something we maybe should pick a sensible default?

**Comment by rhuss** [comment]
Let's make it configurable, and use a default of 2. If set to 0 then no revisionHistoryLimit should be added.

**Comment by lordofthejars** [comment]
Closing because of @rohanKanojia comment.
