### ISSUE TITLE
when building a docker image with a SNAPSHOT version, it would be nice to replace "1.0-SNAPSHOT" with a timestamp in docker

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#77]
if you use `1.0-SNAPSHOT` as the docker image name, then deploy it with `mvn fabric8:deploy` then the second time you build you often get docker failures due to the image label being in use.

it'd be nice if OOTB the plugin was smarter & defaulted the docker label to a timestamp label if the `${project.version}` ends with `SNAPSHOT`; so that the same timestamp is exposed in the kubernetes resource as is created via `fabric8:build`

**Comment by rhuss** [comment]
Is there error, that the image can be deleted because it is in use ? Because normally `docker:build` should override existing images. 

If we implement it this way I wonder who is doing the cleanup. I would make using always a timestamp optional, and by default on a `fabric8:deploy`:

* Try to create image with  `:latest`. 
* If this fails because its in use, create it with a timestamped version.
* Create the resources as usual with refering to `:latest`
* Remove the old Kubernetes resources
* If the image has been timestamped because of the *already in use* use case :
  - Remove `:latest`
  - Retag timestamped version to `:latest`
* Apply the new Kubernetes resources created with `fabric8:resources`

It's a bit involved (also from a transactional point of view), but that would be the cleanest solution for this use case, which btw only applies to a developer workflow using a single node. For multiple nodes you would need to go over a registry anyway and probably use then a different docker daemon for building. 
 
The tricky part in this is the communication between d-m-p's `build` and f-m-p's `deploy`.

**Comment by jstrachan** [comment]
Here's an example error log:
```
INFO] --- fabric8-maven-plugin:3.0-SNAPSHOT:build (default) @ funktion-nodejs-example ---
[INFO] Building tar: /workspace/java/funktion-nodejs-example/target/docker/quickstart/funktion-nodejs-example-nodejs/1.0-SNAPSHOT/tmp/docker-build.tar
[INFO] F8> docker-build.tar: Created [quickstart/funktion-nodejs-example-nodejs:1.0-SNAPSHOT] "funktor" in 71 milliseconds
[INFO] F8> Step 1 : FROM node:5.3-onbuild
[INFO] F8> [91m# Executing 3 build triggers...

[INFO] F8> Step 1 : COPY package.json /usr/src/app/
[INFO] F8> ---> Using cache
[INFO] F8> Step 1 : RUN npm install
[INFO] F8> ---> Using cache
[INFO] F8> Step 1 : COPY . /usr/src/app
[INFO] F8> ---> Using cache
[INFO] F8> ---> cef10049bea7
[INFO] F8> Successfully built cef10049bea7
[INFO] F8> [quickstart/funktion-nodejs-example-nodejs:1.0-SNAPSHOT] "funktor": Built image cef10049bea7
[INFO] Copying files to /workspace/java/funktion-nodejs-example/target/docker/quickstart/funktion-nodejs-example/1.0-SNAPSHOT/build/maven
[INFO] Building tar: /workspace/java/funktion-nodejs-example/target/docker/quickstart/funktion-nodejs-example/1.0-SNAPSHOT/tmp/docker-build.tar
[INFO] F8> docker-build.tar: Created [quickstart/funktion-nodejs-example:1.0-SNAPSHOT]  in 1 second
[INFO] F8> Step 1 : FROM fabric8/java-alpine-openjdk8-jdk
[INFO] F8> ---> a14da8f15df6
[INFO] F8> Step 2 : EXPOSE 8080
[INFO] F8> ---> Using cache
[INFO] F8> ---> 481e3051ebd3
[INFO] F8> Step 3 : COPY maven /app/
[INFO] F8> ---> 0364b0d1be82
[INFO] F8> Removing intermediate container b46fe338f751
[INFO] F8> Successfully built 0364b0d1be82
[INFO] F8> [quickstart/funktion-nodejs-example:1.0-SNAPSHOT] : Built image 0364b0d1be82
[WARNING] F8> [quickstart/funktion-nodejs-example:1.0-SNAPSHOT] : Unable to remove image [19897d88d2f3] (old image) [conflict: unable to delete 19897d88d2f3 (cannot be forced) - image is being used by running container e059f0665a9a (Conflict: 409)]
[INFO] F8> [quickstart/funktion-nodejs-example:1.0-SNAPSHOT] : Tag with latest
```

BTW I think kubernetes does docker image GC? Its maybe worth investigating - though really its just the timestamp labels that would need purging really. We could use a prefix/postfix so that we try to remove all timestamp labels each time (that are not in use)?

**Comment by jstrachan** [comment]
I'm about to submit a PR for a possible fix. Its configurable on the maven plugin whether to stick with the pom version for snapshots, to use 'latest' or use a timestamp label instead. 

Here's an example of a successful second build of a nodejs funktion; which uses a spring boot customizer to generate an image plus a sidecar configured via the `<build>` element; both use the correct labels; as do all the kubernetes manifests. This means on openshift + kubernetes each build generates a nice rolling upgrade too!
```
[INFO] Building tar: /workspace/java/funktion-nodejs-example/target/docker/quickstart/funktion-nodejs-example-nodejs/snapshot-160604-105759-0902/tmp/docker-build.tar
[INFO] F8> docker-build.tar: Created [quickstart/funktion-nodejs-example-nodejs:snapshot-160604-105759-0902] "funktor" in 72 milliseconds
[INFO] F8> Step 1 : FROM node:5.3-onbuild
[INFO] F8> [91m# Executing 3 build triggers...

[INFO] F8> Step 1 : COPY package.json /usr/src/app/
[INFO] F8> ---> Using cache
[INFO] F8> Step 1 : RUN npm install
[INFO] F8> ---> Using cache
[INFO] F8> Step 1 : COPY . /usr/src/app
[INFO] F8> ---> Using cache
[INFO] F8> ---> f962097ce0ca
[INFO] F8> Successfully built f962097ce0ca
[INFO] F8> [quickstart/funktion-nodejs-example-nodejs:snapshot-160604-105759-0902] "funktor": Built image f962097ce0ca
[INFO] Copying files to /workspace/java/funktion-nodejs-example/target/docker/quickstart/funktion-nodejs-example/snapshot-160604-105759-0902/build/maven
[INFO] Building tar: /workspace/java/funktion-nodejs-example/target/docker/quickstart/funktion-nodejs-example/snapshot-160604-105759-0902/tmp/docker-build.tar
[INFO] F8> docker-build.tar: Created [quickstart/funktion-nodejs-example:snapshot-160604-105759-0902]  in 1 second
[INFO] F8> Step 1 : FROM fabric8/java-alpine-openjdk8-jdk
[INFO] F8> ---> a14da8f15df6
[INFO] F8> Step 2 : EXPOSE 8080
[INFO] F8> ---> Using cache
[INFO] F8> ---> 481e3051ebd3
[INFO] F8> Step 3 : COPY maven /app/
[INFO] F8> ---> 60c44f1e1bce
[INFO] F8> Removing intermediate container 468c908fe483
[INFO] F8> Successfully built 60c44f1e1bce
[INFO] F8> [quickstart/funktion-nodejs-example:snapshot-160604-105759-0902] : Built image 60c44f1e1bce
[INFO] F8> [quickstart/funktion-nodejs-example:snapshot-160604-105759-0902] : Tag with latest
[INFO]
```

Here's the PR https://github.com/fabric8io/fabric8-maven-plugin/pull/98
