### ISSUE TITLE
LivenessProbe is no longer enriched

### ISSUE THREAD

**Issue by cheinema** [fabric8io/fabric8-maven-plugin#776]
### Description

In Spring Boot projects a `readinessProbe` is generated into the `kubernetes.yml`, but `livenessProbe` is now missing.

### Info

* f-m-p version : since v3.2.10
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: D:\Apps\Java\apache-maven-3.3.9
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: C:\Programme\Java\jdk8\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"
```

I mean this issue was introduced with dedb0d069a15195f33dfada05785abfb1999c5c3.

[This line](https://github.com/fabric8io/fabric8-maven-plugin/blob/v3.2.14/enricher/api/src/main/java/io/fabric8/maven/enricher/api/AbstractHealthCheckEnricher.java#L54) must be
```
container.withLivenessProbe(probe);
```
in my opinion.

Note: `livenessProbe` is also missing in [it/src/it/spring-boot/expected/kubernetes.yml](https://github.com/fabric8io/fabric8-maven-plugin/blob/v3.2.14/it/src/it/spring-boot/expected/kubernetes.yml).

**Comment by jimmidyson** [comment]
Thanks for the report & investigation, which looks correct to me. Would you be able to send in a PR with that fix?
