### ISSUE TITLE
Add Git URL to GitEnricher

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#788]
e.g. in 
http://central.maven.org/maven2/io/fabric8/devops/packages/logging/2.2.311/logging-2.2.311-kubernetes.yml

we just have:
```yaml
      fabric8.io/git-commit: 2b9f7ce19493fe6d18392ac4f4be16f5e1a76fa3
      fabric8.io/git-branch: release-v2.2.311
```

It would be good to include the git url too. Not sure if this is an fmp issue or something related to how we use it inside the [jenkins pipelines library](https://github.com/fabric8io/fabric8-pipeline-library/)

**Comment by kameshsampath** [comment]
@jstrachan - can we also add <scm> details of the maven project too, like connection,developerConnection, issueTracking etc., ?

**Comment by jstrachan** [comment]
@kameshsampath see https://github.com/fabric8io/fabric8-maven-plugin/issues/789 for issue tracker stuff.

I guess having a non-committer git URL might be handy too; though its a little confusing these days as git has ssh and https with the later usable by committers and non committers; so not sure if just a https URL is enough these days?

**Comment by kameshsampath** [comment]
sorry i missed that out @jstrachan

**Comment by jstrachan** [comment]
btw here's the code that tries to add the git url:
https://github.com/fabric8io/fabric8-maven-plugin/blob/af9c73718c8db9691d24ddd3cf9aac26dd4cd05e/enricher/fabric8/src/main/java/io/fabric8/maven/enricher/fabric8/CdEnricher.java#L118

we may also wanna check the pom details too as per this discussion https://github.com/fabric8io/fabric8-maven-plugin/issues/789#issuecomment-275338729

**Comment by dev-gaur** [comment]
@rohanKanojia @lordofthejars The GitURL can be added by the Continous Delivery enricher (deprecated) .. 

https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/deprecated/src/main/java/io/fabric8/maven/enricher/deprecated/CdEnricher.java#L114 

Should I just transfer the method in the GitEnricher?
