### ISSUE TITLE
Upon `mvn fabric8:undeploy` the replication controllers remain

### ISSUE THREAD

**Issue by heiko-braun** [fabric8io/fabric8-maven-plugin#793]
_Please fill out the following information to help us in analyzing the issue, but feel free to skip it if you don't have the information at hand or if it does not apply. Please remove everything which does not apply to the issue. Including this info paragraph ;-)_

### Description

see $subject

### Info

* f-m-p version : 3.1.92
* Maven version (`mvn -v`) : 3.3.3
```

```
* Kubernetes / OpenShift setup and version : v3.3.1.4

**Comment by heiko-braun** [comment]
Does this duplicate https://issues.jboss.org/browse/OSFUSE-388 ?

**Comment by rohanKanojia** [comment]
@heiko-braun : Hi, I'm not able to reproduce this with latest version of fmp. Are you still facing this issue?

**Comment by rhuss** [comment]
@rohanKanojia @heiko-braun I think we can close this for now as according to issues.jboss.org/browse/OSFUSE-388 it's very likely closed and since you can't reproduce it again, I think its fair to close it now and re-open it if there is still an issue (or create a new issue)
