### ISSUE TITLE
Slim down Mojos

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#801]
Currently nearly all business logic is contained in Mojos, which can not be easily tested and are tightly couple to the Maven platform.

These Mojos should be stripped down to the bare minimum and all business logic should go into dedicated services.

There are two kind of services:

* depending on the Maven API (e.g. `MavenProject` etc)
* independent of the Maven API (no dependency on any Maven artifact)

As much as possible should be moved to Maven independent modules. They are easier to test and could be reused (e.g. for other build systems like gradle).

Ideally the Mojos's task is then to collect the configuration (via  `@Parameter` injection) and then call into these services.

This backend services could be realized as Plexus components (we already have some)

**Comment by nicolaferraro** [comment]
@rhuss I'd like to start working on this. I've already started doing some refactoring in #815, so I'll start this from that branch (hoping that the watcher abstraction will be merged before this one).

**Comment by rhuss** [comment]
ok. I finally make a d-m-p release this evening. always surprised how fast a backlog of issues can pile up ;)
