### ISSUE TITLE
Remove resource object post-processing

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#802]
Currently in `ResourcesMojo` a lot of post processing happens with 

* Converting Kubernetes objects to OpenShift objects
* Converting OpenShift to Kubernetes objects
* Filtering out Kubernetes objects (for openshift.yml)
* Filtering out OpenShift objects (for kubernetes.yml)

All of this is not only complicated and lead to a lot of special conditional cases (`if instanceof ...`), but also hard to debug e.g. **why** a certain objects exists in the generated descriptors.

It is also the natural entry point for **quick hacks** which quickly pleases a certain use case but is pain and harmful in the long run when other use cases (which even might not be envisioned) happens. The _volume permission init container_ was a good example when it was implemented as a post processing step. Also, such special behaviour is not easy to disable, except with a new configuration parameter (which leads to configurtion fragmentation, blows up the mojo, needs to be documented, needs to be added to the various way to configure stuff). Adding to the configuration should be really the last option.

Instead all _functional processing_ should go into the `Enrichers`. See also #678 for more details and a solution to this problem.

**Comment by rohanKanojia** [comment]
Closed via #1521
