### ISSUE TITLE
Make triggers configurable when auto generating DeploymentConfigs

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#816]
if we are reusing an existing docker image in a generated Deployment / DeploymentConfig we should avoid the use of DeploymentConfig image triggers which seem to break the deployment if there's no ImageStream etc.

We maybe even just force the use of vanilla Deployments now if enabled and we are not using s2i builds?

**Comment by jstrachan** [comment]
a workaround for now is to just force kubernetes mode BTW!

**Comment by rhuss** [comment]
I agree that trigger should be created optionally. What's about moving this in dedicated enrichers so that it can be easily enabled or disabled ? (maybe even with a profile)

BTW, do a `Deployment` work on OpenShift ? Thought they were complementary to `DeploymentConfigs` and are not really supported so we cant switch from `DeploymentConfig` to `Deployment` for OpenShift when not using a s2i build.

The ImageStreams are created during a build for S2I, so they should be there if the Deployment created is about the artifact we are building (which it should be for the automatically created Deployment objects).

@jstrachan do you have a concrete project where the current behaviour has problems ? Would love to look at a concrete use case to find the best solution.

I definitely wouldn't change the creation of Deployment object (fabric8:resource) based on using a different build (fabric8:build).

BTW the workaround to generate different descriptors for different `fabric8.mode` should be considered as a bug as we always create both kind of descriptors regardless of the mode.  So they should be the same regardless which mode is set to stay predictable.

**Comment by jstrachan** [comment]
@rhuss agreed on moving this enricher there.

Since we went with always Deployment on kubernetes and DeploymentConfig on OpenShift - now Deployments work on OpenShift. Right now I think the only real reason for a DC is if using S2I really (ImageStreams) - without those then I'd have thought sticking to regular Deployment kinds is a better ideally really.

So we probably need some kind of flag to say whether or not we wish to use DCs at all - defaulting on if folks are using S2I builds

**Comment by rhuss** [comment]
thanks for the heads up, didn't know that. Yes, there should be an option to configure somewhere wether to us Deployment (plain Docker images) or DeploymentConfig (with image streams) for OpenShift. Using plain Docker images though poses the problem where to build the image as OpenShift does not expose a Docker daemon to build against (at least not by default).

Arrgh, so many combinations.

We are currently in a refactoring phase ( @nicolaferraro is working on #799, I wanna start soon on #678) , so if this is not super urgent would be awesome if we could push this back a bit (not too much).

**Comment by jstrachan** [comment]
Disabling ImageStream triggers + DCs is also useful if you want to consume an existing docker image from docker hub inside OpenShift. i.e. you are not building the docker image,  just making a manifest.

**Comment by jstrachan** [comment]
Its not super urgent - I just hit it and worked around by forcing kubernetes mode for now

**Comment by jimmidyson** [comment]
ImageStreams work with images from Docker hub too btw and include stuff like scheduled checks for updated versions, etc.

There's a comparison of DeploymentConfigs vs Deployments at https://docs.openshift.com/container-platform/3.4/dev_guide/deployments/kubernetes_deployments.html#kubernetes-deployments-vs-deployment-configurations if you're interested. It's encouraged to use DeploymentConfigs on OpenShift as Deployments is still only in tech preview for supported deployments.

**Comment by jstrachan** [comment]
@jimmidyson thx - the issue is we've no tooling in fmp yet to create the ImageStream from the upstream docker hub stuff; so we end up with a DeploymentConfig that does absolutely nothing ;)

Having a DC using a docker image and having the image stream trigger but no ImageStream is much much worse than using a Deployment - as a Deployment actually works ;)

So I guess thats a 3rd option; use Deployment on openshift + kubernetes; use the generated ImageStream on DCs or generate an ImageStream for an existing docker image for DCs

**Comment by LarsMilland** [comment]
There is another problem with how things are working now with triggers of both ConfigChange and ImageChange being generated to the DeploymentConfig that is generated when using OpenShift. That is that even I one then removes the triggers afterwards to avoid later triggering of redeploys when either changing the DeploymentConfig or changes occurs to the image, then one end up with not being able to use the "rollback to previous" deployment as soon as the DeploymentConfig is regenerated next time round for instance referencing a new image version, then that DeploymentConfig again contains the trigger, and you would not be able to rollback, as the deployment would have run twice, once initiated by the trigger, and once where you in your deploymentscript yourself activated the deployment. It is also not possible to add for instance an empty "trigger: []" to a yaml snippet for the DeploymentConfig, that will be overwritten by the generator.

So please could this be prioritized, so one can completely disable all triggers, or at least just supply what triggers you would prefer by yourself in the templates Fabric8 generates from.

**Comment by ayen-tibco** [comment]
+1

My story is I don't need DC automatically generated because I have custom Pods yml config files that requires custom pod names. So please, have a property value to disable dc generation. Thanks.

**Comment by aliepold** [comment]
Hello everybody
I have the same problems with the triggers. Especially when I combine several containers via a resource fragment. In my case, I have three different services in a pod. Two services work as sidecar. For example, one container works as a proxy and the other as a database for the microservice.

I also need a feature to exclude generation of triggers for specific containers.
For me, I have found a solution to exclude the section of triggers for certain containers. I've implemented a workaround in my pom.xml which removes the unwanted triggers after the plugin has generated the manifest file. With the help of a simple Groovy script I remove the section afterwards.

As an example, the following situation with a resource file in `src/main/fabric8/deployment.yml` describing two additional containers for nginx and mongodb:
```yaml
spec:
  template:
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: mongodb-config
          image: mongodb:3.4.19
          imagePullPolicy: IfNotPresent
          name: mongodb
          ports:
          - containerPort: 27017
            name: http-mongo
            protocol: TCP
        - envFrom:
            - configMapRef:
                name: nginx-config
          image: nginx:1.15.9
          imagePullPolicy: IfNotPresent
          name: nginx-proxy
          ports:
          - containerPort: 80
            name: http-nginx
            protocol: TCP
```
In the pom.xml, I include the Groovy script in the `process-resources` phase. Right after the fabric8-maven-plugin was executed:
```xml
<build>
  <plugins>
    <plugin>
      <groupId>io.fabric8</groupId>
      <artifactId>fabric8-maven-plugin</artifactId>
      <version>3.5.42</version>
      <executions>
        <execution>
          <goals>
            <goal>resource</goal>
            <goal>build</goal>
          </goals>
        </execution>
      </executions>
    </plugin>
    <!-- Workaround for removing of ImageStream-Triggers -->
    <plugin>
      <groupId>org.codehaus.gmaven</groupId>
      <artifactId>groovy-maven-plugin</artifactId>
      <version>2.1</version>
      <dependencies>
        <dependency>
          <groupId>org.codehaus.groovy</groupId>
          <artifactId>groovy-all</artifactId>
          <version>2.5.6</version>
          <type>pom</type>
        </dependency>
        <dependency>
          <groupId>org.yaml</groupId>
          <artifactId>snakeyaml</artifactId>
          <version>1.24</version>
        </dependency>
      </dependencies>
      <executions>
        <execution>
          <phase>process-resources</phase>
          <goals>
            <goal>execute</goal>
          </goals>
          <configuration>
            <source>
	  <![CDATA[
	  import java.io.File
	  import java.io.FileInputStream
	  import java.io.FileWriter
	  import java.util.List
	  import java.util.Map
	  import org.yaml.snakeyaml.DumperOptions
	  import org.yaml.snakeyaml.Yaml
	  
	  // List of container-names who will have no trigger
	  def excludeTriggerForContainer = ["nginx-proxy", "mongodb"]
  
	  def deploymentFile = new File("target/classes/META-INF/fabric8/openshift.yml")
  
	  if (deploymentFile.exists()) {
  
		def options = new DumperOptions();
		options.setIndent(2);
		options.setPrettyFlow(true);
		options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
  
		def yaml = new Yaml(options);
  
		def inputStream = new FileInputStream(deploymentFile);
  
		def obj = (Map<String, Object>) yaml.load(inputStream);
		def items = (List<Map<String, Object>>) obj.get("items");
  
		for (Map<String, Object> item : items) {
		  for (Map.Entry<String, Object> entryKind : item.entrySet()) {
			if (entryKind.getValue().equals("DeploymentConfig")) {
			  Map<String, Object> spec = (Map<String, Object>) item.get("spec");
			  def triggers = (List<Map<String, Object>>) spec.get("triggers");
			  def triggersToRemove = new ArrayList<Map<String, Object>>();
			  for (Map<String, Object> trigger : triggers) {
				if (trigger.containsKey("imageChangeParams")) {
				  def icp = (Map<String, Object>) trigger.get("imageChangeParams");
				  for (String containerName : (List<String>) icp.get("containerNames")) {
					if (excludeTriggerForContainer.contains(containerName)) {
					  triggersToRemove.add(trigger);
					}
				  }
				}
			  }
			  // remove the matched triggers after foreach
			  for (Object t : triggersToRemove) {
				triggers.remove(t);
			  }
			  yaml.dump(obj, new FileWriter(deploymentFile));
			}
		  }
		}
		System.out.println(obj);
	  }
	  ]]>
            </source>
          </configuration>
        </execution>
      </executions>
    </plugin>
  </plugins>
</build>
```
As you can see, I added exactly the containers named nginx-proxy and mongodb to the ignore list.

I hope it is helpful for everyone
