### ISSUE TITLE
How to configure authentication with java-exec generator

### ISSUE THREAD

**Issue by baluyot** [fabric8io/fabric8-maven-plugin#821]
I've looked at the documentations and even the source code but I can't seem to find a way to configure authentication parameters using java-exec generator. Is it even supported? If not, can we add this feature? From the documentation, it seems the <images> section of the configuration does have this feature. The reason I need is that sometimes I would like to specify my own docker repository which requires authentication to pull my base image from using the java-exec generator.

**Comment by baluyot** [comment]
Any comments?

**Comment by rhuss** [comment]
what kind of authentication do you refer to ? For pushing images to a registry or building against a custom Docker daemon ?

For pushing images see here --> https://maven.fabric8.io/#authentication

**Comment by baluyot** [comment]
I am referring to authentication when pulling the base image. For example, if I have a custom base image I want to use using with java-exec generator that is pulled from a private repository that has basic authentication how can configure the credentials? E.g.

            <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>fabric8-maven-plugin</artifactId>
                <version>${fabric8.maven.plugin.version}</version>
                <configuration>
                    <generator>
                        <config>
                            <java-exec>
                                <name>%g/%a:%l</name>
                                **<from>https://my.private.repo:8888/fabric8/s2i-java</from>**
                                <mainClass>org.apache.camel.spring.Main</mainClass>
                            </java-exec>
                        </config>
                    </generator>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>resource</goal>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

How do I configure authentication for "https://my.private.repo:8888"? As rhuss mentioned, the link provided is for pushing images.

**Comment by rhuss** [comment]
sorry, my fault: the documentation is also about authentication for _pulling_ images. In fact you can even distinguish between pull and push creds. Have you tried to enter the creds in your settings.xml ?

**Comment by baluyot** [comment]
@rhuss just do double confirm the documentation you provided will work even if the environment (e.g PC) where I am building the project is not part of the oc cluster but is logged in Openshift using the oc client?

**Comment by rhuss** [comment]
The plugin is using the information from ~/.kube/config so, yes, it's attached to the same cluster as you connected to with `oc login`.

But if you are using OpenShift and probably s2i I don't understand really why you worry about Docker credentials as in this case you dont have any direct interaction with a Docker daemon (but only via OpenShift image streams).

Maybe you could describe your use case a bit more in detail ?

**Comment by baluyot** [comment]
In the corporate environment we are running Openshift there is no direct internet connection. Everything must go through a proxy. So, Openshift cannot freely just download base images from docker hub. In addition, we also wanted to experiment running our own docker repo containing our own base image. I will try your suggestion and report back if it works or not. Thanks.

**Comment by baluyot** [comment]
@rhuss I configured the credentials using settings.xml. When I run mvn fabric8:deploy I get the following error:

[INFO] F8: Using HTTP proxy http://167.26.79.71:3128 and HTTPS proxy http://167.26.79.71:3128 for script download
[INFO] F8: error: build error: unable to get dsbdev.cibcwm.com:9444/fabric8/s2i-java:latest
[INFO] F8: Build spring-camel-s2i-9 status: Failed
[ERROR] F8: OpenShift Build spring-camel-s2i-9 Failed

Running the same maven command with -e -X parameters gave no useful info. Any idea what's causing the failure?
