### ISSUE TITLE
Move the MetadataEnricher to standard enrichers

### ISSUE THREAD

**Issue by nicolaferraro** [fabric8io/fabric8-maven-plugin#828]
We should move the code that adds selectors and labels to the generated resources from `EnricherManager` to a specific standard `MetadataEnricher`.

**Comment by dev-gaur** [comment]
@rhuss @lordofthejars @rohanKanojia @nicolaferraro I'm currently working on this issue and will send a PR soon when done.

Apart from that, I'm in a bit of dilemna about this issue - is this actually needed ? Would this be the perfect thing to do ?

As far as I under the code in EnricherManager that adds metadata and selector labels invokes some visitor pattern classes and the labels from enrichers such as GitEnricher , TriggerAnnotationEnricher etc 

If we move that functionality into a 'MetadataEnricher' , then it will act as Meta Enricher which facilitates for other Enrichers which have methods like getAnnotations , getLabels

Do we want this kind of flow among enrichers?

Please correct me if I'm wrong.
