### ISSUE TITLE
Not able to include values.yaml file in helm.tar.gz

### ISSUE THREAD

**Issue by libkad** [fabric8io/fabric8-maven-plugin#869]
I'm building helm.tar.gz file using helm goal.
What I would like to achieve is to include values.yaml file inside it but I don't see the way to do it.
Is it possible? 

* f-m-p version : 3.2.28
* Maven version : 3.3.9

**Comment by rohanKanojia** [comment]
@libkad : Are you still using helm goal? FYI helm goal has been deprecated and we're not sure whether to include this or not in upcoming 4.0 release. I would really appreciate if you could provide feedback on this.

**Comment by libkad** [comment]
No, this was a blocker for us and we switched to use maven assembly plugin to achieve what we needed

**Comment by rohanKanojia** [comment]
@libkad : Oh okay. Shall we close this then ;-) ?

**Comment by libkad** [comment]
yes

**Comment by rohanKanojia** [comment]
Thanks for your feedback
