### ISSUE TITLE
Using spring.app.name as servicename

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#872]
The spring boot applications has the option of specifying the `spring.app.name` property, when thats being defined the f8-m-p can use that as service name instead of using `${project.artifactId}`

### Info

* f-m-p version : 3.2.30
* Maven version (`mvn -v`) : 3.3.9
```

```
* Kubernetes / OpenShift setup and version : 1.4.1/3.4.0

**Comment by rhuss** [comment]
Sounds good, lets do this.
