### ISSUE TITLE
Adding Environment Variables

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#876]
The fabric8 maven plugin is not honouring the env variables that are defined inline 

### Description

When I define a plugin def like this,

```xml
 <plugin>
        <groupId>io.fabric8</groupId>
        <artifactId>fabric8-maven-plugin</artifactId>
        <version>${fabric8.maven.plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>resource</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <resource>
            <env>
              <JAVA_OPTIONS>-Dspring.profiles.active=ocp</JAVA_OPTIONS>
            </env>
          </resource>
        </configuration>
      </plugin>
```
the generated deployment resource does not include the JAVA_OPTIONS in the containers environment variables

### Info

* f-m-p version : 3.2.30
* Maven version (`mvn -v`) : 3.3.9

**Comment by rhuss** [comment]
@kameshsampath Sorry, you should use `<resources>` not `<resource>`. That works for me without issue.

I wonder why Maven doesn't throw an error when a given configuration can not be applied, though.

**Comment by kameshsampath** [comment]
thanks @rhuss this works closing the issue
