### ISSUE TITLE
Custom service selector

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#9]
It should be possible to define the service selector in a more
flexible way. Currently the only possibility is to remove the version
label, however one should possibly either configure the kind of labels
which should be able to remove.

**Comment by jstrachan** [comment]
would specifying the subset of `service.yml` you want to configure be enough? like this example:
https://github.com/jstrachan/springboot-config-demo/blob/master/src/main/fabric8/service.yml

you can then specify labels or selector by hand?

**Comment by rhuss** [comment]
If a selector is set by hand it always 'wins'. Its about when creating a selector implicitely. Then naively every label gets part of the selector. However, for e.g. rolling updates it doesnt make sense to include the version label, so its gets currently excluded (hard coded). 

But wouldn't it be nice to let ppl. declare somehow "all labels from all enrichers, except these" ? This could go as a special expression in the yml files or as a plugin configuration (which probably is easier).
