### ISSUE TITLE
Add a simple port mapping to the DefaultServiceEnricher

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#921]
The `DefaultServiceEnricher` allows mapping the first port of an image configuration to specific service ports (the other ports are identity mapped giving a multiport service).

So the logic should be:

* If `<port>` is not configured keep the current rationale: 1:1 mapping of all exposed pod ports (as given in the build configuration) to service ports
* If `<port>` is configured to a plain number, then map the first exposed pod port to this number. So this value becomes the service port.
* If `<port>` is in the format `8080:9090` then map the first port to this particular combination (service port: 8080, pod port: 9090). The question is what to do with other ports in a given build configuration. I suggest to map them again 1:1 (as in the fist two cases, too)

@davsclaus Would support this your use case?

**Comment by davsclaus** [comment]
Yes this sounds good

**Comment by rhuss** [comment]
@davsclaus I enhanced my suggestion a bit, please find the documentation of the new mapping features [here](https://github.com/rhuss/fabric8-maven-plugin/blob/pr/default-service-enricher-refactor/doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc)

Feedback highly appreciated ;-)

**Comment by davsclaus** [comment]
Thanks @rhuss I just browsed the PR and it looks good. Having an example in the documents would be really good. I can struggle a little bit to find out how how all this XML elements must be to set the port names.

**Comment by rhuss** [comment]
Good point. Will embed the example in a fully working XML configuration snippet.

**Comment by rhuss** [comment]
@davsclaus does this [example](https://github.com/rhuss/fabric8-maven-plugin/blob/pr/default-service-enricher-refactor/doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc) looks a bit better ?

**Comment by davsclaus** [comment]
@rhuss I wound prefer a more normal example, eg to set a name, and the port mappings, eg

myservice

And then to expose as port 80 and use 8080 internally
80:8080

Then the user knows its a service name myservice on port 80, then he can call this service using DNS on http://myservice

And then you can have a 2nd example with the multi port (which likely most users dont understand what really does)

**Comment by rhuss** [comment]
ah, ok. understand now, makes  sense.

**Comment by rhuss** [comment]
next [try](https://github.com/rhuss/fabric8-maven-plugin/blob/pr/default-service-enricher-refactor/doc/src/main/asciidoc/inc/enricher/_fmp_service.adoc]
