### ISSUE TITLE
Unable to configure replicas count via property

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#925]
### Description
When `replicas` is configured via fabric8 maven plugin `<resources>` configuration parameter, the plugin still sets the value as `1` which is the default value 

### Info

* f-m-p version : 3.3.5
* Maven version (`mvn -v`) : 3.5
* Kubernetes / OpenShift setup and version : 1.6/1.5

Define the following configuration in the maven project  $replicas: <any number>
```
 <plugin>
                <groupId>io.fabric8</groupId>
                <artifactId>fabric8-maven-plugin</artifactId>
                <version>3.3.5</version>
                <executions>
                    <execution>
                        <id>fmp</id>
                        <goals>
                            <goal>resource</goal>
                            <goal>helm</goal>
                            <goal>build</goal>
                        </goals>
                        <configuration>
                            <resources>
                                <replicas>${replicas}</replicas>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
When you run the fabric8:resource, it still defaults to `1` as the value for replicas instead of what value provides via maven property `${replicas}`

**Comment by kameshsampath** [comment]
@ro14nd - if you see this lines https://github.com/fabric8io/fabric8-maven-plugin/blob/master/enricher/standard/src/main/java/io/fabric8/maven/enricher/standard/DefaultControllerEnricher.java#L89-L93, a new ResourceConfig is always created with default enricher - which means the resource config set via plugin configuration is ignored completely

**Comment by kameshsampath** [comment]
@ro14nd  - made a patch for this via https://github.com/fabric8io/fabric8-maven-plugin/pull/926, please review

**Comment by rhuss** [comment]
This is an issue which we should fix. Actually, any explicit configuration should override and implicit behaviour. 

This is also connected to the #18 to align the XML syntax to include some typically used configuration option.

**Comment by rohanKanojia** [comment]
I can still reproduce this, will send a PR to fix this.
