### ISSUE TITLE
`mvn fabric8:import` should detect Jenkinsfiles and automatically create the BuildConfig with jenkinsPipelineStrategy

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#934]
if the current repo is already in git and has a Jenkinsfile we should create a `BuildConfig` with the corresponding `jenkinsPipelineStrategy` configured.

If there's no pipeline we could maybe provide the user with the option to pick from one of the available pipelines in the library https://github.com/fabric8io/fabric8-jenkinsfile-library/tree/master/maven which if one is selected would then copy the selected Jenkinsfile into the source code (git add and git commit); then setup the `BuildConfig` with the `jenkinsPipelineStrategy`.

Essentially this is kinda like the forge import wizard; but being accessible easily from the mvn CLI

**Comment by rohanKanojia** [comment]
fabric8:import got removed in #1313
