### ISSUE TITLE
Enricher must not override configured environment variables

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#937]
Currently, enricher always set environment variables like JAVA_OPTIONS even if they are configured explicitly in the configuration. This must not be the case. The configured env var must have precedence.

**Comment by kameshsampath** [comment]
related #957

**Comment by rhuss** [comment]
@kameshsampath I think this issue is a bit different than #957 It's more that if you provide them as a fragment it overrides every environment variable which has been configured in the plugin XML configuration.

**Comment by rhuss** [comment]
Not sure whether this is still an issue, so we should check it.

**Comment by lordofthejars** [comment]
@rhuss I have searching where `JAVA_OPTS` were set in an enricher (https://github.com/fabric8io/fabric8-maven-plugin/search?q=JAVA_OPTIONS&unscoped_q=JAVA_OPTIONS) but I have just found in Generators.

**Comment by rhuss** [comment]
Actually, I think `JAVA_OPTIONS` was just a contrived example. It's in general if an enricher adds environment variables with the enricher API call, and you define the same variable in the plugin configuration, then the enricher 'wins' (but it should be vice versa).

**Comment by rhuss** [comment]
Not sure what I'm saying here ;-)

Maybe its about labels and annotations ? (as there is no exposure of an environment variable directly).

**Comment by rhuss** [comment]
Ah, and it's not so much about enrichers but more about fragments:

Consider e.g. a fragment like

```yaml
spec:
  containers:
  - env:
    - name: JAVA_OPTIONS
      value: "-Xmx512m"
```

**and** an plugin configuration

```xml
<resources>
  <env>
    <JAVA_OPTIONS>-Xmx256m</JAVA_OPTIONS>
  </env>
</resources>
```

then `-Xmx512m` is picked up (but IMO should be 256m as this declaration is "closer" to the build where people start to explore). We could issue a warning though that there are conflicts.

**Comment by lordofthejars** [comment]
Ok, then we can say that there is in fragments. Then what we need to do is check if a fragment and plugin define the same environment variable. Ok, then I need to figure out how to check this inside FMP. Is there any place where we have all this information?

**Comment by rhuss** [comment]
"env" is part of the plugin config, not to level pom. It's a simple way to add env vars to pods. A bit similar to label an annotation look into the resource config class

**Comment by lordofthejars** [comment]
@rhuss I am thinking a lot about this issue, and thinking about how to do it. Then what do you think it would be better, just warn the user that there is conflict or warn the user and also apply the change to the environment vars defined in plugin configuration takes precedence. This is what I am not really sure yet.
