### ISSUE TITLE
align default labels more closely with the `oc` CLI tooling

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#945]
it seems the openshift `oc` tool and openshift web console prefers there to be a canonical `app` label on all resources relating to the same project. 

We've traditionally gone with:
* `project` for the `artifactId`
* `groups` for the `groupId`
* `version` for the `version`

To make things more openshift console & `oc` friendly and similar should we switch `project` to `app`?

Am not sure if `app` should be fully qualified with the groupID too though? Otherwise we could easily get clashes

**Comment by jstrachan** [comment]
more background:

here's where `oc` set the app label, if appropriate, on the objects being created.  we also set a default annotation:
https://github.com/openshift/origin/blob/master/pkg/cmd/cli/cmd/newapp.go#L279-L300

The code generating the objects in the console is here: https://github.com/openshift/origin-web-console/blob/master/app/scripts/services/applicationGenerator.js 
The labels are set from here because we let the user update the labels https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/create/createFromImage.js#L380

**Comment by kameshsampath** [comment]
few thoughts @jstrachan for fully qualifying the name with `${groupId}.${artifactId}`.. also just wondering if we could do a `NAMESPACE` prefix as will to it like `${NAMESPACE}.${artifactId}` as I cant have two same app names in the same project . If  OpenShift will query the selectors with NS + app label then ${artifactId} should be suffice..

**Comment by jstrachan** [comment]
Yeah I guess omitting the `${groupId}` would be OK - then if you wanna deploy the same app with the same `${artifactId}` from 2 different group ids you'd either:

* use different namespaces to run them
* customize the app label/artifact ID to be more specific ;)

**Comment by rhuss** [comment]
What's about having both, `project` and `app` ? That way we would stay backwards compatible, too. I would add the `app` label generation to an extra enricher so that it can be switched on and off independently.

**Comment by jstrachan** [comment]
@rhuss we can certainly make `app` and/or `project` configurable for sure. 

I think I'd prefer to just switch to `app` by default for consistency and avoid 2 labels as the default. There's very little code that really depends on which one of these 2 are used really; its more just metadata thats viewed on consoles and CLIs.

So long as we've a simple flag folks can use to preserve `project` if they wish I think we'll be good
