### ISSUE TITLE
Readiness/Liveness probes for srping boot should be aware of server.servlet-path property

### ISSUE THREAD

**Issue by iocanel** [fabric8io/fabric8-maven-plugin#965]
Generated probes for spring boot application need to check the `server.servlet-path` property.

There are cases, where mvc path is moved from / to a custom location. 
Example: https://docs.spring.io/spring-boot/docs/current/reference/html/howto-actuator.html#howto-use-actuator-with-jersey

For those cases, it would be really nice if f-m-p could read the configuration and adapt the path to the health endpoint.

**Comment by rhuss** [comment]
agreed, we should pick up this configuration option from spring-boot.
