### ISSUE TITLE
Support for Multi containers with Resource Fragments

### ISSUE THREAD

**Issue by kameshsampath** [fabric8io/fabric8-maven-plugin#968]
### Description
When using Resource Fragments, the plugin is not able to merge i.e to append to containers - when containers in Deployment Template Spec already has a container defined. This will be typically useful when we handle sidecars

Currently the resource merge thinks the existing container definition as the application definition and merges to it instead of appending it.

### Info

* f-m-p version : 3.4.1 
* Maven version (`mvn -v`) : 
```
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.12.5", arch: "x86_64", family: "mac"
```
* Kubernetes / OpenShift setup and version :
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T20:41:24Z", GoVersion:"go1.8.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-06-21T20:14:56Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
* If it's a bug, how to reproduce :
  1. Create a simple spring boot or any other supported project
  2. Create a `deployment.yml` with one container added to Deployment Template Spec, dont add the application container spec
 3. run mvn fabric8:resource, you will see the plugin merging the application container spec with existing spec defined
* If it's a feature request, what is your use case : support for side cars
* Sample project : https://github.com/kameshsampath/fmp-issue-968-sample

**Comment by rhuss** [comment]
Agreed that this should be possible. I wonder though, how we could distinguish the case whether we should add a new container to the container list and when we should merge containers. Maybe we should correlate over the image name itself ? 

I'm happy about any PR for this feature.

**Comment by kameshsampath** [comment]
yeah using image is the best way - as that will be unique amongst the containers

**Comment by kameshsampath** [comment]
@rhuss - how shall we call the variable for adding probes to multiple contianers

right now am calling as `probeMode` with values:

* `all` - applies Liveliness and Readiness to all containers in deployment
* `first` - applies Liveliness and Readiness to first container of the deployment
* `last` - applies Liveliness and Readiness to last container of the deployment

**Comment by kameshsampath** [comment]
@nicolaferraro  - your thoughts ?

**Comment by kameshsampath** [comment]
@jstrachan , @nicolaferraro , @rhuss   - this https://github.com/fabric8io/fabric8-maven-plugin/pull/969 resolves the issue

**Comment by christophetd** [comment]
Any update on this? I believe it would be a very important feature to have, especially since service meshes such as Linkerd or Envoy running as a sidecar container are starting to get a lot of traction.

It seems that #969 has been abandoned, are there any plans to support this feature?

Thanks!

**Comment by kameshsampath** [comment]
@jstrachan @hrishin - shall we start dust this out ?

CC: @pradeepto

**Comment by jstrachan** [comment]
sounds good - if we use the container name in the fragments to do the merge things should be straightforward I hope

**Comment by jpkrohling** [comment]
Just wanted to add my support to this issue :-) Without proper support to sidecars, it's also hard to get a Jaeger Agent deployed automatically with an application making use of distributed tracing with Jaeger.
