### ISSUE TITLE
fabric8:helm goal does not package Go template files (.tpl)

### ISSUE THREAD

**Issue by idlv75** [fabric8io/fabric8-maven-plugin#971]
### Description
I am creating Helm Charts with the fabric8:helm mvn goal, but it only packages the yaml files from the /src/main/fabric8 directory and ignores other valid file types like _helpers.tpl and NOTES.txt
I checked the [HelmMojo](https://github.com/fabric8io/fabric8-maven-plugin/blob/1034839ec13cdb861e8a32de0c1b992abc0b5376/plugin/src/main/java/io/fabric8/maven/plugin/mojo/build/HelmMojo.java) implementation and indeed this functionality is missing.
Are there are plans to support this in the future?

### Info
* f-m-p version : 3.2.13
* Maven version (`mvn -v`) : 3.3.9

**Comment by rohanKanojia** [comment]
@idlv75 : Hi, Do you still use `fabric8:helm` goal? We are cleaning up unused Mojos and right now we're not sure whether it's actually used or not.

**Comment by idlv75** [comment]
Kumar hi,
I opened this request some time ago when i worked for Amdocs. At the time
the goal was not very useful and we implemented our own helm templates
solution.
Regards,
Vladi Ifat
