### ISSUE TITLE
vertx generator should add the -cluster arg when a cluster.xml is given

### ISSUE THREAD

**Issue by MarWestermann** [fabric8io/fabric8-maven-plugin#976]
### Description
To cluster vertx applications (access the event bus), the fat jar needs to be launched with the -cluster argument. This could be provided by the vert.x generator if it finds a cluster.xml under src/main/.

On the other hand I cannot find a possibility to add the -cluster argument manually via config. Is this possible as workaround? 

### Info

* f-m-p version : 3.4.2
* Maven version (`mvn -v`) :
```
Apache Maven 3.3.9
```
* Kubernetes / OpenShift setup and version : minishift 1.5
* If it's a feature request, what is your use case : cluster vert.x application on openshift

**Comment by cescoffier** [comment]
It's a bit more tricky as the configuration file depends on the cluster manager used. What about looking at the vert.x maven plugin runArgs parameter to detect if cluster needs to be enabled?

**Comment by MarWestermann** [comment]
Yeah. Realized it in the meantime that you don't always have a cluster.xml. But what if people want to use the maven shade plugin instead? Maybe we could have an optional property: fabric8.runArgs or sth. like that, too.

**Comment by rhuss** [comment]
Fixed with #1035
