### ISSUE TITLE
Build getting failed [master branch]

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#990]
### Description
Build is getting failed failed. Some test cases are getting failed for `OpenshiftBuildServiceTest.java`.
@nicolaferraro @ro14nd @jstrachan could you please confirm it with current master?
PFA error log [error_log.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/1158260/error_log.txt)

### Info
* f-m-p version : 3.5-SNAPSHOT

* Maven version (`mvn -v`) : 
```
Apache Maven 3.3.9 (NON-CANONICAL_2016-07-01T11:53:38Z_mockbuild; 2016-07-01T17:23:38+05:30)
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.131-1.b12.fc25.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.11.8-200.fc25.x86_64", arch: "amd64", family: "unix"

```
* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce : mvn clean install/package
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by nicolaferraro** [comment]
@hrishin yes, it seems a recent change has introduced an error in the build. I'm fixing it.
