### ISSUE TITLE
generated Dockerfile has newlines in the entry point breaking it when migrating from 2.x to 3.x

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-maven-plugin#993]
here's a sample project https://github.com/MarWestermann/hello forked from https://github.com/redhat-reactive-msa/hello and migrated to the latest fmp version

but it seems broken as the generated Dockerfile has newlines https://pastebin.com/i0Zc2GQS versus the 2.x version https://pastebin.com/zunEpxQk

it looks like we need to trim the strings before combining them in the generated dockerfile

**Comment by MarWestermann** [comment]
Just figured out that the newlines came from pom.xml as the <entrypoint> tag had newlines in it:
<entryPoint>java -Dvertx.zookeeper.hosts=${ZOOKEEPER_SERVICE_HOST} -jar
                                            ${project.artifactId}-${project.version}-fat.jar -cluster -cp . -conf
                                            config.json
</entryPoint>

**Comment by jstrachan** [comment]
so it seems the issue is still a thing as newlines can sneak in
